### ISSUE TITLE
Can anyone  convert below curl to equivalent java code?

### ISSUE THREAD

**Issue by ananth10** [twilio/video-quickstart-android#101]
I need to create a room in android platform. i am using twilio sdk. i am using Retrofit for API calling. i have set everything to call room api. but i dont know what to do with  **"{YourSigningKeySID}:{YourSigningKeySecret}"** i have both api key and secret. how can i pass these to api . should i pass these in the header or data?

curl -XPOST "https://video.twilio.com/v1/Rooms" \

-u "{YourSigningKeySID}:{YourSigningKeySecret}" \

-d "Type=group" \

-d "UniqueName=DailyStandup”

**Comment by sashjakk** [comment]
You should take a look at Retrofit Interceptors and Basic Auth. You can try [this link](http://lgvalle.xyz/2015/07/27/okhttp-authentication/) as example.

**Comment by ananth10** [comment]
@sashjakk Thanks.  "-u {YourSigningKeySID}:{YourSigningKeySecret}" is Header or Paramater? dont consider Retrofit now becaues i am checking this api in postman client
![postman](https://cloud.githubusercontent.com/assets/13381242/25172194/dc76fa28-250d-11e7-894b-9db4543d77b4.png)

**Comment by ananth10** [comment]
@sashjakk  Thanks , its working now in postman.   is there sperate  "Authorization" header in retrofit like postman?  i am doing  like below . is it ok?

 OkHttpClient defaultHttpClient = new OkHttpClient.Builder()
                .addInterceptor(
                        new Interceptor() {
                            @Override
                            public Response intercept(Chain chain) throws IOException {
                                Request request = chain.request().newBuilder()
                                        .addHeader("Content-Type","application/json")
                                        .addHeader("type","Android")
                                        .addHeader("token", "")
                                        .addHeader("session", "")
                                        .build();
                                return chain.proceed(request);
                            }
                        })

**Comment by sashjakk** [comment]
I've been doing authorization like this:

```
Request requestWithHeader = origin.newBuilder()
    .header("Authorization", Credentials.basic("YOUR_USER", "YOUR_PASS"))
    .build();
```

**Comment by ananth10** [comment]
@sashjakk Thanks :+1:

**Comment by aaalaniz** [comment]
Closing this issue. Thanks @sashjakk !

**Comment by lalithanjali0111** [comment]
Through curl command I am able to send files to particular url, can u tell how can we send in java

**Comment by SyedTahura** [comment]
hi can anyone tell me how to add certificate like .csr file from the curl command to  wso2 enterprise integrator xml

curl -v -X GET --cert {{path_to_client_certificate_generated_in_developer_portal} } --cert-type DER --key {{insert_path_to_private_key_used_to_create_CSR}} -H "x-fapi-financial-id: test" -H "Authorization: Bearer {{insert_access_token_retrieved_from_call#5}}" -H "Cache-Control: no-cache" "https://sandbox.hsbc.com/psd2/obie/v3.1/accounts"

 

<?xml version="1.0" encoding="UTF-8"?>

<api context="/hsbc" name="HsbcBankAdapter" xmlns="http://ws.apache.org/ns/synapse">

    <resource methods="POST" url-mapping="/getAccounts">

        <inSequence>

            <header name="Content-Type" scope="transport" value="application/x-www-form-urlencoded"/>

            <header name="Accept" scope="transport" value="application/json"/>

            <header name="x-fapi-financial-id" scope="transport" value="test"/>

            <header name="Cache-Control" scope="transport" value="no-cache"/>

            <property expression="$trp:grant_type" name="client_credentials" scope="default" type="STRING"/>

            <property expression="$trp:scope" name="accounts" scope="default" type="STRING"/>

            <property expression="$trp:client_assertion_type" name="urn:ietf:params:oauth:client-assertion-type:jwt-bearer" scope="default" type="STRING"/>

           

            <payloadFactory media-type="json">

                <format>{

  "grant_type": "$1",

  "scope": "$2",

  "client_assertion_type": "$3"

  }</format>

                <args>

                    <arg evaluator="xml" expression="$trp:grant_type"/>

                    <arg evaluator="xml" expression="$trp:scope"/>

                    <arg evaluator="xml" expression="$trp:client_assertion_type"/>

                </args>

            </payloadFactory>

            <call>

                <endpoint>

                    <http method="post" statistics="enable" uri-template="https://sandbox.hsbc.com/psd2/obie/v3.1/as/token.oauth2">

                        <suspendOnFailure>

                            <initialDuration>-1</initialDuration>

                            <progressionFactor>-1</progressionFactor>

                            <maximumDuration>0</maximumDuration>

                        </suspendOnFailure>

                        <markForSuspension>

                            <retriesBeforeSuspension>0</retriesBeforeSuspension>

                        </markForSuspension>

                    </http>

                </endpoint>

            </call>

            <sequence key="conf:sequence/HttpFaultSequence.xml"/>
