### ISSUE TITLE
How to get default video configuration?

### ISSUE THREAD

**Issue by ananth10** [twilio/video-quickstart-android#103]
I need to know default video call configuration. things like , **Frame Size, FPS & color configuration.**. and also how to customise those things?

**Comment by ananth10** [comment]
@aaalaniz can you answer above question ASAP?

**Comment by aaalaniz** [comment]
Hi @ananth10 

You can use `Room#getStats` API to query the statistics for audio and video tracks being shared to a `Room`. In terms of customization, we allow specifying `VideoConstraints` when creating a `LocalVideoTrack`. The snippet below demonstrates how to create a `LocalVideoTrack` that captures at only 720p.

```
CameraCapturer cameraCapturer = new CameraCapturer(context, CameraCapturer.CameraSource.FRONT_CAMERA);
VideoConstraints videoConstraints = new VideoConstraints.Builder()
        .minVideoDimensions(VideoDimensions.HD_720P_VIDEO_DIMENSIONS)
        .maxVideoDimensions(VideoDimensions.HD_720P_VIDEO_DIMENSIONS)
        .build();
LocalVideoTrack localVideoTrack = LocalVideoTrack.create(context, true, cameraCapturer,
                videoConstraints);
```

**Comment by ananth10** [comment]
@aaalaniz  Thanks. 
1. Should i use Room#getStats api or is not there any default method in SDK to know about the FrameRate and FrameSize?.  

2. Is it possible to modify FrameSize and FPS ?. if it is then how can i do it?

**Comment by aaalaniz** [comment]
Frame size directly corresponds to the resolution at which you capture frames. We also support specifying a minimum or maximum FPS.

Here is an example of a camera capturer that captures at 352x288 between 5 and 15 FPS.

```
CameraCapturer cameraCapturer = new CameraCapturer(context, CameraCapturer.CameraSource.FRONT_CAMERA);
VideoConstraints videoConstraints = new VideoConstraints.Builder()
        .minFps(5)
        .maxFps(15)
        .minVideoDimensions(VideoDimensions.CIF_VIDEO_DIMENSIONS)
        .maxVideoDimensions(VideoDimensions.CIF_VIDEO_DIMENSIONS)
        .build();
LocalVideoTrack localVideoTrack = LocalVideoTrack.create(context, true, cameraCapturer,
                videoConstraints);
```

**Comment by ananth10** [comment]
@aaalaniz  Thanks. So different mobile has different resolution. so i will get different framesize and FPS.

can i set it optimal ? like common frame size and FPS for All the mobiles .

**Comment by aaalaniz** [comment]
The default capturing resolution for CameraCapturer on all devices in SDK is 640x480@30 FPS. We find that this resolution and framerate covers the majority of use cases. If the device's camera does not support this resolution the SDK will capture at the closest format to 640x480@30 FPS.

**Comment by ananth10** [comment]
@aaalaniz  Thanks . i will try with VideoConstraints. if i have any doubts then i will come back here.

**Comment by aaalaniz** [comment]
Thanks @ananth10 

I'm closing ticket. Please reopen if you have further questions.

**Comment by ananth10** [comment]
@aaalaniz Can you give me some more information?
1. What is the current color format ? 
2. What is the current color depth?

Actually we need to set  4:2:0 color format. and we need to set 10 as color depth. so how can i change color format and color depth?
