### ISSUE TITLE
Can not connecting to the room

### ISSUE THREAD

**Issue by iorikingdom** [twilio/video-quickstart-android#106]
Since this Tuesday the twilio video server become unstably . Such as  can not connecting to the room without any error message.

Sorry for my poor English.

**Comment by aaalaniz** [comment]
Hi @iorikingdom 

Can you describe the instability more? Do you find that you have to attempt multiple times before successfully connecting to `Room`? Are you being randomly disconnected from a `Room`?

Please also provide the following.

- Video Android SDK Version
- Any logcat output when the instability occurs
- Room SIDs for which you see instability

**Comment by aaalaniz** [comment]
Hey @iorikingdom 

Can you try the 1.0.0 release and see if you are still experiencing problems?

Thanks!

**Comment by bubomancer** [comment]
I was having the same problem yesterday, will try with the new libraries.  On a related note, what is the proper way to migrate from Configuration Profile SID to Room Setting usage @aaalaniz ?

**Comment by iorikingdom** [comment]
> Can you try the 1.0.0 release and see if you are still experiencing problems?

Hi @aaalaniz 

I try the 1.0.0 release version. But the problem is not solved yet.
The problem is same

> Video Android SDK Version

1.0.0 release 

> Any logcat output when the instability occurs

We try to find out the error logs from logcat. 
Just one error log about twilio video library.

04-27 15:34:11.546 27299-27377/com.comsty.talker.tablet E/chromium: [ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain

> Room SIDs for which you see instability

The UNIQUE NAME & SID is 

2b2f1932-2744-4852-b5d5-213637b6d100 
RM7ea1fba3b8d963c13732ad377184b2c0

7e6ee29d-9230-4700-ae16-59218e72c87d 
RM8f6f682a465fe446c188cf4294528e9a

46888fc0-9fa5-4d67-acdd-985bc7b4e0d4 
RM8b4a18acf1a578e5bcc5360661cb22d7

40439cb6-d1b3-4995-9629-b0ab97a33f09 
RM08a38e611286a8945af018a2eb91b8a0

etc.

By the way we using twilio japan account 
https://jp.twilio.com

**Comment by aaalaniz** [comment]
Hey @bubomancer 

Can you file a separate issue? It makes things easier to track. Thanks!

**Comment by aaalaniz** [comment]
Thanks @iorikingdom 

I will take a look at these Room SIDs. Can you describe what is happening? Are you being disconnected from Rooms? 

We did deploy a backend update Tuesday (4/25/2017) that enforces "single point of presence" for participants. This means that if you connect to a `Room` with the same identity on two different devices you will be disconnected from one device when you connect on the other. We have had some customers who were reusing the same identity for participants report being disconnected.

**Comment by iorikingdom** [comment]
> We did deploy a backend update Tuesday (4/25/2017) that enforces "single point of presence" for participants. This means that if you connect to a Room with the same identity on two different devices you will be disconnected from one device when you connect on the other. We have had some customers who were reusing the same identity for participants report being disconnected.

This is the point ,I fix the code at server side ,It became working
Thank a lot.

**Comment by soufian97** [comment]
@iorikingdom how you fix it please ?
