### ISSUE TITLE
When the 2nd user connect to a room the 1st is disconnected

### ISSUE THREAD

**Issue by jojape** [twilio/video-quickstart-android#109]
Hello,

I am testing the VideoCalls and since 2 days ago I can't establish connection between two users. I've tried with the quickstart too and I have the same issue.

1. User grant connection to TEST room (successful)
2. User2 grant connection to TEST room (successful)
2.1 User is disconnected
2.2 User2 is still connected (until I press "Hang up" button)

I can see the logs in the dashboard (with both users, duration ...)

Hope your answer,

Best

**Comment by aaalaniz** [comment]
Hey @jojape 

We deployed a backend update Tuesday (4/25/2017) that enforces "single point of presence" for participants. This means that if you connect to a Room with the same identity on two different devices you will be disconnected from one device when you connect on the other. We have had some customers who were reusing the same identity for participants report being disconnected. Please be sure you are generating tokens with separate identities.

Thanks

**Comment by aaalaniz** [comment]
Hey @jojape 

Were you able to resolve this issue? Let me know if I can provide any assistance diagnosing the problem.

**Comment by jojape** [comment]
Yes @aaalaniz :)

Thx so much!
