### ISSUE TITLE
What is the current color format of Video Frame?

### ISSUE THREAD

**Issue by ananth10** [twilio/video-quickstart-android#110]
@aaalaniz #103 continue here. 

1. What is the current color format ?
2. What is the current color depth?

Actually we need to set 4:2:0 color format. and we need to set 10 as color depth. so how can i change color format and color depth?

**Comment by aaalaniz** [comment]
Hey @ananth10 

The `CameraCapturer` captures frames in [NV21 format](https://developer.android.com/reference/android/graphics/ImageFormat.html#NV21). YUV 4:2:0 planar image, with 8 bit Y samples, followed by interleaved V/U plane with 8bit 2x2 subsampled chroma samples.

We do not support changing the capture format of `CameraCapturer`. You can implement a custom `VideoCapturer` where you specify your own capturing format.

**Comment by aaalaniz** [comment]
@ananth10 closing this issue. Open a new ticket if you have any more questions about frame format.
