### ISSUE TITLE
Is there any way to audio routing to speaker or headset 

### ISSUE THREAD

**Issue by Sunilkumarr** [twilio/video-quickstart-android#114]
Before i was using sdk`  compile "com.twilio:video-android:1.0.0-beta10"` then i migrated to new version `compile "com.twilio:video-android:1.0.0"`  i cant see this option  in latest               
 videoClient.setAudioOutput(on ? AudioOutput.SPEAKERPHONE : AudioOutput.HEADSET);

Before i was using this below code :

```
 private View.OnClickListener speakerClickListener() {
        return new View.OnClickListener() {
            @Override
            public void onClick(View v) {
             *//*
                 * Audio routing to speakerphone or headset
                 *//*
                if (room == null) {
                    Log.e(TAG, "Unable to set audio output, conversation client is null");
                    return;
                }
                setSpeakerphoneOn(!(videoClient.getAudioOutput() == AudioOutput.SPEAKERPHONE));
            }
        };
    }

``````

    private void setSpeakerphoneOn(boolean on) {
        if (room == null) {
            Log.e(TAG, "Unable to set audio output, conversation client is null");
            return;
        }
        try {
            if (videoClient != null) {
                videoClient.setAudioOutput(on ? AudioOutput.SPEAKERPHONE : AudioOutput.HEADSET);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        if (on) {
            Drawable drawable = ContextCompat.getDrawable(this,
                    R.drawable.ic_volume_down_green_24px);
            speakerActionFab.setImageDrawable(drawable);
        } else {
            // route back to headset
            Drawable drawable = ContextCompat.getDrawable(this,
                    R.drawable.ic_volume_down_white_24px);
            speakerActionFab.setImageDrawable(drawable);
        }
    }
```

**Comment by aaalaniz** [comment]
Hey @Sunilkumarr 

We removed this functionality from the SDK so developers can manage their own audio output. We have a [guide for configuring audio output](https://www.twilio.com/docs/api/video/configuring-audio-video-inputs-and-outputs#selecting-a-specific-audio-output).

Here is a snippet that changes the audio output

```
// Get AudioManager
AudioManager audioManager = (AudioManager) context.getSystemService(Context.AUDIO_SERVICE);

// Route audio through speaker
audioManager.setSpeakerphoneOn(true);

// Route audio through headset
audioManager.setSpeakerphoneOn(false);
```

**Comment by Sunilkumarr** [comment]
@aaalaniz Thanks its working

**Comment by hwolf0610** [comment]
Hi @aaalaniz 
I just used your code.
but, your code run in low android version than 9.0 correctly.
if i test your code in android 9.0, my audio can't hear me via usb head jack.
And then, i want to hear via head set and usb head jack in same time.
Can you help me about this?
I have two device as android 9.0 and 6.0.
Best Regards.
