### ISSUE TITLE
How to reduce the resulting binary size due to using twilio video library?

### ISSUE THREAD

**Issue by xhuatli** [twilio/video-quickstart-android#115]
Hello,

After adding twilio video library and built a simple video chat experience (following the example), I noticed my app's binary size got about 40MB increase, which is very large. Is there anyway to shrink it down? Notice the size issue will affect pretty much all developers who are using this library.

Thanks,
Xin

**Comment by idelgado** [comment]
See https://github.com/twilio/video-quickstart-android/blob/master/README.md#reducing-apk-size
