### ISSUE TITLE
noise when using speaker mode

### ISSUE THREAD

**Issue by kvikrama** [twilio/video-quickstart-android#119]
Hi,

   We are using speaker mode for communication. Often we get noise because of feedback between mic and speaker.
Please get this fixed ASAP. Using speaker is the regular mode of operation for us.

**Comment by aaalaniz** [comment]
Hi @kvikrama 

Does the feedback occur on certain devices? We are actively investigating audio inconsistencies in our own internal application as well. Can you share a snippet of how you are configuring the `AudioManager`?

Thanks

**Comment by kvikrama** [comment]
@ananth10 please give the code snippet to Aaron.
@aaalaniz we started the code from https://github.com/twilio/video-quickstart-android/tree/master/exampleCustomVideoRenderer. Should be same as what we see there.

**Comment by ananth10** [comment]
@aaalaniz  i have enabled the speaker using AudioManager . see below code

```
 private void setSpeaker(boolean isEnable) {
        if (isEnable) {
            autioManager = (AudioManager) VideoActivity.this.getSystemService(Context.AUDIO_SERVICE);
            autioManager.setMode(AudioManager.MODE_IN_CALL);
            autioManager.setSpeakerphoneOn(false);
        } else {
            autioManager = (AudioManager) VideoActivity.this.getSystemService(Context.AUDIO_SERVICE);
            autioManager.setMode(AudioManager.MODE_IN_CALL);
            autioManager.setSpeakerphoneOn(true);
        }
    }
```

**Comment by aaalaniz** [comment]
Thanks for the snippet @ananth10 

In terms of turning speakerphone on, the snippet looks correct. However, please be sure you are configuring the `AudioManager` the same way we [demonstrate in the quickstart module](https://github.com/twilio/video-quickstart-android/blob/master/quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java#L650). Let me know if you still experience problems after configuring `AudioManager` correctly.

**Comment by aaalaniz** [comment]
Hey @ananth10 and @kvikrama 

Did configuring `AudioManager` correctly resolve your issues?

**Comment by sabodh** [comment]
`
    private void configureAudio(boolean enable) {
        if (enable) {
            audioManager.requestAudioFocus(null, AudioManager.STREAM_VOICE_CALL,
                    AudioManager.AUDIOFOCUS_GAIN_TRANSIENT);            
            audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
            audioManager.setSpeakerphoneOn(true);
        } else {
            audioManager.setMode(AudioManager.MODE_NORMAL);
            audioManager.abandonAudioFocus(null);
            audioManager.setSpeakerphoneOn(false);
        }
    }`
I have tried this but the noise is not resolved

**Comment by sudheeshdh** [comment]
`
    private void configureAudio(boolean enable) {
        if (enable) {
            audioManager.requestAudioFocus(null, AudioManager.STREAM_VOICE_CALL,
                    AudioManager.AUDIOFOCUS_GAIN_TRANSIENT);            
            audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
            audioManager.setSpeakerphoneOn(true);
        } else {
            audioManager.setMode(AudioManager.MODE_NORMAL);
            audioManager.abandonAudioFocus(null);
            audioManager.setSpeakerphoneOn(false);
        }
    }`
I have tried this but the noise is not resolved

**Comment by aaalaniz** [comment]
Hey @sudheeshdh 

Can you provide device information? 

Thanks!

**Comment by sudheeshdh** [comment]
Hi I am using samsung galaxy S4 and Moto G5 and Lenovo Note 4.

**Comment by aaalaniz** [comment]
Hey @sudheeshdh 

You had mentioned in another issue with noise. Are the devices you are testing on in separate rooms when the noise occurs?

**Comment by sabodh** [comment]
Nobo haven't tested using separate rooms. I have tested to connected in a
single  room .

**Comment by sudheeshdh** [comment]
If I had connected these devices to single room and the distance between
these devices around less than 2 meter the noises occurs otherwise not.

**Comment by aaalaniz** [comment]
I apologize for the confusion. By rooms, I mean the devices need to be in two separate physical rooms while connected to the same Video SDK `Room`. When devices sit near each other the echo and noise problem is a known problem that is not fixable.

**Comment by sudheeshdh** [comment]
Oky..
I have configured these devices in a single physical room and connected
with in a range of 2 meter.
But this issue only happened if the device put to speaker mode.

**Comment by zackm0571** [comment]
@kvikrama we have updated our SDK to version `4.0.0` which contains a much more recent of WebRTC (Version 67 to be exact). Could you try updating and see if you still experience this issue?

**Comment by aaalaniz** [comment]
I'm closing this issue. Please reference our [Troubleshooting Audio article](https://github.com/twilio/video-quickstart-android#troubleshooting-audio) for any audio related issues. Thank you.
