### ISSUE TITLE
When the 2nd user connect to a room the 1st is disconnected (automatically)

### ISSUE THREAD

**Issue by jojape** [twilio/video-quickstart-android#120]
Hello,

I have the same issue than some weeks ago (https://github.com/twilio/video-quickstart-android/issues/109#issuecomment-297747645). But now I am generating the access tokens using the API.

Process:
1. User grant connection to TEST room (successful)
2. User2 grant connection to TEST room (successful)
2.1 User is disconnected
2.2 User2 is still connected (until I press "Hang up" button)

- Both devices can connect to the room
- They have different tokens

Hope your answer,

Best

**Comment by aaalaniz** [comment]
Hey @jojape 

Can you validate that you are using unique identities for each token? Below are two examples of tokens with unique identities. 

```
{
  "iss": "SK00000000000000000000000000000000",
  "exp": 1495471329,
  "jti": "SK0000000000000000000000000000000000000000000",
  "sub": "AC00000000000000000000000000000000",
  "grants": {
    "identity": "alice"
  }
}

{
  "iss": "SK00000000000000000000000000000000",
  "exp": 1495471329,
  "jti": "SK0000000000000000000000000000000000000000000",
  "sub": "AC00000000000000000000000000000000",
  "grants": {
    "identity": "bob"
  }
}
```

**Comment by jojape** [comment]
I didn't use unique identities.
Thx so much again :)

-- 
Jorge Jaramillo

**Comment by aaalaniz** [comment]
Glad to help!
