### ISSUE TITLE
Reconnecting to a room - Video freezes if user minimizes then restores app

### ISSUE THREAD

**Issue by sdharmarajah** [twilio/video-quickstart-android#121]
We have noticed that if a user **minimizes, then restores** the app when a video channel is in progress, the video freezes

Is there some _"channel resume feature"_ we need to implement, to prevent this from happening?

Thank you

**Comment by aaalaniz** [comment]
Hey @sdharmarajah 

Are you seeing this issue in the quickstart or your own application?

Thanks!

**Comment by aaalaniz** [comment]
Hey @sdharmarajah 

Were you able to resolve this issue on your own? If so can you share your solution?

Thanks!

**Comment by sdharmarajah** [comment]
Sorry for the late reply - 

You were right - this only happens in OUR app - not the demo app

Thanks again for the stellar service Twilio !

**Comment by sanjogshrestha** [comment]
Yes this is exactly reflected on my side. Only the demo app runs properly for onresume but not ours.
