### ISSUE TITLE
Incorrect minSdkVersion

### ISSUE THREAD

**Issue by luca992** [twilio/video-quickstart-android#13]
In your read-me you mention:
"The minimum supported Android version is 4.0.3 for devices or Android emulators."
4.0.3 is API level 15.

But you have set
        minSdkVersion 16
in gradle.

**Comment by aaalaniz** [comment]
Good find @luca992. The correct minSDKVersion is 16. Will update accordingly.

**Comment by aaalaniz** [comment]
Resolved in #15
