### ISSUE TITLE
Support multiple participants

### ISSUE THREAD

**Issue by Sotatek-TuyenLuu** [twilio/video-quickstart-android#134]
My app needs to support multiple participants at the same time. So I wonder which is the max number of participants can join a room? Anybody can help me to figure it out? Thanks

**Comment by idelgado** [comment]
@Sotatek-TuyenLuu We support up to 10 participants in P2P rooms and up to 50 participants in Group Rooms. If you are planning to share video in your Room I would suggest you use Group Rooms. This is the default in the video console.

**Comment by arshadsk5** [comment]
I am iOS developer, i want to multiple participants to a room. Please share the code

**Comment by aaalaniz** [comment]
Hey @arshadsk5 

I recommend you check out the [Video iOS MultiPartyExample](https://github.com/twilio/video-quickstart-swift/tree/master/MultiPartyExample). If you have any questions, file an issue on that Github project and one of our iOS engineers would be happy to help. 

Thanks!

**Comment by sudhanshu2010** [comment]
Hi, 
I am using our open source Quickstart Android app code, this code has only two candidates video call support, I want to add 4 participants in video call, So kindly share the working code sample for multiple participants call using quicktart code. I have tried in many ways but not getting success to manage all 4 participants video in one room.

Thanks!
