### ISSUE TITLE
Access Raw Buffers from AudioTrack

### ISSUE THREAD

**Issue by lucjac** [twilio/video-quickstart-android#135]
Will there be a way to access Raw Buffers from AudioTrack as it is possible on iOS since the 1.2.0 release?
This is basically the same as https://github.com/twilio/video-quickstart-swift/issues/104 but for Android. Accessing the audio buffers would be great to do some further processing on them like speech recognition.

**Comment by aaalaniz** [comment]
Hey @lucjac 

I will collaborate with @ceaglest to add similar functionality to our Android SDK. Is there a particular framework you plan on using for speech recognition? Please provide any and all details about your use case.

Thanks!

**Comment by lucjac** [comment]
@aaalaniz thanks, that sounds great! I would actually just use it to record, encode and save the Audio from remote tracks locally in AAC Format. For this i would use Androids MediaCodec (https://developer.android.com/reference/android/media/MediaCodec.html). So it would be good the be able to access the audio frames as byte arrays or byte buffers, just like its already possible with the video frames (https://media.twiliocdn.com/sdk/android/video/releases/1.2.0/docs/)

**Comment by aaalaniz** [comment]
Thanks @lucjac

I will update this ticket with any information moving forward.

**Comment by seanadkinson** [comment]
@aaalaniz Any planned updates on accessing the raw remote audio for the purposes of recording on device?

**Comment by aaalaniz** [comment]
Unfortunately no progress here @seanadkinson ☹️

**Comment by aaalaniz** [comment]
@seanadkinson  I'll poke around the implementation and see if I can hack something together.

**Comment by aaalaniz** [comment]
Hey @seanadkinson 

Apologies for the delay, but I looked into this and I don't think there is a hacky solution that I can put together without modifying the SDK. WebRTC manages audio recording from the JNI level so using reflection is not really an option.

**Comment by zackm0571** [comment]
Hey @lucjac, 

We released the Audio Sink API with a quickStart demo you can find [here](https://github.com/twilio/video-quickstart-android/tree/master/exampleAudioSink). Please feel free to open an issue if you have any trouble with it 🙂
