### ISSUE TITLE
No audio in the video recording

### ISSUE THREAD

**Issue by rajesh1158** [twilio/video-quickstart-android#136]
### Description

I have a react native app set up to get an access token for programmable video using a VideoGrant to a unique room name. My room setting is set to automatically start recording when a participant joins. At the end of the video session, Twilio calls the callback url which I set up in the Twilio console. I get the video recording as a download, but when I play it I do not hear audio in it. I read about a VoiceGrant class in the Twilio docs, but that is for programmable voice sdk, and I am using programmable video sdk. What am I missing?

### Steps to Reproduce

1. Set up a callback url in Twilio console, pointing to your live dev server
2. Set up the quick start android app on any android device, which will act as participant 1
3. Get an access token, hard code into the app
4. Do the steps 1 and 2 on another android device also, which will act as participant 2
5. Do a video call, and end the call after few seconds/minutes
6. Get the recording url from the Twilio callback, download it

#### Expected Behavior

After the video recording is downloaded and I play it, I expect to hear the audio in the recording

#### Actual Behavior

The recording just has the video, and no audio

#### Reproduces how Often

Able to reproduce 100% of the time

### Versions

All relevant version information for issue.

#### Video Android SDK

1.1.0

#### Android API

24

#### Android Device

Nubia N1

**Comment by aaalaniz** [comment]
hey @rajesh1158 

What you are observing is currently the expected behavior of our Recording feature. Each audio and video track is recorded as a separate resource. We do not currently provide a participant's muxed and audio and video track as a recording resource. Can you provide more details about your use case? I will notify our backend team of your request as well.

Thanks!

**Comment by aaalaniz** [comment]
I have follow-up @rajesh1158 

We are currently working on a composition API where developers can request muxed audio and video recordings. This functionality should be available later this year. For your immediate needs, we encourage developers to try using [FFmpeg](https://ffmpeg.org/). @ktoraskartwilio Can provide more details on how to use ffmpeg to mux audio and video recordings.

Thanks!

**Comment by rajesh1158** [comment]
I downloaded the audio recording as a .mka file. But I do not hear any voice as the media plays. What could be the issue?

**Comment by rajesh1158** [comment]
@aaalaniz  The use case I am working on is to show the video conferencing recording at the end of a video conference session. With the Twilio programmable video sdk, I was able to create an app with video conference feature (2 participants, in a room). At the end of the session, I want to show a single recording which has both audio and video of both participants, kind of like how television news debates work. Having recordings as separate audio and video streams is not of much help in the real world. If there are 2 (or N) participants in a room, there must be a single recording at the end of the session. Imagine a camera watching and capturing everything happening in the room.

**Comment by aaalaniz** [comment]
Hey @rajesh1158 

Thank you for the additional details. I am able to reproduce the audio issue you are describing locally. I will notify our media server team and get back to you.

Thanks!

**Comment by aaalaniz** [comment]
Hey @rajesh1158 

Apparently the audio files are only playable on [Elmedia Player](https://mac.eltima.com/media-player.html). I've requested our media server team provide additional documentation to our [Recording page](https://www.twilio.com/docs/api/video/recordings-resource) that provides additional guidance for developers interested in local playback of their recordings. I'll update this ticket when the documentation is added.

Thanks!

**Comment by aaalaniz** [comment]
Hey @rajesh1158

The recording documentation has been updated with guidance for playing back recorded files.

**Comment by simformsolutions** [comment]
@aaalaniz  we also need that feature which provide recorded video of all participants of conference call.currently we are getting individual recorded file, we need everything in one file, kindly provide your answer.

**Comment by lwilio** [comment]
@simformsolutions Twilio Media Composer API (still in private developer preview) solves that problem. Send an e-mail explaining your use case to video-product at twilio.com if you are interested in being part of the private preview.

**Comment by maido155** [comment]
@lwilio Right now I'm testing  the programmable video, we are starting an interview startup product. could be awesome if we can use Twilio Media Composer API, Thank you
