### ISSUE TITLE
VideoCall make camera more bright

### ISSUE THREAD

**Issue by namhvcntt** [twilio/video-quickstart-android#140]
We are building a video call application and we choose Twilio for video call. But we want to change video bright, color. Can you provide some code which makes video more bright? Else, can you tell me how to do it?
Thanks.

#### Video Android SDK

[eg. 1.1.0]

#### Android API

[eg. 21]

#### Android Device

[eg. Nexus 5]

**Comment by aaalaniz** [comment]
Hey @namhvcntt 

Do you want to apply a brighter filter to the rendered video or are capturing video in low lighting?

We have received requests for adding image processing capabilities to our SDK, but it's not currently on our immediate roadmap. 

If you just need some additional lighting I recommend checking out our [Advanced Camera Example](https://github.com/twilio/video-quickstart-android/tree/master/exampleAdvancedCameraCapturer) where we demonstrate how to toggle the flash while capturing video.

Thanks!

**Comment by namhvcntt** [comment]
@aaalaniz  I want to apply the color filter. Where can I add code to apply the color filter and can you suggest me a document to do it? Thanks/

**Comment by aaalaniz** [comment]
Hey @namhvcntt 

Unfortunately this is a non-trivial answer. I recommend using something like [OpenCV](http://opencv.org/platforms/android/opencv4android-samples.html) to process camera frames and write your own `OpenCVCameraCapturer` that allows you to apply filters on the frames that are shared to a Room.

**Comment by namhvcntt** [comment]
I found VideoCapturerDelegate.initialize with code: `if(this.videoCapturer instanceof CameraCapturer) ` how can I modify VideoCaptureDelegate?

**Comment by aaalaniz** [comment]
Hey @namhvcntt 

`VideoCapturerDelegate` is not part of our public API. The object is created internally and cannot be modified from your application. Is there something you need from this class?

**Comment by namhvcntt** [comment]
I created a CameraCapturer sub-class but on VideoCaptureDelegate it's check
`
public void initialize(SurfaceTextureHelper surfaceTextureHelper, Context context, CapturerObserver capturerObserver) {
        this.listenerAdapter = new VideoCapturerListenerAdapter(capturerObserver);
        if(this.videoCapturer instanceof CameraCapturer) {
            CameraCapturer camera2Capturer = (CameraCapturer)this.videoCapturer;
            camera2Capturer.setSurfaceTextureHelper(surfaceTextureHelper);
        } else if(this.videoCapturer instanceof ScreenCapturer) {
            ScreenCapturer camera2Capturer1 = (ScreenCapturer)this.videoCapturer;
            camera2Capturer1.setSurfaceTextureHelper(surfaceTextureHelper);
        } else if(this.videoCapturer instanceof Camera2Capturer) {
            Camera2Capturer camera2Capturer2 = (Camera2Capturer)this.videoCapturer;
            camera2Capturer2.setSurfaceTextureHelper(surfaceTextureHelper);
        }
    }`

So some my VideoCapture.setSurfaceTextureHelper not called.

**Comment by aaalaniz** [comment]
Hey @namhvcntt,

We currently do not support capturing to a texture in our public Capturer API. We enable this functionality for our own capturers because of the efficiency gain. We do plan on supporting capturing to a texture as part of our public capturer API, but we have not finalized the API.

**Comment by namhvcntt** [comment]
Can you tell me how to access Camera frame? It is not public!

**Comment by aaalaniz** [comment]
Hey @namhvcntt 

You can intercept the frames from `CameraCapturer`. Reference the following snippet.

```
public class CustomCameraCapturer extends CameraCapturer {
    public CustomCameraCapturer(Context context, CameraSource cameraSource) {
        super(context, cameraSource);
    }

    public CustomCameraCapturer(Context context,
                                CameraSource cameraSource,
                                Listener listener) {
        super(context, cameraSource, listener);
    }

    @Override
    public void startCapture(VideoFormat captureFormat,
                             VideoCapturer.Listener videoCapturerListener) {
        super.startCapture(captureFormat, videoCapturerListener);
    }

    private static class CameraFrameProxy implements VideoCapturer.Listener {
        private final VideoCapturer.Listener videoCapturerListener;

        public CameraFrameProxy(VideoCapturer.Listener videoCapturerListener) {
            this.videoCapturerListener = videoCapturerListener;
        }

        @Override
        public void onCapturerStarted(boolean success) {
            videoCapturerListener.onCapturerStarted(success);
        }

        @Override
        public void onFrameCaptured(VideoFrame videoFrame) {
            VideoFrame processedFame = processFrame(videoFrame);

            videoCapturerListener.onFrameCaptured(processedFame);
        }

        private VideoFrame processFrame(VideoFrame videoFrame) {
            // TODO: Process camera frame

            return videoFrame;
        }
    }
}
```

**Comment by aaalaniz** [comment]
I'm going to close for now. Feel free to re-open if you have further questions.

**Comment by kobewangSky** [comment]
Hi @aaalaniz 
How can I change VideoFrame to NV21?
Thanks
kobe

**Comment by aaalaniz** [comment]
Hey @kobewangSky 

The `VideoFrame` from `CameraCapturer` is NV21. You can access the frame from the `imageBuffer` property of `VideoFrame`.

**Comment by kobewangSky** [comment]
Hi @aaalaniz 
Thank you very much!
kobe
