### ISSUE TITLE
maxFps not working

### ISSUE THREAD

**Issue by iorikingdom** [twilio/video-quickstart-android#144]
Our project consider using 3G/4G to video and voice calling in Japan.
I want to control the network traffic by maxFps parameters.
But when i setting maxFps to 10,24 or 30,It cost the same network traffic.
(About ↑10M ↓7M at one minute)

Android and iOS both of that have no effect by setting maxFps parameter.
I don't want to change the screen size, It is any other parameter for control network
traffic?

Thanks so much.

**Comment by aaalaniz** [comment]
Hey @iorikingdom 

Unfortunately the application of `maxFps` varies by device. We are currently working on a bandwidth constraints API that will allow customers to control the amount of bandwidth used for publishing and receiving media. This feature is actively being developed and should be made available later this year.

**Comment by aaalaniz** [comment]
Hey @iorikingdom 

I recommend you check out our new Bandwidth Constraints API. We have added support for setting a max bit rate for sender audio and video. This feature is available as part of the 2.0.0-preview1 release. I recommend checking out the PR #154 for more details about how the API works.

We are continuing to iterate on our 2.x API so expect changes and improvements with more releases.

Thanks!

**Comment by iorikingdom** [comment]
Thanks so much
