### ISSUE TITLE
Enable Flash for Camera2 Apis

### ISSUE THREAD

**Issue by erito** [twilio/video-quickstart-android#146]
### Description

AFAIK there is no capability to enable the camera torch for users that are on Lollipop and above if you utilize the Camera2 Apis.  This puts us in the very odd situation of restricting a particular feature to an api level _and below_.  It would be nice if we could enable a "flashlight" feature for our users running the latest devices.  A quick search seemed to surface [the AOSP implementation](http://androidxref.com/5.0.0_r2/xref/frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/policy/FlashlightController.java[http://androidxref.com/5.0.0_r2/xref/frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/policy/FlashlightController.java]) that enables flash from the toolbar as reference.

**Comment by aaalaniz** [comment]
Hey @erito 

You are correct. Unfortunately, `Camera2Capturer` does not support enabling flash right now. We are aware of the feature disparity between `CameraCapturer` and `Camera2Capturer` and do have tasks to close this gap. I will prioritize this task in our next sprint and will provide updates on this issue. I appreciate your patience.

Thanks!

**Comment by mkutlev** [comment]
Hi @aaalaniz 
What is the status of this issue? Can we expect to have it in recent releases?

**Comment by aaalaniz** [comment]
Hey @mkutlev

Unfortunately no update on this issue. Apologies for the delays. I will provide updates when the feature is complete.

Thanks!

**Comment by BrunoTrovoN26** [comment]
Hello @aaalaniz 
What is the status of this issue?

**Comment by aaalaniz** [comment]
Hey @BrunoTrovoN26 

Unfortunately, no update on this feature.

**Comment by k3bu** [comment]
Hi @aaalaniz 
I know that, this issue is strongly connected with WebRTC but are there any chances to enable this feature?

**Comment by S-Saagar** [comment]
Hello!

@aaalaniz 

Any update on this issue?

**Comment by aaalaniz** [comment]
Hey @S-Saagar 

We have no update at this time. We are prioritizing Programmable Video platform related features and enhancements at this time.

Thank you.

**Comment by ArikYa** [comment]
Hey @aaalaniz, if you have the capture session, just use:
```
captureRequestBuilder.set(CaptureRequest.FLASH_MODE, CaptureRequest.FLASH_MODE_TORCH)
captureSession?.setRepeatingRequest(captureRequestBuilder.build(), CameraCaptureCallback(), cameraThreadHandler)
```

**Comment by ppilip** [comment]
Hi @aaalaniz 

Any chance this has moved up a bit in the priority list?

If not, any quick advice how to bypass this?

I tried with old Camera API, but old one does not allow me to pick from **multiple** back cameras (Samsung S10). It chooses wide angle one as default in my case, but wide one does not have flash, so there is no way of activating flash on this device in any API.

Thanks.

**Comment by aaalaniz** [comment]
Hey everyone,

Sorry for the incredible delay getting this feature implemented. This feature is available in [Video Android 5.5.0](https://www.twilio.com/docs/video/changelog-twilio-video-android#550-april-3rd-2020).

Check out this snippet for a quick example of how to enable flash with `Camera2Capturer`

```
camera2Capturer.updateCaptureRequest(captureRequestBuilder -> {
                CameraCharacteristics cameraCharacteristics =
                        cameraManager.getCameraCharacteristics(camera2Capturer.getCameraId());
                Boolean flashEnabled =
                        cameraCharacteristics.get(CameraCharacteristics.FLASH_INFO_AVAILABLE);
                
                if (flashEnabled != null && flashEnabled) {
                    captureRequestBuilder.set(CaptureRequest.FLASH_MODE, CaptureRequest.FLASH_MODE_TORCH);
                }
            });

```

Thanks!

**Comment by anilchahalaig** [comment]
Hey @aaalaniz

For a flash on-off feature in an ongoing video, I implemented the same as you mentioned but Flash is not turning on. I also gave proper permission in the manifest file as well for Flashlight,  it's is not turning on. 
I was using Kotlin example of your sample SDK

camera2Capturer!!.updateCaptureRequest { captureRequestBuilder: CaptureRequest.Builder ->
            val cameraCharacteristics =
                cameraManager!!.getCameraCharacteristics(camera2Capturer!!.cameraId)
            val flashEnabled =
                cameraCharacteristics.get(CameraCharacteristics.FLASH_INFO_AVAILABLE)
            if (flashEnabled != null && flashEnabled) {
                captureRequestBuilder.set(
                    CaptureRequest.FLASH_MODE,
                    CaptureRequest.FLASH_MODE_TORCH
                )
            }
 }

My minimum version is 21. 
Kindly reopen this issue and fix this asap.

**Comment by aaalaniz** [comment]
Hey @anilchahalaig 

Please open a separate bug and fill out the issue template as best you can so we can properly investigate.

Thanks you!
