### ISSUE TITLE
Index out of Bounds exception with Camera2Capturer

### ISSUE THREAD

**Issue by erito** [twilio/video-quickstart-android#148]
We recently updated our app to conditionally (on API version) load the Camera2Capturer for use in calling.  It seems to have fixed quite a few of the quirks we saw with foregrounding and backgrounding on newer devices, however one exception we've been getting shouldn't be happening at all: 

`java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.`  

For a little background, this is happening when we try to retrieve the first camera in the supported cameras list if we cant find a front facing camera in the list.  Heres the catch:  _the devices are Kitkat devices_.  Before we load Camera2Capturer, we use the following code to determine which API to use: 

``` java
//currentImp and kitKatImp are wrapper classes to keep an upper bound return type
if (Camera2Capturer.isSupported(context)) {
    return currentImp; 
} else {
    return kitKatImp;
}

```  
The devices we've seen this on thus far are all KitKat 4.4.2.  Is it possible Camera2Capturer is returning true incorrectly in some edge cases?

**Comment by aaalaniz** [comment]
Hey @erito 

This sounds interesting. Are you saying that `Camera2Capturer.isSupported` returns `true` on KitKat 4.4.2? Can you post the full stack trace?

Thanks!

**Comment by erito** [comment]
Thats my first impression, yes (looking at the decompiled sdk makes that seems very unlikely, admittedly).  

We have a wide range of devices this is affecting according to fabric they are all running 4.4.4 and below (that may be incorrect, though):

* Note 2
* Galaxy S5
* Tab Pro 10.1
* S4
* Droid Ultra 

The stacktrace may not be as helpful as we use an internal array that takes the first two cameras retrieved from `cameraManager.getCameraIdList()`.  This is returning an empty list, causing the Index Out of Bounds Exception.



````
  | kotlin.collections.EmptyList.get (Collections.kt:45)
  | kotlin.collections.EmptyList.get (Collections.kt:33)
  | com.doctorondemand.android.patient.flow.visitation.call.video.TwCameraCapturerLollipop. (TwCameraCapturerLollipop.kt)
  | com.doctorondemand.android.patient.flow.visitation.call.video.TwCameraCapturerLollipop_Factory.get (TwCameraCapturerLollipop_Factory.java:38)
  | com.doctorondemand.android.patient.flow.visitation.call.video.TwCameraCapturerLollipop_Factory.get (TwCameraCapturerLollipop_Factory.java:11)
  | com.doctorondemand.android.patient.flow.visitation.call.injection.CallModule_ProvideTwCameraCapturerFactory.get (CallModule_ProvideTwCameraCapturerFactory.java:44)
  | com.doctorondemand.android.patient.flow.visitation.call.injection.CallModule_ProvideTwCameraCapturerFactory.get (CallModule_ProvideTwCameraCapturerFactory.java:12)
  | com.doctorondemand.android.patient.flow.visitation.call.video.TwilioRxAdapter_Factory.get (TwilioRxAdapter_Factory.java:67)
  | com.doctorondemand.android.patient.flow.visitation.call.video.TwilioRxAdapter_Factory.get (TwilioRxAdapter_Factory.java:12)

com.doctorondemand.android.patient.flow.visitation.call.video.VideoSessionManager_Factory.get (VideoSessionManager_Factory.java:48)
--
  | com.doctorondemand.android.patient.flow.visitation.call.video.VideoSessionManager_Factory.get (VideoSessionManager_Factory.java:11)
  | com.doctorondemand.android.patient.flow.visitation.call.CallActivity_MembersInjector.injectMembers (CallActivity_MembersInjector.java:109)
  | com.doctorondemand.android.patient.flow.visitation.call.CallActivity_MembersInjector.injectMembers (CallActivity_MembersInjector.java:17)
  | com.doctorondemand.android.patient.base.injection.DaggerBaseFlowComponent$CallFlowComponentImpl.inject (DaggerBaseFlowComponent.java:1610)
  | com.doctorondemand.android.patient.flow.visitation.call.CallActivity.onCreate (CallActivity.java:205)
````

**Comment by aaalaniz** [comment]
Hey @erito 

I have a Galaxy S5 that I develop with, so I will confirm the return value of `Camera2Capturer.isSupported()`. Let me confirm the current steps reproducing this crash.

1. Create `currentImp` or `kitKatImp`
2. Check `Camera2Capturer.isSupported`
3. Crash ?

How are you able to obtain an instance of `CameraManager` on pre-Lollipop devices? Is there anyway you can check `Camera2Capturer.isSupported` before creating `currentImp` or `kitKatImp`

**Comment by erito** [comment]
>  Let me confirm the current steps reproducing this crash.

Step three would be to have the CameraCapturer2 implementation.

>  How are you able to obtain an instance of CameraManager on pre-Lollipop devices?

TBH, I'm not even sure.  We have seen `NoClassDef` found crashes in regards to this (which is more intuitive).  But the fact that this exception handles after querying the `CameraManager` makes this all the more perplexing.

>  Is there anyway you can check Camera2Capturer.isSupported before creating currentImp or kitKatImp

I suppose so, I'm not sure how that would change the outcome?

**Comment by erito** [comment]
I'm closing for now as I think this is an issue with our dependency injection implementation.  I'll reopen if we have anything else that might lead back to `Camera2Capturer`.

**Comment by aaalaniz** [comment]
Sounds good @erito 

Thanks for writing in!
