### ISSUE TITLE
Restrict Room creation in Android SDK

### ISSUE THREAD

**Issue by sudheeshdh** [twilio/video-quickstart-android#155]
Hello, how can I prevent creating new rooms from Android SDK. I need to join only the existing Room if available otherwise not. I  am trying to create a room by using the REST API's and send the room details to the clients . Is this possible ?

**Comment by aaalaniz** [comment]
Hey @sudheeshdh 

You are correct in not using Video REST API in your Android client. One solution is to create a Room using the Video REST API in your application's backend service and provide the Room SID to your clients via any of the following options:

1. [Twilio Notify](https://www.twilio.com/notify)
2. [Firebase Cloud Messaging (FCM)](https://firebase.google.com/docs/cloud-messaging/)
3. REST API
4. [Websocket Connection](https://en.wikipedia.org/wiki/WebSocket)

Let me know if you have any other questions. I'd be happy to help you through your use case.

Thanks!

**Comment by sudheeshdh** [comment]
Hi Aaron,
Thanks for the replay.Also I have another query for viewing the videos in
the client side. I need to view only the videos (rooms) without sending the
streams  to room. Any suggestion  for this.?

**Comment by aaalaniz** [comment]
Hey @sudheeshdh 

You can definitely connect to a Room without sharing any media. See the snippet below for connecting to a Room without audio or video tracks.

```
ConnectOptions connectOptions = new ConnectOptions.Builder(accessToken)
        .roomName(roomName)
        .build();

Room room = Video.connect(this, connectOptions, roomListener);
```

After connecting to the room you will receive callbacks for other participant's media. If you want to share media with participants later you can publish using `LocalParticipant`

```
LocalParticipant localParticipant = room.getLocalParticipant();

localParticipant.addVideoTrack(localVideoTrack);
localParticipant.addAudioTrack(localAudioTrack);
```

Let me know if you need any other help.

Thanks!

**Comment by aaalaniz** [comment]
I'm closing this issue @sudheeshdh 

Feel free to reopen if you have any further questions.

Thanks!

**Comment by sudheeshdh** [comment]
Hi,

I am getting high noise while two android devices are connected to each
other in a small distance. I have enabled the speakerphone in the device,
how can I solve this issue,
code that I have tried is specified below,

private void configureAudio(boolean enable) {
    if (enable) {
        // Request audio focus before making any device switch.
        audioManager.requestAudioFocus(null, AudioManager.STREAM_VOICE_CALL,
                AudioManager.AUDIOFOCUS_GAIN_TRANSIENT);
        /*
         * Use MODE_IN_COMMUNICATION as the default audio mode. It is required
         * to be in this mode when playout and/or recording starts for the best
         * possible VoIP performance. Some devices have difficulties with
         * speaker mode if this is not set.
         */
        audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
        audioManager.setSpeakerphoneOn(true);
    } else {
        audioManager.setMode(AudioManager.MODE_NORMAL);
        audioManager.abandonAudioFocus(null);
        audioManager.setSpeakerphoneOn(false);
    }
}

**Comment by aaalaniz** [comment]
Hey @sudheeshdh 

Echo cancellation is performed while sharing audio between between participants. However, echo cancellation will not work if the devices are close to each other. Devices should be in separate rooms in order for echo to not occur. This is a known issue that is unavoidable and troublesome for local development. If you are experiencing echo with devices that are in separate rooms please file a separate issue and include the device information so we can investigate further.

Thanks!
