### ISSUE TITLE
Video flickers when there are more people in room

### ISSUE THREAD

**Issue by kesh-1139** [twilio/video-quickstart-android#156]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

Video flickering is seen when there are more people in the room

I am using twill video sdk. There are two phases of video in the application, one is minimised mode and the other is maximised mode. At any given point of time only one video will shown in maximised mode and all other videos will shown in minimised mode.

Avatars are placed inside android recycler view and their minimised videos are shown in avatars.

Video works fine until there are three users in the room showing video. But when the fourth user joins the room video showing in the avatar starts flickering, we do not know the reason for this and need your help in figuring out whats gong wrong. Logic seems fine. Is it the reason that we are using recycler view and we are notifying avatars when ever user joins the room, when another user starts video, when user leaves room causing this flickering. Please help us in getting rid of this issue. 

### Steps to Reproduce

1. Have 3 people in room showing video, 1 user will be showing video in full screen and rest will be showing video and will be in avatar (all avatars are placed inside recycler view)
2. 4th user enters room video of the existing users starts to flicker in avatar, also happens when 4th user starts showing video
3. [Insert as many steps as needed]

#### Code

Adding user in recycler view
```
if (!isUserNeedsToBeAdded) {
                                if (user.getJID().equalsIgnoreCase(PreferenceHandler.getXMPPUserName(activity))) {
  profilePicRecyclerViewAdapter.list.add(0, user);
 profilePicRecyclerViewAdapter.notifyItemInserted(0);
 profilePicRecyclerViewAdapter.notifyItemRangeChanged(0, profilePicRecyclerViewAdapter.list.size());
 profilePicRecyclerViewAdapter.notifyItemChanged(0);
} else {
 user.userShowingStatus = false;
user.userJustEntered = true;
 profilePicRecyclerViewAdapter.list.add(user);
profilePicRecyclerViewAdapter.notifyItemInserted(profilePicRecyclerViewAdapter.list.size());
 //profilePicRecyclerViewAdapter.notifyItemRangeChanged(1, profilePicRecyclerViewAdapter.list.size());
 //profilePicRecyclerViewAdapter.notifyItemChanged(1);
  }
```
### removing user
```
if (userLeftOrStatusIndex != -1) {
 user.userJustEntered = false;
 user.userShowingStatus = false;
 //profilePicRecyclerViewAdapter.list.remove(userLeftOrStatusIndex);
 //profilePicRecyclerView.removeViewAt(userLeftOrStatusIndex);
 profilePicRecyclerViewAdapter.notifyItemRemoved(userLeftOrStatusIndex);                        profilePicRecyclerViewAdapter.remove(profilePicRecyclerViewAdapter.getItem(userLeftOrStatusIndex));
 //profilePicRecyclerViewAdapter.notifyItemRangeChanged(userLeftOrStatusIndex, profilePicRecyclerViewAdapter.list.size());
profilePicRecyclerViewAdapter.notifyItemRangeRemoved(userLeftOrStatusIndex, profilePicRecyclerViewAdapter.list.size());
}
```

### starting video in avatar
```
 if (userLeftOrStatusIndex != -1) {
 LivesessionUser livesessionUser = user;
  livesessionUser.userJustEntered = false;
 livesessionUser.goingMiniScreen = true;
 profilePicRecyclerViewAdapter.notifyItemChanged(userLeftOrStatusIndex);
  //profilePicRecyclerViewAdapter.notifyDataSetChanged();
}
```

### Adding renderer in onBindViewHolder on recyclerView for avatar
```
position is obtained by holder.getAdapterPosition
and based on unique id i.e jid we get specific users video track
```
## Adding renderer
```
//add streaming on avatar, with camera selection same as before
holder.incomingStreamView.setMirror(false);
if (va.videoTrackList.get(jid) != null) {
 va.videoTrackList.get(jid).addRenderer(holder.incomingStreamView);
holder.incomingStreamView.setVisibility(View.VISIBLE);
 }
// store the view
va.PrimaryVideoView.put(jid, holder.incomingStreamView);
va.videoTrackList.put(PreferenceHandler.getXMPPUserName(BaseActivity.mCurrentActivity), va.localVideoTrack);
```
#### Expected Behaviour
Video should not flicker

#### Actual Behavior
video starts flickering and becomes unusable

#### Reproduces how Often
99 %

### Versions

All relevant version information for issue.

#### Video Android SDK
latest

#### Android API
latest

#### Android Device
On All devices

**Comment by aaalaniz** [comment]
Hey @kesh-1139 

I think the problem may be that you have a `VideoView` renderering multiple video tracks which is causing the video to "flicker". Because a `RecyclerView` is using the ViewHolder pattern, when `onBindViewHolder` is called after the 4th user joined you are likely using a VideoView that is rendering a previous user's video. I think the fix is to just call `removeRenderer(holder.incomingStreamView)` before adding the new renderer.

Here is a simple example of how to properly use `VideoView` in a `RecyclerView`. 

[VideoView used in RecyclerView](https://gist.github.com/aaalaniz/b779b12d2887c32576ffa4d5828b88c1)

**Comment by kesh-1139** [comment]
@aaalaniz  Thanks a lot for such a quick reply. Thanks a lot for that solution. I seem to have fixed it some what by using ```setHasStableIds(true)``` in the constructor.  calling ```NotifyDataSetChanged``` is causing the problem.

I will try the solution which you have mentioned and will get back to you. I had tried this solution before but I had tried it just before I removed the renderer and not at the start of ```bindViewHolder``` method. Will try that. Thanks a lot.

**Comment by aaalaniz** [comment]
Hey @kesh-1139 

Were you able to resolve the flickering?

Thanks!

**Comment by kesh-1139** [comment]
Hey @aaalaniz  I have tried the solution you had mentioned. it works fine for all the cases. I am seeing flickering in only one scenario that is when a user leaves the room, if the avatar next to the person who leaves is streaming then that avatar flickers. Any idea on this? Thanks a lot for helping out.

**Comment by aaalaniz** [comment]
Hey @kesh-1139 

Be sure to remove the renderer of the user who leaves the room. You should remove the renderer before calling `notifyItemRemoved`.

Hope this helps.

**Comment by kesh-1139** [comment]
@aaalaniz sure will try this and let you know if this fixed the issue. Thanks a lot for the help.

**Comment by kesh-1139** [comment]
@aaalaniz  I tried the solution which you had mentioned the flickering has stopped in many devices but still is sen in few devices.

**Comment by aaalaniz** [comment]
Hey @kesh-1139 

I am closing this issue. Please re-open if you have any further questions. Thanks!
