### ISSUE TITLE
Enable/Disable Flash in Android 

### ISSUE THREAD

**Issue by sudheeshdh** [twilio/video-quickstart-android#161]
How can I enable/ disable the flash feature using  the android sdk.

**Comment by aaalaniz** [comment]
Hi @sudheeshdh 

I recommend referencing our [Advanced Camera Capturer Example](https://github.com/twilio/video-quickstart-android/tree/master/exampleAdvancedCameraCapturer). The example demonstrates how to toggle the flash using `CameraCapturer#updateParameters`. Please note that the ability to enable/disable flash is not yet available for `Camera2Capturer`.

Thanks!
