### ISSUE TITLE
Query for making REST API calls

### ISSUE THREAD

**Issue by sudheeshdh** [twilio/video-quickstart-android#162]
Hi,
I have tried the REST APIs for creating a new Room in the programmable video feature. I got the success result from  Twilio server but the  server didn't choose the room name that I have provided. It will automatically choose the room sid as the unique name. I have used POSTMAN for testing the rest API's.

URL : https://video.twilio.com/v1/Rooms
Method : POST
```
{
    "unique_name": "meetings",
    "max_participants": 50,
    "record_participants_on_connect": true,
    "type": "group"
}
```
Response I am getting 
```
{
    "status": "in-progress",
    "unique_name": "RM25986e9edd2d7f15f0ec033e7c31a073",
    "date_updated": "2017-09-19T10:14:56Z",
    "max_participants": 50,
    "record_participants_on_connect": false,
    "enable_turn": true,
    "account_sid": "AC4ead1dffe26d4ad2207e53eb4aefd90d",
    "url": "https://video.twilio.com/v1/Rooms/RM25986e9edd2d7f15f0ec033e7c31a073",
    "end_time": null,
    "sid": "RM25986e9edd2d7f15f0ec033e7c31a073",
    "duration": null,
    "date_created": "2017-09-19T10:14:56Z",
    "type": "group",
    "status_callback_method": "POST",
    "status_callback": null,
    "links": {
        "recordings": "https://video.twilio.com/v1/Rooms/RM25986e9edd2d7f15f0ec033e7c31a073/Recordings"
    }
}
```

**Comment by aaalaniz** [comment]
Hey @sudheeshdh 

To create a Room with a name the parameter needs to be `UniqueName` and not `unique_name`. For more details please see our [REST API documentation](https://www.twilio.com/docs/api/video/rooms-resource).

Thanks!

**Comment by sudheeshdh** [comment]
yes I have also tried with UniqueName but not getting the expected result.

**Comment by aaalaniz** [comment]
Hey @sudheeshdh 

Please check that you are submitting the parameters as form url encoded parameters.

**Comment by sudheeshdh** [comment]
@aaalaniz 
Thanks for the  information. Its worked, I had used json formated data for creating the room name now I have change to url encoded parameters and its working fine.
