### ISSUE TITLE
Unable to use setZOrderOnTop on VideoView

### ISSUE THREAD

**Issue by malcolmnguyen** [twilio/video-quickstart-android#164]
### Description

I'd like the one of the VideoViews to be on top of the UI window. In order to this we have to be able to `setZOrderOnTop`, however `VideoView.applyZOrder` uses the `setZOrderMediaOverlay` method which overrides `setZOrderOnTop`, this instead puts the surface below the window, but above other surface views. Im not sure when `applyZOrder` is being called but its overriding the desired effect im looking for.

[StackOverFlow](https://stackoverflow.com/questions/5647824/android-multiple-surfaceviews/22746240#22746240)

#### Code

```java
        this.remoteView.applyZOrder(false);
        this.localView.setZOrderOnTop(true);
```

#### Expected Behavior

ViewGroup(Top to bottom) is:

- localView
- UI
- remoteView
- Window

#### Actual Behavior

ViewGroup(Top to bottom) is:

- UI
- localView
- remoteView
- Window

#### Reproduces how Often
100%

#### Video Android SDK

[1.3.1]

#### Android API

[SDK 25]

#### Android Device

[Nexus 6, Google Pixel]

**Comment by aaalaniz** [comment]
Hey @malcolmnguyen 

`applyZOrder` is called in `onAttachedToWindow`. Are you calling `setZOrderOnTop` before adding the `VideoView` to the view hierarchy? Doing this would cause the call to `setZOrderOnTop` to be overwritten when `localView` is attached to window.

**Comment by malcolmnguyen** [comment]
Hi @aaalaniz 

I've tried both before its added and in `onAttachedToWindow` but no luck, The developer docs say 

> Note that this must be set before the surface view's containing
     * window is attached to the window manager.

So would calling it in `onAttachedToWindow` not take effect?

**Comment by aaalaniz** [comment]
Hey @malcolmnguyen 

I'll have to investigate this further. Can you send me a simple layout file that would reproduce the ordering issue?

Thanks!

**Comment by malcolmnguyen** [comment]
One thing to note is that this came up on Android Oreo and that the views Z order seems to be reversed on Oreo and pre Oreo.

Heres a few versions that i've tried, this one we just add the remoteView and localView programmatically to the root of the framelayout.

`<merge>

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="This text should be on top of remote video but below local video" />

</merge>
`

This is how the view used to be, adding the remoteView and localVideo to their respective containers. This one works on pre-Oreo, but on Oreo local_video_root doesn't render.

`<merge >

    <FrameLayout
        android:id="@+id/remote_video_root"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="This text should be on top of remote video but below local video" />

    <FrameLayout
        android:id="@+id/local_video_root"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</merge>
`

**Comment by aaalaniz** [comment]
Hey @malcolmnguyen 

Did you resolve the issue?
