### ISSUE TITLE
Flickering on the VideoView 

### ISSUE THREAD

**Issue by sudheeshdh** [twilio/video-quickstart-android#167]
My video view getting flickering while loading the video. I have used only to view the video from the  viewers side.

just added the videoview at the time on videotrackAdded  event.

` videoTrack.addRenderer(primaryVideoView);`

Why the Video view flickers ? Any condition for this?

**Comment by aaalaniz** [comment]
Hey @sudheeshdh 

I believe this issue is a duplicate of #156. Please follow the guidance issued in that ticket and see your problem still occurs.
