### ISSUE TITLE
Rotate a Video in  com.twilio.video.VideoView

### ISSUE THREAD

**Issue by padhur** [twilio/video-quickstart-android#168]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

### Description

I am having a dongle which runs on Andorid OS which has a HDMI output port.
via HDMI port its connected to a TV which is mounted.
USB camera is connected to the dongle and its mounted in zero degree(i.e Landscape).

Created a LocalVideoTrack as below and the rendered preview is rotated.

streamingVideoTrack = LocalVideoTrack.create(this, true, streamingcontroller.startstreaming(),setvideoConstraints);

There is no issue if the TV is mounted in Landscape and camera is mounted in Landscape.

There is an rotation issue am observing if the TV is mounted in Portrait and the camera is mounted in landscape(cannot change the mount angle, its fixed)

### Steps to Reproduce
Please check the above description
#### Code

```java
// Code that help reproduce the issue
```

#### Expected Behavior
Need an API to rotate the video view

#### Actual Behavior
Not able to rotate a video using videoview
[What actually happens]

#### Reproduces how Often
Always
#### Logs

```
// Log output when issue occurs
```

### Versions

All relevant version information for issue.

#### Video Android SDK
1.3 
API level 22

Customized Android devices dongle

**Comment by aaalaniz** [comment]
Hey @padhur 

Can you try using the [setRequestedOrientation](https://developer.android.com/reference/android/app/Activity.html#setRequestedOrientation(int)) API? This API should force the activity to update the orientation of the device.

Let me know if this helps.

**Comment by idelgado** [comment]
Please reopen if you have additional questions.
