### ISSUE TITLE
How to enable Recording audio and video using SDK

### ISSUE THREAD

**Issue by sabodh** [twilio/video-quickstart-android#169]
Hi,
I am trying to record the audio and video session using android sdk . How can I achieve this ?
How can I provide the flag `RecordParticipantOnConnect=true`  to the `ConnectOptions `

**Comment by sabodh** [comment]
I have configured It using accounts dashboard and it set as true always.
Any way we can disable this through sdk for a particular room?

**Comment by aaalaniz** [comment]
Hey @sabodh 

It is currently not possible to enable or disable recording using our Video SDKs. You will have to use the REST API to configure recording on a particular room.

Thanks!

**Comment by sabodh** [comment]
Ok. How long the recording will be stored in the twilio server?
also is there is any way to move the recordings to an external server like amazon s3 instance ?

**Comment by aaalaniz** [comment]
Hey @sabodh 

Let me talk to our backend team. I'll have an answer for you shortly.

Thanks!

**Comment by aaalaniz** [comment]
Hey @sabodh 

The recording files stay on our backend until you delete them. We are adding external Amazon S3 integration soon. With this new feature, the recordings would be deposited directly on to your S3 buckets.

Hope this helps. I will close this issue. Thanks!
