### ISSUE TITLE
Unable to hear voice in Android client in all devices.

### ISSUE THREAD

**Issue by O-liverQueen** [twilio/video-quickstart-android#172]
Description
    I am trying to use video call. Here i am connecting the users from web to android. User and admin can connect to the same room. This feature is implemented, and i am able to see the video on both ends(web and android). 
Here Web is admin and android is client.
But, for audio, in web app i am able to hear voice, but in android i am unable to hear the voice.

I used the video-quick-start-android for implementing this in android.
 
Is there any thing extra i need to add for listening voice in android?
I am using MODE_IN_COMMUNICATION & STREAM_VOICE_CALL for setting the audioManager.

Thanks in advance.

**Comment by aaalaniz** [comment]
Hey @O-liverQueen 

I recommend referencing our [Troubleshooting Audio guide](https://github.com/twilio/video-quickstart-android#troubleshooting-audio) for optimal audio experience in your application. If you are still having issues can you provide the device information on which you are experiencing audio problems.

Thanks!

**Comment by O-liverQueen** [comment]
Hi @aaalaniz 

thanks for replying back. As you mentioned to use the settings from "Troubleshooting Audio guide", I am using the same settings in Android.

Sorry @aaalaniz  after searching a lot, and reading the documents of twilio for audio configure, whatever i added in android code is correct based on the quickstart for video.
The porblem is i think we are unable to enable the microphone in web, that is the reason we are facing this issue.

Thanks.
