### ISSUE TITLE
Recording video and audio details

### ISSUE THREAD

**Issue by sudheeshdh** [twilio/video-quickstart-android#173]
Hi 
The response of recording the API contain both video and audio url separately. I reviewed the issue #136 
Any progress on this ? Can I get a url that contain both video and audio ?

**Comment by aaalaniz** [comment]
Hey @sudheeshdh 

This feature is still a work in progress.

**Comment by BhanuVGowda** [comment]
Any updates on this one, please.

**Comment by rfbrazier** [comment]
This is the next major feature to be released in our Recordings API, likely available early next year. 

In the meantime, you can use tools like [ffmpeg](https://www.ffmpeg.org/) to compose the raw track-level recordings into a single container. We'll be publishing a guide on our website on this soon.

Thanks for using Twilio Video, and your patience as we work on these enhancements.

**Comment by jasminpsimform** [comment]
Any update on this one.

**Comment by shaelhaldkar** [comment]
please update on this

**Comment by shaelhaldkar** [comment]
Also please share the link to mux audio video using ffmpeg

**Comment by aaalaniz** [comment]
Hey @shaelhaldkar 

I apologize. I should have updated this issue when we announced [Programmable Video Compositions API](https://www.twilio.com/blog/2018/05/group-room-video-compositions-api.html). I recommend reading the [Video compositions API docs](https://www.twilio.com/docs/video/api/compositions-resource).

I will be happy to field any follow up questions about the compositions API. 

Thanks!
