### ISSUE TITLE
Feature Request: takePicture on camera2

### ISSUE THREAD

**Issue by seanadkinson** [twilio/video-quickstart-android#174]
I see `takePicture` is implemented on the deprecated camera api.  Any plans and/or example code of anyone use `camera2` for taking a screenshot?

Google has an example here: https://github.com/googlesamples/android-Camera2Basic/blob/master/Application/src/main/java/com/example/android/camera2basic/Camera2BasicFragment.java#L768

But I'm hoping Twilio Video can abstract the details.

Thanks!

**Comment by aaalaniz** [comment]
Hey @seanadkinson 

We do have a task in our backlog to add this functionality. The goal is for `Camera2Capturer` to have feature parity with `CameraCapturer`. I will update you with progress on this functionality.

Thanks!

**Comment by BrunoTrovoN26** [comment]
Hi @aaalaniz !
Any news about this feature?

**Comment by aaalaniz** [comment]
Hey @BrunoTrovoN26 

Unfortunately, no update on this feature.

**Comment by altunemreInvaco** [comment]
Hi, 
Any new  about the feature ?

**Comment by aaalaniz** [comment]
Hey @altunemreInvaco 

This feature has been removed from the roadmap. I will close the issue and reopen if anything changes.

Thank you
