### ISSUE TITLE
participant.getVideoTracks() always empty

### ISSUE THREAD

**Issue by Amirale-Veri** [twilio/video-quickstart-android#175]
Is there any reason why I am always getting no video track for any participant joining my room?
My code is bellow:
private void joinParticipant(Participant participant) {

        if (participant.getVideoTracks().size() > 0) {
            supplyLocals(true);
            participant.getVideoTracks().get(0).addRenderer(mainVideoView);
        }
      
        Log.e(TAG, participant.getIdentity()+" Participant has video track " + !(participant.getVideoTracks().isEmpty()));
        participant.setListener(participantListener);
    }

#### Reproduces how Often

[100%]

### Versions

All relevant version information for issue.

#### Video Android SDK

[1.0.2]

#### Android API

[26]

#### Android Device

[Pixel]

**Comment by aaalaniz** [comment]
Hey @Amirale-Veri 

`getVideoTracks` returns the added video tracks of that participant. Are you connecting with video tracks and seeing that the other participants do not see these tracks? Also can you update to the latest SDK version? (1.3.3)

Thanks!

**Comment by Amirale-Veri** [comment]
I am updating to V 1.3.3 then will see, I am just following your code sample that I found on git, but no chance to get videoTracks. I will come back to you later one. Also please let me know where can I find an example to add videoTracks, maybe I am doing them wrong.

**Comment by aaalaniz** [comment]
Hey @Amirale-Veri 

Please reference our [connectToRoom](https://github.com/twilio/video-quickstart-android/blob/master/quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java#L276) method in our quickstart for how to properly connect to a Room with audio and video tracks, and the [logic in onResume](https://github.com/twilio/video-quickstart-android/blob/master/quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java#L160) for how to publish video tracks to a Room.

Thanks!

**Comment by aaalaniz** [comment]
Hey @Amirale-Veri 

I'm going to close this issue for now. Please re-open if you still experience any issues.

Thanks!
