### ISSUE TITLE
Problem with video call. supported formats could not be retrieved because an error occurred connecting to the camera service

### ISSUE THREAD

**Issue by viktord1985** [twilio/video-quickstart-android#180]
I have this error when I try to make video call with front camera: Supported formats could not be retrieved because an error occurred connecting to the camera service. The crash is on second field.
```
CameraCapturer cameraCapturer = new CameraCapturer(this, CameraCapturer.CameraSource.FRONT_CAMERA);
LocalVideoTrack localVideoTrack = LocalVideoTrack.create(this, true, cameraCapturer);
```
If I changing **FRONT_CAMERA** to **BACK_CAMERA** it works well. I have tested it on Nexus 5 and Galaxy s7 and it have the same crash.
I am using `com.twilio:video-android:1.2.0`

**Comment by idelgado** [comment]
We fixed an issue that might be related to this in `1.3.1` https://www.twilio.com/docs/api/video/changelogs/android#131-september-14-2017. Please upgrade to the latest `1.3.3` and let us know if you still have an issue.

**Comment by viktord1985** [comment]
Crash steal on version `1.3.3`. It crashes when outgoing call, and mostly works well on incoming call.

**Comment by aaalaniz** [comment]
Hey @viktord1985 

Can you provide more details on the steps leading up to the crash? Are you using the camera in another part of your application before setting up a call? Can you include a full logcat output as well?

Thanks!

**Comment by viktord1985** [comment]
It not depends on using camera in another part, as I reboot my device and setting up an app it also crashes. Here is log from activity, where I making call. Thanks.
[full log.pdf](https://github.com/twilio/video-quickstart-android/files/1379437/full.log.pdf)

**Comment by aaalaniz** [comment]
hey @viktord1985 

Does this happen on every device you run your app on? Can you share a snippet showing the reproduction steps?

**Comment by viktord1985** [comment]
Yes, on 3 devices it crashes: Lenovo p780, Samsung Galaxy S7 and Nexus 5
Those method I call in onCreate()
```
private void createLocalMedia() {
        // Share your microphone
        localAudioTrack = LocalAudioTrack.create(this, true);

        // Share your camera
        cameraCapturer = new CameraCapturer(this, CameraCapturer.CameraSource.FRONT_CAMERA);
        localVideoTrack = LocalVideoTrack.create(this, true, cameraCapturer);
        primaryVideoView.setMirror(true);
        localVideoTrack.addRenderer(primaryVideoView);
        localVideoView = primaryVideoView;
    }
```
And it crashes on  `localVideoTrack = LocalVideoTrack.create(this, true, cameraCapturer);`

**Comment by viktord1985** [comment]
So, you do you working with this problem?

**Comment by aaalaniz** [comment]
Hey @viktord1985 

Can you try to reproduce this problem in the quickstart? The snippet you shared is code that runs frequently in our test cases. My guess is that the camera resource is not available when you try to create a video track. This could result from not calling `LocalVideoTrack#release()` or another component of your application using the camera resource while trying to create a video track.

**Comment by viktord1985** [comment]
I found the problem, it was on my side. Thanks for your help.

**Comment by rishabhja** [comment]
I am getting this issue in version 2.0.0-beta 5

**Comment by SanchezDeivis** [comment]
`private void createLocalTracks() {
        // Comparte tu micrófono
        localAudioTrack = LocalAudioTrack.create(this, true, LOCAL_AUDIO_TRACK_NAME);

        // Comparte tu cámara
        cameraCapturer = new CameraCapturer(this, getAvailableCameraSource());
        //localVideoTrack = LocalVideoTrack.create(this, true, cameraCapturer);
        localVideoTrack = LocalVideoTrack.create(ReceiveVideoCallMedicActivity.this,
                true,cameraCapturer);
        primaryVideoView.setMirror(true);
        localVideoTrack.addRenderer(primaryVideoView);
        localVideoView = primaryVideoView;
    }

    private CameraCapturer.CameraSource getAvailableCameraSource() {
        return (CameraCapturer.isSourceAvailable(CameraCapturer.CameraSource.FRONT_CAMERA)) ?
                (CameraCapturer.CameraSource.FRONT_CAMERA) :
                (CameraCapturer.CameraSource.BACK_CAMERA);
    }`
No se pudieron recuperar los formatos admitidos porque se produjo un error al conectarse al servicio de la cámara mientras el dispositivo estaba en segundo plano

**Comment by SanchezDeivis** [comment]
Caused by: java.lang.IllegalStateException: Supported formats could not be retrieved because an error occurred connecting to the camera service
