### ISSUE TITLE
onRecordingStarted and onRecordingStopped not called while connecting to the room.

### ISSUE THREAD

**Issue by sudheeshdh** [twilio/video-quickstart-android#187]
onRecordingStarted and onRecordingStopped not called after connecting to the room. The Participants will be recorded on connect is already set as true in the twilio console  but not able to identify the recording completed status from the twilio side.

**Comment by aaalaniz** [comment]
Hey @sudheeshdh 

Although these callbacks are part of the `Room.Listener` they are not yet implemented on our backend server. Therefore, you will never see these callbacks invoked. I apologize for how confusing this is.

Thanks!

**Comment by aaalaniz** [comment]
Hey @sudheeshdh 

If you have set Record Participants on Connect for a Group room `room.isRecording()` will return true. However, as mentioned in my previous comment there is currently no way to enable recording while connected to a `Room` so these callbacks are never invoked.

**Comment by sudheeshdh** [comment]
Ok, Thanks for the response.
I had done this using the local API calls in my own server  and I got the recording media urls from the twilio server.But some times while accessing the recordings from the twilio server cause file not found exception.This is only happen when I am accessing the URL with in a time period of 5 seconds after disconnecting from the room. Some times it will cause more than 10 seconds. Why this happen and how can I resolve this ?

**Comment by idelgado** [comment]
@sudheeshdh Based on the behavior you are describing it sounds like the recordings are still being processed and may not be available immediately after the media has stopped flowing through the Room media server.

You can listen for status callbacks on your server and get a `recording-completed` callback which should then allow you to successfully retrieve the recording.

https://www.twilio.com/docs/api/video/status-callbacks#rooms-status-callback-events

**Comment by sudheeshdh** [comment]
I have provided the  callback url in the twilio console, but its not invoked . I hope this is because I am creating the room using the  mobile SDKs.

**Comment by sudheeshdh** [comment]
Hey,
Any suggestions for this issue?

**Comment by idelgado** [comment]
There are 2 ways to enable recording for a room.

The first is to enable it by default for all rooms in the console https://www.twilio.com/console/video/configure:
<img width="600" alt="screen shot 2017-10-31 at 11 26 55 am" src="https://user-images.githubusercontent.com/882552/32232517-9524a14c-be2e-11e7-8645-596aeb8b9f35.png">

The second is to use the REST API prior to joining a room and set recording to enabled. 
```
curl -XPOST 'https://video.twilio.com/v1/Rooms' \
  -u 'SKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:your_api_key_secret' \
  -d 'UniqueName=DailyStandup' \
  -d 'Type=group' \
  -d 'RecordParticipantsOnConnect=true' \
  -d 'StatusCallback=http://example.org'
```

**Comment by sudheeshdh** [comment]
Hey @idelgado 
The problem is not related to the creation of recordings. I had enabled the recordings using the twilio room console. The problem is recordings are still being processed and may not be available immediately after the media has stopped flowing through the Room media server. How can we handle this?
Also I had provided the callback url directly to the console 
[https://www.twilio.com/console/video/configure] .But the provided call back url is not invoked on the specified events based on the documents.

**Comment by idelgado** [comment]
@sudheeshdh are any events listed https://www.twilio.com/docs/api/video/status-callbacks invoked on your callback url?

**Comment by sudheeshdh** [comment]
@idelgado No, If I am creating the room with the help of android sdk it doesn't invoked any event specified in the documents. But I got the successful callback when creating the room with the help of REST APIs.

**Comment by innerverse** [comment]
Hi @sudheeshdh

Sorry to hear you're running into issues with status callback URLs and recordings. Let's see if I can help.

Status Callback URLs
---

The Twilio will send Status Callbacks to your URL as long as it is set for your Room. You can set the URL a few ways - via the REST API but we also apply the Room Settings from the Console if you create the Room dynamically via the SDKs.
One catch is that the Access Token determines which setting to use.

- Verify the AccountSid used in your Token Server matches the AccountSid in the Twilio Console where you’re adjusting the Room Settings
- If you’re somehow still using our deprecated ConfigurationSid in your Token server, look in the (deprecated) Twilio Console Configuration Profile section.  This will only appear if you’ve started with Conversations in our early beta.


Recordings
---

I’d like to offer some assurance that once you receive the `recording-completed` Status Callback at your URL, the recording file is ready to download.  

Here’s an example callback as as GET command:

    
    GET /?MediaUri=/v1/Recordings/RTxxxx/Media&RoomSid=RMxxxx
        &SourceSid=MTxxxx
        &Size=242002
        &RecordingSid=RTxxxx
        &Duration=44.0
        &StatusCallbackEvent=recording-completed
        &Timestamp=2017-11-01T20:07:50.366Z
        &AccountSid=ACxxxx
        &RecordingUri=/v1/Recordings/RTxxxx
        &Codec=opus&Container=mka
        &ParticipantSid=PAxxxx
    

Here’s the `curl` command that will allow you to retrieve the recording:

    curl https://video.twilio.com/v1/Recordings/RTxx/Media 
        -u SKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:your_api_key_secret 
        -L 
        --output audio.mka

You can also use the language specific helper libraries - if you already are, can I ask which language and helper library you’re having trouble with?

If you can send us your AccountSid, we can look further into what may be happening for you.

Hope this helps,
Seth @ Twilio

**Comment by aaalaniz** [comment]
Thanks for the help @innerverse and @idelgado. I'm closing this ticket. @sudheeshdh please reopen if you have any further questions.

Thanks!
