### ISSUE TITLE
Is there a APK Available for Android ?

### ISSUE THREAD

**Issue by ajaypramod** [twilio/video-quickstart-android#190]
Would love to see a APK where i can just paste my API Key and Room Name and Test the App.

While the Quick-start App is good for developers. A Sample APK or Google Play Test App is good for Product Guys to evaluate the potential of Twilio Video related API's.

**Comment by idelgado** [comment]
Unfortunately there is no sample app on the Play Store at the moment. We plan on releasing an app along with the source code to build a more advanced app that leverages a large portion of the SDK soon. I will update the ticket once it becomes available.

**Comment by ervingayle** [comment]
We actually were contemplating doing this as a community contribution. Our platform is available along with the app and we were looking for some community feedback for testing. This may help us and provide feedback needed for v2 api's. Happy to contribute if it is of value

**Comment by idelgado** [comment]
@ervingayle that would be great. We're always open to contributions from our developer community.

**Comment by ervingayle** [comment]
@idelgado I am happy to contribute here.  The OP requested a APK and thats when I thought of sharing what we've done.

Our platform is build around packaging Twilio service offerings particularly for Higher Education but the consumption of the services is pretty much white label. Our app is currently available for Android: https://play.google.com/store/apps/details?id=com.enotchacademics.enotch. iOS coming soon along with updates for DataTracks & Chat.

Using the App you can Create, Join & view history of Video Rooms. The same functionality and more is available in the UI as well. Twilio API Keys should be kept sensitive so at least one user will need to register for a "tenant" which is your isolated area, enter their api key information and then from the app you can connect as a registered user or guest to the platform for the purposes of sharing Video, etc. Simply share the room name and you can connect.

Registration is available via this link: https://goo.gl/q5sSCd

**Comment by idelgado** [comment]
@ervingayle Thanks for this contribution. In 2018 we will be releasing a multi-party sample app as well as a more advanced meeting app source and play store app that will hopefully serve this request better. We'll update this ticket once we make this available. Thanks!

**Comment by aaalaniz** [comment]
We now provide a [multiparty example](https://github.com/twilio/video-quickstart-android/tree/master/exampleMultipartyVideo). However, publishing an app to the Play Store is still a ways out. I will close this issue for now.
