### ISSUE TITLE
Setting VideoScaleType not working

### ISSUE THREAD

**Issue by alestab** [twilio/video-quickstart-android#197]
### Description

Calling setVideoScaleType on primaryVideoView in quickstart sample has no effect.

Video rendered in primaryView doesn't fit and gets cutted in one dimension. 

#### Video Android SDK

2.0.0-preview4

**Comment by aaalaniz** [comment]
Hey @alestab 

Can you post a screenshot of the problem you are seeing? Does it happen for remote or local video?

Thanks!

**Comment by alestab** [comment]
Hi @aaalaniz 

This happens with local video. Camera aspect ratio is 4:3 . Video sent to remote partecipant is ok, so at the receiver with the examples below in portrait Kenny has some more space at his left and right, and in landscape his head and feet aren't cropped. 
I changed a bit the example to keep local video as primaryVideoView also when a remote partecipant joins. 
I expected that aspect ratio of rendered video was kept, adding black bars to fill te empty space.

Setting any value of VideoScaleType to primaryVideoView has no effect.

Am I missing something?

thank you!

![screenshot_20171109-115826](https://user-images.githubusercontent.com/33481676/32602362-29acce2a-c546-11e7-855c-b154f1ac3e65.png)
![screenshot_20171109-115706](https://user-images.githubusercontent.com/33481676/32602363-29c73e4a-c546-11e7-8dcf-365371bdd280.png)

**Comment by aaalaniz** [comment]
Hey @alestab 

I'll investigate this issue further today. Thanks for the screenshots. Definitely one of the better screenshots I've seen lol

Thanks!

**Comment by aaalaniz** [comment]
Hey @alestab 

Apologies for the delay. I think I have found the problem. I will have an answer for you soon.

Thanks!

**Comment by aaalaniz** [comment]
Hey @alestab 

Have a look at the latest PR #201 

It appears that using `match_parent` causes problems with updating video scale type. If you use `wrap_content` or a specific value for width and height dimensions you should be fine to call `setVideoScaleType`. Our next 1.x and 2.x releases will have updated API docs and will log a warning if developers try to call `setVideoScaleType` and `match_parent` is used.

A similar [bug was filed in WebRTC project](https://bugs.chromium.org/p/webrtc/issues/detail?id=7901&can=1&q=setScalingType&colspec=ID%20Pri%20M%20ReleaseBlock%20Component%20Status%20Owner%20Summary). I recommend referencing the bug and subsequent change set if you want any more details.

Thanks!

**Comment by alestab** [comment]
Hi @aaalaniz 
thank you for your answer!

**Comment by aaalaniz** [comment]
No problem @alestab 

I'm going to close this issue. Please reopen if you encounter additional problems.

Thanks!

**Comment by yukitaka13-1110** [comment]
@aaalaniz @alestab 
`ASPECT_FILL` and `ASPECT_FIT` could work but `ASPECT_BALANCED` not working.
Could you check it out for me?
