### ISSUE TITLE
EncodingParameters in ConnectOptions

### ISSUE THREAD

**Issue by emphassis** [twilio/video-quickstart-android#200]
In Java there are options to control the data flow using the connect options. Example below:
`var connectOptions = {
                    name: roomName,
                    tracks: twilioLocalMediaTracks,
                    maxAudioBitrate: 24000,
                    maxVideoBitrate: 128000
                };

                Twilio.Video.connect(token, connectOptions).then(roomJoined, function (error) {
                    handleError("[Twilio.Video.connect]: " + error.message);
                });`

In Android, it seems that there is a class that controls these options and the Bitrate is completely absent. These are all the options I see. I am using the Twilio Android SDK version 1.3.6.

`        ConnectOptions.Builder connectOptionsBuilder = new ConnectOptions.Builder(accessToken)
                .roomName(roomName)
                .videoTracks()
                .iceOptions()
                .audioTracks()
                .enableInsights()
                .build();`

Am I missing something? How can I lower the bitrate for the Android SDK?

**Comment by idelgado** [comment]
@emphassis you can find docs on how to do this here: https://twilio.github.io/twilio-video-android/docs/2.0.0-preview5/com/twilio/video/EncodingParameters.html

Please note that this feature is only available in our 2.X preview releases on Android. We will move to beta and eventual final release early next year.

You can find the quickstart for 2.X in our 2.0 branch https://github.com/twilio/video-quickstart-android/tree/2.0

**Comment by idelgado** [comment]
Encoding parameters are part of the builder in 2.X https://twilio.github.io/twilio-video-android/docs/2.0.0-preview5/com/twilio/video/ConnectOptions.Builder.html

You can browse the root of the docs here: https://twilio.github.io/twilio-video-android/docs/2.0.0-preview5

**Comment by emphassis** [comment]
Hey, thanks for the quick response. I'm trying it out now. It seems you guys are really working this diligently. In this preview version, you're trying to fix the bugs as you find them?

**Comment by idelgado** [comment]
@emphassis Yes. Our 2.X preview releases are quite stable. However there may be API changes made in future preview releases and some of the features especially as they related to multiple/hybrid codec support in a Group Rooms environment, as opposed to Peer-to-peer, is still evolving. There are also cases where we are aware of corner cases that are not well covered yet like reporting error scenarios when negotiating different tracks(Audio, Video, Data tracks). However, in general you'll find that the library itself is quite stable and the exposed feature set is suitable for most customers.

We're working as quickly as possible to move this out of preview. We definitely welcome feedback during these release phases.

**Comment by aaalaniz** [comment]
Closing this issue. @emphassis please reopen if you have any other questions.

Thanks!
