### ISSUE TITLE
Connection to new user 

### ISSUE THREAD

**Issue by rohitlien** [twilio/video-quickstart-android#211]
Hii, I am using twilio to connect 10 people in same room but i want to control which user i want to shown in all windows.
For that ... i have connected all users with 
private void connectToRoom() {

        ConnectOptions.Builder connectOptionsBuilder = new ConnectOptions.Builder(accessToken)
                .roomName(room_name);
        room = Video.connect(this, connectOptionsBuilder.build(), roomListener());
        setDisconnectAction();
}

and when the user wants i do this : 
private void unmuteUser() {           
            if (room != null && room.getState() != RoomState.DISCONNECTED) {
                room.disconnect();
            }
            
            ConnectOptions.Builder connectOptionsBuilder = new ConnectOptions.Builder(accessToken)
                    .roomName(room_name);
            if (localAudioTrack != null) {
                connectOptionsBuilder
                        .audioTracks(Collections.singletonList(localAudioTrack));
            }
            if (localVideoTrack != null) {
                connectOptionsBuilder.videoTracks(Collections.singletonList(localVideoTrack));
            }
            room = Video.connect(this, connectOptionsBuilder.build(), roomListener());
}
But the problem is that i am getting :  participant.getVideoTracks().size()=0

Please help.

**Comment by aaalaniz** [comment]
Hey @rohitlien 

Do none of the participant's have video tracks when you call `getVideoTracks().size()` ? Are you connecting to a Peer-to-Peer or Group room? Please be sure that each of your participants is connecting with a `LocalVideoTrack`. Happy to field any follow up questions you have.

Thanks!

**Comment by rohitlien** [comment]
hey @aaalaniz 
I am connecting to a group and i am not connecting any videotrack of user in the beginning.
When a user request to be seen , then i disconnect the user and connect him once again with local video track.
But here the participant.getVideoTrack().size is zero.

**Comment by aaalaniz** [comment]
Hey @rohitlien 

Based on your use case, rather than disconnecting and reconnecting to a `Room` when a user requests to be seen, I recommend using the [LocalParticipant#addVideoTrack](https://twilio.github.io/twilio-video-android/docs/latest/com/twilio/video/LocalParticipant.html#addVideoTrack-com.twilio.video.LocalVideoTrack-) method. You can get the `LocalParticipant` after you have connected to a `Room`. Reference the following snippet:

```
// After connecting to room
LocalParticipant localParticipant = room.getLocalParticipant();

// Once user requests to be seen
LocalVideoTrack localVideoTrack = LocalVideoTrack.create(context, true, cameraCapturer);

// Share video track via local participant
localParticipant.addVideoTrack(localVideoTrack)

// At this point other connected participants should get onVideoTrackAdded event from Participant.Listener interface
```

Hope this helps. Thanks!

**Comment by rohitlien** [comment]
Hey @aaalaniz 
I dont know what was wrong in rejoining the room , but this worked. Thanks a lot.
