### ISSUE TITLE
closes the activity with warning

### ISSUE THREAD

**Issue by rohitlien** [twilio/video-quickstart-android#215]
hi @aaalaniz 
I have integrated twilio in our app but the problem is it keeps destroying the activity every now and then with warning : 

E/ExynosCameraMCPipe: [CAM_ID(1)][PIPE_3AA]-ERR(m_getBuffer[1960]):node(3AA_OUTPUT)->getBuffer() fail, index(19), frameCount(48147), ret(-1)

E/ExynosCameraMCPipe: [CAM_ID(1)][PIPE_3AA]-ERR(m_getBuffer[2092]):node(SCP_PREVIEW)->getBuffer() fail, index(3), frameCount(48147), ret(-1)

How can i prevent it?

**Comment by rohitlien** [comment]
This is my logs : 

12-06 23:24:57.774 7388-11732/com.rohit.test E/VOLLEY: Added request object
12-06 23:24:57.870 7388-11674/com.rohit.test W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[78,tid=11674,Native,Thread*=0x9ad3c800,peer=0x14004140,"IncomingVideoSt - 11674"]
12-06 23:24:58.272 7388-7388/com.rohit.test E/AIRTEL: User display name  rohitlien asdgfg
12-06 23:24:58.283 134-134/? E/hwcomposer: [HWC] ION is invalid (handle=0xb360d0a0, num=-1, idx=-1) !!
12-06 23:24:58.283 134-134/? W/hwcomposer: [HWC] Failed to get ION fd !! (handle=0xb360d0a0) !!
12-06 23:24:58.299 134-134/? E/hwcomposer: [HWC] ION is invalid (handle=0xb5d1b4c0, num=-1, idx=-1) !!

**Comment by aaalaniz** [comment]
Hey @rohitlien 

Can you describe what is happening in detail or provide some steps to reproduce? Please provide any code snippets as well. 

Thanks!

**Comment by rohitlien** [comment]
Hi @aaalaniz 
i am connecting two users to a room and wait a while like 10 minutes and it just dismisses the whole activity .I can't find anything more in the logs.

**Comment by aaalaniz** [comment]
Interesting @rohitlien 

...Is this issue reproducible in the quickstart? I can try to reproduce there.

**Comment by rohitlien** [comment]
Hi @aaalaniz 
I think not. The quickstart works fine.

**Comment by rohitlien** [comment]
Hi @aaalaniz 
i am getting this log : 

12-07 01:34:07.926 7388-7388/com.rohit.test I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = com.twilio.video.VideoView{396ebb94 V.E..... ........ 0,0-600,815 #7f0e043f app:id/primary_video_view}
12-07 01:34:27.235 7388-7405/com.rohit.test D/MessageLogger: Msg#:370665 <<<<< Finished to Handler (android.app.ActivityThread$H) {11d188f0} null from 2017-12-07 01:32:42.145 elapsedTime:85712 ms/upTime:85713ms
                                                                 Msg#:370655 <<<<< Finished to Handler (android.app.ActivityThread$H) {11d188f0} null from 2017-12-07 01:32:41.558 elapsedTime:491 ms/upTime:492ms
                                                                 Msg#:370349 <<<<< Finished to Handler (android.app.ActivityThread$H) {11d188f0} null from 2017-12-07 01:32:26.973 elapsedTime:7088 ms/upTime:7089ms

**Comment by rohitlien** [comment]
Hi @aaalaniz 
Is it possible that recording is messing up everything?
these are my logs : 
W/APM_AudioPolicyManager: startInput() HOTWORD will be blocked in call
12-07 15:58:34.323 13256-14124/? E/AudioRecord: start() status -22
12-07 15:58:34.324 13256-14124/? E/AudioProvider: recording stopped, not in RECORDSTATE_RECORDING state
12-07 15:58:34.327 2425-2425/? E/audio_hw_primary: adev_close_input_stream, set jack_in to null
12-07 15:58:35.266 2405-2405/? E/audit: type=1400 audit(1512642515.247:963943): avc:  denied  { ioctl } for  pid=17739 comm="Thread-45" path="socket:[15452202]" dev="sockfs" ino=15452202 ioctlcmd=8906 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app:s0:c512,c768 tclass=udp_socket permissive=0 SEPF_SECMOBILE_7.0_0009 audit_filtered
12-07 15:58:35.267 2405-2405/? E/audit: type=1300 audit(1512642515.247:963943): arch=40000028 syscall=54 per=8 success=no exit=-13 a0=d3 a1=8906 a2=b74ff218 a3=0 items=0 ppid=2397 pid=17739 auid=4294967295 uid=10707 gid=10707 euid=10707 suid=10707 fsuid=10707 egid=10707 sgid=10707 fsgid=10707 tty=(none) ses=4294967295 comm="Thread-45" exe="/system/bin/app_process32" subj=u:r:untrusted_app:s0:c512,c768 key=(null)
12-07 15:58:35.267 2405-2405/? E/audit: type=1327 audit(1512642515.247:963943): proctitle="com.oustme.oustsdk"
12-07 15:58:35.267 2405-2405/? E/audit: type=1400 audit(1512642515.247:963944): avc:  denied  { ioctl } for  pid=17739 comm="Thread-45" path="socket:[15452202]" dev="sockfs" ino=15452202 ioctlcmd=8906 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app:s0:c512,c768 tclass=udp_socket permissive=0 SEPF_SECMOBILE_7.0_0009 audit_filtered
12-07 15:58:35.267 2405-2405/? E/audit: type=1300 audit(1512642515.247:963944): arch=40000028 syscall=54 per=8 success=no exit=-13 a0=d3 a1=8906 a2=b74ff218 a3=0 items=0 ppid=2397 pid=17739 auid=4294967295 uid=10707 gid=10707 euid=10707 suid=10707 fsuid=10707 egid=10707 sgid=10707 fsgid=10707 tty=(none) ses=4294967295 comm="Thread-45" exe="/system/bin/app_process32" subj=u:r:untrusted_app:s0:c512,c768 key=(null)
12-07 15:58:35.267 2405-2405/? E/audit: type=1327 audit(1512642515.247:963944): proctitle="com.oustme.oustsdk"
12-07 15:58:35.267 2405-2405/? E/audit: type=1400 audit(1512642515.247:963945): avc:  denied  { ioctl } for  pid=17739 comm="Thread-45" path="socket:[15452202]" dev="sockfs" ino=15452202 ioctlcmd=8906 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app:s0:c512,c768 tclass=udp_socket permissive=0 SEPF_SECMOBILE_7.0_0009 audit_filtered
12-07 15:58:35.267 2405-2405/? E/audit: type=1300 audit(1512642515.247:963945): arch=40000028 syscall=54 per=8 success=no exit=-13 a0=d3 a1=8906 a2=b74ff218 a3=0 items=0 ppid=2397 pid=17739 auid=4294967295 uid=10707 gid=10707 euid=10707 suid=10707 fsuid=10707 egid=10707 sgid=10707 fsgid=10707 tty=(none) ses=4294967295 comm="Thread-45" exe="/system/bin/app_process32" subj=u:r:untrusted_app:s0:c512,c768 key=(null)
12-07 15:58:35.267 2405-2405/? E/audit: type=1327 audit(1512642515.247:963945): proctitle="com.oustme.oustsdk"
12-07 15:58:35.268 2405-2405/? E/audit: type=1400 audit(1512642515.247:963946): avc:  denied  { ioctl } for  pid=17739 comm="Thread-45" path="socket:[15452202]" dev="sockfs" ino=15452202 ioctlcmd=8906 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app:s0:c512,c768 tclass=udp_socket permissive=0 SEPF_SECMOBILE_7.0_0009 audit_filtered
12-07 15:58:35.268 2405-2405/? E/audit: type=1300 audit(1512642515.247:963946): arch=40000028 syscall=54 per=8 success=no exit=-13 a0=d3 a1=8906 a2=b74ff218 a3=0 items=0 ppid=2397 pid=17739 auid=4294967295 uid=10707 gid=10707 euid=10707 suid=10707 fsuid=10707 egid=10707 sgid=10707 fsgid=10707 tty=(none) ses=4294967295 comm="Thread-45" exe="/system/bin/app_process32" subj=u:r:untrusted_app:s0:c512,c768 key=(null)
12-07 15:58:35.268 2405-2405/? E/audit: type=1327 audit(1512642515.247:963946): proctitle="com.oustme.oustsdk"
12-07 15:58:35.273 2405-2405/? E/audit: type=1400 audit(1512642515.257:963947): avc:  denied  { ioctl } for  pid=17739 comm="Thread-45" path="socket:[15452202]" dev="sockfs" ino=15452202 ioctlcmd=8906 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app:s0:c512,c768 tclass=udp_socket permissive=0 SEPF_SECMOBILE_7.0_0009 audit_filtered
12-07 15:58:35.273 2405-2405/? E/audit: type=1300 audit(1512642515.257:963947): arch=40000028 syscall=54 per=8 success=no exit=-13 a0=d3 a1=8906 a2=b74ff218 a3=0 items=0 ppid=2397 pid=17739 auid=4294967295 uid=10707 gid=10707 euid=10707 suid=10707 fsuid=10707 egid=10707 sgid=10707 fsgid=10707 tty=(none) ses=4294967295 comm="Thread-45" exe="/system/bin/app_process32" subj=u:r:untrusted_app:s0:c512,c768 key=(null)
12-07 15:58:35.273 2405-2405/? E/audit: type=1327 audit(1512642515.257:963947): proctitle="com.oustme.oustsdk"
12-07 15:58:35.511 2436-18149/? W/libexynosv4l2: failed to ioctl: VIDIOC_DQBUF (22 - Invalid argument)
12-07 15:58:35.512 2436-18148/? W/libexynosv4l2: failed to ioctl: VIDIOC_DQBUF (22 - Invalid argument)
12-07 15:58:35.517 2436-28975/? W/GraphicBufferSource: Dropped back down to Loaded without Executing
12-07 15:58:35.581 2436-18109/? W/libexynosv4l2: failed to ioctl: VIDIOC_DQBUF (22 - Invalid argument)
12-07 15:58:35.583 2436-18108/? W/libexynosv4l2: failed to ioctl: VIDIOC_DQBUF (22 - Invalid argument)
12-07 15:58:35.589 14945-19515/com.oustme.oustsdk W/org.webrtc.Logging: MediaCodecVideoEncoder: Codec OMX.Exynos.VP8.Encoder requires bitrate adjustment: DYNAMIC_ADJUSTMENT
12-07 15:58:35.595 2436-18109/? W/libexynosv4l2: failed to ioctl: VIDIOC_DQBUF (22 - Invalid argument)
12-07 15:58:35.601 2425-2575/? W/audio_hw_primary: get_playback_delay: pcm_get_htimestamp error,setting playbackTimestamp to 0
12-07 15:58:35.614 14945-19517/com.oustme.oustsdk W/ACodec: do not know color format 0x7f000011 = 2130706449
12-07 15:58:35.615 14945-19517/com.oustme.oustsdk W/ACodec: do not know color format 0x10 = 16
12-07 15:58:35.615 14945-19517/com.oustme.oustsdk W/ACodec: do not know color format 0x7f00a000 = 2130747392
12-07 15:58:35.615 14945-19517/com.oustme.oustsdk W/ACodec: do not know color format 0x7f000789 = 2130708361
12-07 15:58:35.619 14945-19517/com.oustme.oustsdk W/ACodec: do not know color format 0x7f000789 = 2130708361
12-07 15:58:35.620 2436-2649/? E/OMXNodeInstance: getConfig(9840de2:Exynos.VP8.Encoder, ConfigAndroidIntraRefresh(0x6f60000a)) ERROR: UnsupportedIndex(0x8000101a)
12-07 15:58:35.623 2425-2575/? W/audio_hw_primary: get_playback_delay: pcm_get_htimestamp error,setting playbackTimestamp to 0
12-07 15:58:35.623 2425-2575/? W/audio_hw_primary: get_playback_delay: pcm_get_htimestamp error,setting playbackTimestamp to 0

**Comment by rohitlien** [comment]
Hi @aaalaniz 

can it be this : 
at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:620)
?

**Comment by rohitlien** [comment]
I think , i found the issue . I attaching the log files from crashlytics.
Please take a look.
[com.oustme.oustsdk_issue_37_crash_5A291AF7032900011EFF47D83AE6870B_55938aa0db3d11e7a60a56847afe9799_0_v2.txt](https://github.com/twilio/video-quickstart-android/files/1538875/com.oustme.oustsdk_issue_37_crash_5A291AF7032900011EFF47D83AE6870B_55938aa0db3d11e7a60a56847afe9799_0_v2.txt)

**Comment by aaalaniz** [comment]
Hey @rohitlien 

I do not see any errors in the logs related to the Video SDK. If you can't reproduce the issue in the quickstart then I'm afraid I can't help much more.

**Comment by rohitlien** [comment]
Hey @aaalaniz 
I don't know the real issues but i had a dialog for showing if someone joined. Removing the dialog solved my problem. 

Thanks for the support.
