### ISSUE TITLE
Need to get amplitude of user's voice sound

### ISSUE THREAD

**Issue by NehaKushwah993** [twilio/video-quickstart-android#220]
Hi,

I am developing app using Twilio which has feature to display a highlighted view when any user is speaking. Is this possible by using Twilio?
It will be helpful too if I can get my voice recorder instance to detect my voice amplitude only. Because creating recorder to get my voice amplitude is causing issue in transmission of voice in Twilio call, because we can not create 2 instances of recorder in Android, and to get voice's amplitude i need to user recorder. 

Please suggest me any way to do this.

Thanks

**Comment by aaalaniz** [comment]
Hey @NehaKushwah993 

I recommend using our Stats API. You can call `getStats` on a `Room` and `audioLevel` is available for local and remote audio track stats.

1.x
[Remote Audio Track Stats](https://twilio.github.io/twilio-video-android/docs/latest/com/twilio/video/AudioTrackStats.html) 
[Local Audio Track Stats](https://twilio.github.io/twilio-video-android/docs/latest/com/twilio/video/LocalAudioTrackStats.html)

2.x
[Remote Audio Track Stats](https://twilio.github.io/twilio-video-android/docs/2.0.0-preview7/com/twilio/video/RemoteAudioTrackStats.html) 
[Local Audio Track Stats](https://twilio.github.io/twilio-video-android/docs/2.0.0-preview7/com/twilio/video/LocalAudioTrackStats.html)

**Comment by NehaKushwah993** [comment]
Hi,

Thanks for reply, Can you please give me any example that how can i access RemoteAudioTrackStats or LocalAudioTrackStats objects to get output level?

Thanks

**Comment by NehaKushwah993** [comment]
I found use of this Class here in Swift : https://github.com/twilio/video-quickstart-swift/issues/181

I implemeted this in same way and its working for me. Thanks

Needed to add listener in room instance (had to call continuously with delay) : 
 try {
                    room.getStats(new StatsListener() {
                        @Override
                        public void onStats(List<StatsReport> list) {
                            processStatsReports(list);
                        }
                    });
                    speakerHandler.postDelayed(this, 100);
                } catch (Exception e) {
                    e.printStackTrace();
                }


    public void processStatsReports(List<StatsReport> list) {
        try {

            if (list == null || list.size() == 0) {
                return;
            }

            for (StatsReport statsReport : list) {
                for (AudioTrackStats audioTrackStats : statsReport.getAudioTrackStats()) {
                    int audioLevel = audioTrackStats.audioLevel;
                    String participantId = getParticipantByTrackId(audioTrackStats.trackId); // Saved trackId with its participantId locally in ParticipantListener method
                }
                for (LocalAudioTrackStats audioTrackStats : statsReport.getLocalAudioTrackStats()) {
                    int audioLevel = audioTrackStats.audioLevel;
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
