### ISSUE TITLE
Audio Echo on Pixel 2XL

### ISSUE THREAD

**Issue by shivthepro** [twilio/video-quickstart-android#221]
Im able to hear my voice echoed when other person is connected in a pixel 2 xl device. I think it is a similar issue to this
 -  https://github.com/twilio/video-quickstart-android/issues/65

**Comment by aaalaniz** [comment]
Hey @shivthepro 

What version of the SDK are you using? Are you using a `Peer-to-Peer` or `Group` room?

Thanks!

**Comment by shivthepro** [comment]
SDK Version : 2.0.0-preview7 and its a group room

**Comment by aaalaniz** [comment]
Hey @shivthepro 

Have you tried all the suggestions in our [Troubleshooting Audio guide](https://github.com/twilio/video-quickstart-android#troubleshooting-audio)? Does the echo happen only in speaker mode?

Thanks!

**Comment by shivthepro** [comment]
As far as I know it happens only in speaker mode.. will check it out and ill let you know there may be a delay cause I don't have the mobile now will update here once I test it out.

**Comment by seanadkinson** [comment]
@aaalaniz I also experienced echo and volume issues with a Pixel 2.  Disabling OpenSL ES seems to have fixed it for me.

**Comment by aaalaniz** [comment]
Thanks for the tip @seanadkinson !

@shivthepro can you confirm this resolves the echo problem?

Thanks!

**Comment by aaalaniz** [comment]
@shivthepro reopen if the issue was not resolved with @seanadkinson fix. Thanks!

**Comment by mcorner** [comment]
Can anyone comment on if this fixed their problem?  

We implemented it and it seemed to fix it for the android side of a call, but the other side (in our case it is web/js) was still getting lots of echo with Pixel 2XLs.

We create the audio track first then disable opensl es.  We can try flipping the order to see what happens.

**Comment by idelgado** [comment]
@mcorner yes please try setting this before creating the LocalAudioTrack.
```
/*
 * Execute any time before creating a LocalAudioTrack and connecting 
 * to a Room.
 */

// Disable OpenSL ES 
WebRtcAudioManager.setBlacklistDeviceForOpenSLESUsage(true);
```

**Comment by CaptainJeff** [comment]
This doesn't seem to work. I'm on a pixel 2 and have the echo after calling 

`WebRtcAudioManager.setBlacklistDeviceForOpenSLESUsage(true);`

Anyone have any suggestions?
