### ISSUE TITLE
Programmable video - date_created in GET/Recordings API 

### ISSUE THREAD

**Issue by BhanuVGowda** [twilio/video-quickstart-android#222]
The date_created in the response of GET/Recordings API is rounded-off to secs. Is it possible to get the date_created in milli secs?

**Comment by aaalaniz** [comment]
Hey @BhanuVGowda 

I reported this request to our backend team. I will have more information next week.

Thanks!

**Comment by igracia** [comment]
Thanks @aaalaniz from bouncing this! TBH we hadn't expected that field to be used as the source of truth for synchronizing tracks when merging, as that represents the time when the file is created, which can actually be a bit different from the time the media starts flowing. Also, there's . For that reason, we'd recommend gathering the information from the media file itself that you download. If you have a look at the [mixing guide](https://gist.github.com/igracia/581a8dfb8b88aa624c1d456adc6affb2), you'll see an example that uses `ffprobe` to get that information.

@BhanuVGowda Trying to understand the use case here. Could you give us some background on the rationale behind ms precision in `date_created`?

**Comment by BhanuVGowda** [comment]
Thank you for the pointer to the mixing guide. You are right, date_created was being used to synchronize tracks.
