### ISSUE TITLE
Route audio output to HDMI

### ISSUE THREAD

**Issue by ACoderMan** [twilio/video-quickstart-android#230]
I am unable to route the audio output on an Android device to the HDMI port. I have setup a BroadcastReceiver that detects when the HDMI connector is inserted. Neither of the following 3  commands work:

 audioManager.setParameters("audio_devices_out_active=AUDIO_CODEC");

audioManager.setParameters("audio_devices_out_active=AUDIO_HDMI");
      audioManager.setParameters("audio_devices_out_active=AUDIO_HDMI,AUDIO_CODEC");

I have tried this with devices running Android 4.4, 5.1, and 6.0.

**Comment by aaalaniz** [comment]
Hey @ACoderMan 

Are you able to route other audio (song or sound effect) through HDMI? I'll have to investigate this further. Are you just trying to plug an Android device to a TV and connect to a Room?

Thanks!

**Comment by ACoderMan** [comment]
Aaron
Yes I can route other audio through the HDMI port. I wrote a simple test
app using a WebView. When setting the URL to a streaming video the audio
and video automatically switched from the speakers to the HDMI port when
connected to a TV. I did not need a BroadcastReceiver the Android OS took
care of it automatically.

You are correct in my app I am connected to a Room and want to display the
Room audio and video on a TV. I can use AudioManager.setSpeakerPhoneOn() to
control the headphones but I am unable to find a way to control the HDMI
audio.


On Jan 25, 2018 5:55 PM, "Aaron Alaniz" <notifications@github.com> wrote:

Hey @ACoderMan <https://github.com/acoderman>

Are you able to route other audio (song or sound effect) through HDMI? I'll
have to investigate this further. Are you just trying to plug an Android
device to a TV and connect to a Room?

Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/twilio/video-quickstart-android/issues/230#issuecomment-360628174>,
or mute the thread

**Comment by aaalaniz** [comment]
Hey @ACoderMan 

I investigated this issue further and didn't find much insight. Can you try setting the mode of `AudioManager` to `MODE_NORMAL`

`audioManager.setMode(AudioManager.MODE_NORMAL);`

Currently in our quickstart we recommend `MODE_IN_COMMUNICATION` and that may affect the way audio is routed. Can you provide the following additional details too?

- Video Android SDK Version
- Android Device
- Android API Level

If changing the audio manager mode does not work I will order the appropriate device/accessories and debug locally.

Thanks!

**Comment by ACoderMan** [comment]
Aaron

I ran some tests and got interesting results. These tests were made using
the Twilio Programmable Video 1.0.0 SDK. I tested 2 Android 4.4 devices, a
Teclast x98 Air 3G tablet and a LG E-980 phone with a SlimPort cable.
Neither of them would produce audio out of the HDMI connector when set to
MODE_NORMAL or MODE_IN_COMMUNICATION.

I rested a Teclast P89H tablet with Android 6.0 The HDMI audio did work
when the audio mode was set to MODE_NORMAL but did not work with
MODE_IN_COMMUNICATION.

I tested a Teclast X98 Air III running Android 5.0. The HDMI audio worked
both in the MODE_NORMAL and MODE_IN_COMMUNICATION modes.

The last test I did was to upgrade my app to use version 1.3.10 of the
Twilio SDK. Retesting the Android 4.4 Teclast tablet showed that the
upgrade did not make any difference. The audio was never directed to the
HDMI port.

ACoderMan




On Jan 26, 2018 10:24 AM, "Aaron Alaniz" <notifications@github.com> wrote:

Hey @ACoderMan <https://github.com/acoderman>

I investigated this issue further and didn't find much insight. Can you try
setting the mode of AudioManager to MODE_NORMAL

audioManager.setMode(AudioManager.MODE_NORMAL);

Currently in our quickstart we recommend MODE_IN_COMMUNICATION and that may
affect the way audio is routed. Can you provide the following additional
details too?

   - Video Android SDK Version
   - Android Device
   - Android API Level

If changing the audio manager mode does not work I will order the
appropriate device/accessories and debug locally.

Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/twilio/video-quickstart-android/issues/230#issuecomment-360814256>,
or mute the thread

**Comment by aaalaniz** [comment]
Hey @ACoderMan 

I really appreciate you doing further testing. Based on your findings it looks like the behavior is not consistent across API levels. Can you elaborate on your use case? Does your app require that users connect to a TV often?

Thanks!

**Comment by ACoderMan** [comment]
My use case can best be described as a remote participant of a meeting. The
participant can view the speaker as well as images or videos that are
displayed on monitors in the meeting. They can also raise their hand and
their name shows up on a display at the podium. When called upon a
microphone image shows up on the participant's screen to let them know it
is OK to talk.

In the majority of cases there are one or two people watching on an Android
or iPad tablet. On occasion their may be a group watching so a TV display
would be nice. Not many of the participants are running Android 4.4 so I do
not see this as a big problem. It looks like I can support levels 5.0 and
above using MODE_NORMAL. I was also considering adding casting capability
in the Android version. The Apple version works with an Apple TV.

ACoderMan




On Jan 31, 2018 10:25 AM, "Aaron Alaniz" <notifications@github.com> wrote:

Hey @ACoderMan <https://github.com/acoderman>

I really appreciate you doing further testing. Based on your findings it
looks like the behavior is not consistent across API levels. Can you
elaborate on your use case? Does your app require that users connect to a
TV often?

Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/twilio/video-quickstart-android/issues/230#issuecomment-361966261>,
or mute the thread

**Comment by aaalaniz** [comment]
Please reopen if you have any more questions @ACoderMan. Thanks!
