### ISSUE TITLE
How to render audio of multiple participants without creating multiple views

### ISSUE THREAD

**Issue by rishabhja1994** [twilio/video-quickstart-android#234]
I need to do audio call without creating multiple video views? How can i do that

**Comment by idelgado** [comment]
There is no need to add a `View` for audio to playback. As audio tracks are published they will get mixed into the audio stream that is played back on the output device.

**Comment by rishabhja1994** [comment]
So basically, audio stream works independent of the video stream?

**Comment by idelgado** [comment]
That’s correct

**Comment by aaalaniz** [comment]
Closing because looks like question was answered. @rishabhja1994 please reopen if you have any further questions.

Thanks!
