### ISSUE TITLE
Support onFirstFrame callback for each VideoTrack a VideoView renders

### ISSUE THREAD

**Issue by aaalaniz** [twilio/video-quickstart-android#243]
### Description

@rishabhja points out in #236 that `onFirstFrame` is only called when a VideoView renders the first frame of the first VideoTrack it renders. If the VideoView is removed as a renderer from a VideoTrack and then added back as a renderer on another VideoTrack then `onFirstFrame` is not invoked. 

This is currently expected behavior, but there is value in receiving a unique onFirstFrame callback for each VideoTrack because it enables a better reuse of VideoViews across video tracks.

Please feel free to add additional details in the comments @rishabhja

### Steps to Reproduce

1. Inflate VideoView
2. Add VideoView as renderer to VideoTrack A
3. Remove VideoView as renderer to VideoTrack A
4. Add VideoView as renderer to VideoTrack B

#### Expected Behavior

`onFirstFrame` invoked for both VideoTrack A and B

#### Actual Behavior

`onFirstFrame` invoked for only VideoTrack A

#### Reproduces how Often

100%

### Versions

All relevant version information for issue.

#### Video Android SDK

1.3.11 and 2.0.0-beta1

**Comment by aaalaniz** [comment]
Hey @rishabhja

After investigating this request further @idelgado and I came up with a better workaround. I suggest using [this class](https://gist.github.com/aaalaniz/b88e1977a56015ad391ad8523a3865aa) to render video tracks. This CustomVideoView notifies when the first frame is rendered and the first frame after calling `resetListener`. Reference the snippet below for reusing the CustomVideoView on different tracks.

```
// Inflate or create custom video view
CustomVideoView videoView;

// Set listener
videoView.setListener(listener);

// Add first video track (onFirstFrame should be invoked after adding renderer)
videoTrackOne.addRenderer(videoView);

// Remove renderer
videoTrackOne.removeRenderer(videoView);

// Reset video view and add as renderer to another track
videoView.resetListener();

// onFirstFrame should be called again after calling resetListener
videoTrackTwo.addRenderer(videoView);
```

**Comment by shivthepro** [comment]
Can I get the same listener set up for the [VideoView backed up by TextureView ](https://gist.github.com/aaalaniz/bfbc4891c98ef3b23558ff2260cbcc8e#file-videotextureview-java)

**Comment by aaalaniz** [comment]
Hey @shivthepro 

You should be able to reuse the same class but just extend VideoTextureView instead of VideoView.

**Comment by shivthepro** [comment]
@aaalaniz 
I'll add the interface to it instead :)

**Comment by aaalaniz** [comment]
One thing I forgot to mention. @shivthepro @rishabhja

[CustomVideoView](https://gist.github.com/aaalaniz/b88e1977a56015ad391ad8523a3865aa) is not thread safe. This shouldn't be a problem for you use case, but just thought I would let you know.

**Comment by rishabhja** [comment]
Thanks for the help. This would surely solve my use case 👍

**Comment by aaalaniz** [comment]
I'm closing this issue because modifying the behavior of `VideoRenderer.Listener` is not on our roadmap and the provided workaround seems suitable for the use cases.

Thanks @shivthepro @rishabhja !

**Comment by shivthepro** [comment]
That is great to know VideoRenderer.Listener's behaviour would change accordingly..  Expecting the update soon.

Thanks @aaalaniz
