### ISSUE TITLE
How to route audio output to headphones?

### ISSUE THREAD

**Issue by rishabhja** [twilio/video-quickstart-android#248]
By default, audio output goes only to speaker. it does not go through the headphone

**Comment by aaalaniz** [comment]
Hey @rishabhja 

[Check out the quickstart](https://github.com/twilio/video-quickstart-android/blob/master/quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java#L206) for switching the audio output.

```
// Route audio to speaker
audioManager.setSpeakerphoneOn(false);

// Route audio to headset
audioManager.setSpeakerphoneOn(true);
```

Thanks!

**Comment by rishabhja** [comment]
I am asking about headphones and not headset

**Comment by aaalaniz** [comment]
If user has headphones connected the audio will be routed to the headphones when you invoke `audioManager.setSpeakerphoneOn(false);`

**Comment by brownpixel** [comment]
I noticed this as well and realized that for bluetooth headsets, the `audioManager.setSpeakerphoneOn(false);` seems to only work if you set the mode in the audio manager to `AudioManager.MODE_IN_CALL` before setting the speaker boolean

**Comment by rishabhja** [comment]
@brownpixel The above approach is not working for me
