### ISSUE TITLE
How to disable audio from twilio sdk?

### ISSUE THREAD

**Issue by rishabhja** [twilio/video-quickstart-android#253]
I am unable to mute audio from twilio call which is  a problem as i can hear twilio audio during phone calls

#### Code

```java

private fun requestAudioFocus() {
        val focusResult = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val playbackAttributes = AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_VOICE_COMMUNICATION)
                .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)
                .build()
            val focusRequest = AudioFocusRequest.Builder(AudioManager.AUDIOFOCUS_GAIN_TRANSIENT)
                .setAudioAttributes(playbackAttributes)
                .setAcceptsDelayedFocusGain(true)
                .setOnAudioFocusChangeListener(this)
                .build()
            audioManager.requestAudioFocus(focusRequest)
        } else {
            audioManager.requestAudioFocus(this, AudioManager.STREAM_VOICE_CALL,
                AudioManager.AUDIOFOCUS_GAIN_TRANSIENT)
        }
        when (focusResult) {
            AudioManager.AUDIOFOCUS_REQUEST_GRANTED -> handleAudioFocusGained()
            else -> handleAudioFocusLost()
        }
    }

//Used to mute stream
audioManager.setStreamMute(AudioManager.STREAM_VOICE_CALL, false)
```

#### Expected Behavior
Audio from twilio call should get muted

#### Actual Behavior
Does not work

**Comment by aaalaniz** [comment]
Hey @rishabhja 

Here is everything you need to know about muting audio in your application. These snippets are for the the 2.x version of the Video Android SDK.

#### Muting Local Audio
There are two options for muting local audio.

```
// Disable audio track. Audio still flows to participants but the audio is silent.
localAudioTrack.enable(false);

// Release and unpublish audio track. Audio no longer flows to participants.
localAudioTrack.release()
localParticipant.unpublish(localAudioTrack);
```

#### Muting Remote Audio

```
// Disable playback of a remote audio track
remoteAudioTrack.enablePlayback(false);
```

**Comment by aaalaniz** [comment]
Closing this issue for now. Please reopen if you need further assistance.

Thanks!

**Comment by AnkanDey** [comment]
Hello aaalaniz,

How can I mute remote audio in 1.3 version?

Gradle dependency : 'com.twilio:video-android:1.3.10'

**Comment by aaalaniz** [comment]
Hey @AnkanDey 

Muting remote audio is not supported in the 1.x versions of the Video Android SDK. Please update your application to 2.x to use this feature.

Thanks!

**Comment by wi-vaibhav** [comment]
> Hey @rishabhja
> 
> Here is everything you need to know about muting audio in your application. These snippets are for the the 2.x version of the Video Android SDK.
> 
> #### Muting Local Audio
> There are two options for muting local audio.
> 
> ```
> // Disable audio track. Audio still flows to participants but the audio is silent.
> localAudioTrack.enable(false);
> 
> // Release and unpublish audio track. Audio no longer flows to participants.
> localAudioTrack.release()
> localParticipant.unpublish(localAudioTrack);
> ```
> 
> #### Muting Remote Audio
> ```
> // Disable playback of a remote audio track
> remoteAudioTrack.enablePlayback(false);
> ```

Hii how can I get instance of remoteAudioTrack in Js
