### ISSUE TITLE
Crashed when i try to disconnect room before any of the callback(onConnected, onDisconnected, onConnectFailure) executes 

### ISSUE THREAD

**Issue by rishabhja** [twilio/video-quickstart-android#254]
Crash log: 
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 29764 (RoomNotifier - )

I can reproduce this every time

**Comment by aaalaniz** [comment]
Hey @rishabhja 

Please follow the [issue template](https://github.com/twilio/video-quickstart-android/blob/master/.github/ISSUE_TEMPLATE.md) as closely as possible when opening issues. The issue template helps our team understand the problem so we can investigate more effectively. Please re-open with more details.

Thanks!
