### ISSUE TITLE
CustomCapturer from TextureView/SurfaceTexture

### ISSUE THREAD

**Issue by ayavilevich** [twilio/video-quickstart-android#256]
### Description

I have a closed third-party component that renders video to a SurfaceTexture provided by a TextureView.
I would like to send that video to a Twilio video room as a track.

Is there a way for me to get the oesTextureId from a SurfaceTexture?
I can call SurfaceTexture.getTransformMatrix(float[]) to get the matrix and it seems I am very close to creating valid VideoFrames.

#### Code

```java
        videostreamPreviewTtView.setSurfaceTextureListener(new TextureView.SurfaceTextureListener() {
            @Override
            public void onSurfaceTextureAvailable(SurfaceTexture surfaceTexture, int width, int height) {
                Log.d(TAG, String.format("real onSurfaceTextureAvailable %d %d", width, height));
                mCodecManager = new thirdParty(getApplicationContext(), surfaceTexture, width, height);
            }

            @Override
            public void onSurfaceTextureSizeChanged(SurfaceTexture surface, int width, int height) {
                Log.d(TAG, "onSurfaceTextureSizeChanged: not handled!");
            }

            @Override
            public boolean onSurfaceTextureDestroyed(SurfaceTexture surface) {
                Log.d(TAG, "onSurfaceTextureDestroyed");
                if (mCodecManager != null)
                    mCodecManager.cleanSurface();

                return false;
            }

            @Override
            public void onSurfaceTextureUpdated(SurfaceTexture surface) {
                //Log.d(TAG, "onSurfaceTextureUpdated: not handled");
                // get frame here
                // called each frame
            }
        });
```

#### Video Android SDK

2.0.0-beta1

#### Android API

    compileSdkVersion 26
        minSdkVersion 16
        targetSdkVersion 26

#### Android Device

LG G5

**Comment by aaalaniz** [comment]
Hey @ayavilevich 

Our version of WebRTC does support capturing from a texture, but we do not expose an API in our `VideoCapturer`. 

Can you share your custom capturer? I'd like to explore enabling this use case.

Thanks!

**Comment by ayavilevich** [comment]
Hi @aaalaniz ,

I saw there is a non-public constructor in VideoFrame that works with textures. I assume it will be easy to set a VideoFrame with a textureId using reflection. The problem is that I don't have a textureId. I just have a TextureView/SurfaceTexture.

I don't have anything working yet. I am sharing a mock-up of a capturer that I have in my mind. LMK if you need anything else to take a look on this concept.

I believe that some use of MediaCodec decoding is generating the content in the SurfaceTexture. What about streaming an mp4 file to a room? Is that a similar use case?
After some reading I am believing to think I need to create my own texture, then build a surfaceTexture around it. Is that the right approach? Any assistance would be appreciated.

```
public class TexCapturer implements VideoCapturer {
    private static final String TAG = TexCapturer.class.getSimpleName();

    private int mWidth;
    private int mHeight;
    private int mFPS;
    private static final VideoPixelFormat PIXEL_FORMAT=VideoPixelFormat.NV21;

    private VideoCapturer.Listener videoCapturerListener;
    private AtomicBoolean started = new AtomicBoolean(false);

    public TexCapturer(int width, int height, int fps) {
        mWidth = width;
        mHeight = height;
        mFPS = fps;
    }

    public void sendFrameP(SurfaceTexture surfaceTexture, int width, int height) {
        // check stuff
        if(started.get()==false || videoCapturerListener==null || mWidth!=width || mHeight!=height)
            return;

        final long captureTimeNs = TimeUnit.MILLISECONDS.toNanos(SystemClock.elapsedRealtime());

        // Create video frame
        VideoDimensions dimensions = new VideoDimensions(mWidth, mHeight);

        // get matrix
        float mtx[]=new float[16];
        surfaceTexture.getTransformMatrix(mtx);

        // get textureId TODO
        int textureId=0;
        //textureId=surfaceTexture.ToTextureId(); // ToTextureId TBD

        // call private constructor TODO
        VideoFrame videoFrame = new VideoFrame(textureId, mtx,
                dimensions, VideoFrame.RotationAngle.ROTATION_0, captureTimeNs);
        videoCapturerListener.onFrameCaptured(videoFrame);
    }

    /**
     * Returns the list of supported formats for this view capturer.
     *
     * @return list of supported formats.
     */
    @Override
    public List<VideoFormat> getSupportedFormats() {
        List<VideoFormat> videoFormats = new ArrayList<>();
        VideoDimensions videoDimensions = new VideoDimensions(mWidth, mHeight);
        VideoFormat videoFormat = new VideoFormat(videoDimensions, mFPS, PIXEL_FORMAT);
        videoFormats.add(videoFormat);
        return videoFormats;
    }

    /**
     * Returns true because we are capturing screen content.
     */
    @Override
    public boolean isScreencast() {
        return false;
    }

    /**
     * This will be invoked when it is time to start capturing frames.
     *
     * @param videoFormat the video format of the frames to be captured.
     * @param listener capturer listener.
     */
    @Override
    public void startCapture(VideoFormat videoFormat, VideoCapturer.Listener listener) {
        // Store the capturer listener
        this.videoCapturerListener = listener;
        this.started.set(true);

        // Notify capturer API that the capturer has started
        this.videoCapturerListener.onCapturerStarted(true);
    }

    /**
     * Stop capturing frames. Note that the SDK cannot receive frames once this has been invoked.
     */
    @Override
    public void stopCapture() {
        this.started.set(false);
    }

}
```

**Comment by myxoh** [comment]
Is there any update from this? I have a very similar use case!

**Comment by xenois** [comment]
i ran into the same problem and i managed to create a custom VideoCapturer to send raw bytes 
`class RawCapturer : VideoCapturer {
    override fun stopCapture() {

    }

    override fun isScreencast(): Boolean {
        return false
    }

    var surfaceTextureHelper: SurfaceTextureHelper? = null
    var context: Context? = null
    var capturerObserver: VideoCapturer.CapturerObserver? = null

    override fun startCapture(p0: Int, p1: Int, p2: Int) {

    }

    override fun changeCaptureFormat(p0: Int, p1: Int, p2: Int) {

    }

    fun onFrame(data: ByteArray,
                mWidth: Int,
                mHeight: Int,
                rotation: Int) {
        val captureTimeNs = TimeUnit.MILLISECONDS.toNanos(SystemClock.elapsedRealtime())
        val buffer = NV21Buffer(data, mWidth, mHeight) {}
        val frame = VideoFrame(buffer, rotation, captureTimeNs)
        capturerObserver?.onFrameCaptured(frame)
    }

    override fun initialize(
        p0: SurfaceTextureHelper?,
        p1: Context?,
        p2: VideoCapturer.CapturerObserver?
    ) {
        surfaceTextureHelper = p0
        context = p1
        capturerObserver = p2
    }

    override fun dispose() {

    }
}`

now instead a cameraVideoRecorder just use this recorder and manually send your bytes on every frame.For a camera will be like this:
`camera.setPreviewCallback { data, camera ->
textureCapturer.onFrame(data,cam.parameters.previewSize.width,cam.parameters.previewSize.height,0)
}`
or you can poll your TextureView every 1/framerate, get the data and send them to onFrame()

**Comment by reddigfabian** [comment]
I'm curious if the latest twilio sdks support capturing a TextureView. I tried the ViewCapturer provided in the sample code but it is unable to capture TextureView content.

@xenois I'm dealing with the same third party you are and am also looking for a solution to this. What version of the twilio SDK are you using with the above code sample?

**Comment by aaalaniz** [comment]
Hey everyone,

Capturing from a texture is not currently on our roadmap. I will close this issue for now. Feel free to ask any additional questions and we will do our best to respond appropriately.

Thank you

**Comment by GauravAndroidIS** [comment]
can I download a 5 sec mp4 video as a sample parallely while video is rendering?

**Comment by aaalaniz** [comment]
Hey @GauravAndroidIS 

>can I download a 5 sec mp4 video as a sample parallely while video is rendering?

This should be possible, but I would need more details to confirm. Please open an issue and our team can provide more detailed guidance.

Thanks!
