### ISSUE TITLE
Unnecessary invite in specific case

### ISSUE THREAD

**Issue by Skalaw** [twilio/video-quickstart-android#26]
I using: 'com.twilio:conversations-android:0.12.2'.

**Reprosteps:**
1. Call Client1 to Client2
2. Client2 accepted
3. Invite Client4
4. Client4 declined
5. Invite Client3
6. Client3 accepted (If Client3 declined - then everything is ok)
Now when Client3 accepted, automatically Client4 have once again invite.

**Acceptance Criteria**
Client4 not should have once again invite

**My findings:**
IncomingInvite.accept() - this cause another request.

**Comment by aaalaniz** [comment]
Hi @Skalaw,

I encourage you to try our new library which is in developer preview. One of the shortcomings of the conversations library, is that it required inviting. In this developer preview, we no longer invite. Users join using a room name. You are free to signal the room name to other participants with whatever you prefer(GCM, Firebase, etc.). The developer preview is available here (https://github.com/twilio/video-quickstart-android/tree/rooms) and we will be deprecating conversations in favor of this new library in the coming weeks as it goes into public beta.
