### ISSUE TITLE
Outgoing call reject not working

### ISSUE THREAD

**Issue by Mahawbc** [twilio/video-quickstart-android#261]
**Outgoing call reject not working**

When i make outgoing call its connecting to receiver. In receiver side before pick the call they disconnect the call it disconnected but in sender side call not disconnecting. timer for the call duration still running after the call disconnected by receiver side.

**Voice-quickstart-andriod-sdk**

Android studio 3.0.1
Android Build version 25.0.0
Android Gradle Version "com.android.tools.build:gradle:2.3.0"
target sdkversion 23

**Comment by aaalaniz** [comment]
Hey @Mahawbc 

The issue you are describing appears to be related to Voice Android SDK. You can file an issue on their [quickstart](https://github.com/twilio/voice-quickstart-android).

Thanks!
