### ISSUE TITLE
Video Capturer class missing

### ISSUE THREAD

**Issue by emphassis** [twilio/video-quickstart-android#262]
### Description
Based on what I see the 2.0.0-preview8 is the newest version of this SDK.
In the example code, in the CameraCapturerCompat class, you have a method called getVideoCapturer(), which essentially just grabs the device camera without any way to enable the video constraints that is built into the SDK for other platforms. We have developed a cross platform application that uses these constraints and they must be 640x480. 
When I add the video constraints it may or may not constrain the video to 640x480, but it dumps any setting on an upload. The other side gets the default value, which when the video is captured in portrait form causes the bottom half of the capture to disappear. Then on the record (because we record it at 640x480) it uses a sort of VideoScaleType.ASPECT_FILL with no cropping. It literally shrinks the height and skews the recording.

This is what your getVideoCapturer() method says:
```
    /*
     * This method is required because this class is not an implementation of VideoCapturer due to
     * a shortcoming in the Video Android SDK.
     */

    public VideoCapturer getVideoCapturer() {
        if (usingCamera1()) {
            return camera1Capturer;
        } else {
            return camera2Capturer;
        }
    }
```

#### Code

```
VideoConstraints videoConstraints = new VideoConstraints.Builder()
            .aspectRatio(new AspectRatio(4,3))
            .minVideoDimensions(VideoDimensions.VGA_VIDEO_DIMENSIONS)
            .maxVideoDimensions(VideoDimensions.VGA_VIDEO_DIMENSIONS)
            .minFps(25)
            .maxFps(25)
            .build();

localVideoTrack = LocalVideoTrack.create(this, true, cameraCapturerCompat.getVideoCapturer(), videoConstraints, LOCAL_VIDEO_TRACK_NAME);
```

Is there a way to force the upload of the video into 640x480?

**Comment by emphassis** [comment]
I had another test trying a different route with the same results....
`VideoDimensions videoDimensions = new VideoDimensions(640,480);
        VideoPixelFormat videoPixelFormat = RGBA_8888;
        localAudioTrack = LocalAudioTrack.create(this, true, LOCAL_AUDIO_TRACK_NAME);
        cameraCapturerCompat = new CameraCapturerCompat(this, getAvailableCameraSource());
        cameraCapturerCompat.getVideoCapturer().getSupportedFormats().set(0,new VideoFormat(videoDimensions,25,videoPixelFormat));
        localVideoTrack = LocalVideoTrack.create(this,true, cameraCapturerCompat.getVideoCapturer(),videoConstraints,LOCAL_VIDEO_TRACK_NAME);
        primaryVideoView.setMirror(true);
        localVideoTrack.addRenderer(primaryVideoView);`

**Comment by aaalaniz** [comment]
Hey @emphassis 

I'll address each item below.

> Based on what I see the 2.0.0-preview8 is the newest version of this SDK.

Latest 2.x SDK is `2.0.0-beta2`. I recommend updating to this version.

> Then on the record (because we record it at 640x480) it uses a sort of VideoScaleType.ASPECT_FILL with no cropping. It literally shrinks the height and skews the recording.

Are you using [Twilio Video Recordings](https://www.twilio.com/docs/api/video/recordings-resource) or another method? Can you provide a sample recording that demonstrates the skewed video?

> Is there a way to force the upload of the video into 640x480?

There is no way to force a particular resolution. The SDK will adapt to network conditions and scale your video accordingly.

**Comment by emphassis** [comment]
So I had an idea as a workaround, but I haven't been able to get it to work. I've had two different results.
So in one test, I created another VideoView, used the VideoCapturer class with the create local video track method to get the camera. The VideoView was hard coded at 640x480. I created another localVideoTrack using ViewCapturer to get the view from the VideoView and put that in the primaryVideoView. In that test, it was black. I'm not sure if it's an issue with creating multiple localvideotracks, or if it's an issue trying to capture a dynamic child in an element.
The other test was using the same VideoView and same LocalVideoTrack. I built the first localvideotrack and captured the camera on the primaryvideoview. Then I created another localvideotrack over the old videotrack without stopping it and added the renderer to the primaryvideoview. This caused the view to flash/strobe. When connecting to a room with another participant, it would flash/strobe between your camera and the participants camera without instantiating the thumbnail view.
Do you think that somewhere in the ViewCapturer method is a possibility of sharing the camera with the constraints? And maybe I'm just not doing something right?

**Comment by aaalaniz** [comment]
Apologies for the delayed response @emphassis 

Can you provide the exact details of the problem(s) you are experiencing with maybe some code snippets that demonstrate the problem? I'd be happy to help, but I need a little more clarification.

Thanks!
