### ISSUE TITLE
"Signaling connection error"

### ISSUE THREAD

**Issue by mayurm-virtueinfo** [twilio/video-quickstart-android#267]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

### Description

Hello, I have implemented TwilioVideo in my application. Due to some problem i cannot send you apk. But i can send you screenshot. Video is working fine but some time i gets TwilioException which says "Signaling connection error". I have searched about this but could not find the reason why i am getting this exception. So, I hope i can here your kind response on this issue and provide the solution.

### Steps to Reproduce
I am not sending steps to reproduce but sending explanation of Picture that i have attached.
- While i connect to room i receives TwilioException as showing in attached screenshot.
#### Code

```java
// Code that help reproduce the issue
```

#### Expected Behavior

I should not receive TwilioException "Signaling Connection Error"

#### Actual Behavior

I am receiving TwilioException "Signaling Connection Error"

#### Reproduces how Often

[What percentage of the time does it reproduce?]

#### Logs

```
// Log output when issue occurs
```

#### Video Android SDK

com.twilio:video-android:1.0.0
![img-20180323-wa0015](https://user-images.githubusercontent.com/25951058/37825491-0357d8da-2eb6-11e8-89fb-f3b05ded1b6a.jpg)

#### Android API

Android Version : 7.0.1

#### Android Device

Moto G4 Plus

**Comment by aaalaniz** [comment]
Hey @mayurm-virtueinfo 

Can you turn up logging using `Video.setLogLevel(LogLevel.ALL);` and provide a log? 

Thanks!

**Comment by mayurm-virtueinfo** [comment]
where to put

Video.setLogLevel(LogLevel.ALL);

**Comment by aaalaniz** [comment]
You can invoke `Video.setLogLevel(LogLevel.ALL);` anywhere before connecting to a room.

**Comment by mayurm-virtueinfo** [comment]
ok

**Comment by aaalaniz** [comment]
Hey @mayurm-virtueinfo 

I'm closing this issue. Please re-open with a log and I can investigate further.

Thanks!
