### ISSUE TITLE
primaryVideoView showing transparent after videoTrack.addRenderer(primaryVideoView);

### ISSUE THREAD

**Issue by mayurm-virtueinfo** [twilio/video-quickstart-android#268]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

### Description
Hi,
I am using TwilioVIdeo Chat in my Application please do not share any of video content which i have added in .zip file due to NDA signed.

**Problem is that When i connected to room and add participant video to primary video. It takes time to render videoTrack. So, til videoTrack is not rendered, SurfaceViewRenderer gets Transparent. This is the issue. In Video, See timing from 2nd Second to 10 second. It takes 8 seconds to render and mean while background is showing transparent. Please I have researched so much to get rid of this issue but could not find any solution yet. So, i hope i will get resolved this ticket from you as soon as possible** 

CODE: 
private void addParticipantVideo(VideoTrack videoTrack) {
        moveLocalVideoToThumbnailView();
        primaryVideoView.setMirror(false);
        videoTrack.addRenderer(primaryVideoView);
        primaryVideoView.setBackground(null);
    }

[vrecord.mp4.zip](https://github.com/twilio/video-quickstart-android/files/1841287/vrecord.mp4.zip)

#### Reproduces how Often

Reproduces each time **when i start video and it takes 5 to 10 seconds** to rendere and mean while **"SurfaceViewRenderer"** gets transparent

#### Logs

```
// Log output when issue occurs
```

### Versions

All relevant version information for issue.

#### Video Android SDK
SDK Version : com.twilio:video-android:1.0.0

#### Android API
Android Version : 7.0.1

#### Android Device
Moto G4 Plus

**Comment by aaalaniz** [comment]
Hey @mayurm-virtueinfo 

Unfortunately, there is not much that can be done in our SDK to reduce the negotiation time of media, so there will be cases where it takes seconds to see the first video frame. However, as a workaround can you show a temporary UI element until the first frame is received? You can call setListener on `VideoView` to get a callback when the first frame is rendered that way your users do not see just a transparent screen while awaiting the first frame.

Also, I highly recommend updating to our 2.x SDKs (latest is 2.0.0-beta2). We have put together a [migration guide](https://www.twilio.com/docs/api/video/migrating-1x-2x-android-20) for developers using our 1.x SDK. 

Thanks!

**Comment by mayurm-virtueinfo** [comment]
Can i catch first video frame in SDK 1.0?

**Comment by aaalaniz** [comment]
Yes

**Comment by mayurm-virtueinfo** [comment]
how could i get the first video frame in SDK 1.0?

**Comment by aaalaniz** [comment]
Reference the following snippet for getting the onFirstFrame callback

```
videoView.setListener(new VideoRenderer.Listener() {
    @Override
    public void onFirstFrame() {
        
    }

    @Override
    public void onFrameDimensionsChanged(int width, int height, int rotation) {

    }
});

```

**Comment by mayurm-virtueinfo** [comment]
ok.
I will implement this and let you know soon.

**Comment by mayurm-virtueinfo** [comment]
This is worked mam.
Thank you so much.

**Comment by mayurm-virtueinfo** [comment]
Hello Mam,
I need your help again for the same in IOS.

Your code is worked in Android. But, I have the same situation in IOS. Is there any way to override delegate method for IOS as we have override

videoView.setListener(new VideoRenderer.Listener() {
    @Override
    public void onFirstFrame() {
        
    }

    @Override
    public void onFrameDimensionsChanged(int width, int height, int rotation) {

    }
});


in Android.

Waiting for you kind response.

**Comment by aaalaniz** [comment]
Hey @mayurm-virtueinfo 

I recommend filing an issue on our [Twilio Video iOS](https://github.com/twilio/twilio-video-ios) repo to get help regarding your question. One of our iOS engineers will be able to help.

Thanks!
