### ISSUE TITLE
Sometimes preview is not available in specific case

### ISSUE THREAD

**Issue by Skalaw** [twilio/video-quickstart-android#27]
I using: 'com.twilio:conversations-android:0.12.2'.

**Reprosteps:**
1. Call Client1 to Client2
2. Client2 accepted
3. Call Client1 to Client2
4. Client3 is accepted and Client2 is declined on the same time.
Sometimes i don't have preview in Client1, but Client3 have/don't have preview Client1

**Acceptance Criteria:**
Client1 should always have preview Client3.
Client3 should always have preview Client1

Just method "onAudioTrackAdded" is not called and it's all, conversation continue without Audio and Video.

It is something what i can find here: https://www.twilio.com/docs/api/video/changelogs/android 
"Known Issues

The Conversation audio of participants is not interrupted when the user accepts a PSTN call on the same device." ??

**Comment by aaalaniz** [comment]
Hi @Skalaw,

As I mentioned in my previous response, the Conversations SDK is being sunset. We are encouraging developers to migrate to your new developer preview of our Rooms API. You will find the latest quickstart [here](https://github.com/twilio/video-quickstart-android/tree/rooms). These invite race conditions are less of a problem in the Rooms API. The Rooms API will be going to be public beta soon and all our documentation will be updated.
