### ISSUE TITLE
Do not send video to remote participant when show activity on Lock Screen

### ISSUE THREAD

**Issue by doananhtai** [twilio/video-quickstart-android#270]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

### Description

if show activity on lock screen, video sdk do not send video to remote participant

### Steps to Reproduce

1. A make a video call to B
2. B show activity on LOCK SCREEN
3. B can get video from A. But B do not send video to A.

#### Expected Behavior

B send video to A when activity shown on Lock Screen, so A can get the video from B.

#### Actual Behavior

B do not send video (camera works and show video on local).  A do not get video at all.

#### Reproduces how Often

happen only when activity show on lock screen.

#### Video Android SDK

2.0.0-beta2

**Comment by doananhtai** [comment]
sorry...It's all my fault

**Comment by doananhtai** [comment]
it's exactly not send video when activity shown on lock screen.

**Comment by doananhtai** [comment]
Call onResume twice cause the localVideoTrack malfunction

**Comment by aaalaniz** [comment]
Hey @doananhtai 

Are you still encountering issues? Can you share some code that reproduces the problem?

Thanks!

**Comment by fakeehtech** [comment]
Do not send video to remote participant when show activity on Lock Screen
