### ISSUE TITLE
com.twilio.video.TwilioException: Access Token expired or expiration date invalid

### ISSUE THREAD

**Issue by bhuvaneshwariarkala** [twilio/video-quickstart-android#274]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

Hello team,

I download quickstart and was trying to run on the Android Sumsung devices. I generated test token from https://www.twilio.com/console/video/runtime/testing-tools separately for 2 phones and ran the application. When I try to connect to Room, it said Access token expired. But  when i debug the token, it was not expired, it has more time to expire.

Token generated was , eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTSzdkOTRiNjg5Zjk1MGE2ZjRkMjEyMmIzMmQxYWU5MjllLTE1MjIyMzk0ODciLCJpc3MiOiJTSzdkOTRiNjg5Zjk1MGE2ZjRkMjEyMmIzMmQxYWU5MjllIiwic3ViIjoiQUNmN2VjMWFmZDYxYTYzN2JmMTY4OWZkNDQwMWE4ODFhNiIsImV4cCI6MTUyMjI0MzA4NywiZ3JhbnRzIjp7ImlkZW50aXR5IjoidXNlcjQiLCJ2aWRlbyI6eyJyb29tIjoidGVzdCJ9fX0.qqVuYTdfdzSXAk5H7mjYXCbnJ2xG5g4bpnB8odl6ubc

payload:
{
  "jti": "xxxxxxx",
  "iss": "xxxxxxxxx"
  "sub": "xxxxxxxxxxx",
  "exp": 1522243087,
  "grants": {
    "identity": "user4",
    "video": {
      "room": "test"
    }
  }
}
Why Iam facing this issue. Please can you help me?

Thanks

**Comment by aaalaniz** [comment]
Hey @bhuvaneshwariarkala 

Can you provide a log? Also, be sure to use unique identities for each token you generate.

Thanks!

**Comment by bhuvaneshwariarkala** [comment]
Hello,

Iam not getting more details, than the  

Access Token expired or expiration date invalid
03-28 21:20:51.327 12127-12127/com.twilio.video.quickstart I/System.out: VideoActivity:Access Token expired or expiration date invalid
03-28 21:20:51.327 12127-12127/com.twilio.video.quickstart I/System.out: VideoActivity
03-28 21:20:51.327 12127-12127/com.twilio.video.quickstart I/System.out: Bhuvana[Ljava.lang.StackTraceElement;@ee1a210


I created token now again:
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTSzdkOTRiNjg5Zjk1MGE2ZjRkMjEyMmIzMmQxYWU5MjllLTE1MjIyNTE2OTEiLCJpc3MiOiJTSzdkOTRiNjg5Zjk1MGE2ZjRkMjEyMmIzMmQxYWU5MjllIiwic3ViIjoiQUNmN2VjMWFmZDYxYTYzN2JmMTY4OWZkNDQwMWE4ODFhNiIsImV4cCI6MTUyMjI1NTI5MSwiZ3JhbnRzIjp7ImlkZW50aXR5IjoidDEiLCJ2aWRlbyI6eyJyb29tIjoidGVzdDEifX19._4M1F0CSFKHGETyKeowFpg5XDqDk9rIn85MukLebPto

But still showing same issue

Please help

**Comment by aaalaniz** [comment]
I don't see anything wrong with the token and I verified your account is active. You can also try [Setting up an Access Token Server](https://github.com/twilio/video-quickstart-android#setup-an-access-token-server).

**Comment by bhuvaneshwariarkala** [comment]
Then  am I doing anything wrong? I just crated account, and generated token for one identifier..Used the token in local.properties as

TWILIO_ACCESS_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTSzdkOTRiNjg5Zjk1MGE2ZjRkMjEyMmIzMmQxYWU5MjllLTE1MjIyNTE2OTEiLCJpc3MiOiJTSzdkOTRiNjg5Zjk1MGE2ZjRkMjEyMmIzMmQxYWU5MjllIiwic3ViIjoiQUNmN2VjMWFmZDYxYTYzN2JmMTY4OWZkNDQwMWE4ODFhNiIsImV4cCI6MTUyMjI1NTI5MSwiZ3JhbnRzIjp7ImlkZW50aXR5IjoidDEiLCJ2aWRlbyI6eyJyb29tIjoidGVzdDEifX19._4M1F0CSFKHGETyKeowFpg5XDqDk9rIn85MukLebPto

and then ran the app on android device. Tried to connect to room, but did not.

Any settings we need to do in account?or?

**Comment by aaalaniz** [comment]
Hey @bhuvaneshwariarkala 

Can you validate that the time on your device is setup properly?

**Comment by bhuvaneshwariarkala** [comment]
On device i have IST(GMT+5:30) timezone

**Comment by bhuvaneshwariarkala** [comment]
Its working..thank you

**Comment by aaalaniz** [comment]
Glad you resolved the issue @bhuvaneshwariarkala

**Comment by AnjuResmi** [comment]
I download quickstart and was trying to run on the Android Nokia devices. I generated test token from https://www.twilio.com/console/video/runtime/testing-tools separately for 2 phones and ran the application. When I try to connect to Room, it said Access token expired. But when i debug the token, it was not expired, it has more time to expire.what will i do?

**Comment by aaalaniz** [comment]
Hey @AnjuResmi 

Can you provide a log from this scenario?

Thanks!

**Comment by AnjuResmi** [comment]
Its working..thank you

**Comment by AnjuResmi** [comment]
sir, how can i add multiple participant in same room.

**Comment by aaalaniz** [comment]
Hey @AnjuResmi 

I wish the answer to this question was simpler or I could point you to an example but I cannot. I will do my best to give some **brief** guidance on how to add multiple participants in your application. 

**At a minimum,** here is what you need:

1. A view to render multiple participants. (eg. `RecyclerView`, `ListView`, or `GridView`)
2. Control logic to handle adding/removing participants to the UI
    1. When `Room.Listener.onConnected(...)` is invoked, call `room.getParticipants` and add all the current participants to your UI
    2. Logic to add participant to UI when `Room.Listener.onParticipantConnected(...)` is invoked
    3. Logic to remove participant from UI when `Room.Listener.onParticipantDisconnected(...)` is invoked
3. Control logic to handle video tracks being subscribed to and unsubscribed from

I understand this is not enough to implement in your application. I'm happy to field any follow up questions. We do intend to add a multi party quickstart soon.

Thanks!
