### ISSUE TITLE
Video parameters setting help

### ISSUE THREAD

**Issue by ppriyank40** [twilio/video-quickstart-android#275]
### Description

I want to know some info of below questions.
1) What values i can set for following parameters so that it can actually work?
- Bitrate for both audio and video
- fps
Please also mention what values i can set like min bitrate is 64000 and max is 256000 etc. So that i can know what is the maximum and minimum if each parameter.

2) Does width/height of video needs to be set to specific values when i want to send lower bitrate and fps?
3) I tried to set the bitrate to 64000 but when i see webrtc internal logs the values are touching to 80000-90000. I set the width- 360 height-240 and fps-10.
is that correct or will it work with 64000 bitrate?

One thing i want to make sure that whatever values i am setting in parameters for bitrates,fps and height/width it is set and it won't send higher values then what i have set to max.

#### Code

VideoConstraints videoConstraints = new VideoConstraints.Builder()
.minFps(minfps)
.maxFps(maxfps)
.maxVideoDimensions(maxdimension)
.minVideoDimensions(mindimension)
.aspectRatio(aspectRatio)
.build();

#### Expected Behavior
I tried to set the bitrate to 64000 so it should be grater than 64000 while sending stream. I set the width- 360 height-240 and fps-10.

#### Actual Behavior

I tried to set the bitrate to 64000 but when i see webrtc internal logs the values are touching to 80000-90000. I set the width- 360 height-240 and fps-10.

#### Reproduces how Often

Everytime

#### Video Android SDK

2.0.0 beta1

#### Android Device

Moto G5 and Vuzix M300

**Comment by aaalaniz** [comment]
Hey @ppriyank40 

#### Max Bitrates

Setting the max audio and video bitrate should work. Are you having problems setting max bitrates on iOS or Javascript? The allowed values for max audio bitrates vary by codec. The maximum bitrate for Opus is 510 kbps and the default max bitrate for video is 2MB. I'll have investigate further to get exact numbers for the other codecs. There are no restrictions on what values can be set for max bitrate. WebRTC will try to satisfy the max bitrate or will fallback to the default max bitrate value for the codec. I recommend reading through our [EncodingParameters API docs](https://twilio.github.io/twilio-video-android/docs/2.0.0-beta3/) for more information.

#### Video Constraints

There is no VideoConstraints requirement when setting max bitrates. Note that not all VideoConstraints are not guaranteed to be satisfied. WebRTC will adjust your resolution and FPS in response to network conditions.

What are the exact requirements or use case you are trying to satisfy with these APIs? I'd be happy to guide you to a solution.

Thanks!

**Comment by ppriyank40** [comment]
I am using Vuzix M300 device for video calls and other platforms are Android/ios/Web. So, whenever user wants to call from Android/ios to SG i want to limit the FPS and Bitrate to lowest possible value as M300's hardware not so high enough and because of that the quality of calls is not good.
So, one of the experts suggested limiting the incoming bitrates and fps to lowest possible values so that M300 will use less CPU and thus it can send good quality from itself.

**Comment by aaalaniz** [comment]
Hey @ppriyank40 

I happen to have experience working with this exact situation 😄 

Here are my recommendations based on my past experience and capabilities of the Video SDKs.

#### One Way Video

If possible for your application requirements, have you considered only sending audio/video from the Vuzix M300 and only audio from Android/iOS/Web users to M300? This would remove the work required to process video on the M300. In my experience, rendering remote video on a smart glasses app with a small screen was not worth the performance cost.

#### Prefer H.264 Video Codec

Can you check if the M300 supports H.264? Use the following snippet to determine encoding/decoder support.

```
boolean isH264Supported = MediaCodecVideoDecoder.isH264HwSupported() &&
            MediaCodecVideoEncoder.isH264HwSupported();
```

If H.264 is supported I recommend preferring the H.264 codec as part of the ConnectOptions. Here is a snippet from our [Managing Codecs guide](url).

```
//Check if H.264 is supported in this device
boolean isH264Supported = MediaCodecVideoDecoder.isH264HwSupported() &&
    MediaCodecVideoEncoder.isH264HwSupported();

// Prefer H264 if it is hardware available for encoding and decoding
VideoCodec videoCodec = isH264Supported ? (VideoCodec.H264) : (VideoCodec.VP8);
ConnectOptions connectOptions = new ConnectOptions.Builder(token)
    .preferAudioCodecs(Collections.singletonList(AudioCodec.ISAC))
    .preferVideoCodecs(Collections.singletonList(VideoCodec.H264))
    .build();

Room room = Video.connect(context, connectOptions, listener);
```

Currently H.264 is only supported on Android devices with hardware support, so using H.264 should reduce the CPU impact on the M300.

#### Optimize Capturing Resolution

In my experience the optimal capturing resolution for Vuzix was 640x360. I recommend using the video constraints API to set the max resolution to 640x360.

---

Let me know what options are feasible for your use case and we can keep working to find a solution.

Thanks!

**Comment by ppriyank40** [comment]
Hello,
I have checked with the above code and found that H264 is not supported on M300 so we have to go with VP8 only.Currently, we have set the Resolution to 640x480 so i will change it your suggestion.Can you help me with max bitrates and fps also? What will be the best maximum values for these two?

**Comment by ppriyank40** [comment]
Below is the code snippet of parameters i am setting in M300. But still i am getting very low fps(below 10 sometimes which should not be as i have set min to 10) and also the bitrates are very low.
So,please can you tell is this the correct way to set all parameters? And if yes then why i am getting lower bitrates and fps.


minfps = 10;
maxfps = 24;
VideoDimensions videoDimensions = new VideoDimensions(640,360);
mindimension = videoDimensions;
maxdimension = videoDimensions;
aspectRatio = AspectRatio.ASPECT_RATIO_4_3;


VideoConstraints videoConstraints = new VideoConstraints.Builder()
.minFps(minfps)
.maxFps(maxfps)
.maxVideoDimensions(maxdimension)
.minVideoDimensions(mindimension)
.aspectRatio(aspectRatio)
.build();
localVideoTrack = LocalVideoTrack.create(activity, true, cameraCapturerCompat.getVideoCapturer(), videoConstraints);

videobitrate = 1024*1024*5;
audiobitrate = 300;
videocodec = VideoCodec.VP8;

ArrayList<VideoCodec> arr_videocodec = new ArrayList<>();
arr_videocodec.add(videocodec);

ConnectOptions.Builder connectOptionsBuilder = new ConnectOptions.Builder(accessToken)
.preferVideoCodecs(arr_videocodec)
.encodingParameters(new EncodingParameters(audiobitrate, videobitrate))
.roomName(roomName);

**Comment by ppriyank40** [comment]
Hi Aaron, Thank you for your help. Your points on the 16:9 resolution are very valid, and we are testing the changes at our end in diff. environment. Will keep you posted very soon.

On the constraints, I understand about webRTC's self-optimization. However, what we are trying to do is send lower quality video on a good network. For example, our network on both the ends support >10Mbps. However, we are trying to limit the bits, frames, and resolution that can be sent. Does that fall in the same category?

**Comment by aaalaniz** [comment]
Hey @ppriyank40 

Apologies for the delayed response. 

> However, what we are trying to do is send lower quality video on a good network. For example, our network on both the ends support >10Mbps. However, we are trying to limit the bits, frames, and resolution that can be sent. Does that fall in the same category?

Setting a limit on the capture resolution and max bitrates reduces the amount of data pushed through the device's network. However, I'm not sure if this answer provides all the details you need. I'm closing this issue for now as I'm not sure there are any action items. Please reopen if you have any more questions @ppriyank40. Thanks!
