### ISSUE TITLE
Wrong amount of active users when incomingInvite.getParticipants() is called.

### ISSUE THREAD

**Issue by Skalaw** [twilio/video-quickstart-android#28]
I using: 'com.twilio:conversations-android:0.12.2'.

Sometimes i don't have correct user when TwilioConversationsClient.Listener onIncomingInvited is called, variable incomingInvite.getParticipants() returns the wrong amount of active users.

**Comment by aaalaniz** [comment]
Hi @Skalaw,

I encourage you to try our new library which is in developer preview. One of the shortcomings of the conversations library, is that it required inviting. In this developer preview, we no longer invite. Users join using a room name. You are free to signal the room name to other participants with whatever you prefer(GCM, Firebase, etc.). The developer preview is available here (https://github.com/twilio/video-quickstart-android/tree/rooms) and we will be deprecating conversations in favor of this new library in the coming weeks as it goes into public beta.
