### ISSUE TITLE
How can I disable remote audio of all participants.

### ISSUE THREAD

**Issue by shivthepro** [twilio/video-quickstart-android#281]
I want to disable audio of all remote participants. I saw this https://github.com/twilio/video-quickstart-android/issues/253 issue. The solution given for this issue will work fine if there is only one remote participant. 

But In my case If I have more number of remote participants(group-call) I can't disable playback for all the the participants everytime I want them to be muted. Is there a global way to mute the whole room at once.

**Comment by aaalaniz** [comment]
Hey @shivthepro 

We don't currently support globally muting a room, but I have raised this request with our backend team. What type of use case are you developing?

Thanks!

**Comment by shivthepro** [comment]
Hey @aaalaniz 

Consider that I'm connected to room which has more number of remote participants in it. While I'm in the video call I'm getting a incoming phone call in my mobile.

In this situation I have to mute the room, mute my mic as well as disable my video to attend the phone call and once the phone call is over I have to re-enable these. Im able to have control over the muting the mic and disabling video and re-enabling them after the phone call. 

The problem is with the room, if Im not muting the room I will be hearing the audio from both phone call and the video call. And if I want to mute the room the only option now is to get all the remote participants AudioTrack and mute them individually and once the call finishes I have to unmute for all the remote-participants.

I hope you got my use-case. Let me know if you have any other alternative solution for it.

Thanks!

**Comment by aaalaniz** [comment]
Hey @shivthepro 

Thanks for highlighting the details. Unfortunately, what you are currently doing is the only solution at this time. I have sent this request to our team and I will provide any relevant updates on this issue. 

Thanks!

**Comment by aaalaniz** [comment]
@shivthepro  Closing as a won't fix for now as there are no plans to add this type of feature to the SDK or REST API. Thanks!
