### ISSUE TITLE
Gson issue

### ISSUE THREAD

**Issue by bhuvaneshwariarkala** [twilio/video-quickstart-android#282]
Hi,

Iam facing below issue while using Binding API.

Exception creating binding: Unable to invoke no-args constructor for class com.twilio.rest.notify.v1.service.BindingCreator. Register an InstanceCreator with Gson for this type may fix this problem.
java.lang.RuntimeException: Unable to invoke no-args constructor for class com.twilio.rest.notify.v1.service.BindingCreator. Register an InstanceCreator with Gson for this type may fix this problem.

Please help
Thanks,
Bhuvana

**Comment by aaalaniz** [comment]
Hey @bhuvaneshwariarkala 

Are you using the [Twilio Java helper library](https://www.twilio.com/docs/libraries/java)? I recommend filing an issue on their [Github repo](https://github.com/twilio/twilio-java).

Thanks!
