### ISSUE TITLE
Local Video gets black screen when I open camera app in phone.

### ISSUE THREAD

**Issue by shivthepro** [twilio/video-quickstart-android#286]
Consider you are on a call with someone and you are opening the local camera app in your phone.. After you are returning back to the call. Im getting a black screen for the local video view. 

Steps to Reproduce...
1. Be on Call in the twilio app.
2. Go to home and open camera app.
3. Return back to twilio app.

**Comment by aaalaniz** [comment]
Hey @shivthepro 

Is this a bug in the quickstart or is this a problem you are seeing in your own application?

Thanks!

**Comment by shivthepro** [comment]
Hey @aaalaniz  Thanks ... Found the issue -> I was not releasing and acquiring the camera back when I go to background and come back ..

**Comment by softhealtech** [comment]
Shangeethsivan i have same problem can u tell me solution.. what you do exactly in onPause method

**Comment by braver-tool** [comment]
@shangeethsivan I am also facing the same problem, can you share the fix for that issue?
