### ISSUE TITLE
ScreenCapturer is fixed to landscape orientation

### ISSUE THREAD

**Issue by ryanjohn1** [twilio/video-quickstart-android#287]
### Description

When using the ScreenCapturer to record the device screen and then uploading the resulting video as a VideoTrack it seems like the video is always being set to be 640 x 480 pixels. If you record the screen when the device is landscape this is ok (even if it would be better to use an aspect ratio that matched the actual screen). However if you record a portrait screen  then its still recording the width as 640 pixels and a height of 480 with wide black bars to the left and right.
Is there a way to tell the ScreenCapturer the device orientation in order to choose the larger dimension? Would overriding getSupportedFormats() do any good? 
There is a comment in that method:        
 // TODO: Add support for more formats based on the size of device screen GSDK-1243

I tried to replace the ScreenCapturer with our own implementation to customise it. This doesn't seem possible currently though as you can't instantiate a VideoFrame as the Texture version of the constructor is not public. I see you haven't settled on an API for that yet but would it be possible make the constructor public with an @Experimental tag and/or comment to make it clear that this may change in future versions

Let me know if any further information or code would be useful

### Versions

All relevant version information for issue.

#### Video Android SDK

2.0.0-beta5

#### Android API

21+

#### Android Device

Any

**Comment by aaalaniz** [comment]
Hey @ryanjohn1 

Thanks for submitting this issue. Ironically, I just fixed the issue with the fixed VGA capturing size in  `ScreenCapturer` last week. The new implementation will capture at the device's resolution instead of VGA. The change is being tested internally and should be available in `2.0.1` this week. If you want to test this new change for yourself you can use the following snippet.

```
@TargetApi(21)
public class CustomScreenCapturer extends ScreenCapturer {
    private static final int SCREENCAPTURE_FRAME_RATE = 30;
    
    private final Context context;
    
    public CustomScreenCapturer(Context context,
                                int screenCaptureIntentResult,
                                Intent screenCaptureIntentData,
                                Listener screenCapturerListener) {
        super(context, screenCaptureIntentResult, screenCaptureIntentData, screenCapturerListener);
        this.context = context;
    }

    @Override
    public synchronized List<VideoFormat> getSupportedFormats() {
        List<VideoFormat> screencastFormats = new ArrayList<>();
        DisplayMetrics displayMetrics = new DisplayMetrics();
        WindowManager windowManager =
                (WindowManager) context.getSystemService(Context.WINDOW_SERVICE);
        windowManager.getDefaultDisplay().getRealMetrics(displayMetrics);
        VideoDimensions screenDimensions = new VideoDimensions(displayMetrics.widthPixels,
                displayMetrics.heightPixels);

        screencastFormats.add(new VideoFormat(screenDimensions,
                SCREENCAPTURE_FRAME_RATE, VideoPixelFormat.RGBA_8888));

        return screencastFormats;
    }
}
```

Regarding exposing capturing to a texture to the `VideoCapturer` API, we have had this in our backlog but have not prioritized the work. If `2.0.1` changes to `ScreenCapturer` satisfy your use case, is capturing to a texture still a need for you app?

**Comment by ryanjohn1** [comment]
Thanks @aaalaniz for getting back to me so quickly!
I've just tried the above CustomScreenCapturer and it massively improved the portrait quality so that's great. 
I have noticed one issue which is the same as before:

When the host device and viewing device are the same orientation as each other everything is fine.
When the host and viewer are at different orientations to each other then the width is always being fitted. So for one combination then the screen is small and all fits on the screen as planned. However, for the other combination (host = portrait, viewer = landscape) then the width is fixed and most of the content is either cropped off the top or bottom

I'd have expected it to fit so that the biggest dimension is fixed to the sides.
Should I be doing something different with the VideoView? It's set to Match parent in both directions to fill the screen and I've not changed the scale type from the default which is FIT

With regards to capturing a texture, we may not need to with these changes. Although, one thing we wanted to try out was trying to customise which view elements are captured from the MediaProjectionManager. What we'd love to do is remove the hosts notifications from the stream so we were going to see if we could play with the WindowManager to try and remove that layer before capturing. Not even sure if that is possible though. We'd need the ability to capture a texture in order to attempt that though I think. Any thoughts on that?

**Comment by aaalaniz** [comment]
Hey @ryanjohn1 

I'm actually able to reproduce your issue where the viewer is in landscape and the host device sharing screen is in portrait. This happens with both ScreenCapturer and CameraCapturer, so I think there may be a problem renderer side. I'll investigate more and get back to you.

> What we'd love to do is remove the hosts notifications from the stream so we were going to see if we could play with the WindowManager to try and remove that layer before capturing

I'm not sure MediaProjection supports this, but it's certainly worth a try. Either way it would be great capture to a texture in custom capturers.

**Comment by ryanjohn1** [comment]
Great, thanks. 
Also, what's the best way to keep up to date with details of releases and view the change log for the video-android library?

**Comment by aaalaniz** [comment]
The Video Android 2.x SDK is now GA the changelog is updated [here](https://www.twilio.com/docs/video/changelog-twilio-video-android-version-2x). The 1.x SDK is still GA with changelog [here](https://www.twilio.com/docs/video/changelog-twilio-video-android-version-1x), but updates will only be limited to critical bug fixes.

Thanks!

**Comment by aaalaniz** [comment]
>  However, for the other combination (host = portrait, viewer = landscape) then the width is fixed and most of the content is either cropped off the top or bottom. I'd have expected it to fit so that the biggest dimension is fixed to the sides.
Should I be doing something different with the VideoView? It's set to Match parent in both directions to fill the screen and I've not changed the scale type from the default which is FIT

Apologies but I think I misinterpreted your question here. If you would like the video to fill the entire view and preserve aspect ratio then I recommend using `VideoScaleType.ASPECT_FILL`. Note that this may cause cropping.

The original ScreenCapturer issue submitted has been fixed in 2.0.1. Thanks for filing this issue @ryanjohn1.

**Comment by ryanjohn1** [comment]
@aaalaniz I've been doing some testing on 2.0.1 and I think there may still be an issue. This fix works great if you start and remain streaming in the same orientation. However, if you start streaming in one orientation then change, the stream dimensions remain the size of the original and you end up with a tiny display. 
I've recorded a gif to demonstrate from the viewers perspective on an iOS device: it's a little difficult to follow as you can't see the device being rotated, so I'll explain the 4 combinations of views being shown:

1. We start with host in landscape, viewer is portrait. (all good)
2. Viewer rotates to landscape to match (all good)
3. Host now rotates to portrait (also correctly showing)
4. Viewer rotates to landscape (not right)
![screen-capturer-rotation](https://user-images.githubusercontent.com/6177486/39475901-028206a0-4d52-11e8-9964-73d207127d19.gif)

So in the final stage you can see that the video stream still has the initial aspect ratio (slightly less dark than the rest of screen) and the portrait video is being shown fitted into landscape stream.

**Comment by aaalaniz** [comment]
Thanks for the gif @ryanjohn1 

This behavior does seem strange. I'll chat with our team today to diagnose. Do these same steps work if the viewer is an Android device?

**Comment by ryanjohn1** [comment]
Android to Android does behave a bit differently. When the host is landscape and viewer is portrait the view is all wrong, it looks zoomed in. All the other combinations are ok.
