### ISSUE TITLE
Participant disconnected

### ISSUE THREAD

**Issue by ycoupe** [twilio/video-quickstart-android#29]
I using: 'com.twilio:conversations-android:0.12.2'.

Sometines (~2/3) a participant is disconnected. These event are called : 
- Participant.onAudioTrackRemoved
- Participant.onVideoTrackRemoved
- Conversation.onParticipantDisconnected

If I look at the trace, this first event is called by this fonction in Conversation.class : 
`public void onAudioTrackAdded(TrackInfo trackInfo, AudioTrack webRtcAudioTrack)`

at the line : `participant.getParticipantListener().onAudioTrackAdded(SessionObserverInternal.this.conversation, participant, audioTrack);`

Thanks

Yann

**Comment by idelgado** [comment]
Hi @ycoupe 

We are deprecating the `conversations` library moving forward in favor of this Room based video library. In this video library you no longer have to invite, you simply pre-define or share a room name with other participants using whatever signaling channel you prefer(GCM, Firebase, etc.).

I encourage you to try our new library which was just released in beta last Friday. We will GA this library later this year.

You can find more information on how to get started in the link below or checkout the latest quickstart to give it a try.

https://www.twilio.com/docs/api/video
