### ISSUE TITLE
How can i send invite or add new user in existing video call??

### ISSUE THREAD

**Issue by imran-samed** [twilio/video-quickstart-android#290]
I want to add new user , while already two person are video calling,
I can't find a method in twilio android sdk to add new user.

I'm using  this video sdk version
**implementation "com.twilio:video-android:2.0.0-beta5"**

**Comment by ceaglest** [comment]
Hey @imran-samed,

We don't support inviting Participants in Twilio Video, but we encourage you to use a separate signaling channel like push notifications for this purpose. Take a look at [ExampleVideoInvite](https://github.com/twilio/video-quickstart-android/tree/master/exampleVideoInvite) for a solution using Twilio Notify to deliver invites over FCM.

Best,
Chris

**Comment by aaalaniz** [comment]
Thanks @ceaglest! 

Please re-open @imran-samed if you have more questions about using Twilio Notify to invite participants.

Thanks!

**Comment by imran-samed** [comment]
But as per mention in VideoInviteActivity.class , that app doesn't support multiple participants.

` if (thumbnailVideoView.getVisibility() == View.VISIBLE) {

            Snackbar.make(connectActionFab,
                    "Rendering multiple participants not supported in this app",
                    Snackbar.LENGTH_LONG)
                    .show();
            return;

        }`

**Comment by aaalaniz** [comment]
Hey @imran-samed 

You will have to render video tracks from all the participant's that join the Room. Our quickstarts currently only demonstrate 1:1 calling for simplicity. We plan on a releasing a multi-party example at some point, but I cannot provide timeline details.

Thanks!

**Comment by bansalparul26** [comment]
Hi @aaalaniz . 
Can you please describe how to add multiple render video tracks?

**Comment by aaalaniz** [comment]
Hey @bansalparul26 

Please reference the [Video Collaboration App](https://github.com/twilio/twilio-video-app-android) for this use case.

Thanks!
