### ISSUE TITLE
Group Video Call

### ISSUE THREAD

**Issue by imran-samed** [twilio/video-quickstart-android#295]
### Description

I just implemented 1:1 video call in application. but I'm not getting any hint to how can i make group  video call.
what are the steps to follow...
How multiple notifications will be send.
I searched a lot but nothing found.

Is it possible to using [VideoInviteActivity.class](https://github.com/twilio/video-quickstart-android/blob/master/exampleVideoInvite/src/main/java/com/twilio/video/examples/videoinvite/VideoInviteActivity.java) in QuickStart...??

**Comment by aaalaniz** [comment]
Hey @imran-samed 

I recommend reading the [Video Invite README](https://github.com/twilio/video-quickstart-android/tree/master/exampleVideoInvite) for detailed instructions on how to setup a Group call using Twilio Notify.

Thanks!

**Comment by imran-samed** [comment]
**Is it possible using VideoInviteActivity.class  ??**

**Comment by aaalaniz** [comment]
The VideoInviteActivity provides an example of how to join a room from a push notification received from Twilio Notify. Building Group calling is certainly possible from VideoInviteActivity but there will need to be changes to accommodate rendering all participant video tracks.
