### ISSUE TITLE
getting crash while video calling

### ISSUE THREAD

**Issue by darshanjoc** [twilio/video-quickstart-android#298]
### Description

During video call stream freezes and stops rendering, I just call from web/Android/ios to RealWear HMT-1. This issue is only reproducible in REalWear HMT-1, I got this error every time.
After updating Video SDK to 2.0.2, I didn't get crash but stream stucks during video call, I mentioned logs for your information 

### Steps to Reproduce

normal video call from web/Android/ios to RealWear HMT-1.

#### Code

Camera Capturer class:
https://drive.google.com/file/d/1Rleqn6CkMW0vWbD__adCfneojk_Ji0n1/view?usp=sharing

#### Expected Behavior

video call should work properly.

#### Actual Behavior

Video call screen freeze during the video call.

#### Reproduces how Often

100%

#### Logs

link to the log file:
https://drive.google.com/file/d/1B08aCTe7HAoMsdvMVzTkgLoahd2F_CmB/view?usp=sharing

### Versions

Android Version: 6.0.1

#### Video Android SDK

2.0.0 and 2.0.2

#### Android API

23

#### Android Device

RealWear HMT-1

**Comment by zackm0571** [comment]
Closing for now. Please reopen if you're still having issues.
