### ISSUE TITLE
Get RecordingSid from recording events in android

### ISSUE THREAD

**Issue by valerymadiedo** [twilio/video-quickstart-android#299]
### Description
Hello! I've been working on a demo but I need to get the recordingSid from the onRecordingStarted event. My question is if possible, how can I get the recordingSid in an android device? or if not possible what alternative do I have to get the recordingSid?

**Comment by aaalaniz** [comment]
Hey @valerymadiedo 

I recommend setting up a Webhook to your backend that receives [Room Status Callbacks](https://www.twilio.com/docs/video/api/status-callbacks#rooms-status-callback-events). Your backend will receive the documented [recording information](https://www.twilio.com/docs/video/api/status-callbacks#recordings-status-callback-request-parameters) with the `recording-completed` event. You can then deliver any relevant information to your Android client with a service of your own (FCM, Websocket, etc).

Happy to field any follow-up.

Thanks!

**Comment by aaalaniz** [comment]
@valerymadiedo 

You can setup a Webhook in the Twilio console [under Room settings](https://www.twilio.com/console/video/configure).

![screen shot 2018-05-16 at 9 08 12 am](https://user-images.githubusercontent.com/1734140/40122157-c49d6a30-58e8-11e8-83e9-b808886821a0.png)

**Comment by valerymadiedo** [comment]
@aaalaniz 
Thank you!! I will proceed to try it :)
