### ISSUE TITLE
How to use custom screen capture with camera capture?

### ISSUE THREAD

**Issue by SagarSculpt** [twilio/video-quickstart-android#306]
private void addCameraVideo() {
        cameraCapturer = new CameraCapturer(this, CameraCapturer.CameraSource.BACK_CAMERA);
        localVideoTrack = LocalVideoTrack.create(this, true, cameraCapturer);
        localVideoTrack.addRenderer(LocalvideoView);
        addCaptureView();
    }

    private void addCaptureView() {
        CapturedVideoTrack = LocalVideoTrack.create(this, true, new ViewCapturer(ToBeSharedView));
        CapturedVideoTrack.addRenderer(CapturedvideoView);
    }

I am adding 2 twilio video view to single xml and in It's main activity using above code to particular view to share in 2nd video view. but It giving me black view on 2nd video view.
In this case I'm using Custom capture view which is in Twilio gitHub quik start example.

**Comment by ahmadtahirpk** [comment]
What is in your "ToBeSharedView". It might that the view is not initialized when you start capturing view.

**Comment by aaalaniz** [comment]
Hey @SagarSculpt 

I apologize for the delayed response. What are the contents of `ToBeSharedView`? Can you share any logs?

Thanks!

**Comment by SagarSculpt** [comment]
This is my MainActivity.java

public class MainActivity extends AppCompatActivity {
    private static final int CAMERA_PERMISSION_REQUEST_CODE = 100;

    private VideoView LocalVideoView;
    private VideoView CapturedVideoView;
    private RelativeLayout ToBeSharedView;

    private CameraCapturer cameraCapturer;
    private LocalVideoTrack localVideoTrack;
    private LocalVideoTrack CapturedVideoTrack;
    private Chronometer mChronometer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        LocalVideoView = findViewById(R.id.local_video_view);
        CapturedVideoView = findViewById(R.id.captured_video_view);
        ToBeSharedView = findViewById(R.id.tobe_shared_view);
        mChronometer = findViewById(R.id.chronometer);

        mChronometer.start();

        if (!checkPermissionForCamera()) {
            requestPermissionForCamera();
        } else {
            addCameraVideo();
        }
    }


    private boolean checkPermissionForCamera() {
        int resultCamera = ContextCompat.checkSelfPermission(this,
Manifest.permission.CAMERA);

        return resultCamera == PackageManager.PERMISSION_GRANTED;
    }

    private void requestPermissionForCamera() {
        ActivityCompat.requestPermissions(this,
                new String[]{Manifest.permission.CAMERA},
                CAMERA_PERMISSION_REQUEST_CODE);
    }

    private void addCameraVideo() {
        cameraCapturer = new CameraCapturer(this,
CameraCapturer.CameraSource.BACK_CAMERA);
        localVideoTrack = LocalVideoTrack.create(this, true, cameraCapturer);
        localVideoTrack.addRenderer(LocalVideoView);
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                addCaptureView();
            }
        }, 2000);
    }

    private void addCaptureView() {
        CapturedVideoTrack = LocalVideoTrack.create(this, true, new
ViewCapturer(ToBeSharedView));
        CapturedVideoTrack.addRenderer(CapturedVideoView);
    }

    @Override
    public void onRequestPermissionsResult(int requestCode,
                                           @NonNull String[] permissions,
                                           @NonNull int[] grantResults) {
        if (requestCode == CAMERA_PERMISSION_REQUEST_CODE) {
            boolean cameraPermissionGranted = true;

            for (int grantResult : grantResults) {
                cameraPermissionGranted &= grantResult ==
PackageManager.PERMISSION_GRANTED;
            }

            if (cameraPermissionGranted) {
                addCameraVideo();
            } else {
                requestPermissionForCamera();
            }
        }
    }
}

This is XML of mainactivity

<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout
xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="sagar.s.screenshare.MainActivity">

    <RelativeLayout
        android:id="@+id/tobe_shared_view"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:background="@android:color/white"
        app:layout_constraintDimensionRatio="H,16:9"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <com.twilio.video.VideoView
            android:id="@+id/local_video_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:visibility="visible" />

        <EditText
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_margin="8dp" />

    </RelativeLayout>

    <com.twilio.video.VideoView
        android:id="@+id/captured_video_view"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintDimensionRatio="H,16:9"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/tobe_shared_view"
        app:layout_constraintVertical_bias="0.1" />

    <Chronometer
        android:id="@+id/chronometer"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        android:layout_marginBottom="8dp"
        />

</android.support.constraint.ConstraintLayout>

**Comment by SagarSculpt** [comment]
06-30 10:47:23.696 4387-4433/sagar.s.screenshare E/EGL_emulation: eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
06-30 10:47:23.696 4387-4433/sagar.s.screenshare E/EGL_emulation: tid 4433: eglQueryContext(1696): error 0x3004 (EGL_BAD_ATTRIBUTE)

above is the log when below method called.

addCaptureView()

**Comment by aaalaniz** [comment]
Hey @SagarSculpt 

Have you tried our [ScreenCapturer](https://twilio.github.io/twilio-video-android/docs/latest/com/twilio/video/ScreenCapturer.html)? This might be a better fit for your use case.

Thanks!

**Comment by SagarSculpt** [comment]
ScreenCapturer working fine but I want show only that particular view to opponent. Not my whole screen.

**Comment by aaalaniz** [comment]
Hey @SagarSculpt 

It looks like you are trying to use `ViewCapturer` to render a `VideoView` however, I don't think that `ViewCapturer` can render `VideoView` because `VideoView` is a subclass of `SurfaceView`. If your app has a hard requirement on sharing the contents of a `VideoView` then I recommend trying [VideoTextureView](https://gist.github.com/aaalaniz/bfbc4891c98ef3b23558ff2260cbcc8e) with `ViewCapturer`.

Thanks!

**Comment by SagarSculpt** [comment]
Hey @aaalaniz 

Above solution is not working. Black stream showing remote side.
I'm attaching zip of my code here.
[VideoCall.zip](https://github.com/twilio/video-quickstart-android/files/2187270/VideoCall.zip)

**Comment by zackm0571** [comment]
Hey @SagarSculpt, 

Just wanted to check back in on this one. Are you still having the same issue?

**Comment by zackm0571** [comment]
We're going to close this one for now, but please reach out if this is still an issue. Hope you found a solution!
