### ISSUE TITLE
Disconnection problem.

### ISSUE THREAD

**Issue by sanjogshrestha** [twilio/video-quickstart-android#310]
The participant is automatically thrown out from the room. What is the actual logic behind it? How can we avoid this or is there any way we could get reason for the same. FYI, onDisconnected() is invoked

**Comment by shivthepro** [comment]
Hey @sanjogshrestha  I have faced this issue while you are trying to connect to the room with same access tokens. Check once weather your devices are having different access tokens.

**Comment by sanjogshrestha** [comment]
@shivthepro Initially the user are inside the room and then after 15 minutes , user is thrown out from the room. In between that period, user can easily communicate with each other.

**Comment by aaalaniz** [comment]
Hey @sanjogshrestha 

The [onDisconnected](https://twilio.github.io/twilio-video-android/docs/latest/com/twilio/video/Room.Listener.html#onDisconnected-com.twilio.video.Room-com.twilio.video.TwilioException-) callback includes a `TwilioException`. Can you check if `onDisconnected` is invoked with a non `null` exception and provide the code and message? If the `TwilioException` is `null` then the participant was disconnected normally without error.

Thanks!

**Comment by sanjogshrestha** [comment]
@aaalaniz The exception says "Unable to re-establish signalling connection to Twilio". What might be the cause of so?

**Comment by aaalaniz** [comment]
Hey @sanjogshrestha 

I can look into it. Can you get the Room SID from the `Room` object? You can call `getSid` on the Room object when you receive the `onDisconnected` callback.

Thanks!

**Comment by zackm0571** [comment]
@sanjogshrestha are you still experiencing this issue? If so, could you provide the room SID?

**Comment by zackm0571** [comment]
Feel free to reopen if you're still having issues

**Comment by sanjogshrestha** [comment]
Sure. Thanks!
