### ISSUE TITLE
VIdeo Group Call

### ISSUE THREAD

**Issue by MohdIrfan12** [twilio/video-quickstart-android#313]
I am implementing group video call. For one to one it works well, But if there are multiple user's we can't see each other's video   
below is the code i have written in onVideoTrackSubscribed callback and remoteVideoTrackPublication.isTrackSubscribed() is always true.

 /*
         * Add remote participant renderer
         */
        if (remoteParticipant.getRemoteVideoTracks().size() > 0) {
            RemoteVideoTrackPublication remoteVideoTrackPublication = remoteParticipant.getRemoteVideoTracks().get(0);
            /*
             * Only render video tracks that are subscribed to
             */

            if (remoteVideoTrackPublication.isTrackSubscribed()) {
                holder.videoView.setMirror(false);
                holder.videoView.setVisibility(View.VISIBLE);
                videoTrack.addRenderer(holder.videoView);
            } else {
                holder.videoView.setVisibility(View.GONE);
            }
        }

**Comment by zackm0571** [comment]
@MohdIrfan12 could you post your activity in full? This will be easier to debug with more context.

Thanks!

**Comment by AnkitSingh80** [comment]
Hi,i have to make a video group call of maximum 4 people and need to show all the videos.so do the library provide any related help in rendering multiple videos  or we have to handle it by ourself?.

**Comment by AnkitSingh80** [comment]
Hi,i have to make a video group call of maximum 4 people and need to show all the videos.so do the library provide any related help in rendering multiple videos  or we have to handle it by ourself?.

**Comment by aaalaniz** [comment]
Hey @AnkitSingh80 

The Video Android SDK does not provide components that help with rendering a multi-party call. We require developers to handle rendering participants video according to their application's needs. However, our team has discussed adding these type of UI components (or creating a separate library) to help reduce the amount of code required to add video to your application. Open a separate issue with this request and provide details about what type of UI related components would be helpful.

Thanks!

**Comment by AnkitSingh80** [comment]
thanks @aaalaniz.

**Comment by jd-gupta27** [comment]
Hi,
I am trying to make a video group call of 4 people. I used QuickStart code and one to one call is working fine. I want to make it for multi participant.

**Comment by chandrikaReddyBunga** [comment]
private fun connectButtonClick() {
        InputUtils.hideKeyboard(this)
        binding.joinRoom.connect.isEnabled = false
        // obtain room name
        val text = binding.joinRoom.roomName.text
        if (text != null) {
            val roomName = text.toString()
            //val viewEvent = Connect( "sidhu777", roomName)
            val viewEvent = Connect( "chandu", roomName)
            roomViewModel.processInput(viewEvent)
        }
    } when connect the room its automatically disconnect on one device and then connect on another device
