### ISSUE TITLE
Integrating wikitude with twillio

### ISSUE THREAD

**Issue by shrungBhatt** [twilio/video-quickstart-android#314]
I have made an Augmented Reality app which augments 3d objects on detecting various 3d objects. My next use case is to make that augmentation available for a video chat. Now the wikitude sdk needs a Camera for the object detection purpose, but as the VideoTrack in Tiwillio gives mutual exclusion to the Camera, is there any other way to give the camera access to Wikitude sdk?

**Comment by zackm0571** [comment]
@shrungBhatt will take a look at the Wikitude SDK after the holiday weekend. In the mean time, if Wikitude SDK has some way to consume raw camera frames, all you would need to do is write a custom capturer to feed frames to both Twilio and Wikitude, The [custom capturer example](https://github.com/twilio/video-quickstart-android/tree/master/exampleCustomVideoCapturer) might be a good place to start :)

**Comment by shrungBhatt** [comment]
Yup I have used PluginAPI from the start. Can you tell me how I can get the frame from Twilio in order to pass it in the CameraCapturer?

**Comment by zackm0571** [comment]
@shrungBhatt apologies for the major delay in response. You can grab a reference to the raw frame byte data by using a custom `VideoCapturer` and an implementation of `VideoCapturer.Listener`. 

- Start by extending  [VideoCapturer](https://twilio.github.io/twilio-video-android/docs/3.2.2/com/twilio/video/VideoCapturer.html).
- Implement it's methods.
- Add a [VideoCapturer.Listener](https://twilio.github.io/twilio-video-android/docs/3.2.2/com/twilio/video/VideoCapturer.Listener.html).
- `VideoCapturer.Listener.onFrameCaptured` will provide a handle to a [VideoFrame](https://twilio.github.io/twilio-video-android/docs/3.2.2/com/twilio/video/VideoFrame.html)
- `videoFrame.imageBuffer` will contain the raw image bytes of the frame. 

Hope you've found a solution!

Zack

**Comment by zackm0571** [comment]
@shrungBhatt I apologize. This was the incorrect response. I'll be crafting the correct response today. Sorry for any inconvenience.

**Comment by zackm0571** [comment]
@shrungBhatt just want to make sure that you're looking to get a frame from Twilio and then pass it off to Wikitude? If this is the case I can make a quick example. Hope to hear from you soon!

- Zack

**Comment by shrungBhatt** [comment]
Hi there @zackm0571, I would appreciate that help.

**Comment by zackm0571** [comment]
Hey @shrungBhatt,

I apologize for the dragged out response. Unfortunately, we don't officially support the interception of frames within our existing capturers. However, we fully support custom capturers. Which means you can create an implementation of `Camera2`, `WikitudeCamera2`, or the [WebRTC Camera2 Capturer](https://chromium.googlesource.com/external/webrtc/+/772bd0d40b3b4c18d391c943b92c9c2714a8c027/webrtc/api/android/java/src/org/webrtc/Camera2Capturer.java) and perform operations on the byte buffer from that capturer before sending to our SDK. Our [custom video capturer example](https://github.com/twilio/video-quickstart-android/tree/master/exampleCustomVideoCapturer) does a really good job of showing how to do this except by capturing an Android `View`. I would suggest checking out [ViewCapturer.java](https://github.com/twilio/video-quickstart-android/blob/master/exampleCustomVideoCapturer/src/main/java/com/twilio/video/examples/customcapturer/ViewCapturer.java) specifically. 

Zack

**Comment by aaalaniz** [comment]
Hello all,

Integrating the Twilio Video SDK with Wikitude is not currently on our roadmap. We appreciate the input and suggestions, but I will close this issue.

Thank you
