### ISSUE TITLE
Issue In streaming video in CustomViewCapturer example

### ISSUE THREAD

**Issue by AnkanDey** [twilio/video-quickstart-android#316]
Hello.

I am facing the an issue here. I have downloaded the twilio example of CustomVideoCapturer from git, and just added a videoview in the activity_custom_capturer.xml. Everything showing in the local videoview(@+id/video_view)(eg. Checkbox, Chronometer) but the video(@+id/video) showing black.

My XML looks like below.

<LinearLayout
        android:id="@+id/captured_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:layout_weight="1"
        android:background="@android:color/white">

<Chronometer
    android:id="@+id/timer_view"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_margin="8dp" />

<CheckBox
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_margin="8dp" />

<EditText
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_margin="8dp" />

<VideoView
    android:id="@+id/video"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />

</LinearLayout>

<com.twilio.video.VideoView
android:id="@+id/video_view"
android:layout_width="match_parent"
android:layout_height="match_parent"
android:layout_weight="1" />

Please help me.

**Comment by AnkanDey** [comment]
Hello...Is there anyone to help?

**Comment by zackm0571** [comment]
Hey @AnkanDey, I apologize for the delayed response. To help troubleshoot can you provide a screenshot of what you're seeing, the xml of your activity, and the code where you're setting up your video tracks?

**Comment by zackm0571** [comment]
@myxoh can please you add a screenshot of this behavior to help understand what's happening?

**Comment by myxoh** [comment]
I'm sorry, I don't have the code anymore as I've ended up solving the issue in a different way and didn't commit the non-working example anywhere

**Comment by skytron** [comment]
Hi @myxoh, I have same issue. I would streaming a sceneview from ARcore, but the screen is black. How to solve this problem, thanks!

**Comment by myxoh** [comment]
I've ended up generating bitmaps somewhere else in the code based on the view, and using them to generate Frames

**Comment by skytron** [comment]
Hi @myxoh thanks to reply. I've resolved generating bitmaps with PixelCopy and using them in CustomViewCapturer. I hope this useful for someone.

**Comment by zackm0571** [comment]
Closing issue. Thanks @skytron for providing your solution!
