### ISSUE TITLE
Remote participant's video overlaps the local participant's video in Android 8.0 devices

### ISSUE THREAD

**Issue by jardsman** [twilio/video-quickstart-android#325]
### Description

Remote participant's video overlaps the local participant's video after remote participant has connected and its video starts rendering.

### Steps to Reproduce

1. Set up the video of the local participant in front of the remote participant's video
2. Initiate call to a remote participant.
3. Remote participant connects to call.

#### Expected Behavior

Remote participant's video is shown at the back of the local participant's video.

#### Actual Behavior

Remote participant's video is shown in front of the local participant's video.

#### Reproduces how Often

100%

#### Video Android SDK

2.1.1

![remote_participant_connected](https://user-images.githubusercontent.com/2498316/44795752-0af94d80-abde-11e8-95f6-b6cce3e64b2e.jpg)
![remote_participant_video_rendered](https://user-images.githubusercontent.com/2498316/44795754-0af94d80-abde-11e8-9899-300d7ba75895.jpg)
![initiate_call](https://user-images.githubusercontent.com/2498316/44795755-0b91e400-abde-11e8-8e8c-ef38741ac57e.jpg)

#### Android API

26

#### Android Device

Samsung S7 edge

**Comment by zackm0571** [comment]
Hey @jardsman,

Looking into this. Could you please provide a code snippet of your xml layout?

**Comment by jardsman** [comment]
In devices pre-8.0, I also noticed that when `local_video_container` comes first (which means it is behind) in the layout before `remote_video_container` and the remote participant's video starts rendering, the local video is displayed on top of the remote video. It seems that the rendering of the video layers are being rendered in reverse. This scenario doesn't apply to 8.0 devices.

**Comment by zackm0571** [comment]
@jardsman thanks for the information. I'll investigate this morning.

**Comment by idelgado** [comment]
@jardsman can you try conditionally changing the ZOrder for these Views in Android 8.0 vs older versions?

https://twilio.github.io/twilio-video-android/docs/latest/com/twilio/video/VideoView.html#applyZOrder-boolean-

There a snippet with an example here: https://github.com/twilio/video-quickstart-android/blob/b667be5791c349fc8b33aec041a8bd4143e09cf1/README.md#adding-videoview-programmatically

**Comment by zackm0571** [comment]
@jardsman three questions:

- Could you provide the xml for the layouts in each `<include>` tag? I'm trying to reproduce the image we see above and cannot seem to do so with only the xml given. 
- In the interim could you try swapping the order of the remote video view container and the local video to see if this fixes the issue?
- Would this potentially be solved by adding padding to both sides and adjusting the size of the video views so that they don't overlap?

**Comment by jardsman** [comment]
@zackm0571 kindly disregard the include tags. I updated the layout and removed those views and replaced String references with hardcoded values in the `text` fields of the layout.

> In the interim could you try swapping the order of the remote video view container and the local video to see if this fixes the issue?
- This is the workaround we implemented when we first noticed this, but it doesn't seem to work for devices Android 8.0.

>Would this potentially be solved by adding padding to both sides and adjusting the size of the video views so that they don't overlap?
- Unfortunately, no. Our requirement for this screen requires that the local video is on top of the remote video like the facebook video call.

**Comment by zackm0571** [comment]
@jardsman 

I have good news and bad news. The bad news is after doing a little bit of digging I found that you cannot overlay two SurfaceView's, which is what `VideoView` is using as it's renderer. The good news is that we just released Video Android 2.2.0 which contains `VideoTextureView`. `VideoTextureView` uses a TextureView as it's renderer and in fact supports the behavior you're looking for. 

To solve your problem:

- Update to `2.2.0` of our SDK
- Replace all instances of `VideoView` with `VideoTextureView`

If you're interested, [here](https://stackoverflow.com/questions/16916877/whats-differences-between-surfaceview-and-textureview) is some deeper reading on SurfaceView vs TextureView and their limitations.

**Comment by zackm0571** [comment]
@jardsman 

Quick word of caution,`VideoTextureView` can experience dead locking on API Level 19 or below due to a [WebRTC bug](https://bugs.chromium.org/p/webrtc/issues/detail?id=5702). If you have a need to support devices using API 19 or below you might want to include some logic to switch between `VideoView` and `VideoTextureView` depending on API level.

**Comment by yprak** [comment]
@zackm0571 

I am trying to use 2.2.0 and replaced VideoView with VideoTextureView, as mentioned above. But I get the following error:
Error:In <declare-styleable> VideoView, unable to find attribute overlaySurface

Anything else to be added in build.gradle? Could you please help?

**Comment by jardsman** [comment]
@zackm0571 I tried the solution you provided and it worked. We can close this ticket.

**Comment by jardsman** [comment]
@yprak yes, this line should be in your build.gradle: `implementation 'com.twilio:video-android:2.2.0'`.

**Comment by yprak** [comment]
@jardsman, thanks for your reply. As I have mentioned above, I have indeed added 
implementation 'com.twilio:video-android:2.2.0'. 

But when I do that, I get the following error - 
Error: In < declare-styleable > VideoView, unable to find attribute overlaySurface.

My question is whether there must be a change in buildToolsVersion or is there any other dependency?
My current buildToolsVersion is 25.0.2. What is the buildToolsVersion you are using?

**Comment by jardsman** [comment]
>But when I do that, I get the following error -
Error: In < declare-styleable > VideoView, unable to find attribute overlaySurface.

Are you using `com.twilio.video.VideoView` or `android.widge.VideoView?`.
>My question is whether there must be a change in buildToolsVersion...

Not really sure about that.
>... or is there any other dependency?

There is none other than the twilio dependency.
>What is the buildToolsVersion you are using?

I'm using 27.0.3.

**Comment by yprak** [comment]
@jardsman, I had to upgrade buildToolsVersion to 27.0.3. Thanks for that. 
I was away for a long time. Hence couldn't reply on sooner.

**Comment by snehadhagade** [comment]
Hello

**Comment by snehadhagade** [comment]
Hello
implementation 'com.twilio:video-android:3.1.0'.
But when I do that, I get the following error -
Error: In < declare-styleable > VideoView, unable to find attribute overlaySurface.
My current buildToolVersio 27.0.3 and compileSdkVersio 27
