### ISSUE TITLE
Instance of com.twilio.video.VideoTrack$VideoRendererCallbackAdapter cause memory leaks

### ISSUE THREAD

**Issue by olmur** [twilio/video-quickstart-android#327]
Hello! I got a message from LeakCanary that com.twilio.video.VideoTrack$VideoRendererCallbackAdapter is leaking VideoView context (the one that render LocalVideoTrack) when I'm finishing a call. Before finish I remove video renderer from local video track, than unpublish local video track, release it and set it to null. Doing everything as in quick start application. 

This happens on all of my devices on different android versions.

I have several leaked objects: ReportFragment, LifecycleHandler, RequestManagerFragment and my Activity but all leaks are caused by VideoTrack$VideoRendererCallbackAdapter.videoRenderer object.

Twilio Sdk version: 2.1.1

Could u help with that please?

**Comment by zackm0571** [comment]
Hey @olmur, 

We're going to integrate LeakCanary into our instrumentation tests and follow up with our findings. Thanks for pointing this out.

**Comment by zackm0571** [comment]
@olmur can you post a dump of all the findings that LeakCanary provided? Running about 500+ tests right now and would be interested to compare my findings to yours when it's done.

**Comment by olmur** [comment]
@zackm0571 sure, here it is. 
[leakcanary-dump.txt](https://github.com/twilio/video-quickstart-android/files/2356262/leakcanary-dump.txt)

**Comment by olmur** [comment]
@zackm0571 any progress on that? :)

**Comment by zackm0571** [comment]
@olmur we've put this on the backlog for now. We'll keep you updated as we make progress towards a solution. Is this impacting releases to production for you guys?

**Comment by olmur** [comment]
@zackm0571 hello :) sorry for the delay. yeah it's impacting a little bit but we will release to production anyway. I saw version 3.0 came up recently, should we expect those fixes there?

**Comment by olmur** [comment]
Any progress on this? Version 4.2.0 still has a leak

**Comment by vernazza** [comment]
Same problem in 5.6 ....

**Comment by afalls-twilio** [comment]
Closing, last comment 2 years old
