### ISSUE TITLE
Local view in landscape not showing proper preview

### ISSUE THREAD

**Issue by kbagchiGWC** [twilio/video-quickstart-android#328]
Porting from https://github.com/twilio/voice-quickstart-android/issues/199

Hey,

I'm using twilio video call on landscape mode from android.
I have shared screen shot link below what problem I'm facing now.
Local view height not proper as my local stream size streaming to opponent side.
https://drive.google.com/open?id=1jNMJTv4pfb3aG75f-y7tpZxkH-irEzqL

**Comment by SagarSculpt** [comment]
@zackm0571 I forget to add that currently I'm using textureview for that local view.

**Comment by zackm0571** [comment]
@SagarSculpt To better understand what's happening could you provide a sample of your xml layout, please?

**Comment by SagarSculpt** [comment]
https://drive.google.com/open?id=1QcDNXJcOWuelbOuBlFOZzRFRyVn624Pt

Above link of my video call activity xml.

**Comment by SagarSculpt** [comment]
@zackm0571 

Hi...

My issue solved by this line

twilio_localview.setScalingType(RendererCommon.ScalingType.SCALE_ASPECT_FIT);

**Comment by zackm0571** [comment]
@SagarSculpt glad you got it resolved. Feel free to open another issue if you have anymore questions.
