### ISSUE TITLE
unpublishTrack() calls webhook "participant-disconnected"

### ISSUE THREAD

**Issue by april21dev** [twilio/video-quickstart-android#344]
Like kotlin example, I call unpublishTrack() when my activity goes to onPause state.

And then your system calls "participant-disconnected" to WebHook URL

Is it normal process?

below is my activity's onPause code

fun doOnPause() {
        /*
         * If this local video track is being shared in a Room, remove from local
         * participant before releasing the video track. Participants will be notified that
         * the track has been removed.
         */
        localVideoTrack?.let { localParticipant?.unpublishTrack(it) }

        /*
         * Release the local video track before going in the background. This ensures that the
         * camera can be used by other applications while this app is in the background.
         */
        localVideoTrack?.release()
        localVideoTrack = null
}

**Comment by zackm0571** [comment]
Duplicate issue
