### ISSUE TITLE
No video feed even when connected

### ISSUE THREAD

**Issue by amiga** [twilio/video-quickstart-android#347]
got connected message but cannot see or hear  the other participant and he cant see me. No errors.

**Comment by zackm0571** [comment]
Hey @amiga to make troubleshooting this a little easier could you provide a couple of things?

- Android SDK Version
- Your full video activity with tokens and such omitted 

Thanks!

**Comment by amiga** [comment]
Apologies I was using chatRoomId, it works with roomID
