### ISSUE TITLE
Integrating Google Speech API with Twilio Conversation?

### ISSUE THREAD

**Issue by vikram-gupta** [twilio/video-quickstart-android#35]
Hi Team,

I tried to integrate the Google Speech API (streaming) with the Twilio Conversation sample app so that i can do speech recognition along with video chat. Here is the [link](https://github.com/GoogleCloudPlatform/ios-docs-samples/blob/master/speech/Objective-C/Speech-gRPC-Streaming/README.md) to the Google Speech API sample app that I am integrated. 

But I keep getting a continuous and weird clicking noise in place of the actual audio. The video just works fine. My suspicion is that both the Twilio API  and Google API use the AVAudioSession and in some way they are interacting in an unwanted way.

Any pointers or suggestions?

**Comment by idelgado** [comment]
@vikram-gupta Looks like you are asking about `AVAudioSession` which is part of the obj-c implementation. Please repost your issue here: https://github.com/twilio/video-quickstart-objc

**Comment by vikram-gupta** [comment]
Thanks @idelgado !
