### ISSUE TITLE
Throw error whenever I Use Recording class or Message class

### ISSUE THREAD

**Issue by sanjayrajsinh** [twilio/video-quickstart-android#350]
not even any class work without any  build problem.so Please if required other dependency or any gradle entry then tell me and add in your doc for Android 

I Add all the require dependency i.g
  ```
implementation 'com.twilio.sdk:twilio:7.28.0'
  implementation "com.twilio:video-android:3.0.0"
```

but when try to get redording like
```Twilio.init(ACCOUNT_SID, AUTH_TOKEN);
        ResourceSet<Recording> recordings = Recording.reader()
            .setGroupingSid(Promoter.listOfOne("RMXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))
            .read()

        for(Recording record : recordings) {
            System.out.println(record.getSid());
        }
```
And also when try to use Message at then time also throw same error
` 
  val message = Message.creator(
                                        PhoneNumber("+15558675309"),
                                        PhoneNumber("+15017250604"),
                                        "This is the ship that made the Kessel Run in fourteen parsecs?"
                                ).create()
`

It was throw error
 **java.lang.NoSuchFieldError: No static field INSTANCE of type  Lorg/apache/http/conn/ssl/lHostname
  at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)**

**Comment by zackm0571** [comment]
@sanjayrajsinh could you provide clarity on `implementation 'com.twilio.sdk:twilio:7.28.0'`? What is this being used for? Is video interfering with your ability to use that sdk?

**Comment by idelgado** [comment]
This dependency `implementation 'com.twilio.sdk:twilio:7.28.0' otherwise known as the Java helper library is not supported on Android. It is intended to be used in a server side application.

You can read the docs here for more info: https://www.twilio.com/docs/libraries/java
