### ISSUE TITLE
i have to make a video group call of maximum 4 people and need to show all the videos.

### ISSUE THREAD

**Issue by AnkitSingh80** [twilio/video-quickstart-android#352]
_Originally posted by @AnkitSingh80 in https://github.com/twilio/video-quickstart-android/issues/313#issuecomment-431782912_

**Comment by aaalaniz** [comment]
Hey @AnkitSingh80 

Please update this issue with context from original comment on #313. Provide details of what you are trying to implement and what components that could be added to the Video Android SDK to support your use case. 

Thanks!

**Comment by AnkitSingh80** [comment]
Max 4 people can do video group call so i want the screen to be divided in to 4 equal parts  and if one people leave the call then 2 parts merged into 1 part and other 2 remain same.

currently i am able to make video call for 1 user and its working fine but once i add another one to the same room to the on going video call,onVideoUnsubscribed() call which result in disconnection.
i am finding difficult in understanding the callback methods.
can you please provide me steps for implementing the group video call.

**Comment by zackm0571** [comment]
Feel free to open another issue if you're still having problems!

**Comment by zackm0571** [comment]
Hey @AnkitSingh80 we've added a multi party video quickstart which you can find [here](https://github.com/twilio/video-quickstart-android/tree/master/exampleMultipartyVideo). I hope it serves your purposes. Please let us know if you have any issues with it 🙂
