### ISSUE TITLE
onVideoTrackSubscribed() called even though receiver did not join the room

### ISSUE THREAD

**Issue by AnkitSingh80** [twilio/video-quickstart-android#354]
hi, i have implemented a video group call but currently facing some issues.
1)Videoview flickering a lot before rendering call and workes fine after video load on it.
2)onVideoTrackSubscribed() called even though receiver did not join the room.and then killing app and restart solve my problem.It happends when onDisconnected() call.
3)Calling notificaiton did not come but when i kill the app, then i get notification
4)Dialer can add multiple user in a single room but when receiver add, it gives error... Participant disconnected because of duplicate identity

**Comment by zackm0571** [comment]
@AnkitSingh80 can you post your call activity code? That might make it a little easier to help debug.
