### ISSUE TITLE
How to use flash with Camera 2?

### ISSUE THREAD

**Issue by S-Saagar** [twilio/video-quickstart-android#355]
With below code done to on/off flash using camera1
-----------------------------------------------------------
if (enable) {
              camera1Capturer.updateCameraParameters(cameraParameters -> cameraParameters.setFlashMode(Camera.Parameters.FLASH_MODE_TORCH));
            } else {
                camera1Capturer.updateCameraParameters(cameraParameters->
cameraParameters.setFlashMode(Camera.Parameters.FLASH_MODE_OFF));
            }
-----------------------------------------------------------
But in camera2 how to do that?

**Comment by aaalaniz** [comment]
Duplicate of #146
