### ISSUE TITLE
LocalParticipant Listener isn't called

### ISSUE THREAD

**Issue by lqgioan** [twilio/video-quickstart-android#359]
### Description

[HELP] LocalParticipant Listener isn't called

### Steps to Reproduce

1. I connect to a Room -> it's OK
2. I received the `onConnected(Room)` callback. In this method, I set a listener for the `LocalParticipant` by the below code.
```
// Using Kotlin
room?.localParticipant?.let {
       it.setListener(LocalParticipant.Listener)
       // More code here
}
// Code for publishing LocalVideoTrack and LocalAudioTrack
```
I'm sure that `room?.localParticipant` is not null. But I don't receviced any callback from `LocalParticipant.Listener` when the `LocalVideoTrack` and `LocalAudioTrack` are published.

I try to debug I saw that `LocalParticipant$localParticipantListenerProxy` isn't called by Twilio SDK. Any help would be greatly appreciated.

#### Expected Behavior

I want to receive `LocalParticipant.Listener` callback so that I'm able to check whether `LocalVideoTrack` and `LocalAudioTrack` are published or not

#### Actual Behavior

I don't receive any callback.

#### Reproduces how Often

100%

#### Logs

Don't have any log

#### Video Android SDK

2.2.1, 3.0.0, 3.1.0

#### Android Device
Nexus 5 -Android version 6.0.1
Samsung Galaxy J - Android version 8.0.0

**Comment by zackm0571** [comment]
Hey @lqgioan, thanks for reaching out. I can't seem to get the code you posted above to compile. Particularly this line ```it.setListener(LocalParticipant.Listener)```. Could you try reproducing with our quickStart or provide a simple example that reproduces the issue you're seeing? Thanks!

**Comment by lqgioan** [comment]
Thanks for your replying @zackm0571,

In the **quickstartKotlin** project, **I added the code from line 113 to 150 in the com.twilio.video.quickstart.kotlin.VideoActivity files to reproduce the problem.**

After the app connected to a `Room`, I did two things

- I register a listener for the LocalParticipant by calling localParticipant?.setListener(LocalParticipant.Listener) in the `onConnected(Room)` callback
- I publish the LocalVideoTrack in the `onConnected(Room)` callback

The result is that I don't receive any callback.

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

I press the home button and reopen the app from the recent list
The result is that I receive the `onVideoTrackPublished` callback because there is a line of code to publish the video in the `onResume()` method

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Maybe I do something wrong? Please help me to correct it!

This is my modification for the **quickstartKotlin** project
[quickstartKotlin.zip](https://github.com/twilio/video-quickstart-android/files/2627696/quickstartKotlin.zip)

**Comment by zackm0571** [comment]
@lqgioan I'm investigating now. Thanks for all the info!

**Comment by lqgioan** [comment]
@zackm0571 yes, `localParticipant?.publishTrack(it)` always return false in my case. 

We called `publishTrack` in two places. 

- One is in the `onResume` -> the `publishTrack` wasn't called when the app was opened the first time or wasn't connected to a `Room`
- One is in `onConnected(Room)` callback -> in my case

You said **the video track was already published by the time I called `publishTrack`**, so when was the video track published? How to receive a callback in my case? (Maybe call `unpublishTrack` and then call `publishTrack` again)

**Comment by zackm0571** [comment]
@lqgioan I just saw now that you were trying to check whether a track was published or not. My apologies. Instead of this, you can call a function like this from `onConnect`.

```
    private boolean isVideoTrackPublished(Room room){
       LocalParticipant participant = room.getLocalParticipant();
       if(participant == null) return false;

        if (participant.getLocalVideoTracks().size() > 0) {
            // Assuming you only have one video track published
           LocalVideoTrack localVideoTrack = participant.getLocalVideoTracks().get(0).getLocalVideoTrack();
           if(localVideoTrack.isEnabled()){
               return true;
           }
        }
        return false;
    }
```
Here I'm passing in a `Room` to this function to demonstrate how to get a handle to a `LocalVideoTrack`, but you can pass in the `LocalVideoTrack` itself if you have a reference to it elsewhere. 

Make sure you still set your callback to receive events in the future, but for now it sounds like this function may be what you're looking for? Let me know if it works for you. :)

**Comment by zackm0571** [comment]
@lqgioan we're going to be adding some clearer documentation in a future release. To summarize, when the `Room.Listener#onConnected` callback is called any audio or video track that was provided as part of `ConnectOptions` will already be published. As a result, when adding the `LocalParticipant.Listener` there will be no callbacks raised for the tracks that were previous added via `ConnectOptions`. Any new audio or video tracks that are added afterwards will result in a callback. Note that `boolean publishTrack` on the `LocalParticipant` will return `false` if the local track has been previously published or if the `LocalParticipant` is no longer connected to the `Room`.

**Comment by nicksav** [comment]
Hey, Sorry to post here, but what to do if for some reason the Video track is not published? 
Is there any way to sort of re-publish it? We dot really strange error and it happens time to time. Most of the cases when user first time logs in and open app. From second attempt, it works fine.
![image](https://user-images.githubusercontent.com/9266365/74791220-a10ac180-5305-11ea-950a-d92a511a11c5.png)
