### ISSUE TITLE
Opponent side participant disconnected.

### ISSUE THREAD

**Issue by S-Saagar** [twilio/video-quickstart-android#360]
Hii...

I have one case while doing One to One call.
Below case both the time U1 and U2 have same identity and same room name.

U1 is web user
U2 is Android user

Step - 1
Call from U1 to U2.
Now incoming call screen showing to U2.
Step - 2 
User 2 accept the call and wait till all procedure completed related to twilio.
Step - 3
Now U2 turn off internet and reject call. Call screen stay there on U1 due to not getting acknowledgement from U2 about reject call. U1 too reject call(U1's internet is alive).
Step - 4
Now user 2 turn on internet and again Call from U1 to U2. Now when U2 accept call both side call method **public void onParticipantDisconnected(Room room, RemoteParticipant remoteParticipant)** 
First on U1 side and then U2 side.

**Comment by zackm0571** [comment]
@S-Saagar thanks for reaching out. 
Two quick things:
- 1) Our SDK doesn't currently support users with the same identity. Can you try giving each user a unique identity and then seeing if this resolves this issue?
- 2) Are you seeing this bug with the video invite quickstart? Could you provide your Android call activity?

**Comment by zackm0571** [comment]
Closing. Feel free to open if you're still having issues!
