### ISSUE TITLE
Error 53404 No supported codec

### ISSUE THREAD

**Issue by beautifulsoul84hung** [twilio/video-quickstart-android#363]
Hi.
I have an issue need your support.
When I use some android devices to make video call, the error 53404 appear: "No supported codec". Then, these devices can't connect to room (this issue occur on some devices as huawei emui 4.1.3, galaxy c8 but not with some others as galaxy A7)
I think this problem related to twilio account, but I don't know exactly the reason. I guess that because the issues occur when I use twilio jp account (https://jp.twilio.com) but not occur with us account (https://www.twilio.com/)
Please provide me support,
Thanks.

**Comment by aaalaniz** [comment]
Hey @beautifulsoul84hung 

The Video Android SDK only supports encoding/decoding H.264 on devices with H.264 hardware implementations. The SDK does not provide a software implementation of H.264. As a result, Android clients that do not provide hardware H.264 implementations will experience the following behavior when participants are sharing video tracks encoded using H.264:

**Video Android 1.x** - Clients will not be allowed to join Room. `onConnectFailure` will be invoked with the `53404` "No supported Codec" error. This sounds like the scenario you experiencing.

**Video Android 2.x+** - Clients will be allowed to join Room but will fail to subscribe to a video track with the `53404` "No supported Codec" error.

I have a couple of follow up questions:

1. What version of the Video Android SDK are you using?
2. Are you using Programmable Video on any other platforms? (iOS, Web)
3. What are your [Room Settings](https://www.twilio.com/console/video/configure)? (see screenshot from Twilio Console below)

![screen shot 2018-11-27 at 2 39 06 pm](https://user-images.githubusercontent.com/1734140/49110142-442f7100-f252-11e8-84a7-d39d23e693b8.png)

You can find more details about managing Codecs with Programmable Video [here](https://www.twilio.com/docs/video/managing-codecs).

**Comment by beautifulsoul84hung** [comment]
Hi @aaalaniz 

Thank for your provided support. The problem because of  **Room setting** 
My partner config VIDEO CODEC as H.264. When I change config  to VP8&H.264 the issue is solved.

Thanks and kindest regards,
Hung.

**Comment by aaalaniz** [comment]
Glad I could help!
