### ISSUE TITLE
Switch local video track between video views (primary and thumbnail)

### ISSUE THREAD

**Issue by apurcaroiu** [twilio/video-quickstart-android#365]
### Steps to Reproduce

1. Connect to a room with two participants (using the quickstart sample)
2.Try to move local video to primary view during call (similar how whatsapp has when press on the thumbnail view) by calling moveLocalVideoToPrimaryView
3. Local front camera does to move to primary view but it causes flashes of remote video view also (I am getting flashes from both my own front camera and callers remote camera)

#### Code

Use quickstart sample and call moveLocalVideoToPrimaryView while call is initiated

#### Expected Behavior

Expect to switch primary view to local video track.

#### Actual Behavior

causes flashes of remote video view also (I am getting flashes from both my own front camera and callers remote camera)

#### Reproduces how Often

100%

#### Logs

```
// Log output when issue occurs
```

### Versions

com.twilio:video-android:1.3.7

#### Video Android SDK

[eg. 1.0.2]

#### Android API

[eg. 18]

Oreo

[eg. Nexus 5]
Hwaei Mate 10

Does  Twillio support switching between thumbnail view and primary view rendering the local video track?

**Comment by zackm0571** [comment]
@apurcaroiu am I understanding correctly that this is with our quickStart unmodified or is this in your app? If this is only happening in your app could you post your full activity to help debug? Thanks!

**Comment by zackm0571** [comment]
Closing. Please reopen if you're still having issues.

**Comment by kansalmohit19** [comment]
I am also facing the same issue...
Please help!!
