### ISSUE TITLE
Add LocalVideoTrack after room connected

### ISSUE THREAD

**Issue by kawmra** [twilio/video-quickstart-android#366]
I want to enable video feature at the time when the user request to use camera and I want to ask permission to the user at this time (when user taps video button for example).
But `Video#connect()` throws IllegalStateException ("CAMERA permission must be granted to create videotrack with CameraCapturer") if I add LocalVideoTrack to ConnectOptions even if the track is disabled.

It is possible to add local video track to connected room?
I didn't find the way to add LocalVideoTrack after room connected.

If it's impossible, how can I connect to room without Camera permission?
(Of course, LocalVideoTrack will be disabled initially.)

#### Video Android SDK

Version 1.3.9

**Comment by zackm0571** [comment]
Hey @kawmra. `LocalParticipant` has this function `publishTrack(@NonNull LocalVideoTrack localVideoTrack) ` which should publish the track even after connecting to a room. Make sure to save all your camera initialization logic for after the camera permissions have been accepted. Once the permission has been accepted and your `VideoTrack` has been initialized you should be able to publish it without running into this `IllegalStateException` Let me know if this works or if I misunderstood :)

**Comment by kawmra** [comment]
@zackm0571 
Oh, I missed that method. Thank you.
I can't use the latest SDK 3.x for some personal reasons but I found `addVideoTrack(LocalVideoTrack localVideoTrack)` and that is what I was looking for. I think it would work as expected.
I have not tested those methods yet, but anyway, thank you!

**Comment by zackm0571** [comment]
You got it! Feel free to reach out anytime. 😊
