### ISSUE TITLE
Web fails to render VP9 with 3.0+

### ISSUE THREAD

**Issue by ghost** [twilio/video-quickstart-android#368]
### Description

When sending in VP9 as a preferred codec with a compatible device (example Samsung SM-G950F) Twilio.js will not be able to render the video resulting in a black screen.

The web does not send in any preferred video codecs. It also works as expected with versions before 3.0.

We can see that the device has sent video data to the web.

Have you received any other reports regarding this?

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```kotlin
        val isH264Supported = MediaCodecVideoDecoder.isH264HwSupported() && MediaCodecVideoEncoder.isH264HwSupported()
        val isVP9Supported = MediaCodecVideoDecoder.isVp9HwSupported() && MediaCodecVideoEncoder.isVp9HwSupported()

        // Prefer VP9 > H264 > VP8
        val videoCodecs = mutableListOf<VideoCodec>().apply {
            if (isVP9Supported) add(Vp9Codec())
            if (isH264Supported) add(H264Codec())
        }
```

#### Expected Behavior

That Chrome and Firefox renders VP9 tracks just like they can in the 2.0+ versions

#### Actual Behavior

The track is rendered as black screen

#### Reproduces how Often

100%

#### Logs

```
// Log output when issue occurs
```

### Versions

Web Twilio.js version: 14

#### Video Android SDK

3.2.1

#### Android API

28

#### Android Device

Samsung SM-G950F Galaxy S8

**Comment by zackm0571** [comment]
Hey @phsavisiba. Thanks for reaching out. I've tried to reproduce on my end and can't seem to get black video to show from android. Can you send over any code that differs from our android and JS quickstarts? 

Also a few things to try:

- Does this happen on different Android devices?
- Does this happen between Android to Android? What about Android to iOS?
- Does this happen with our quickStart? 

Thanks again, 

Zack

**Comment by zackm0571** [comment]
One more thing. Could you provide the Room Sid when you experience this issue? Quick way to get that is log the value `room.getSid()`. This will help us look into the issue a little more verbosely. Thanks!

**Comment by phsavisiba** [comment]
Thanks for the quick response here is a Room Sid with the issue: "RM1c6429cee24d8ea52e9a456ccd42569a"
I will try your suggestions early next week and see if i can reliably reproduce the isssue.

**Comment by phsavisiba** [comment]
![vp9error](https://user-images.githubusercontent.com/38780186/50213387-c9073980-037d-11e9-9cd3-86c9805bdbde.jpg)

I managed to reproduce the issue with your kotlinQuickStart. I used a Google Pixel 2 and a Samsung S8 that connected to each other. I do not have any other Android devices supporting VP9 available or and iPhone to test with. When i switched to H264 and tested again it worked.

**Comment by aaalaniz** [comment]
I'm closing this issue. I recommend referencing our [Managing Codecs](https://www.twilio.com/docs/video/managing-codecs) for optimal cross platform codec selection.

Thank you
