### ISSUE TITLE
Push Notification Not Supported in Android Smartglass

### ISSUE THREAD

**Issue by rakeshkatta1311** [twilio/video-quickstart-android#370]
Hi,

I'm using push notification to notify user for call but in Realwear HMT-1, Vuzix M300, ODG R7 smart glasses push notification is not supported.  Is there any work around to notify user for call using Twilio SDK?

Thanks & Regards,
Rakesh

**Comment by aaalaniz** [comment]
Hey @rakeshkatta1311 

I don't know of any workaround for devices that do not support push notifications. Are push notifications not allowed due to the absence of Google Play Services? I'd be glad to brainstorm some potential solutions to this problem.

Thanks!

**Comment by zackm0571** [comment]
Closing. Feel free to open if you have anymore questions!

**Comment by aaalaniz** [comment]
Hey @rakeshkatta1311 

I'm closing this issue for now. Feel free to reopen if you have any additional questions.

Thanks!
