### ISSUE TITLE
Dark primaryvideoview with Camera2

### ISSUE THREAD

**Issue by jeunetoujour** [twilio/video-quickstart-android#372]
This is an issue that happens on Camera2 apps sometimes but the preview window appears dark, but when I set it to forced Camera1 its bright and good however the frame rate is at 15fps instead of 30. Any workarounds to get Camera2 to look good?

**Comment by steventacit** [comment]
To expand, on the net there is talk about the FPS not being set correctly. Other places its talked about YUV not shifting colors correctly.

**Comment by zackm0571** [comment]
@jeunetoujour thanks for reaching out. Few quick questions:

1. What device / OS's have you tested on? Is the behavior consistent?
2. What version of the SDK are you running?
3. Can you provide a code sample of your camera setup?

Thanks!

**Comment by zackm0571** [comment]
Hey there @steventacit, @jeunetoujour  

Could you provide a screenshot? There is a possibility that this is an FPS issue, but also want to see the exact behavior you're describing in case it's a device specific problem. Thanks!

**Comment by zackm0571** [comment]
Closing for now. Please reach out if you're still having issues.
