### ISSUE TITLE
imageBuffer is null in the VideoFrame in the version 3.x.x

### ISSUE THREAD

**Issue by john-lq** [twilio/video-quickstart-android#375]
Hello Guys,
The `VideoFrame.imageBuffer` is null in version `3.x.x`. Please help me to get the frame buffer in the `VideoFrame`. It works fine in the version `2.x.x`.

```java
localVideoTrack?.videoCapturer?.startCapture(VideoFormat, object : VideoCapturer.Listener {
    override fun onCapturerStarted(success: Boolean) {
        Log.d("Capture started with status $success") // success is true
    }

    override fun onFrameCaptured(videoFrame: VideoFrame?) {
        // videoFrame is not null. But:
	// - videoFrame.imageBuffer is not null in the version 2.x.x
	// - videoFrame.imageBuffer is null in the version 3.x.x
	// A question is how to get buffer from the videoFrame argument?
    }
})
```
Thanks

**Comment by zackm0571** [comment]
Hey @john-lq thanks for reaching out. Is there anyway you could try reproducing this in our quickStart?

**Comment by zackm0571** [comment]
Hey @john-lq, 

I noticed you're explicitly calling `videoCapturer.startCapture` from your example. The SDK will actually invoke this function for you when you call `LocalVideoTrack.create`. 

Could I ask your use case in accessing `videoFrame.imageBuffer`?

**Comment by john-lq** [comment]
Hi @zackm0571 ,

Thanks for your information. I didn't find any document about this change. And now, how to capture a `VideoFrame` dynamically after I created `LocalVideoTrack` by calling `LocalVideoTrack.create`. 

Thanks

**Comment by zackm0571** [comment]
Glad you found a solution, @john-lq ! Thanks for reaching out. 😀

**Comment by TieuNhi95** [comment]
@zackm0571 
i'm facing this problem, can you help me.
My example : https://github.com/TieuNhi95/CustomVideoFrame

**Comment by john-lq** [comment]
@TieuNhi95 ,

This one can help you. https://github.com/twilio/video-quickstart-android/issues/531

**Comment by TieuNhi95** [comment]
@john-lq 
Thanks, i was custom camera source instead read video frame from VideoCapturer.Listener
