### ISSUE TITLE
My device doesn't seem to support any of the video codec options

### ISSUE THREAD

**Issue by timtraversy** [twilio/video-quickstart-android#378]
When I run this code:
```
Log.d("h2 encode", MediaCodecVideoEncoder.isH264HwSupported().toString())
Log.d("h2 decode", MediaCodecVideoDecoder.isH264HwSupported().toString())
Log.d("vp8 encode", MediaCodecVideoEncoder.isVp8HwSupported().toString())
Log.d("vp8 decode", MediaCodecVideoDecoder.isVp8HwSupported().toString())
Log.d("vp9 encode", MediaCodecVideoEncoder.isVp9HwSupported().toString())
Log.d("vp9 decode", MediaCodecVideoDecoder.isVp9HwSupported().toString())
```
The result is:
```
D/h2 encode: false
D/h2 decode: true
D/vp8 encode: false
D/vp8 decode: false
D/vp9 encode: false
D/vp9 decode: false
```
I'm running Android 5 on a Galaxy S4. Shouldn't at least one of these be supported? If not how can I use Programmable Video? Currently when I connect to a room I get this output.

```

I/org.webrtc.Logging: Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging: Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 270
I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 270
I/org.webrtc.Logging: Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging: Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 270
I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 270
E/LocalVideoTrack: Applying VideoConstraints closest to 640x480@30 FPS.
I/org.webrtc.Logging: EglBase14: SDK version: 21. isEGL14Supported: true
I/org.webrtc.Logging: Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging: Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 270
I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 270
I/org.webrtc.Logging: Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging: Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 270
I/org.webrtc.Logging: Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging: Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 270
I/org.webrtc.Logging: CameraCapturer: startCapture: 640x480@30
I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 270
I/org.webrtc.Logging: Camera1Session: Open camera 1
I/org.webrtc.Logging: Camera1Session: Available fps ranges: [[4.0:30.0]]
I/org.webrtc.Logging: Camera1Session: Create new camera1 session on camera 1
I/org.webrtc.Logging: Camera1Session: Start capturing
I/org.webrtc.Logging: CameraCapturer: Create session done. Switch state: IDLE. MediaRecorder state: IDLE
D/ResourcesManager: creating new AssetManager and set to /data/app/com.example.videocallexample-1/base.apk
I/org.webrtc.Logging: EglRenderer: Initializing EglRenderer
I/org.webrtc.Logging: EglRenderer: EglBase.create shared context
I/org.webrtc.Logging: EglBase14: SDK version: 21. isEGL14Supported: true
I/org.webrtc.Logging: EglRenderer: setMirror: true
I/org.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1080x1920
E/BufferQueueProducer: [unnamed-21775-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=11 undequeued=0)
E/BufferQueueProducer: [unnamed-21775-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=10 undequeued=1)
I/org.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1080x1920
I/org.webrtc.Logging: EglRenderer: setLayoutAspectRatio: 0.5625
I/org.webrtc.Logging: SurfaceEglRenderer: : surfaceChanged: format: 4 size: 1080x1920
D/Room Listener: Connected to roommy-room as tim
I/org.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1080x1920
I/org.webrtc.Logging: EglRenderer: setLayoutAspectRatio: 0.5625
I/org.webrtc.Logging: WebRtcAudioRecord: initRecording(sampleRate=48000, channels=1)
I/org.webrtc.Logging: WebRtcAudioRecord: byteBuffer.capacity: 960
I/org.webrtc.Logging: WebRtcAudioRecord: AudioRecord.getMinBufferSize: 4096
I/org.webrtc.Logging: WebRtcAudioRecord: bufferSizeInBytes: 8192
I/org.webrtc.Logging: WebRtcAudioEffects: enable(audioSession=209)
I/org.webrtc.Logging: WebRtcAudioRecord: AudioRecord: session ID: 209, channels: 1, sample rate: 48000
I/org.webrtc.Logging: WebRtcAudioRecord: startRecording
I/org.webrtc.Logging: WebRtcAudioRecord: AudioRecordThread@[name=AudioRecordJavaThread, id=1942]
I/org.webrtc.Logging: CameraStatistics: Camera fps: 27.
I/org.webrtc.Logging: CameraStatistics: Camera fps: 30.
I/org.webrtc.Logging: EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: 0.0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging: CameraStatistics: Camera fps: 30.
I/org.webrtc.Logging: CameraStatistics: Camera fps: 30.
I/org.webrtc.Logging: EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: 0.0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging: CameraStatistics: Camera fps: 30.
I/org.webrtc.Logging: CameraStatistics: Camera fps: 30.
```
So it seems like no frames are being received by the framework.

**Comment by zackm0571** [comment]
Hey @timtraversy does this behavior happen when using `Camera2Capturer`? Android 5.0 introduces the new `Camera2` API.

**Comment by timtraversy** [comment]
The quickstart code determines camera1 vs camera2 like this: https://github.com/twilio/video-quickstart-android/blob/186a547eccf4a7d78f4f9624a9d68b8a821c3936/quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/CameraCapturerCompat.kt#L79-L81

I changed it to always return camera2, but that only seems to throw more errors:
```
kotlin.KotlinNullPointerException
        at com.example.videocall.CameraCapturerCompat$override.getVideoCapturer(CameraCapturerCompat.kt:47)
        at com.example.videocall.CameraCapturerCompat$override.access$dispatch(CameraCapturerCompat.kt)
        at com.example.videocall.CameraCapturerCompat.getVideoCapturer(CameraCapturerCompat.kt)
```
And that still won't solve the fact that I can't support H2, VP8, or VP9 right?

**Comment by zackm0571** [comment]
Are you running the unmodified Kotlin Quickstart on a stock Galaxy S4? I ask because this might be something our team will need to get hardware to specifically reproduce. Thank you for your responsiveness and level of details by the way!

**Comment by timtraversy** [comment]
No I haven't actually tried running the quickstart unmodified, I'll give that a go!

**Comment by timtraversy** [comment]
Ok it looks like the unmodified Quickstart is actually failing as well.
![pic](https://user-images.githubusercontent.com/21370530/52823564-6c758180-3083-11e9-9a58-9e95c7a01f0b.jpg)
It's just a black screen and then fails to connect if I try to join a room. The error logs are pretty verbose I'll try to pick out important things.
(Sorry for the non-screenshot, this phone is too old to interact with normally)

**Comment by zackm0571** [comment]
@timtraversy can you put the full log into a .txt file? I would be glad to take a look. :)

**Comment by timtraversy** [comment]
[logcat.txt](https://github.com/twilio/video-quickstart-android/files/2867321/logcat.txt)
Thanks! This is Verbose from just before the app starts.

**Comment by timtraversy** [comment]
[logcat2.txt](https://github.com/twilio/video-quickstart-android/files/2867332/logcat2.txt)
This is if you filter by the twilio package, more to the point.

**Comment by timtraversy** [comment]
Weird, the quickstart is now running on my device 🤔

**Comment by zackm0571** [comment]
@timtraversy sorry for the delayed response. Are you still able to reproduce?

**Comment by ArvindMewada** [comment]
`I/CameraCapturerCompat1234(12277): onFirstFrameAvailable
I/tvi.webrtc.Logging(12277): CameraStatistics: Camera fps: 16.
I/tvi.webrtc.Logging(12277): CameraStatistics: Camera fps: 20.
D/Twiliovideo(12277): onMethodCall: disconnect
D/ROOM    (12277): 
I/flutter (12277): Room Disconnect Method Channel is Successful: true
I/flutter (12277): Building the complete view now
I/tvi.webrtc.Logging(12277): CameraStatistics: Camera fps: 20.
I/tvi.webrtc.Logging(12277): CameraStatistics: Camera fps: 20.
I/tvi.webrtc.Logging(12277): CameraStatistics: Camera fps: 20.
D/TwilioVideo(12277): onDisconnected sent!
I/Disconnected(12277): room: null
I/tvi.webrtc.Logging(12277): CameraStatistics: Camera fps: 20.
I/tvi.webrtc.Logging(12277): CameraStatistics: Camera fps: 20.
`

after call disconnecting but log is continuously run.

**Comment by Zeehshan** [comment]
> `I/CameraCapturerCompat1234(12277): onFirstFrameAvailable I/tvi.webrtc.Logging(12277): CameraStatistics: Camera fps: 16. I/tvi.webrtc.Logging(12277): CameraStatistics: Camera fps: 20. D/Twiliovideo(12277): onMethodCall: disconnect D/ROOM (12277): I/flutter (12277): Room Disconnect Method Channel is Successful: true I/flutter (12277): Building the complete view now I/tvi.webrtc.Logging(12277): CameraStatistics: Camera fps: 20. I/tvi.webrtc.Logging(12277): CameraStatistics: Camera fps: 20. I/tvi.webrtc.Logging(12277): CameraStatistics: Camera fps: 20. D/TwilioVideo(12277): onDisconnected sent! I/Disconnected(12277): room: null I/tvi.webrtc.Logging(12277): CameraStatistics: Camera fps: 20. I/tvi.webrtc.Logging(12277): CameraStatistics: Camera fps: 20. `
> 
> video call disconnecting but log is continuously run.

same me any solution ?
