### ISSUE TITLE
null received in Camera2Capturer.Listener.onCameraSwitched

### ISSUE THREAD

**Issue by palimad** [twilio/video-quickstart-android#379]
Fatal Exception: java.lang.IllegalArgumentException
Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter newCameraId
xxx.CameraCaptureCompat$camera2Listener$1.onCameraSwitched (Unknown Source:2)

Some part of camera subsystem passed null reference to onCameraSwitched, listener was used only for Camera2Capturer initialization:

            camera2Capturer = Camera2Capturer(context,
                getCameraId(cameraSource),
                camera2Listener)

Could you remove  @NonNull annotation from method parameters of Camera2Capturer.Listener interface, or what is your suggestion to deal with this?

**Comment by aaalaniz** [comment]
Hey @palimad 

What version of the SDK are you using?

Thanks!

**Comment by palimad** [comment]
Hello Aaalaniz, I use SDK version 3.2.1

**Comment by aaalaniz** [comment]
Hey @palimad 

Is this issue reproducible in the quickstart?

I can have a look. Thanks!

**Comment by palimad** [comment]
I believe so,
I see crash reports from  Huawei ATU-L31 running 8.0.0 and Oneplus A6000 running  9

**Comment by aaalaniz** [comment]
Hey @palimad 

I tried switching cameras with Kotlin example and I'm not able to reproduce this problem. Can you provide an example how to reproduce this?

Thanks!

**Comment by palimad** [comment]
Hello I just saw this on Crashlytics, can't reproduce it myself

**Comment by palimad** [comment]
It appears on: 
Galaxy S8
Galaxy S8+
Galaxy Note8
Mate 20 Pro

I believe simply removing NonNull annotation of  void onCameraSwitched(@NonNull String newCameraId) would solve it. Not sure though why I get null there, but I do not use camera2Listener anyway. It is forced, I believe is not good practise anyway, it should be nullable as well.

**Comment by aaalaniz** [comment]
Hey @palimad 

Our goal is to correctly annotate the nullability of all public APIs. In this scenario, it looks like we may have not accounted for all cases where onCameraSwitched is invoked. I investigated a little and could not find where onCameraSwitched could be invoked with `null`, but there is probably a bug in our code somewhere that doesn't account for an error case.

In short, we will not remove these nullability annotations, but I want to root cause this issue because onCameraSwitched *should* not be invoked with `null`. Can you provide any logs or possible reproduction steps for this issue so we can fix?

Thanks!

**Comment by aaalaniz** [comment]
Hey @palimad 

I have a few follow-up questions as well:

1. Does this only occur when using the Camera2Capturer?
2. At what version of the SDK did you start observing this issue?

Thanks!

**Comment by palimad** [comment]
Hello, I first noticed it in 3.2.1 but I wasn't using Twilio before, so it could be there before. It is still not fixed in 4.0.0.
Yes it occurs only with Camera2Capturer. Thanks

**Comment by aaalaniz** [comment]
Hey @palimad 

We have created a bug in our backlog and will investigate this issue in the coming sprint.

Thank you for reporting this issue.

**Comment by palimad** [comment]
Right now this is the most frequent bug in our production app, please fix it ASAP somehow. Thank you

**Comment by zackm0571** [comment]
@palimad thank you for bringing this to our attention. This is my highest priority for the week. I'm currently working on a solution and will keep you updated.

**Comment by zackm0571** [comment]
@palimad I have found a solution, trying to move it through our pipeline as quickly as possible. Thank you for your continued patience.

**Comment by zackm0571** [comment]
@palimad quick update: We have gotten this fix pushed through QA. Please expect `4.0.2` to be released very soon containing this fix.

**Comment by zackm0571** [comment]
@palimad we've just released `4.0.2` with this crash fix. Please let me know that this resolves the crash on your end.

**Comment by zackm0571** [comment]
Feel free to open another issue if you see this or something similar pop up again 🙂
