### ISSUE TITLE
Video Stretch on Samsung 

### ISSUE THREAD

**Issue by testingflexsin** [twilio/video-quickstart-android#381]
I have  run sample video call app. When I test on Samsung (On Nxt) then video stretch.

     <com.twilio.video.VideoView
        android:id="@+id/thumbnail_video_view"
        android:layout_width="96dp"
        android:layout_height="96dp"
        android:layout_alignParentEnd="true"
        android:layout_margin="16dp"
        android:visibility="gone"
        app:mirror="true"
        app:overlaySurface="true" />

    <com.twilio.video.VideoView
        android:id="@+id/primary_video_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"
    />

Android video SDK version -  3.2.2
Device Name - Samsung On Nxt
OS - 8.1.1

I have also tested it  on other device ( Samsung J2  and HTC) and there is no stretch.
I had take screenshot  fo a pen from same distance using  two devices.
1). Samsun J2  - OS ->Lollipop

![samsung_j2](https://user-images.githubusercontent.com/4298672/53328428-37352300-3910-11e9-92fb-c5740a57b776.png)

2. Samsung On NXT -> OS - 8.1.1
![samsung_on_nxt_stretec](https://user-images.githubusercontent.com/4298672/53328429-f0472d80-390f-11e9-89da-ff147d6f82fe.jpg)

**Comment by zackm0571** [comment]
Hey @testingflexsin, 

My apologies for the late response. Thank you for taking the time to attach so much detail. It looks like you've tested quite a few things already. Could you please test one more thing by going to [this link](https://appr.tc/) and try setting up a call between the Samsung (On Nxt) and another device? WebRTC has a web app that allows you to test camera functionality. If the image appears stretched on the call with On Nxt, this may be a device specific issue. Please let me know your findings!

Best, 
Zack

**Comment by zackm0571** [comment]
Hey @testingflexsin, 
Two more things to try. 
- If you use `videoView.setVideoScaleType(ASPECT_FIT);`  or `videoView.setVideoScaleType(ASPECT_FILL);` do you see a difference?
- Could you provide a screenshot of something round (eg. clock or drink coaster)? 

Thanks!

**Comment by testingflexsin** [comment]
Hi @zackm0571 ,

Thanks for response and there is no need to apologie.

As you suggest, I had take screenshot  of circle drink coaster with AppRTCDemo, ASPECT_FIT , ASPECT_FILL  and WhatsApp. Its looks stretch by width except WhatsApp screenshot

**1. AppRTCDemo**

I have download sample of [Apprtc ](https://github.com/njovy/AppRTCDemo)and run on samsung device and I have found that video is also stretching in the AppRTCDemo.


**AppRTC - Screenshot on Samsung (On Nxt)**
![Screenshot_20190312-120906_AppRTC](https://user-images.githubusercontent.com/4298672/54180716-4f857000-44c2-11e9-9d8c-65667634d622.jpg)


**2. Aspect Ratio**
I have tried  videoView.setVideoScaleType(ASPECT_FIT) and videoView.setVideoScaleType(ASPECT_FILL), but still video is stretch on Samsung (On Nxt).

**ASPECT_FIT - Screenshot on Samsung (On Nxt)**
![Fit_The Vip Group](https://user-images.githubusercontent.com/4298672/54180830-9ffccd80-44c2-11e9-9cbe-d350e38d08ea.jpg)


**ASPECT_FILL - Screenshot on Samsung (On Nxt)**
![Fill_The Vip Group](https://user-images.githubusercontent.com/4298672/54180819-96736580-44c2-11e9-9929-cfb17f7f7184.jpg)


**2. WhatsApp** ->  when I placed a video call with WhatsApp using Samsung (On Nxt) then video is not stretching.

**WhatsApp - Screenshot on Samsung (On Nxt)**
![Screenshot_20190312-121041_WhatsApp](https://user-images.githubusercontent.com/4298672/54180789-7b085a80-44c2-11e9-94fc-e4be23d99d02.jpg)

Thanks

**Comment by zackm0571** [comment]
Thanks for taking the time to work through this, @testingflexsin. I found an [older breakdown](https://webrtchacks.com/whats-up-with-whatsapp-and-webrtc/) of WhatsApp video calling that seems to show it's using a modified version of WebRTC. This [blog post](https://blog.contus.com/how-whatsapp-works-technically-and-how-to-build-an-app-similar-to-it/) also seems to give some insight into the WhatsApp stack. 

Unfortunately, if the video is stretching in the AppRTC demo, it looks like this may be an AppRTC issue.  On the plus side, I've gone ahead and [filed an issue with AppRTC](https://bugs.chromium.org/p/webrtc/issues/detail?id=10402) on your behalf and will notify you if I hear back from them. :)

**Comment by testingflexsin** [comment]
Thanks for support @zackm0571

**Comment by testingflexsin** [comment]
Hi @zackm0571 ,

 Previously, I had implemented [FlashPhoner](https://flashphoner.com/) in my project. I had installed the previous apk on Samsung(On Nxt)  and I found that video is not stretched with FlashPhoner. 

FlashPhoner also use AppRTC.

**Screenshot with FlashPhoner** 

![Screenshot_20190318-131908_The Vip Group](https://user-images.githubusercontent.com/4298672/54515434-0fbafe80-4982-11e9-9dfa-bf50a59e54dd.jpg)

**Comment by zackm0571** [comment]
@testingflexsin I don't have much knowledge of FlashPhoner. Though, it appears that they prioritize H.264 in their video calls. To narrow down our variables, could you see if there's a difference in this stretching when using `VP8Codec` vs `H264Codec`? Here's a code snippet that will allow you to set the priority for video codecs in `ConnectOptions`.

```
ConnectOptions.Builder connectOptionsBuilder =
                                           new ConnectOptions.Builder(token)
                                          .roomName(roomName)
                                          .enableInsights(enableInsights);
VideoCodec preferedVideoCodec = new H264Codec();
connectOptionsBuilder.preferVideoCodecs(Collections.singletonList(preferedVideoCodec));
```

Thank you for your patience!

**Comment by testingflexsin** [comment]
@zackm0571 , I have changed codec to H264Codec. It is little better than VP8Codec but it still stretch.

![H264](https://user-images.githubusercontent.com/4298672/54599090-ed97ae00-4a5f-11e9-9432-629ad61feb1b.jpg)


Thanks

**Comment by zackm0571** [comment]
@testingflexsin 
Could you try changing your xml to the following?
```
 <com.twilio.video.VideoView
    android:id="@+id/thumbnail_video_view"
    android:layout_width="96dp"
    android:layout_height="96dp"
    android:layout_alignParentEnd="true"
    android:layout_margin="16dp"
    android:visibility="gone"
    app:mirror="true"
    app:overlaySurface="true" />

<com.twilio.video.VideoView
    android:id="@+id/primary_video_view"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="center"
/>
```

You may need to play with your layout to display for all devices properly, but `match_parent` can cause `VideoView` or `VideoTextureView` to stretch its contents. 

Best, 

Zack

**Comment by zackm0571** [comment]
Hey @testingflexsin did you see less stretching when using `wrap_content`?

**Comment by zackm0571** [comment]
Hey @testingflexsin I think we're going to close this one for now. If you'd like any further triaging feel free to open another issue 🙂

**Comment by testingflexsin** [comment]
> Hey @testingflexsin did you see less stretching when using `wrap_content`?


I can not use wrap_content. I have to seen video on whole screen, but when I change it wrap_content. It leaves extra space.

**Comment by aaalaniz** [comment]
Hey @testingflexsin 

I'm going to close this issue for now. Please reopen if you are continuing to experience aspect ratio issues.

Thank you
