### ISSUE TITLE
Screen Capture in background

### ISSUE THREAD

**Issue by muhammadsr** [twilio/video-quickstart-android#382]
Any ideas on how to Screen Capture in the background (outside the app)?

**Comment by aaalaniz** [comment]
Hey @muhammadsr 

There are no limitations with the `ScreenCapturer` for capturing the screen from the background. The `ScreenCapturer` uses the [Media Project API](https://developer.android.com/reference/android/media/projection/MediaProjection) which should work when your application is in the background. I recommend referencing [our ScreenCapturer example.](https://github.com/twilio/video-quickstart-android/tree/master/exampleScreenCapturer) 

I'm happy to field any follow up questions.

Thanks!

**Comment by aaalaniz** [comment]
Hey @muhammadsr 

I'm closing this issue for now. Feel free to reopen the issue if you have any additional questions.

Thanks!
