### ISSUE TITLE
After call interruption audio output change to earpiece speaker from default speaker.

### ISSUE THREAD

**Issue by vincent001agile** [twilio/video-quickstart-android#383]
### Description

Two users are connected in a room and one of the user gets an incoming call and after the decline call, his volume is very low. it means after call state comes on Ideal my speaker mode is off but I can hear sound from earpiece speaker. In your githubdemo we are having the same issue. 

### Steps to Reproduce

1. User A and B join a room.
2. [User A receive incoming phone call]
3. [User A decline call and came back to room]
4. [User A speaker mode is off and only hear sound from earpiece speaker]

#### Code

```java
// Code that help reproduce the issue
```
    /**
     * Local Broadcast of Call State.
     */
    private val callStateLocalBroadcastReceiver: BroadcastReceiver = object : BroadcastReceiver() {
        override fun onReceive(context: Context?, intent: Intent?) {
            if (intent != null && intent.hasExtra(Consts.BundleExtras.CURRENT_CALL_STATE)) {
                val state = intent.getStringExtra(Consts.BundleExtras.CURRENT_CALL_STATE)

                if (state.equals(TelephonyManager.EXTRA_STATE_RINGING, true)) {
                    Timber.d("RINGIING")
                    starttimer?.cancel()
                    isInterruption = true
                    isCallEndTimerStarted = true
                    localDataTrack?.send(Consts.TWILIODATA.pause)

                    localAudioTrack?.enable(false)
                    localVideoTrack?.enable(false)

                    if (mChatController.isSocketConnected)
                        mChatController.disConnectSocket()
                    Timber.d("Socket Disconnected !!!!")
                    callEndWaitTimer = object : CountDownTimer(Consts.Delays.CALL_END_WAIT_DELAY, Consts.Delays.TIMMER_INTERVAL) {
                        override fun onFinish() {
                            isInterruption = false
                            isCallEndTimerStarted = false
                            disconnectRoom()
                            endBroadcast()
                        }

                        override fun onTick(millisUntilFinished: Long) {
                        }
                    }.start()
                    //disconnectRoom()
                } else if (state.equals(TelephonyManager.EXTRA_STATE_OFFHOOK, true)) {
                    Timber.d("OFFHOOK")
                    isCallEndTimerStarted = false
                    callEndWaitTimer?.cancel()
                    isInterruption = false
                    disconnectRoom()
                    endBroadcast()
                } else if (state.equals(TelephonyManager.EXTRA_STATE_IDLE, true)) {
                    //stopBroadCast()
                    // redirectToHomeScreen()
                    Timber.d("IDEL")
                    isInterruption = false
                    if (isCallEndTimerStarted) {
                        resumeBroadcast()
                    }
                }
            }
        }
    }

#### Expected Behavior

When call state comes to the IDLE state, we can hear sound from speaker mode. 

#### Actual Behavior

When call state comes to the IDLE state, we will hear sound from earpiece speaker. 

#### Reproduces how Often

Every time we follow above steps.

#### Logs

```
// Log output when issue occurs
```

### Versions

All relevant version information for issue.

#### Video Android SDK

[4.0.0]

#### Android Device

OnePlus 6 & xiaomi poco f1

**Comment by aaalaniz** [comment]
Hey @vincent001agile 

I apologize for the delayed response. Thank you for the detailed description and steps. We will investigate and get back to you.

Thanks!

**Comment by dtragas** [comment]
Thank you!

Thanks!

--
Dimitrios Tragas

**Comment by zackm0571** [comment]
Hey @vincent001agile, 

Thanks for the detailed info. We don't officially support audio routing in our sdk, but you can add this snippet of code to your `onResume` method to set the audio routing to speaker again. 
```
// Get AudioManager
AudioManager audioManager = (AudioManager) context.getSystemService(Context.AUDIO_SERVICE);

// Route audio through speaker
audioManager.setSpeakerphoneOn(true);
```

If for any reason you want to switch back to the handset simply use `audioManager.setSpeakerPhoneOn(false)`. Let me know if you have any trouble!

Best, 

Zack

**Comment by dtragas** [comment]
Ok thanks for your response. We will check this.

Thanks!

--
Dimitrios Tragas

**Comment by zackm0571** [comment]
@dtragas @vincent001agile have you had any luck with this one?

**Comment by dtragas** [comment]
Hi Zack, we haven’t had the chance to test. When we do we will let you know the outcome. Thanks for your help! Much appreciated. If we come across any other issue we will let you know.

Thanks!

--
Dimitrios Tragas

**Comment by zackm0571** [comment]
Hey @dtragas did you guys get this one resolved?

**Comment by dtragas** [comment]
We have fixed this issue another way. If we come across another issue we will let you know thanks.

Thanks!

--
Dimitrios Tragas

**Comment by zackm0571** [comment]
Glad you got this resolved :)

**Comment by camposbrunocampos** [comment]
hey @dtragas how did you manage to fix this issue?
