### ISSUE TITLE
Failed to connect when trying retrieve token in app using "Ion" library

### ISSUE THREAD

**Issue by mudi256** [twilio/video-quickstart-android#388]
when i retrieve token from my chrome browser and paste the token in app, all is works fine while i'm trying to retrieve token from app using "Ion" library, i received token but can not connect to room and Failed to connect message appears.

**Comment by zackm0571** [comment]
Hey @mudi256, 

To better understand what's happening could you please provide your "logcat" logs and your relevant code?

**Comment by mudi256** [comment]
Working
Ion.with(this).load("https://070e5a78.ngrok.io/?identity=alice&room=example").asString().setCallback(new FutureCallback<String>() {
            @Override
            public void onCompleted(Exception e, String token) {
                if (e == null) {
                    Log.d(TAG, "Access token: " + token);
                    accessToken = "paste token retrieve from browser using  'https://070e5a78.ngrok.io/?identity=alice&room=example';
                    

                } else {
                        Toast.makeText(VideoActivity.this,
                                R.string.error_retrieving_access_token, Toast.LENGTH_LONG)
                                .show();
                }
            }
        });

below Not working

Ion.with(this).load("https://070e5a78.ngrok.io/?identity=alice&room=example").asString().setCallback(new FutureCallback<String>() {
            @Override
            public void onCompleted(Exception e, String token) {
                if (e == null) {
                    Log.d(TAG, "Access token: " + token);
                    accessToken = token;
                    
                } else {
                        Toast.makeText(VideoActivity.this,
                                R.string.error_retrieving_access_token, Toast.LENGTH_LONG)
                                .show();
                }
            }
        });

**Comment by mudi256** [comment]
2019-03-15 07:32:40.887 15055-15055/com.twilio.video.quickstart E/onConnectFailure: com.twilio.video.TwilioException: Missing authorization token

**Comment by zackm0571** [comment]
@mudi256 thank you so much for the detailed info. I do believe I will need a bit more information though. Could you please provide logs from your token server when the client is trying to receive the token? It seems that there's some error between the client talking to the server and it's not obvious from I see here. Thank you again for your patience.

**Comment by zackm0571** [comment]
Hey @mudi256 are you still facing this issue?

**Comment by zackm0571** [comment]
Hey @mudi256 we're going to close this one for now. Please feel free to open another issue if you'd like us to triage further. 🙂

**Comment by mudi256** [comment]
yes sure the problem was "\n" in your returning token
for example your token looking like  "\n+hasjgdjhsadkadbvagdavdakbbmabsd"

**Comment by zackm0571** [comment]
Ah interesting. So removing the "\n" resolved your issue? If there was something faulty with the server code you may want to open another issue with the [Video Access Token Server](https://github.com/TwilioDevEd/video-access-token-server-node) project so that they're aware.

**Comment by mudi256** [comment]
yes.
ok
