### ISSUE TITLE
 receive calls with dead application and locked device screen

### ISSUE THREAD

**Issue by solracved91** [twilio/video-quickstart-android#389]
Can you receive video calls when the app is dead ? Also, can you receive video calls when the device has the screen blocked ? In Twilio Voice there are some Issues with this solution but those solutions are useful when implementing the video called ?

**Comment by aaalaniz** [comment]
Hey @solracved91 

The Video Android SDK does not provide any mechanism for "calling" users. The SDK provides the Room which serves as the place for your app's participants to share media. We recommend developers using a push notification service such as [Firebase Cloud Messaging (FCM)](https://firebase.google.com/docs/cloud-messaging/) to implement calling functionality. We [provide a quickstart](https://github.com/twilio/video-quickstart-android/tree/master/exampleVideoInvite) that demonstrates how to invite users via push notification to join a room.

This behavior is different from the Voice Android SDK which provides calling mechanisms via GCM or FCM.

Based on the provided knowledge let me address your questions:

>Can you receive video calls when the app is dead ? Also, can you receive video calls when the device has the screen blocked ?

While the SDK does not provide a calling mechanism, you should be able to receive a push notification and connect to a Room while your app is not active or the device is locked.

I'd be happy to answer any follow-up questions.

Thanks!

**Comment by solracved91** [comment]
Thank you very much for your quick response, that's what I meant. 
I just successfully implemented the quick start of notify for android and its backend in node.js.
The problem of push notifications in this case is that it does not directly show the view to answer or reject the call, I thought they had this functionality predesigned or some case in which has already been implemented to follow that line of implementation, if you know or can help me see the light I would appreciate it very much.

**Comment by solracved91** [comment]
I was reading the solution of quick start of voice of Android and I was able to initially show the view of VideoCallActivity with the dead app and also with the blocked device, I do not have done yet the whole flow (for that reason I will be bothering in next occasions around here) but it's a big step and that's what I was asking, thank you and I leave the comment in case it helps someone else. Thank you.
