### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by palimad** [twilio/video-quickstart-android#398]
Hi there,

do you have any idea what could be causing this issue?

Twilio SDK version 4.0.2
proguard is disabled by minifyEnabled false
It occurs only on Android 6

xxx.RoomFragment$roomListener$1.onParticipantConnected (RoomFragment.kt:2464)
com.twilio.video.Video$2.onParticipantConnected (Video.java:192)
com.twilio.video.Room$1.lambda$onParticipantConnected$5 (Room.java:166)
com.twilio.video.-$$Lambda$Room$1$LlZfk87VaalONO5RoOD5TD5Dp10.run (lambda)

**Comment by zackm0571** [comment]
Hey @palimad, 

Thanks for reaching out and providing a log. I'll be investigating further on my end. In the interim could I request two things?
- Could you try deleting your gradle cache and rebuilding? You can do this by deleting two folders named `.gradle`. One is located in your home directory `~/.gradle` and the other is located in your project directory. `~/MyProjectFolder/.gradle`. 
- Could you provide a sample of the code from `onParticipantConnected`?

Hope we can figure this out one out soon :)

**Comment by zackm0571** [comment]
Hey @palimad are you still facing this issue?

**Comment by zackm0571** [comment]
Feel free to open another issue if you still need some help :)
