### ISSUE TITLE
Echo on 4.0.2

### ISSUE THREAD

**Issue by mcorner** [twilio/video-quickstart-android#399]
### Description

We are getting horrible echo on calls after upgrading from 2.x to 4.x.    These are calls between android phones and a js web client.  Two participants, no headphones etc.

### Steps to Reproduce

Nothing in particular other than above.

#### Code

Very similar to quickstart, but we do use a class to manage bluetooth microphones.  But this does seem to be related to our upgrade.

We do have this already:
WebRtcAudioManager.setBlacklistDeviceForOpenSLESUsage(true);

We also had to start using aapt2, which we had disabled, upgraded gradle, and a few other build items that I wouldn't expect would happen.

#### Expected Behavior

No echo.

#### Actual Behavior

Lots of echo.  Web/JS user can hear themselves.

I have recording examples I can share privately.

#### Reproduces how Often

10% of calls perhaps

#### Logs

No logs

### Versions

All relevant version information for issue.

#### Video Android SDK

4.0.2

#### Android API

27

#### Android Device
Two examples thus far:
ONEPLUS A5010 (os 9)
Pixel 3 XL, Android "Q"

**Comment by zackm0571** [comment]
Hey @mcorner thanks for reaching out. If I understand correctly, you're saying that this is a regression? You didn't see the behavior in 2.x and are now seeing this happen at least 10% of the time in 4.x? 

I would love to hear some of these samples as well as take a look at your bluetooth manager class. Could you please send them to `zmatthews@twilio.com`?

Unsure if you've seen our [Troubleshooting Audio](https://github.com/twilio/video-quickstart-android#troubleshooting-audio) section of the quickStart, but please take a look if you haven't. I don't have your code in front of me, but the first thing I would try is something like this. 

```java
// Use software AEC
/* AEC has a [known bug](https://bugs.chromium.org/p/webrtc/issues/detail?id=10386#c1) 
that we have filed that causes the microphone to be muted system wide. 
If this hasn't been fixed on Android Q, please set this to false. 
*/
WebRtcAudioUtils.setWebRtcBasedAcousticEchoCanceler(true);

// Use sofware NS
WebRtcAudioUtils.setWebRtcBasedNoiseSuppressor(true);

// Use software AGC
WebRtcAudioUtils.setWebRtcBasedAutomaticGainControl(true);
```

I look forward to hearing your samples and taking a look at your bluetooth class :)

**Comment by mcorner** [comment]
Thanks for your help.  I read the Troubleshooting Audio section and I have a possible lead from that.  There is code for SDK versions >= O for requesting audio focus.  We don't have that, so I will add that and see how it goes in production.

We have definitely had users at >= O, but we did also upgrade to compileSDK 27 (from 23).  Could that have caused this?

**Comment by zackm0571** [comment]
@mcorner I'm glad you have a potential lead. Hopefully it won't take us too long to root cause. Could you please describe your testing setup when trying to reproduce echo? Things like:

- Are these devices in the same room? 
- Do you only experience this one out of every ten calls?
- Is there a particular set of steps that leads to echo being reproducible?
- What other testing matrices have you tried / experience this on? (ie: Android to iOS, Android to Android, etc)

Thanks 🙂

**Comment by mcorner** [comment]
- Devices are not in the same room, these are live customer calls.
- I got better information, and it is a very small % of calls, just a few out of hundreds.
- No steps as of yet, but there are two customers that it seems to happen a lot (or perhaps every time) to.  One is  ONEPLUS A5010 (os 9) and the other is Pixel 3 XL (os Q).
- Our business does Android -> Web and iOS -> Web only.  So no mobile to mobile calls.  This only happens on Android -> Web.

We will deploy the audiofocus change, but unfortunately the android documentation is completely opaque about what those settings do.  If you have any suggestions of things to log, that would be great.

**Comment by mcorner** [comment]
Also we are currently blacklisting *all* devices from using SLES:
WebRtcAudioManager.setBlacklistDeviceForOpenSLESUsage(true);

Perhaps we should be more selective about where we blacklist it?

Signal has a pretty good example of this:
https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/ApplicationContext.java#L250

Does the Twilio library already have a blacklist for SLES?

**Comment by aaalaniz** [comment]
Hey @mcorner 

Thank you for the update.

The Video Android library does not contain an OpenSLES blacklist. The [WebRTC team recommends](https://webrtc.googlesource.com/src/+/refs/heads/master/modules/audio_device/android/java/src/org/webrtc/voiceengine/WebRtcAudioUtils.java#39) managing a blacklist elsewhere and calling `WebRtcAudioManager.setBlacklistDeviceForOpenSLESUsage(true);` from the blacklisted device.

We intentionally avoid attempting to manage a blacklist ourselves. We currently do not have the facilities to accurately maintain this list. However, (as you have discovered) we often refer to the Signal app as a guide for how to configure audio in an Android WebRTC application.

I recommend adopting their OpenSLES blacklist as a potential solution. In addition, I also recommend adopting [their hardware AEC blacklist](https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/ApplicationContext.java#L252). The echo could also be the result the device's echo cancellation implementation.

We will take an action item to update our troubleshooting audio section to include this reference to the Signal App's blacklist and whitelists. 

Thanks again!

**Comment by zackm0571** [comment]
@mcorner thank you for reaching out. We've updated our troubleshooting audio section. Please let us know if we can help troubleshoot this or anything else further 🙂
