### ISSUE TITLE
Screen Share In Room With Remote Participants.

### ISSUE THREAD

**Issue by rashidabbas** [twilio/video-quickstart-android#404]
Hi I want to implement screen sharing into my android project in room with participants but I am facing issue that I am unable to share my device screen into room with other participants.

Please help me to implement this feature .

thanks in advance.

**Comment by zackm0571** [comment]
Hey @rashidabbas, thanks for reaching out. Have you looked at our [Screen Capturer example](https://github.com/twilio/video-quickstart-android/tree/master/exampleScreenCapturer)?
