### ISSUE TITLE
Typo in javadoc

### ISSUE THREAD

**Issue by Gryzor** [twilio/video-quickstart-android#407]
### Description

The class `LocalVideoTrack` has a few static `create()` methods, one of them has a typo in the javadoc:

```
    /**
     * Creates an audio track. Note that the RECORD_AUDIO permission must be granted in order for
     * this operation to succeed. If RECORD_AUDIO is not granted null is returned.
     *
     * @param context applicatoin context.
     * @param enabled initial state of audio track.
     * @param audioOptions audio options to be applied to the track.
     * @return local audio track if successfully added or null if audio track could not be created.
     */
    @Nullable
    public static LocalAudioTrack create(
            @NonNull Context context, boolean enabled, @Nullable AudioOptions audioOptions) {
        return create(context, enabled, audioOptions, null);
    }
```

Notice: `      * @param context applicatoin context.` 

I think this is part of the Twilio Android SDK, but I couldn't find the repo, otherwise I'd have submitted a PR. 

### Steps to Reproduce

1. Include Twilio com.twilio:video-android:4.1.2 
2. Open class LocalVideoTrack.
3. Observe...

#### Expected Behavior

`application` is correctly spelled. 

#### Actual Behavior

`applicatoin` is offered :)

#### Reproduces how Often

100%

#### Logs
N/A/

### Versions

All relevant version information for issue.

#### Video Android SDK
4.1.2

#### Android API
N/A

#### Android Device
N/A

**Comment by zackm0571** [comment]
Heh. Nice catch @Gryzor. Made a PR and you should see it not in 4.2.0 but the next release. Thanks for reporting this one :)
