### ISSUE TITLE
Chronometer not increment by one

### ISSUE THREAD

**Issue by MukFlex** [twilio/video-quickstart-android#408]
I have implemented  Chronometer to show call duration during Video and  Audio call. Chronometer increase by one during the video call, but during the video call, it sometimes increases by one or two.

Start Chronometer after call connected
      
`       timeChronometer.setBase(SystemClock.elapsedRealtime());
        timeChronometer.start();
`

    <?xml version="1.0" encoding="utf-8"?>
    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/mainRootLyt"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:keepScreenOn="true"
    android:orientation="vertical">

    <com.twilio.video.VideoView
        android:id="@+id/thumbnail_video_view"
        android:layout_width="@dimen/thumb_video_width"
        android:layout_height="@dimen/thumb_video_height"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:layout_margin="16dp"
        android:visibility="gone"
        app:mirror="true"
        app:overlaySurface="true" />

    <com.twilio.video.VideoView
        android:id="@+id/primary_video_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center" />

    <View
        android:id="@+id/video_upgrading_overlay"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:alpha="0.4"
        android:background="#ff1e272c" />

      <LinearLayout
        android:id="@+id/caller_details"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <LinearLayout
            android:id="@+id/call_type"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:orientation="horizontal"
            android:paddingLeft="16.0dip"
            android:paddingTop="23.0dip"
            android:paddingRight="16.0dip">

            <TextView

                android:id="@+id/voip_call_label"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:drawableStart="@drawable/calllogo"
                android:drawableLeft="@drawable/calllogo"
                android:drawablePadding="6dp"
                android:text="@string/video_call_label"
                android:textColor="#99ffffff"
                android:textSize="14.0sp" />

        </LinearLayout>

        <FrameLayout
            android:id="@+id/caller_contact_photo"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:animateLayoutChanges="true"
            android:paddingTop="28dip">

            <ImageView
                android:id="@+id/contact_photo"
                android:layout_width="90.0dip"
                android:layout_height="90.0dip"
                android:layout_gravity="center"
                android:src="@drawable/ic_circle_img"
                android:scaleType="fitCenter" />

            <android.support.v7.widget.AppCompatImageView
                android:id="@+id/whatsapp_icon"
                android:layout_width="20.0dip"
                android:layout_height="20.0dip"
                android:layout_gravity="bottom|center|right"
                android:layout_marginEnd="4dp"
                android:layout_marginRight="4dp"
                android:layout_marginBottom="4dp"
                android:rotation="-10.0"
                android:src="@drawable/icon"
                android:visibility="gone" />
        </FrameLayout>

        <LinearLayout
            android:id="@+id/name_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:paddingLeft="16.0dip"
            android:paddingTop="20.0dip"
            android:paddingRight="16.0dip">

            <TextView
                android:id="@+id/name"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:ellipsize="end"
                android:paddingBottom="20.0dip"
                android:singleLine="true"
                android:text="Mukesh Singh"
                android:textColor="@android:color/white"
                android:textSize="26.0sp" />
        </LinearLayout>

        <TextView
            android:id="@+id/call_status"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:lineSpacingMultiplier="1.5"
            android:paddingLeft="12.0dp"
            android:paddingRight="12.0dp"
            android:paddingBottom="20.0dp"
            android:text="INCOMING"
            android:textColor="#99ffffff"
            android:textSize="14.0sp" />
    </LinearLayout>

    <RelativeLayout
        android:id="@+id/top_bar_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:visibility="visible">

        <ImageButton
            android:id="@+id/top_minimize_btn"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentLeft="true"
            android:layout_gravity="center"
            android:background="@drawable/voip_btn_background"
            android:contentDescription="@string/voip_call_goto_chat_description"
            android:padding="18.0dip"
            android:src="@drawable/call_minimize"
            android:visibility="gone" />

        <Chronometer
            android:id="@+id/timeChronometer"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
          android:layout_centerHorizontal="true"
            android:layout_gravity="center"
            android:gravity="center"
            android:paddingStart="18.0dp"
            android:paddingTop="24.0dp"
            android:paddingEnd="18.0dp"
            android:textColor="#99ffffff"

            android:textSize="14.0sp"
            android:visibility="gone" />
    </RelativeLayout>
     </RelativeLayout >

**Comment by zackm0571** [comment]
Hey @MukFlex. Thanks for reaching out. Can you add a `Chronometer.OnChronometerTickListener` to your chronometer and log the results? Seeing the logs next to the video logs might be of use.

**Comment by zackm0571** [comment]
@MukFlex, this also could be a performance issue on the SDK end. If you have the time, could you please profile your application to determine the impact of our SDK?

Thanks :)

**Comment by MukFlex** [comment]
@zackm0571, When I start chronometer before call connection then it works perfectly. How can I profile my application to determine the impact of the SDK?

**Comment by MukFlex** [comment]
@zackm0571,  I have found the problem. Problem is in my code. I had implemented a HandlerThread to show 'Poor Connection'. When I comment  this line the chronometer works perfectly.

I am sorry and Thanks for the support.

I have one more question. Is Twilio provide network strength related data?
