### ISSUE TITLE
Android Q Audio Input not working

### ISSUE THREAD

**Issue by mcorner** [twilio/video-quickstart-android#409]
### Description

Microphone appears not to work on Android Q/10.

### Steps to Reproduce

We don't have a real device, but one of our users is using Android Q and we can't hear him.  We tested on an Android Q emulator and get the same result.

#### Code

Quickstart and our own app.

#### Expected Behavior

Be able to hear Android Q user at the other end of the connection.

#### Actual Behavior

Silence

#### Reproduces how Often

100%

#### Logs

We didn't notice anything odd in the logs

### Versions

Latest Android Q and SDK

#### Video Android SDK

4.1.2

#### Android API

28

#### Android Device

Emulator and Pixel 3 XL

**Comment by mcorner** [comment]
Although, we *do* get the user's Pixel 3 XL audio in our recording (taken at the other side).  I can't quite explain how that happens if the other side can't hear it in their output (they are using JS).

**Comment by mcorner** [comment]
Argh, I forgot there is no microphone in the emulator.  Still not sure what the problem is with this user's audio, but I am not thinking this isn't a Twilio problem.  If you get a chance to test Android Q, that would be great though.

**Comment by zackm0571** [comment]
Hey @mcorner.

I'm doing all of my development on a Pixel 3 XL running Android Q beta 2 (upgraded to 3 last night) and I haven't run into this yet. Android Beta versions can have some strange media related defects until they're released. For example, I noticed screen sharing was broken in beta 1. There's also a way to disable the mic system wide using a WebRTC flag.

 With that said, I would still like to investigate. Can you provide logs and a room sid, please?  Hopefully this will be resolved once Android Q is released.

**Comment by mcorner** [comment]
I am not sure there is a bug here at all, we are just a bit stuck on why we can't hear the user.  We don't have an Android Q device handy ATM to test with.

The audio is definitely making it out of the user's device as we get it in the recording on the Web/JS side.  The bandwidth on the audio stream is good and the level is not 0.  We do client side recording there by grabbing the streams and merging them using:
https://github.com/t-mullen/video-stream-merger

It is possible that the recorder is interfering with playing the audio, but we don't see this show up other times (many, many calls).  I could certainly share our code, but I am not sure it is relevant here.

These were the rooms:
RM309040c6fa19193b61e671d2f8b11966
RMdf681fe71dd64dbb6c202b4dba0e3a68

Since this happens on a user device we don't have logs.  If you add the ability for a custom logger we could provide lower level Twilio logs (I mentioned this in an iOS github issue as well).

**Comment by zackm0571** [comment]
@mcorner have you seen anything different since the latest beta versions? Was never able to reproduce this locally on the Pixel 3 XL running the previous three betas.

**Comment by zackm0571** [comment]
Hey @mcorner we can't reproduce this in our test suite. If you experience this problem in the future please feel free to reopen the issue. 🙂

**Comment by mrisek** [comment]
Hi, I have the same problem as described here
Microphone doesn’t work, and nobody can hear us, although I am connected in room and can hear the other users.

SDK: 4.3
Android devices: Xiaomi Note4, Huawei, et cetera

Code example:
[IncomingCallActivity.kt.zip](https://github.com/twilio/video-quickstart-android/files/3476909/IncomingCallActivity.kt.zip)

**Comment by zackm0571** [comment]
Hey @mrisek Could you please provide some more details? 

- What Android Q beta are you running? 
- Could you provide the Room SID's of a call where you experience this?
- Could you provide device logs? 
- Does this happen on devices running older versions of Android?

**Comment by mrisek** [comment]
_What Android Q beta are you running?_
We were running Android 10, 9 and 7 to reproduce this issue.

_Could you provide the Room SID's of a call where you experience this?_
![photo_2019-09-24_11-55-45](https://user-images.githubusercontent.com/19214159/65501990-412cfd80-dec2-11e9-99e8-ba8dbc8f3d3e.jpg)

_Could you provide device logs?_
[Twilio logs.zip](https://github.com/twilio/video-quickstart-android/files/3646575/Twilio.logs.zip)

_Does this happen on devices running older versions of Android?_
Yes, it happened on all Android devices that we used including older versions.
We are developing Kotlin application and maybe we are doing something wrong. Please provide us code example.

**Comment by gomobishop** [comment]
i have same issue on android 10 but its working fine on android 6

**Comment by aaalaniz** [comment]
Hey @gomobishop 

Do you have this problem if you use [AudioSwitch](https://github.com/twilio/audioswitch)? If you do please file a bug in the project.

Thanks!

**Comment by Manit-Chanthavong** [comment]
using Pixel 4 android 12, with Twilio Android SDK 7.1.0. Mic not published to room this happens random on calls. Anyone else experience the same issue. Google WebRTC has no issues.
