### ISSUE TITLE
Switch  

### ISSUE THREAD

**Issue by kansalmohit19** [twilio/video-quickstart-android#410]
### Description

I am facing an issue while swapping the Local and Primary views.
While adding Local view to Primary, it starts blinking.

#### Code

```java
// Code that help reproduce the issue
```

### Versions

All relevant version information for issue.

#### Video Android SDK

[eg. 1.0.2]

**Comment by kansalmohit19** [comment]
I am facing an issue while swapping the Local and Primary views.
While adding Local view to Primary, it starts blinking.

**Comment by zackm0571** [comment]
Hey @kansalmohit19 thanks for reaching out. Could you please update your original post with code from your `Activity`?

**Comment by zackm0571** [comment]
@kansalmohit19 could you please make sure you're only rendering one track at a time to the primary video view. Typically this blinking can happen when rendering more than one track at a time to a `VideoView` or a `VideoTextureView`.
