### ISSUE TITLE
The video stream from iOS does not come on Android tablets

### ISSUE THREAD

**Issue by backenddoneit** [twilio/video-quickstart-android#420]
### Description
Hello
I use Programmable Video in a iOS and Android mobile app. I ran into a problem.
The video stream from iOS does not come on Android tablets:
remoteVideoTrackPublication.isTrackSubscribed == false from RemoteParticipant
On Android phones, there is no such problem, only with android tablets.
Library Versions -
4.2.0 on android
2.10.0 on ios
Could you please help and tell me what could be the problem? What can make your service works differently with the phone and the tablet?

**Comment by zackm0571** [comment]
Hey @backenddoneit, 

Thanks for reaching out. Sorry you're experiencing problems with video on tablet. Could you provide a few things for us to help debug?

- Logs from tablet connecting to a room and not subscribing to video.
- Make sure you have `enableAutomaticSubscription` set to `true` in `ConnectOptions`.
- Do you see this behavior on the video android quickstart without any modification?

Thanks! Hope we can get this resolved soon. :)

**Comment by backenddoneit** [comment]
The problem was in the iOS codec. There was this H264 and when we changed to this Vp8 the video stream from iOS started coming to Android tablets.
But thanks anyway for your help!

**Comment by zackm0571** [comment]
Thanks @backenddoneit. Feel free to open another issue if you have any more problems :)
