### ISSUE TITLE
Screen sharing system notification is present even though screen sharing was turned off

### ISSUE THREAD

**Issue by palicka** [twilio/video-quickstart-android#423]
Hi,
when media projection permission is granted, screenCapturer is created this way:

```
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        ...
            screenCapturer = ScreenCapturer(activity!!, resultCode, data!!, screenCapturerListener)
        ...
    }
```
then, LocalVideoTrack screenVideoTrack is created this way:

```
                if (screenVideoTrack == null) {
                    screenVideoTrack =
                            LocalVideoTrack.create(it, true, screenCapturer!!, LOCAL_VIDEO_TRACK_NAME_BROADCAST)
                }
                screenVideoTrack?.enable(true)
```
there is a toggle button in our app that enables/disables screen sharing, and this is how screen sharing is disabled right now:

```
        screenVideoTrack?.let {
              screenVideoTrack?.enable(false)
        }
```
but I noticed, this doesn't work properly because system screen sharing notification is still present in status bar. I tried to call:

` screenCapturer?.stopCapture()`
and it worked. System notification was gone. but now I want to start screen capturing again, and I guess I need to call: 
`screenCapturer?.startCapture()` 
and the problem is, this method requires two parameters:

> VideoFormat captureFormat and VideoCapturer.Listener capturerListener

and the question is, why do we need set captureFormat now, when it wasn't necessary when the screen was shared for the first time... I don't know what to set there...
Thanks

**Comment by zackm0571** [comment]
Hey @palicka, 

Thanks for reaching out. Enabling and disabling the `screenCapturer` doesn't actually release the underlying resource providing the frames. In order to actually stop capturing the screen you will need to unpublish the track and release it. Consequently this means you will have to re-create the track and re-publish it should you want to resume capturing. This code example shows how you might accomplish that. 

Unpublish / Release
```
        localParticipant = room?.localParticipant
        screenVideoTrack?.let { localParticipant?.unpublishTrack(screenVideoTrack) }
        screenVideoTrack?.release()
        screenVideoTrack = null
```

Re-Create / Re-Publish
```
         screenVideoTrack =
                            LocalVideoTrack.create(it, true, screenCapturer!!, LOCAL_VIDEO_TRACK_NAME_BROADCAST)
localParticipant?.publishTrack(screenVideoTrack)
```

Hope this helps :)
