### ISSUE TITLE
Twilio AR Core Support (H264 Encoding)

### ISSUE THREAD

**Issue by HaiderSaleem** [twilio/video-quickstart-android#425]
Hi! Using Twilio with Arcore, i have developed an app and its working.
sometimes, it passes one arview to another and sometimes it cant.

Is there any problem with twilio that it cant stream AR well?
might be some packet size issue? 
As i'm having no issue with AR fragment but with glsurface view.

update: setting H264 encoder as default in app, its working fine but later it doesn't then repeating again it works.

**Comment by aaalaniz** [comment]
Hey @HaiderSaleem 

AR Core support is not currently on our roadmap. Thank you for the filing the issue, but I will close for now.

**Comment by HaiderSaleem** [comment]
I have achieved it, thank you for responding after 5 months.  :)

> Hey @HaiderSaleem
> 
> AR Core support is not currently on our roadmap. Thank you for the filing the issue, but I will close for now.

I have achieved it, thank you for responding after 5 months.  :)

**Comment by Mehequanna** [comment]
@HaiderSaleem Do you mind sharing how you achieved it? I'm trying to do something similar to no avail. Any help or sample code/app would be hugely appreciated.

**Comment by HaiderSaleem** [comment]
> @HaiderSaleem Do you mind sharing how you achieved it? I'm trying to do something similar to no avail. Any help or sample code/app would be hugely appreciated.

sure, i'll share it soon.
kindly, wait.
