### ISSUE TITLE
Chrome 76+ DataTrack incompatibility with 2.X Mobile SDKs in P2P Rooms

### ISSUE THREAD

**Issue by ceaglest** [twilio/video-quickstart-android#433]
Chrome 76 [added support](https://groups.google.com/forum/#!msg/discuss-webrtc/Y7TIuNbgP8M/UoXP-RuxAwAJ) for a [new SDP format](https://bugs.chromium.org/p/webrtc/issues/detail?id=4612) for data channel negotiation. This new SDP format is not compatible with 2.x Android and iOS Video SDKs when used with P2P Rooms.

### What is the impact?

In a P2P room, Chrome 76+ Participants and affected mobile SDKs might not be able to subscribe to each other’s data tracks. The issue occurs when the Chrome Participant connects to a Room after an incompatible mobile Participant has already connected.

### Are audio and video tracks affected?

No. Participants can subscribe to audio and video tracks and they continue to function as expected.

### Is my app impacted by this change?

The following table shows the impacted mobile SDK versions and the recommended upgrade path:

| Twilio Video SDK | Affected versions | Recommended Upgrade path |
| ---------------- | ----------------- | ------------------------ |
| Android SDK      | 2.X               | 3.0.0 +                  |
| iOS SDK          | 2.0.0 - 2.2.2     | 2.3.0 +                  |

### I am impacted, what should I do?

Please refer to the upgrade paths listed above and the following guides for performing the upgrades:

- [Migrating from 2.X to 3.X - Android](https://www.twilio.com/docs/video/migrating-2x-3x-android-30)

### Additional Resources

- [Android 3.X Change log (Twilio Docs)](https://www.twilio.com/docs/video/changelog-twilio-video-android-3x)
- [iOS 2.X Change log (Twilio Docs)](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x)
- [Programmable Video (Twilio Docs)](https://www.twilio.com/docs/video)

**Comment by afalls-twilio** [comment]
closing due to age
