### ISSUE TITLE
 After rejoin room, getting  isTrackSubscribed() false for first two participants and RemoteVideoTracks `null` .

### ISSUE THREAD

**Issue by Midhun9638** [twilio/video-quickstart-android#437]
### Description
 I'm using 'com.twilio:video-android:4.0.0' Version

I have created room and 3 remote participant connect one by one to room and I can render all three remote participant video  then I just disconnected room and rejoin same room 
//Room events listener
```
onConnected(Room room) 
 for (RemoteParticipant participant : room.getRemoteParticipants()) {
                    remoteParticipantJoin(participant);
                    break; 
                }
```
 I got all three remote participant but I can only render last one participant not first two 
because I got error on  isTrackSubscribed() false for first two participants and RemoteVideoTracks
`null` .
```

 if (participant.getRemoteVideoTracks().size() > 0) {
                        RemoteVideoTrackPublication remoteVideoTrackPublication =
                                participant.getRemoteVideoTracks().get(0);
               
                        /*
                         * Only render video tracks that are subscribed to
                         */
                        if (remoteVideoTrackPublication.isTrackSubscribed()) {   // false for first two

}
}
```
 why this  RemoteVideoTracks getting null ? please help

**Comment by patchra** [comment]
Did you fix the problem? I'm getting the same issue
