### ISSUE TITLE
Android video connected is very slow

### ISSUE THREAD

**Issue by rameshannadhurai** [twilio/video-quickstart-android#445]
How to handle the network connection,when before call connected. Why means because of my mobile network speed is slow so how to handle that time.

**Comment by aaalaniz** [comment]
Hey @rameshannadhurai 

We recently released our 5.0.0 SDK. The primary feature of this major release is the use of Global low latency (GLL) signaling by default. This means users should experience faster connect times as they are now connecting to Twilio closer to their physical location. We also now allow developers to specify a signaling region themselves in their application if they would like to use the Android framework to determine a users region with more precise accuracy. Reference the snippet below.

Specifying a Region
```
val connectOptions = ConnectOptions.Builder(accessToken).apply {
    region("us1")
}.build()

Video.connect(context, connectOptions, roomListener)
```

In addition, developers can get the signaling region selected via `LocalParticipant.getSignalingRegion()`.

I will close this issue, but I would be happy to address any follow up questions or comments.
