### ISSUE TITLE
Showing Dominant Speaker in the primaryView

### ISSUE THREAD

**Issue by sylendra7** [twilio/video-quickstart-android#446]
Hi ,

How to display the dominant speaker in the primary view in the quickstart application of Android . 

https://github.com/twilio/video-quickstart-android/tree/master/quickstart

Thanks & Regards
Sylendra

**Comment by aaalaniz** [comment]
Hey @sylendra7 

I recommend referencing our [Multiparty Example](https://developer.android.com/training/monitoring-device-state/doze-standby) which demonstrates how to update the UI when the dominant speaker of a room changes.

I'll close this issue for now. Please open a new issue or reopen this issue if you have additional questions.

Thank you!
