### ISSUE TITLE
Twilio Send custom Audio bytes using LocalAudioTrack

### ISSUE THREAD

**Issue by faiziakbr** [twilio/video-quickstart-android#452]
I am trying to send my Custom audio bytes recorded from AudioRecord to PSTN. If i use the Twilio example android app ExampleAudioSink. I am able to send and receive the bytes that are recorded and played by the WebRtcAudioRecord. What i want is to send my own Custom recorded bytes in realtime to via LocalAudioTrack. I have also bypassed the webrtcAudioPlay but can't seem to figure out, how to send my own bytes via LocalAudioTrack.

```
private void connectToRoom(String roomName) {
        ConnectOptions.Builder connectOptionsBuilder = new ConnectOptions.Builder(accessToken)
                .roomName(roomName);

    if (localAudioTrack != null) {
        connectOptionsBuilder
                .audioTracks(Collections.singletonList(localAudioTrack));
    }

    room = Video.connect(this, connectOptionsBuilder.build(), roomListener());
}


private void createAudioTrack() {
    localAudioTrack = LocalAudioTrack.create(this, false, LOCAL_AUDIO_TRACK_NAME);
}
```

I am trying to send my Custom audio bytes recorded from AudioRecord to PSTN. If i use the Twilio example android app ExampleAudioSink. I am able to send and receive the bytes that are recorded and played by the WebRtcAudioRecord. What i want is to send my own Custom recorded bytes in realtime to via LocalAudioTrack. I have also bypassed the webrtcAudioPlay but can't seem to figure out, how to send my own bytes via LocalAudioTrack.

private void connectToRoom(String roomName) {
        ConnectOptions.Builder connectOptionsBuilder = new ConnectOptions.Builder(accessToken)
                .roomName(roomName);

    if (localAudioTrack != null) {
        connectOptionsBuilder
                .audioTracks(Collections.singletonList(localAudioTrack));
    }

    room = Video.connect(this, connectOptionsBuilder.build(), roomListener());
}

private void createAudioTrack() {
    localAudioTrack = LocalAudioTrack.create(this, false, LOCAL_AUDIO_TRACK_NAME);
}

as you can see i have stopped the sending of WebRtcAudioRecord bytes to PSTN by placing false in the second param of LocalAudioTrack.create, but couldn't figure it out how to send my own.

Please don't suggest me to send my bytes using LocalDataTrack because they will not play in PSTN.

Or if there is a way where i can send audio bytes via LocalDataTrack to PSTN and it plays the bytes.?

**Comment by aaalaniz** [comment]
Hey @faiziakbr 

The Video Android SDK does not currently support using a custom audio device with a `LocalAudioTrack`. However, this feature is on our roadmap, and I will be happy to provide updates as the feature progresses.

Thank you

**Comment by faiziakbr** [comment]
Thanks for the reply.

 need suggestion: is there a way where i can send audio bytes via LocalDataTrack to PSTN and it plays the bytes?

**Comment by aaalaniz** [comment]
Hey @faiziakbr 

I don't recommend sending audio bytes using the DataTrack API. I do not think what you are proposing is possible.

Thank you

**Comment by mail2chromium** [comment]
Hey @aaalaniz,

I am developing my android Application using Twilio. By using only `LocalDataTrack`, I was sending my custom audio bytes to PSTN. 

I have performed multiple test using Twilio Video Conference API. During my initial testings, it was noticed that I have been able to maintain a successful communication between my *Android Client and PSTN* by sending my custom audio bytes to PSTN. 

I have recordings of my tests using `Twilio Record API`  which i can share. I am also in contact with twilio Support Center in order to resolve this issue. Because, Now i am unable to send my bytes to PSTN, but i am able to receive bytes from PSTN.

Looking forward for some extensive help and solution.
Thanks.

**Comment by aaalaniz** [comment]
Hey @mail2chromium @faiziakbr 

I believe our Audio Device feature, which we intend on finishing this quarter, would provide the facilities you need in your application.

However, if you would like to research another way forward feel free to provide an example for our team to review.

I'm going to close this issue for now.

Thank you

**Comment by acrolink** [comment]
> I don't recommend sending audio bytes using the DataTrack API. I do not think what you are proposing is possible.

Why it is not recommended?

**Comment by aaalaniz** [comment]
Hey @acrolink 

While the DataTrack API does provide a low latency mechanism for sending data to participant's, there are no facilities for ensuring that audio and video data will remain synchronized. I supposed if your application does not depend on AV synchronization you could attempt to do this.

Hope this helps

**Comment by mail2chromium** [comment]
Hey @aaalaniz

I have been looking forward to this solution from the past 6 months. I want to confirm these following things:

With Twilio Video SDK:
-----

- Is there any privilege that I can record from MicroPhone by using my own method/recording CallBack? 
- Is there any method/Point where I can push those **Custom AudioBytes** to Twilio Rooms for other participants?
- Is there any privilege that I can get bytes from the receiving side and perform any actions before playing?
- Is there any privilege that I can play this method by using my own method?

Without Twilio Video SDK:
-----

What are the alternatives to connect to Twilio Video SDK Rooms to use its services?

I have purchased Twilio Account and I have been using Twilio for the last 1 year for Audio Communications using Twilio NTS Service. I am using WebRtc interface to make communication possible. In that way, I have complete access to Audio Pre-Processing(near-end) and Post-Processing(far-end). But I am interested to do that for **more than 2 participants** and if I go with Twilio SDK, then this can't be possible as 

> "The Video Android SDK uses a default audio device that captures audio frames from the microphone" 

 Please assist me in this matter.
