### ISSUE TITLE
Is it possible to use the API with regular WebRTC objects?

### ISSUE THREAD

**Issue by ceggert87** [twilio/video-quickstart-android#453]
Hello everyone!

I'm just trying to get started with Twilio video (using 5.1.0) and noticed that all WebRTC-related classes (PeerConnection, videotracks, views etc.) have their own package despite being at least mostly identical to the WebRTC standards.

My plan is to use an existing solution that uses the official WebRTC classes (direct communication and conferences) and extend it with Twilio as a new option. I was hoping I could "just" get the video and audiotracks from the listeners and apply them to the logic I already have, but due to the different packages they are incompatible and it looks to me like I'd have to basically copy and paste my whole logic or implement wrappers to accept the Twilio classes as well, although the method calls are the same.

I was wondering if there is a suggested way to achieve what I am trying? Or am I missing something central?

Thanks a lot for any suggestions!

**Comment by aaalaniz** [comment]
Hey @ceggert87 

I recommend you read issue #340. Inter opting the Video Android SDK with an existing WebRTC solution is currently not possible. Side-by-side support enables developers to use Twilio Video alongside another WebRTC library, *but does not provide any interop capabilities*. 

Interoperability with other WebRTC libraries is not on our roadmap. I will close this issue, but I'm happy to answer any follow up questions or comments.

Thank you
