### ISSUE TITLE
How to share screen to Room with My Audio using Android SDK

### ISSUE THREAD

**Issue by guruaugust** [twilio/video-quickstart-android#456]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```java
// Code that help reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces how Often

[What percentage of the time does it reproduce?]

#### Logs

```
// Log output when issue occurs
```

### Versions

All relevant version information for issue.

#### Video Android SDK

[eg. 1.0.2]

#### Android API

[eg. 18]

#### Android Device

[eg. Nexus 5]

**Comment by aaalaniz** [comment]
Hey @guruaugust 

I've provided an answer to this question [here](https://github.com/twilio/video-quickstart-android/issues/369#issuecomment-566713499). In the future, please fill out the issue template as best you can for your request. Thank you
