### ISSUE TITLE
Get Video track resolution

### ISSUE THREAD

**Issue by mattcianna** [twilio/video-quickstart-android#457]
Hi, 

is there a way to get my video track's current resolution? (e.g. 1920x1080)?

Thank you.

**Comment by aaalaniz** [comment]
Hey @mattcianna 

You can use the `Room.getStats` API to get the resolution of local and remote video tracks. The [StatsReport](https://twilio.github.io/twilio-video-android/docs/latest/com/twilio/video/StatsReport.html) object will contain all local and remote track media information.

Thank you
