### ISSUE TITLE
Record local video and save it to file ? 

### ISSUE THREAD

**Issue by bataemperor** [twilio/video-quickstart-android#459]
### Description

Hello. I'm using twilio video for video chat between two participants.
I want to develop functionality where user can record his local video track only with both audio tracks. Video track and audio tracks need to be synchronized . 
I am able to record both audio tracks to a file using AudioSink following the example from your repository. I need to record local video as well so I can later merge this 3 files into one file.
Is there any example how to record local video track to a file(mp4 ie) like the one with audio file ?

I guess I need to use CustomVideoRender like SnapshotVideoRenderer example but I don't know how to use renderFrame method and to make a video file from this frames.

I am aware of recording api on twilio but I'm trying to do it locally, simple because I need to have an option to record only part of conversation.

Thank you

**Comment by aaalaniz** [comment]
Hey @bataemperor 

The Video Android SDK does not currently provide facilities to record synchronized audio/video locally. However, you are welcome to attempt this by using the VideoRenderer and AudioSink APIs. I recommend reading through the [MediaMuxer](https://developer.android.com/reference/android/media/MediaMuxer) documentation and examples in the [Grafika project](https://github.com/google/grafika/blob/master/app/src/main/java/com/android/grafika/CircularEncoder.java).

I am closing this ticket as local recording is not on our SDKs roadmap. I also invite you to file a support ticket to request Recording API changes that accommodate your application needs.

Thank you
