### ISSUE TITLE
Would it be possible to get Intel H264 supported?

### ISSUE THREAD

**Issue by ceggert87** [twilio/video-quickstart-android#465]
### Description

Although the Vuzix M300 supports H264 natively, it doesn't seem to work using the 5.1.0 version of the library. Despite setting the preferredVideoCodec in the ConnectOptions, it still sends VP8 material. Forcing another participant (e.g. a browser) to H264 leads to the video not being shown, with the WebRTC Internals showing the following codec sent from the browser to the M300:
H264 (payloadType: 125)

From my knowledge, the WebRTC team has dropped official support for Intel hardware encoders/decoders. So despite them working, the OMX.Intel prefix is simply not part of the H264 hardware list so that MediaCodecVideoEncoder.isH264HwSupported() always returns false.

**Would it be possible to get this into your library, or get some sort of access to manually add these?**

I have another implementation that does not use the Twilio library, but the official one from WebRTC with the OMX.Intel prefix being added manually. With this, calls work as expected with hardware support.

### Steps to Reproduce

1. Prepare a call for devices using an Vuzix M300 and any other end supporting H264
2. In the connection options of both sides, set H264 as the preferred codec with .preferVideoCodecs(Collections.singletonList(new H264Codec()));
3. Connect to a room and attach a video stream
4. The M300 will send in VP8 despite the setting and will not be able to render the other participant's video when it's in H264.

#### Code

Basically just default examples using something like:

        ConnectOptions.Builder connectOptionsBuilder = new ConnectOptions.Builder(accessToken)
                .roomName(roomName)
                .preferVideoCodecs(Collections.singletonList(new H264Codec()));

on the Android end and 
            Video.connect(
                twilioToken,
                {name: twilioRoomname,
                preferredVideoCodecs: ["H264"],
                preferredAudioCodecs: ["opus"]})

on the browser end.

#### Expected Behavior

H264 should be used by the M300, it should be able to render the received H264 content

#### Actual Behavior

The M300 only works using software VP8 encoders/decoders with the expected bad performance of doing so.

#### Reproduces how Often

100%

### Versions

Android SDK 5.1.0

#### Android API

23

#### Android Device

Vuzix M300

**Comment by aaalaniz** [comment]
Hey @ceggert87 

I investigated this further and was able to put together an experimental snippet for you to try to enable H.264 on the Vuzix M300. I suggest you modify this code to only be allowed to be run on that device. Execute this code anytime before calling our Video SDK APIs.

```
    private static void addIntelH264HwSupport() {
        try {
            // Get Qualcomm H264 Codec Properties Field
            final Class mediaCodecVideoEncoderClass = Class.forName("tvi.webrtc.MediaCodecVideoEncoder");
            final Field qcomH264HwPropertiesField = mediaCodecVideoEncoderClass.getDeclaredField("qcomH264HwProperties");
            qcomH264HwPropertiesField.setAccessible(true);
            final Object qcomH264HwProperties = new Object();
            qcomH264HwPropertiesField.get(qcomH264HwProperties);

            // Create new entry with Intel details
            final String codecPrefix = "OMX.Intel.";
            final int minSdk = Build.VERSION_CODES.LOLLIPOP;
            final MediaCodecVideoEncoder.BitrateAdjustmentType bitrateAdjustmentType =
                    MediaCodecVideoEncoder.BitrateAdjustmentType.NO_ADJUSTMENT;
            final Class mediaCodecPropertiesClass = Class.forName("tvi.webrtc.MediaCodecVideoEncoder$MediaCodecProperties");
            final Constructor mediaCodecPropertiesCtor = mediaCodecPropertiesClass
                    .getDeclaredConstructor(String.class,
                            int.class,
                            MediaCodecVideoEncoder.BitrateAdjustmentType.class);
            mediaCodecPropertiesCtor.setAccessible(true);
            final Object intelH264HwProperties = mediaCodecPropertiesCtor.newInstance(codecPrefix,
                    minSdk,
                    bitrateAdjustmentType);

            // Replace Qualcomm properties field with Intel properties
            qcomH264HwPropertiesField.set(qcomH264HwProperties, intelH264HwProperties);
        } catch (Exception e) {
            Log.e("AddIntelH264Support", "Failed to add Intel H264 support");
        }
    }
``` 

Let me know if this works. As far as I could tell, WebRTC does not restrict the use of the MediaCodecVideoDecoder with Intel hardware.

Thank you

**Comment by ceggert87** [comment]
Hi @aaalaniz ,

thanks for the specific response and for taking a look into this! 

Unfortunately, it seems like this only partly fixed the issue. Adding these reflections, it seems like the H264 encoding in general is enabled (I can successfully transmit video now). However, the performance indicates that it still uses software encoding. I'm having fps in the single digit range, while the modified WebRTC solution runs with 30fps without issues. 

One assumption I would have is that the HardwareVideoEncoderFactory still returns false in "isHardwareSupportedInCurrentSdkH264" since the Intel prefix is not part of that. I couldn't find any point to insert it via reflections here though. 

Not so surprisingly since nothing was changed regarding that, receiving H264 content still doesn't work either. It looks to me like the OMX.Intel prefix is present in both the Decoder and DecoderFactory though, so I'm not quite sure why this is not working. With VP8 I'm receiving things just fine.

I noticed that in my own solution the received H264 content is set with payloadType 100 vs. payloadType 125 when using Twilio. Is it possible that the issue is related to the H264 profile? If so, are there ways to change the profile level?

**Comment by ceggert87** [comment]
@aaalaniz 

Your solution actually works like a charm, I just had issues because the org.webrtc packages were taken instead of the tvi.webrtc ones. Although only the encoder is manipulated, receiving H264 actually works hardware encoded as well with that for some reason. So it's looking great with this approach, thanks a bunch! 

One final question then: Is it possible to get this included officially in general in future versions? I'm not the biggest fan of using reflections for maintainability, although it's quite a fancy solution for this issue :).

Thank you and please feel free to close this issue.

**Comment by aaalaniz** [comment]
Hey @ceggert87 

I've captured a task in our backlog, but adding this functionality to our SDK is not on our roadmap. I'm glad the snippet was able to help. I'm closing this issue for now, but I'd be happy address any follow up questions or comments.

Thank you
