### ISSUE TITLE
Quickstart Kotlin: action bar - Speaker ON/OFF label doesn't toggle

### ISSUE THREAD

**Issue by esmitperez** [twilio/video-quickstart-android#466]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

When you tap "Speaker ON" the label never changes to reflect "OFF"

### Steps to Reproduce

1. Launch QuickStart Kotlin
2. Click "..." button on upper right corner
3. Click Speaker ON
4. Repeat step #2: label still displays Speaker ON even when this line (VideoActivity.kt) ` audioManager.isSpeakerphoneOn = false` has been executed

#### Code

```kotlin
// Code that help reproduce the issue
 audioManager.isSpeakerphoneOn = false
```

#### Expected Behavior

Label should switch to "Speaker OFF" or "Speaker ON" depending on status of `audioManager.isSpeakerphoneOn`

#### Actual Behavior

See "Steps to reproduce" section

#### Reproduces how Often

100%

#### Logs

N/A

### Versions

All relevant version information for issue.

#### Video Android SDK

5.1.0

#### Android API

29

#### Android Device

Pixel 3a

**Comment by aaalaniz** [comment]
Hey @esmitperez 

Thank you for pointing this out. We will land a PR that soon resolves this issue.

Thank you
