### ISSUE TITLE
Rotation causes black screen on remote video

### ISSUE THREAD

**Issue by aaalaniz** [twilio/video-quickstart-android#47]
A rotation bug has been introduced with the enabling of decoding from a texture. When rotating a device, the remote video renderer will show black frames indefinitely because of a bug in our rendering pipeline. This issue only affects version `1.0.0-beta5`.

Below is a screenshot of the bug in the quickstart.
![device-2017-01-15-122406](https://cloud.githubusercontent.com/assets/1734140/21965892/bf8316ca-db1d-11e6-99fc-c2cca673f377.png)

**Comment by Aubtin** [comment]
Is there a timeline for the fix?

**Comment by aaalaniz** [comment]
Hi Aubtin,

I apologize for the continued delays, but our timeline is this week.

**Comment by aaalaniz** [comment]
As a workaround, can you try overriding [onConfigutationChanged()](https://developer.android.com/reference/android/app/Activity.html#onConfigurationChanged(android.content.res.Configuration) and removing and adding the renderer for the remote video when the orientation has changed. This is not ideal, but it should prevent permanent black frames being rendered.

**Comment by aaalaniz** [comment]
Hey @Aubtin 

I appreciate your patience. We have released [1.0.0-beta6](https://bintray.com/twilio/releases/video-android/1.0.0-beta6). This release contains the fix.
