### ISSUE TITLE
The shared screen does not appear well from Chrome

### ISSUE THREAD

**Issue by kkamikawa** [twilio/video-quickstart-android#473]
### Description

I am trying to video chat by connecting the app to Twilio Flex. I was able to start a video from the app and video chat with Flex. However, when I share the screen from Flex, it looks like the image of the camera and the shared screen appear alternately like a gif. Is there a way to solve this? For example, the shared screen is shown above the camera image.

I use this plugin(https://github.com/trogers-twilio/plugin-video-chat) for Flex Video Channel.

### Steps to Reproduce

1. Enter at twilio room from Device A (Xperia 1) and Device B(Windows PC chrome https://github.com/trogers-twilio/plugin-video-chat)
2. Publish video tracks
3. Share screen from Chrome

#### Expected Behavior

The shared screen appears correctly in the area where the conversation partner was shown.

#### Actual Behavior

![TwilioVideoAppScreenShare](https://user-images.githubusercontent.com/56712463/74124847-06302a00-4c17-11ea-9987-e5b9228f8257.gif)

#### Reproduces how Often

every time

#### Logs

[VideoActivity_log.log](https://github.com/twilio/video-quickstart-android/files/4179464/VideoActivity_log.log)

### Versions

 'java': JavaVersion.VERSION_1_8,
        'androidGradlePlugin': '3.5.3',
        'googleServices': '3.2.1',
        'compileSdk': 29,
        'buildTools': '28.0.3',
        'minSdk': 16,
        'targetSdk': 29,
        'supportLibrary': '26.1.0',
        'constraintLayout': '1.1.3',
        'firebase': '10.0.1',
        'retrofit': '2.0.0-beta4',
        'okhttp': '3.6.0',
        'ion': '2.1.8',
        'videoAndroid': '5.1.0'

#### Android Device

Xperia 1

**Comment by aaalaniz** [comment]
Hey @kkamikawa 

This may just be a limitation of the quickstart application. I don't think the app is setup to render multiple video tracks from a participant.

Can you try a similar exercise but using the application below?

https://github.com/twilio/twilio-video-app-android

We recently released a more fully featured collaboration app that is capable of rendering multiple video tracks from a single participant. The application complexity is higher, but it should be pretty easy to get started.

Thanks!

**Comment by aaalaniz** [comment]
I'm going to close this issue for now @kkamikawa as adding more complex UI/UX is not part of the scope of these quickstarts.

Please reopen if you find that this issue is present in both applications.

Thanks!

**Comment by kkamikawa** [comment]
Thank you very much.
I will try it!
