### ISSUE TITLE
onNetworkQualityLevelChanged is not getting called in any case.

### ISSUE THREAD

**Issue by himanshu-my** [twilio/video-quickstart-android#478]
I have implemented the below code 

```
ConnectOptions.Builder connectOptionsBuilder = new ConnectOptions.Builder(accessToken)
                                            .roomName(roomName)
                                            .enableNetworkQuality(true);
```

to get network quality level 

```
private void roomConnected(CallingEvents callingEvents) {
        Room room = callingEvents.getRoom();
        
        if (room.getRemoteParticipants().size() > 0) {
            addRemoteParticipant(room.getRemoteParticipants().get(0));
        }

        if (room.getLocalParticipant() != null) {
            room.getLocalParticipant().setListener(localParticipantListener());
        }
    }

public  LocalParticipant.Listener  localParticipantListener(){
        return new LocalParticipant.Listener() {
            @Override
            public void onAudioTrackPublished(@NonNull LocalParticipant localParticipant,
                                              @NonNull LocalAudioTrackPublication localAudioTrackPublication) {

            }

            @Override
            public void onAudioTrackPublicationFailed(@NonNull LocalParticipant localParticipant,
                                                      @NonNull LocalAudioTrack localAudioTrack,
                                                      @NonNull TwilioException twilioException) {

            }

            @Override
            public void onVideoTrackPublished(@NonNull LocalParticipant localParticipant,
                                              @NonNull LocalVideoTrackPublication localVideoTrackPublication) {

            }

            @Override
            public void onVideoTrackPublicationFailed(@NonNull LocalParticipant localParticipant,
                                                      @NonNull LocalVideoTrack localVideoTrack,
                                                      @NonNull TwilioException twilioException) {

            }

            @Override
            public void onDataTrackPublished(@NonNull LocalParticipant localParticipant,
                                             @NonNull LocalDataTrackPublication localDataTrackPublication) {

            }

            @Override
            public void onDataTrackPublicationFailed(@NonNull LocalParticipant localParticipant,
                                                     @NonNull LocalDataTrack localDataTrack,
                                                     @NonNull TwilioException twilioException) {

            }

            @Override
            public void onNetworkQualityLevelChanged(
                    @NonNull LocalParticipant localParticipant,
                    @NonNull NetworkQualityLevel networkQualityLevel) {
                Logger.logE(TAG, "onNetworkQualityLevelChanged");
                Logger.logD(TAG, "Network Quality:-" + networkQualityLevel.name());
            }
        };
    }
```
The problem here is that I am not getting callback of network quality level changed. I am trying to change the network level through switching from mobile data to wifi, in aeroplane mode and switching off the router. Please suggest the required changes to make it working.

**Comment by paynerc** [comment]
@himanshu-my,

The first question I have for you is, are you using P2P or group rooms? The Network Quality API is only supported when connecting to group rooms. You connect options seem correct. If you *are* using group rooms and this still isn't working, can you provide a Room Sid where you seeing this behavior and I can dig deeper into this?

Thank you,

Ryan

**Comment by himanshu-my** [comment]
Hello @paynerc Thanks for the quick response. I am using **group rooms** and still network quality API is not working. `RM473624108c4719af074503c71716e842` this is the room sid in that I have connected in call.

**Comment by paynerc** [comment]
@himanshu-my,

I looked up the information on this particular Room Sid you provided and it shows that it was actually a peer-to-peer room:

```
Summary for Room: <redacted> | RM473624108c4719af074503c71716e842 | <redacted>
Topology: peer-to-peer | Adhoc: True | TURN: True | Recording: False | Video Codecs: None | Media Region: None
```

From what it looks like this room was not created via the [REST API](https://www.twilio.com/docs/video/api/rooms-resource). When creating rooms via just calling the `connect` method, then an adhoc room is created using the `Room Type` value specified in the Programmable Video Default Rooms Settings page in the console (https://www.twilio.com/console/video/configure).

Try logging into the console and navigating to the page listed above and verify that the `Room Type` is set to either `Group` or `Group-Small` and not `Peer-to-peer`.

I believe that that is the issue you are seeing. Let me know if that doesn't resolve the issue.

Thanks!

Ryan

**Comment by himanshu-my** [comment]
Thanks @paynerc We have changed the room type to group now its working fine. Still I have a question whats the difference between group and peer to peer room?

**Comment by paynerc** [comment]
That's great to hear!

Take a look at the [Understanding Video Rooms](https://www.twilio.com/docs/video/tutorials/understanding-video-rooms) documentation on our website.

At a high level, media is shared directly between participants in Peer-to-peer rooms using a mesh network topology. Every participant manages media connections with all other participants and must encode and decode media for all participants. This works well for small numbers of participants, but doesn't scale well on a mobile device for more participants as the mobile devices are limited by the CPU and battery.

Group rooms use a media server in the middle. Each participant maintains one set of media connections to the media server and can be thought of as a star topology. Group rooms then have the benefit of having more capabilities, such as recordings, dominant speaker detection, network quality level computations, etc. These features are unavailable in Peer-to-peer rooms as there is no central node that can perform the required processing.

That is just off the top of my head, but the [documentation](https://www.twilio.com/docs/video) goes into greater details.

Again, I am happy to hear you are now getting Network Quality levels being reported for your local participant. I am currently working on brining remote participant network quality reporting to Android to match what is available on iOS. I am going to close this issue, but feel free to reach out if you have any further questions.

Thanks!

Ryan
