### ISSUE TITLE
SDK not compiling on AGP 3.6.0

### ISSUE THREAD

**Issue by shaunpanjabi** [twilio/video-quickstart-android#479]
### Description
Unable to build with Twilio Video SDK using the latest Android Gradle Plugin 3.6.0.

### Steps to Reproduce

1. Update to AGP 3.6.0, with Twilio Video 5.1.1
2. Try to run project

#### Code

```java
classpath 'com.android.tools.build:gradle:3.6.0'
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip
```

#### Expected Behavior

To actually build

#### Actual Behavior

Throws the following error: 
```
Android resource linking failed
/Users/shaunpanjabi/AndroidStudioProjects/airVet/vet/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:7950: AAPT: error: resource attr/overlaySurface (aka com.myairvet.android.vet.debug:attr/overlaySurface) not found.
```
Which links to:
```
<declare-styleable name="VideoView">
        <attr name="mirror"/>
        <attr name="scaleType"/>
        <attr name="overlaySurface"/>
    </declare-styleable>
```
Which I believe is related to the Twilio Video View in the SDK.

#### Reproduces how Often

100%

#### Logs

see above

### Versions

All relevant version information for issue.

#### Video Android SDK

5.1.1

#### Android API

n/a

#### Android Device

n/a

**Comment by shaunpanjabi** [comment]
I was hoping to upgrade since it is supposed to resolve this issue:
https://github.com/twilio/video-quickstart-android/issues/430

**Comment by aaalaniz** [comment]
Hey @shaunpanjabi 

Thank you for filing the issue. We will take a look and get back to you.

**Comment by aaalaniz** [comment]
Hey @shaunpanjabi 

We have a bug in the SDK where we are missing the format declaration of `overlaySurface`. I have filed a bug and we will submit a patch release soon. However, in the mean time you can add the following to your `attrs.xml` file as a workaround. Apologies for the inconvenience.

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <attr name="overlaySurface" format="boolean" />
</resources>
```

**Comment by shaunpanjabi** [comment]
@aaalaniz thanks! it works now

**Comment by mark-veenstra** [comment]
We also experienced this with the `5.1.0` SDK when updating Gradle in Android Studio. Adding the `attrs.xml` to `android/app/src/main/res/values/` with the content solved the issue for now.

But I think all SDK version with this Gradle update report same error.

![flameshot-2020-02-27-09-09-01](https://user-images.githubusercontent.com/8984015/75424540-219e7300-5941-11ea-8950-831e2830b74a.png)

**Comment by koeks525** [comment]
> 
> 
> Hey @shaunpanjabi
> 
> We have a bug in the SDK where we are missing the format declaration of `overlaySurface`. I have filed a bug and we will submit a patch release soon. However, in the mean time you can add the following to your `attrs.xml` file as a workaround. Apologies for the inconvenience.
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <resources>
>     <attr name="overlaySurface" format="boolean" />
> </resources>
> ```

Thank you so much for sharing this information. I am running into the same issue now. This worked for me.

**Comment by aaalaniz** [comment]
Fixed in `5.1.2`

Thanks for filing @shaunpanjabi !

**Comment by mriaz764** [comment]
My apk size increased 45MB to 89MB after updating to 5.1.2

**Comment by RumsPatel** [comment]
I got the same issue and resolved by using the latest Twillio depencecy.

`implementation "com.twilio:video-android:5.10.1"`

Updated couple of things in `<com.twilio.video.VideoView`

Old:
```
        app:mirror="true"
        app:overlaySurface="true"
```

New:

```
        app:tviMirror="true"
        app:tviOverlaySurface="true"
```

**Comment by carman247** [comment]
> Hey @shaunpanjabi
> 
> We have a bug in the SDK where we are missing the format declaration of `overlaySurface`. I have filed a bug and we will submit a patch release soon. However, in the mean time you can add the following to your `attrs.xml` file as a workaround. Apologies for the inconvenience.
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <resources>
>     <attr name="overlaySurface" format="boolean" />
> </resources>
> ```

I have no idea why adding this attrs.xml file to "android/app/src/main/res/values/" fixed it but it did. Thanks!
