### ISSUE TITLE
Failed to load library libjingle_peerconnection_so.so on a Sony Xperia S

### ISSUE THREAD

**Issue by AgentKnopf** [twilio/video-quickstart-android#48]
I am trying to run a basically (almost) unmodified version of the twilio video quickstart app on the following device:

Sony Xperia LT26i (also called Sony Xperia S)
Android Version 4.1.2
Build Number 6.2.B.1.96

The app successfully authenticates but crashes when trying to create the LocalMedia instance in VideoActivity#createLocalmedia:

`localMedia = LocalMedia.create(this);`

with the following stacktrace:

https://gist.github.com/AgentKnopf/2ac49a76c262466113c5e0c9e25821ec

Local Media is however correctly created (without a crash) on a: 
Google Pixel
Android Version 7.1.1
Build Number NMF260

Are there some constraints regarding the supported devices? Let me know if you need additional information. For reference, here is my minimally modified VideoActivity class:

https://gist.github.com/AgentKnopf/3b27a70a73e0649691cf4a88ef7162da

**Comment by aaalaniz** [comment]
Hi,

This crash appears to be device specific and related to [this issue](https://github.com/KeepSafe/ReLinker/issues/15). We build our native dependencies with NDK r12b, so it could be that this crash would be fixed when we update to the latest NDK. We do plan upgrading soon, but I do not believe there is anything that can be done to resolve this crash with the current version of the library.
