### ISSUE TITLE
TimeoutException

### ISSUE THREAD

**Issue by a1nouru** [twilio/video-quickstart-android#483]
Getting a `java.util.concurrent.TimeoutException` inside `retrieveAccessTokenfromServer`: 

`private void retrieveAccessTokenfromServer() { 

        Ion.with(this)
                .load(String.format("%s?identity=%s", ACCESS_TOKEN_SERVER,
                        UUID.randomUUID().toString()))
                .asString()
                .setCallback((e, token) -> {
                    if (e == null) {
                        VideoActivity.this.accessToken = token;
                    } else {System.out.println("FAILED TO RETRIEVE: " + e);
                        Toast.makeText(VideoActivity.this,
                                R.string.error_retrieving_access_token, Toast.LENGTH_LONG)
                                .show();
                    }
                });
    }`

I've made sure that the `ACCESS_TOKEN_SERVER` is correctly set. Twillio function also works fine as I use it for the iOS client which works just fine. 

What could be the issue

**Comment by aaalaniz** [comment]
hey @a1nouru 

Are you still experiencing this issue? If you post a log we can have a look.

Also, I'd encourage you to check out our new open source [Video Android App](https://github.com/twilio/twilio-video-app-android). The on-boarding experience is much quicker and you can check out Programmable Video with a more fully featured app.

Thanks!

**Comment by aaalaniz** [comment]
I will close this issue due to inactivity. Please reopen if you have further questions.

Thanks you!
