### ISSUE TITLE
Crash affter connected - Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 21138 (Thread-4), pid 20840 (ickstart.kotlin)

### ISSUE THREAD

**Issue by TieuNhi95** [twilio/video-quickstart-android#484]
note: this happened in only 1 device: google pixel - android 10 

i run twilio base video-quickstart-android, in my project (also sample : quickStartKotlin or quickStart), app always crash after room connected, although I deleted all implemented of Room.Listener and replace by Timber Log.

**Comment by aaalaniz** [comment]
Hey @TieuNhi95 

Please fill out the issue template as best you can and our team will investigate.

Thank you!
