### ISSUE TITLE
Can we Capture 5sec video parallely while video rendering in twilio android video sdk

### ISSUE THREAD

**Issue by GauravAndroidIS** [twilio/video-quickstart-android#488]
I want to create a scenario where while video rendering I can fetch a 5 sec video from the rendering and pass it to my system ?

**Comment by aaalaniz** [comment]
Hey @GauravAndroidIS 

This might be possible, but I would need more details to confirm. I would suggest you start with our custom [video rendering example](https://github.com/twilio/video-quickstart-android/tree/master/exampleCustomVideoRenderer).

Thanks!
