### ISSUE TITLE
No audio voice hearing when app running in Background after 30 to 45 seconds

### ISSUE THREAD

**Issue by mriaz764** [twilio/video-quickstart-android#495]
This is working fine when app running in foreground, but it does not work when the app is running in the background (either locked or just with the app in the background). From both ends of the line, nothing can be heard. Any thoughts?

**Comment by aaalaniz** [comment]
Hey @mriaz764 

I suggest you reference our recently open source [Video Android Collaboration App](https://github.com/twilio/twilio-video-app-android). In this project, we demonstrate a fully featured collaboration experience. Namely, the application demonstrates how to manage the lifecycle of a `Room` using an [Android Foreground Service](https://github.com/twilio/twilio-video-app-android/blob/master/app/src/main/java/com/twilio/video/app/ui/room/VideoService.kt). Managing the Room with a Service ensures that the user continues to share and receive media when entering the background for extended periods of time.

I hope this helps. I will close this issue for now, but feel free to ask additional questions here or in a separate issue on the Quickstart or the collaboration app project.

Thanks!
