### ISSUE TITLE
Video freezes when remoteParticipant disables the video.

### ISSUE THREAD

**Issue by TeniG** [twilio/video-quickstart-android#496]
I have implemented the code by taking reference of quikstartkotlin project. In my project one participant connect using android application and other participant connect using browser.

Here is the scenario. From Android application Participant A connects and from Browser Participant B connect the Room.(Peer to Peer).

When remote participant disables the video below are the methods called.
1)onVideoTrackUnsubscribed 
2)onVideoTrackUnpublished

Below is the pseudo code

 override fun **onVideoTrackUnsubscribed**(remoteParticipant: RemoteParticipant, remoteVideoTrackPublication: RemoteVideoTrackPublication, remoteVideoTrack: RemoteVideoTrack) {
            Log.d(TAG, "onVideoTrackUnsubscribed: " + "[RemoteParticipant: identity=${remoteParticipant.identity}], " + "[RemoteVideoTrack: enabled=${remoteVideoTrack.isEnabled}, " + "name=${remoteVideoTrack.name}]")
           videoStatusTextView.text = "onVideoTrackUnsubscribed"
            removeParticipantVideo(remoteVideoTrack)
        }

   override fun **onVideoTrackUnpublished**(remoteParticipant: RemoteParticipant, remoteVideoTrackPublication: RemoteVideoTrackPublication) {
            Log.d(TAG, "onVideoTrackUnpublished: " + "[RemoteParticipant: identity=${remoteParticipant.identity}], " + "[RemoteVideoTrackPublication: sid=${remoteVideoTrackPublication.trackSid}, " + "enabled=${remoteVideoTrackPublication.isTrackEnabled}, " + "subscribed=${remoteVideoTrackPublication.isTrackSubscribed}, " + "name=${remoteVideoTrackPublication.trackName}]")
 videoStatusTextView.text = "onVideoTrackUnpublished"
           
       }

private fun **removeParticipantVideo**(videoTrack: VideoTrack) {
     videoTrack.removeRenderer(primaryVideoView)
}

**videoTrack.removeRenderer(primaryVideoView) -> I think this line of code makes the screen freeze but I want the black screen to be appear on the screen.**

Please can you help me how to display black screen instead of screen freeze.Suggest me any alertnative solution for the same.

**Comment by aaalaniz** [comment]
Hey @TeniG 

What you are describing is definitely possible and understandable from a UX perspective. However, these quickstarts are limited in UX functionality to reduce code complexity. I suggest you checkout our [recently open source Video Apps](https://www.twilio.com/blog/open-source-video-apps-reactjs-ios-android). Specifically, I recommend the [Video Android App](https://github.com/twilio/twilio-video-app-android)'s [renderAsPrimary logic](https://github.com/twilio/twilio-video-app-android/blob/5dff90937d149d5229c93d68b06b46af0b2d43a6/app/src/main/java/com/twilio/video/app/ui/room/ParticipantController.java#L302). Here you will find that when a video track is unsubscribed from the application will update the UI with a placeholder avatar.

I hope you find this helpful. I will close this issue, but please feel free to ask additional questions in this issue or a new issue either here or in the Video Android App repo.

Thanks!

**Comment by TeniG** [comment]
Your reference was helpful and I was able to solve the problem. 
Thank you for the help and support.
