### ISSUE TITLE
How to force to change video constraints for some frames?

### ISSUE THREAD

**Issue by teomel** [twilio/video-quickstart-android#499]
I need to get some frames of the localVideoTrack at a better resolution to take a snapshot of the video, even if that could result in lag. Is there any method to do so?

**Comment by ceggert87** [comment]
You can update the camera parameters' pictureSize with your desired resolution - the takePicture functionality of Twilio should consider that and not use the current video resolution.

**Comment by aaalaniz** [comment]
Hey @teomel 

I suggest you reference our [Advanced Camera Capturer](https://github.com/twilio/video-quickstart-android/tree/master/exampleAdvancedCameraCapturer) example which demonstrates how to take a picture with CameraCapturer.

Thanks!

PS. Thanks for the suggestions too @ceggert87! ...The part about `updateCameraParameters` followed by `takePicture` I had not considered as an option. That's a good idea if you would like to change the resolution before taking a picture. 👍
