### ISSUE TITLE
Huawei H264 Hardware Encoding/Decoding

### ISSUE THREAD

**Issue by ceggert87** [twilio/video-quickstart-android#500]
Hello Twilio team,

this issue is strongly related to this resolved ticket: https://github.com/twilio/video-quickstart-android/issues/465

Specifically, when using Huawei devices with HiSilicon processors with H264, Twilio refuses to use Hardware encoding and decoding. The background is that WebRTC does not officially support them, so OMX.hisi is not part of any accepted device prefix. 

Using the same approach as with the ticket above, I was able to get the encoding working. However, in contrast to Intel, OMX.hisi is also not part of WebRTC's decoding part. I did not find any possible reflection anchor point in the decoding process to add a support for this, however, as everything has hardcoded strings and uses methods from what I can see.

WebRTC has changed this logic for a long time: the current versions do not have these hardcoded string limitations anymore, but rather a blacklist. So it would probably not be an issue with more modern WebRTC libraries. Are there any plans to update this and if not, is there any chance to have other changes so that it could at least be achieved via reflections or something similar? 

Thank you!

**Comment by aaalaniz** [comment]
Hey @ceggert87 

Thank you for filing the issue. Let me address your questions.

>WebRTC has changed this logic for a long time: the current versions do not have these hardcoded string limitations anymore, but rather a blacklist. 

We are in the process of upgrading WebRTC, so as you correctly pointed out, these hardcoded limitations should not be a problem after we ship an SDK release with an upgraded WebRTC.

>Using the same approach as with the ticket above, I was able to get the encoding working. However, in contrast to Intel, OMX.hisi is also not part of WebRTC's decoding part. I did not find any possible reflection anchor point in the decoding process to add a support for this, however, as everything has hardcoded strings and uses methods from what I can see.

I can take a crack at this and get back to you.

Thanks!

**Comment by aaalaniz** [comment]
This issue should be resolved in 6.0.0 which includes the upgrade to Webrtc 83.


Thank you!
