### ISSUE TITLE
Multi Participant Video Call

### ISSUE THREAD

**Issue by jd-gupta27** [twilio/video-quickstart-android#502]
Hi, 
I am using QuickStart project and it is working fine for one to one but i want more than 2 participant

**Comment by aaalaniz** [comment]
Hey @jd-gupta27 

We recently removed [the multi-party quickstart example](#491 ) in favor of our recently open source [Video Android Collaboration App](https://github.com/twilio/twilio-video-app-android). I recommend you reference that project for any multi-party video needs.

Thanks!

**Comment by Sunilnlahane** [comment]
Video Android Collaboration App code is built in kotlin, can you provide java based android code

**Comment by aaalaniz** [comment]
Hey @Sunilnlahane 

We do not have plans to implement a Java based collaboration application at this time.

Thank you
