### ISSUE TITLE
audio and video preview  is not working on AndroidX

### ISSUE THREAD

**Issue by mukeshocpc** [twilio/video-quickstart-android#509]
**audioDeviceSelector.activate();** is crashing there is no audio rendered when participants  joins the room  below is the sample code were **AndroidX** is used. 
Any help will be appreciated. 
Detail of a device were its crashes :
![1589177816060](https://user-images.githubusercontent.com/30304398/81828900-ef6fdb00-9557-11ea-8169-e2abc9cf4813.JPEG)

          minSdkVersion 21
          targetSdkVersion 29
          versionCode 1
          versionName "1.0"

           'videoAndroid'       : '5.6.0',
            'audioSwitch'        : '0.1.0'

https://github.com/mukeshocpc/TwillioSample

**Comment by aaalaniz** [comment]
Hey @mukeshocpc 

I believe @Alton09 answered your question [here](https://github.com/twilio/audioswitch/issues/17). Thank you for filing the issue, but I will close!
