### ISSUE TITLE
Voice of call is quite

### ISSUE THREAD

**Issue by matdennoigi** [twilio/video-quickstart-android#51]
Hi guys,

I use "quickstart" code for my app, but in call, the voice is quite

**Comment by FranziscaZarrai** [comment]
@matdennoigi It works fine with all the devices I tried it on. Are you sure your devices are not muted or are you using an emulator?

**Comment by aaalaniz** [comment]
@matdennoigi Can you provide device information and are you using headset or speaker audio?

**Comment by aaalaniz** [comment]
No response has been provided. Closing

**Comment by matdennoigi** [comment]
I'm so sorry for my late. I fixed it by set speaker on, but if 2 devices near together it make noise (feedback loop)

**Comment by aaalaniz** [comment]
@matdennoigi glad you were able to resolve the volume issue. Echo cancellation is known to not work well when two devices are sitting side-by-side. Please open an issue if you are experiencing echo between devices that are not side-by-side.

Thanks

**Comment by matdennoigi** [comment]
@FranziscaZarrai It's only appear when two devices are sitting side-by-side. Many thanks
