### ISSUE TITLE
Lag in stream on high resolution

### ISSUE THREAD

**Issue by HaiderSaleem** [twilio/video-quickstart-android#511]
I have been working on a project in which we using Twilio View Capturer Class to stream our custom view from one user to another.
A few days ago, i had to use Samsung Galaxy Note 9 in which we had option to choose display resolution, As you can see.

![device-2020-05-13-234513](https://user-images.githubusercontent.com/28349518/81852341-4d122080-9574-11ea-9a3d-c88c0bc57805.png)

While setting highest and mid resolution, we are facing a lot of lag on other side but its working fine with lower resolution.

The setting we are using to initiate video call are as below:

```
        const val PREF_VIDEO_CODEC_DEFAULT = H264Codec.NAME
        const val PREF_SENDER_MAX_AUDIO_BITRATE = "sender_max_audio_bitrate"
        const val PREF_SENDER_MAX_AUDIO_BITRATE_DEFAULT = "16"
        const val PREF_SENDER_MAX_VIDEO_BITRATE = "sender_max_video_bitrate"
        const val PREF_SENDER_MAX_VIDEO_BITRATE_DEFAULT = "0"

        val videoConstraints = VideoConstraints.Builder()
                .maxFps(24)
                .maxVideoDimensions(VideoDimensions.HD_540P_VIDEO_DIMENSIONS)
                .build()
```
We are using Small group on Twilio server side with max users set to 2 and latency set to gll.

What can be the possible solution to fix it out at earliest as we are in production phase.

Device specs:
Samsung Galaxy Note 9
Android 10

**Comment by aaalaniz** [comment]
Hey @HaiderSaleem 

Can you provide a Room SID where you are observing the latency? You can grab a room sid from the `Room` object by calling `getSid`.

Thanks!

**Comment by HaiderSaleem** [comment]
> Hey @HaiderSaleem
> 
> Can you provide a Room SID where you are observing the latency? You can grab a room sid from the `Room` object by calling `getSid`.
> 
> Thanks!

Here's SID

> RMde1d9ade18dc47ad0d12c0eaf4bc8bf0

**Comment by aaalaniz** [comment]
Hey @HaiderSaleem 

Thanks for providing this Room SID. I did some investigating and I have thoughts and suggestions.

1. Your app appears to capture some sort of view at a potentially high resolution depending on the user selection. Have you tried lowering the maxFps in `VideoConstraints` to something like 15 or even 5? In general, if you are capturing a screen you do not need the high frame rate required for live video from a camera. Additionally, does your custom capturer return `true` for the `isScreencast` method that is part of the `VideoCapturer` API?
2. I also noticed that the resolved media region for this room is `de1` (Germany), but both of the participants appear to be closer to `in1` (India). Can you try explicitly setting the media region to `in1` to see if that improves your latency? You can learn more about signaling and media regions in this [Video Developer Guide](https://www.twilio.com/docs/video/tutorials/video-regions-and-global-low-latency).

**Comment by HaiderSaleem** [comment]
Thank you for respinse, i'll look into it and get back to you soon.
However, i had set room to small group with max 2 participants and latency to gll, so now its working well.

**Comment by aaalaniz** [comment]
Hey @HaiderSaleem 

Thanks for response. I will close this issue for now. Please reopen if you encounter any more latency issues.

Thanks!
