### ISSUE TITLE
Some Android Devices Not supported H264, VP8,VP9 VideoCodecs. Participant video not appearing.

### ISSUE THREAD

**Issue by amandian14** [twilio/video-quickstart-android#516]
Twillio only supported two video codecs:
1. H264
2. VP8
But my android device hardware not supported H264 and VP8 video codec.
And it not working properly on my phone. its not showing other remote participants videos on my screen after room join.
I have checked in two Android Device : RealMe C2 & Vivo phone.
It should support all video codecs so that it can work in all android phones.

Can anyone help me what should i do if my phone not supported both video codecs?
Thanks in advance.
I m looking forward for your suggestions or help.

**Comment by aaalaniz** [comment]
Hey @amandian14 

Thanks for writing in. I can provide some clarification about our codec support. You are correct that Group or Small Group Rooms only support VP8 and H.264. However, with respect to Android codec support the statements below should summarize:

1. H.264 is only supported on Android devices with hardware support. Our SDK does not provide a software implementation of H.264.
2. **VP8 is supported on every Android device**. However, some devices do support hardware accelerated VP8. The SDK will default to using hardware implementations of VP8 if they are available and fallback to a software implementation of VP8 if they are not.

If participant's are not being rendered then your settings may be configured in such a way that results in an unsupported codec error. I highly recommend reading through our [Managing Codecs guide](https://www.twilio.com/docs/video/managing-codecs) for guidance. Additionally, can you provide a Room SID so our team can investigate.

Thanks!

**Comment by aaalaniz** [comment]
Hey @amandian14 

I will close this issue for now. Please reopen if you need any more assistance with respect to Video Codec guidance.

Thanks!
