### ISSUE TITLE
in AndroidX participants don't see or hear each other

### ISSUE THREAD

**Issue by amirocpc** [twilio/video-quickstart-android#518]
### Description

We have created the AndroidX version of this sample code but unfortunately although everything seems to be fine, when participants enter a room they can't hear or see each other. Can you please review this code and advise? what are we missing?
https://github.com/mukeshocpc/TwillioSample

### Expected Behavior

When 2 people are in the same room, they should see each other and hear each other and when one participant leaves the room the room will get terminated.

### Actual Behavior

When 2 people are in the room, you still just see yourself, you don't see or hear the other person.

### Reproduces how Often

Everytime.

### Device & Versions Info

Galaxy Note8
Model #: SM-N950U
Android Version: 7.1.1

minSdkVersion 21
targetSdkVersion 29
versionCode 1
versionName "1.0"

'videoAndroid' : '5.6.0',
'audioSwitch' : '0.1.0'

**Comment by amirocpc** [comment]
How can we get expedited help on this? We have spent almost 1 month on this and now it’s not working at all :) it’s delaying the release date of our apps. It’s probably something minor that u can point out after reviewing.

**Comment by aaalaniz** [comment]
Hey @amirocpc 

I cloned your sample project and I was able to connect to a room from two separate devices and hear and see each participant. Can you provide a log file or potentially a room Sid so we can investigate further thanks!
