### ISSUE TITLE
Android System: A call is in progress, sticky notification.

### ISSUE THREAD

**Issue by vinayappypiellp** [twilio/video-quickstart-android#519]
While implemeting video sdk in a demo project,
in some devices, sticky notification get visible, showing

 *Android System: 
A call is in progress. You can only just call...*

and the notification does get removed, even after removing the app from stack.

**Comment by aaalaniz** [comment]
Hey @vinayappypiellp 

This ticket does not contain enough information to investigate. Please provide more details as per the provided issue template and reproduction steps in either the Quickstart itself, the [Video Collaboration App](https://github.com/twilio/twilio-video-app-android), or a separate sample project.

Thank you!

**Comment by blinkev** [comment]
Same for my project. I successfully adapted demo to my project but noticed sometimes this notification is showing while twillio Fragment is in the background.
