### ISSUE TITLE
Listing of available audio input devices AKA microphone/s

### ISSUE THREAD

**Issue by vismay11** [twilio/video-quickstart-android#528]
Description
Currently, there is no option to select the available audio input device/s (microphone/s). Suppose I have earphones connected to the device whose microphone is not working properly or is not working at all then I should be able to select the default inbuild microphone to have a smooth calling experience.

**Comment by Alton09** [comment]
Hi @vismay11 . Thank you for reaching out and sorry for the late response. Please take a look at the [AudioSwitch](https://github.com/twilio/audioswitch) library. It allows users to easily switch between all of the connected audio devices on an Android device. Hope that helps!

**Comment by Alton09** [comment]
Closing this issue for now. Please open another as needed. Thanks!
