### ISSUE TITLE
Please help me I am trying to create a video conference app using Twilio but I am facing problems now

### ISSUE THREAD

**Issue by ujwalrajeev** [twilio/video-quickstart-android#529]
Please help me I am trying to create a video conference app using Twilio but I am facing problems now 

final VideoGrant grant = new VideoGrant();
grant.setRoom(groupName);

Here setRoom cannot be resolved and also

final String jwt = token.toJWT();

toJWT cannot be resolved

I have imported these,
import com.twilio.jwt.accesstoken.AccessToken;
import com.twilio.jwt.accesstoken.VideoGrant;

and gradle includes these,
implementation 'com.twilio:video-android:5.8.0'
implementation 'com.twilio.sdk:twilio-java-sdk:6.3.0'
implementation 'com.twilio.sdk:twilio:7.0.0'

Please help. @aaalaniz @alexdlaird @kolencherry @cjcodes

**Comment by Preetinegi11** [comment]
Did  you get any solution?

**Comment by aaalaniz** [comment]
Hey @ujwalrajeev @Preetinegi11 

I see that your project is using the Twilio Java Helper library. Please note that the Twilio Java Helper library is intended to be used in server side applications. The helper libraries require access to your Twilio credentials and should not be used in any client side video application.

If you are new to Twilio Video and are specifically looking for help getting started then I highly recommend checking out our [Video Collaboration App](https://github.com/twilio/twilio-video-app-android). For any other general Twilio questions, please file a [support ticket](https://support.twilio.com/hc/en-us).

Thank you!
