### ISSUE TITLE
How to get webRtcVideoFrame value from VideoFrame class?

### ISSUE THREAD

**Issue by john-lq** [twilio/video-quickstart-android#531]
Hello Twilio Team

I am using `CameraCapturer` to start the camera in Android. And using the `VideoCapturer.Listener` to catch a frame(`onFrameCaptured(VideoFrame videoFrame)`).

The question is how to get `webRtcVideoFrame` raw data from `VideoFrame` class? Or Is there another way to do that? 

Thanks,
John

**Comment by aaalaniz** [comment]
Hey @john-lq 

This field is intentionally left private and is currently not available through any public APIs. You could access this field via reflection if you absolutely need to. What are you trying to achieve by accessing the WebRTC frame directly?

Thanks!

**Comment by john-lq** [comment]
Hello @aaalaniz ,

Thank you so much for you replying. I am using this way to get the WebRTC frame. 
I want to catch the frame to do some logics. For example: selfie feature.

Are there any plans to public it in the future? 

Thanks,
John

**Comment by aaalaniz** [comment]
Hey @john-lq 

At this time, this feature is not on our roadmap. I will close this issue. However, feel free to ask any questions about accessing the WebRTC frame via reflection. Apologies for the inconvenience.

Thanks!
