### ISSUE TITLE
Audio becomes mono during Twilio call on Android 9.0

### ISSUE THREAD

**Issue by umarniz** [twilio/video-quickstart-android#533]
### Description

If you play a looping stereo sound and start a Twilio call, the stereo sound becomes mono till you end the call.

This happens also if you play a sound specified to be stereo in the middle of a call. 

The Twilio internal SDK when connected to a room, causes all playing audio to be mono.

This same issue also exists in Twilio iOS: https://github.com/twilio/twilio-video-ios/issues/77

### Steps to Reproduce

I have made a fork to showcase this problem with the latest Android SDK + ExoPlayer as well:
https://github.com/umarniz/video-quickstart-android/pull/1

Steps to reproduce in the repo:

- Build and start the app (You should hear a looping stereo sound play as soon as the app starts)
- Start a Twilio call (The looping sound should become mono)
- Stop the Twilio call (The looping sound should become stereo again)

#### Code

https://github.com/umarniz/video-quickstart-android/pull/1

#### Expected Behavior

I would expect the stereo sound to remain stereo and the mono playback from Twilio to mix with it.

#### Actual Behavior

The sound becomes mono

#### Reproduces how Often

Always

#### Video Android SDK

`5.8.1`

#### Android API

Tested on `API 28`

#### Android Device

Tested on `Huawei Y6 2019`

**Comment by umarniz** [comment]
**Update**: Just tested on an Android 5.x device and this behaviour is not reproducible.

Most probably a bug in Android 5.x+ devices.

**Comment by umarniz** [comment]
This issue is rooting from Twilio audioswitch library: https://github.com/twilio/audioswitch

The issue comes from the best practice in Android O+ when calling `requestFocus` and passing `USAGE_VOICE_COMMUNICATION`: https://github.com/twilio/audioswitch/blob/master/audioswitch/src/main/java/com/twilio/audioswitch/selection/AudioFocusRequestWrapper.kt#L13

This in turn causes all OS Audio to be mono.

Not calling `setUsage(AudioAttributes.USAGE_VOICE_COMMUNICATION)` in the `AudioAttributes` passed to `AudioFocusRequest.Builder` fixes the problem.

**Comment by CristianoWinter10** [comment]
Hi @urniz,  were you able to fix the problem or get around this?

We are having this issue, our app rings a ringtone before trying the call, then the app shows a camera view when we connect the customer, then if the call is answered, we stop ringing to start the call. The problem is that when we show the camera preview, the ringtone is muted in some cases, or it is too low. We already tried to request audio focus, but it didn't work, we also tried to change Usage mode in Audio Manager.

**Comment by umarniz** [comment]
@CristianoWinter10 the issue we were facing was different as it involved playing stereo audio during the call.

The issue you are mentioning is most likely coming from the audio device management when the call is initialised. Android has quite a fragmented way of handling the Audio Manager when starting up a call depending on the OS version (i.e Android 6 to Android 12) and the output device (i.e Bluetooth/WiredHeadset/etc)

I would say to use the [Audio Switch](https://github.com/twilio/audioswitch/) library for managing the Audio device should help as it takes over significant complexity of setting up the correct audio device before a call starts.

**Comment by CristianoWinter10** [comment]
Hi @umarniz, thank you for you answer.

We were able to fix that using this config WebRtcAudioTrack.setAudioTrackUsageAttribute(AudioAttributes.USAGE_NOTIFICATION_RINGTONE)

Using that the notification sound keeps the same even when the Video is connected.
