### ISSUE TITLE
How to Connect to Twilio Video Rooms without Twilio SDK?

### ISSUE THREAD

**Issue by mail2chromium** [twilio/video-quickstart-android#535]
Please note, I am already aware of this fact that:

> The SDK is there to take the majority of development off your hands and allow you to get on with building your application 

But perhaps there are specific requirements that the SDK doesn't provide me, So that's why I have been looking forward to this solution from the past 6 months. I want to confirm these following things:

With Twilio Video SDK:
-----

- Is there any privilege that I can record from MicroPhone by using my own method/recording CallBack? 
- Is there any method/Point where I can push those **Custom AudioBytes** to Twilio Rooms for other participants?
- Is there any privilege that I can get bytes from the receiving side and perform any actions before playing?
- Is there any privilege that I can play this method by using my own method?

Without Twilio Video SDK:
-----

What are the alternatives to connect to Twilio Video SDK Rooms to use its services?

I have purchased Twilio Account and I have been using Twilio for the last 1 year for Audio Communications using Twilio NTS Service. I am using WebRtc interface to make communication possible. In that way, I have complete access to Audio **Pre-Processing(near-end)** and **Post-Processing(far-end)**. But I am interested to do that for **more than 2 participants** and if I go with Twilio SDK, then this can't be possible as 

> "The Video Android SDK uses a default audio device that captures audio frames from the microphone" 

 Please assist me in this matter. As I have my own _use cases_ which Twilio SDK doesn't allow.

**Comment by aaalaniz** [comment]
Hey @mail2chromium 

I can address some of these questions.

>Is there any privilege that I can record from MicroPhone by using my own method/recording CallBack?

At this time, the Video Android SDK does not allow Custom AudioDevices like the Voice SDK or the Video iOS SDK. This feature enables developers to provide their own audio facilities for recording or playing back audio when connected to a Room. We do plan on implementing this feature but do not have a timeline.

> Is there any method/Point where I can push those Custom AudioBytes to Twilio Rooms for other participants?

Same answer as first question. Custom audio bytes would be covered with the Custom Audio Device feature.

> Is there any privilege that I can get bytes from the receiving side and perform any actions before playing?

Yes. You can get access to a RemoteAudioTrack's bytes using our `AudioSink` feature. I recommend referencing our [AudioSink example](https://github.com/twilio/video-quickstart-android/tree/master/exa…)!

> Is there any privilege that I can play this method by using my own method?

I am not sure I understand this question. Can you provide more specifics? Thanks!

> What are the alternatives to connect to Twilio Video SDK Rooms to use its services?

At this time the Javascript/iOS/Android SDKs are the only supported way of leveraging the Programmable Video platform.

**Comment by mail2chromium** [comment]
**Mistake**:
> Is there any privilege that I can play this method by using my own method?

**Updated**:
> Is there any privilege that I can play received bytes by using my own method?

@aaalaniz Thanks for your consideration. I must suggest that your team should have to look into the above modifications. Why?

The main reason is that most of your clients would be _Software Companies_. Those Software Companies who basically developing their own _VoIP application_, won't be restricted to Twilio's SDK. I know that

> The SDK is there to take the majority of development off your hands and allow you to get on with building your application

But they will **only use your services** related to **_Twilio Voice Rooms / Video Rooms_**. During their development process, they may be more focused to record and play their own custom bytes rather than using Native Audio Frames as my company needed. 

I appreciate your work and I hope Twilio will focus on the above-mentioned scenarios and challenges.

**Comment by aaalaniz** [comment]
Hey @mail2chromium 

We appreciate your feedback. I believe your use cases would be partially supported by the [Custom Audio Device feature](https://github.com/twilio/video-quickstart-android/issues/353). I recommend following that issue for any updates related to Custom Audio Device.

As for using Programmable Video without our SDKs, this is not something on our roadmap.

I will close this issue for now.

Thanks!
