### ISSUE TITLE
Incoming Call when App killed (Android). 

### ISSUE THREAD

**Issue by ammarubaid** [twilio/video-quickstart-android#537]
Is it possible to get incoming call when android application is killed?
I am receiving Access Token & room name from Firebase Notification even when app is in background or killed but not able to start Android Call screen.

**Comment by aaalaniz** [comment]
Hey @ammarubaid 

Yes this is possible. I recommend referencing our [Video Invite example](https://github.com/twilio/video-quickstart-android/tree/master/exampleVideoInvite) for this type of solution. The example shows how to use Twilio Notify to receive a push notification when a participant joins a room. You should receive the push notification even if the app was backgrounded or ended.

I will close this issue for now. Please reopen if you have any additional questions.

Thanks!
