### ISSUE TITLE
apk size isssue

### ISSUE THREAD

**Issue by SzotsLevente** [twilio/video-quickstart-android#538]
I'm experiencing an increase from 7.5mb apk to 65mb after adding the lib
i've tried adding that splits to it but didn't do much, i'm curios if there is any other way to reduce the size, or that's it with splits and i've did it wrong?

**Comment by aaalaniz** [comment]
Hey @SzotsLevente 

This size increase does seem larger than our [latest documented universal size impact](https://www.twilio.com/docs/video/changelog-twilio-video-android) of ~22 MB. How are you measuring the size? Apk splits should definitely help with the size, but I think the recommended way of reducing size is to enable [Android App bundles](https://developer.android.com/guide/app-bundle).

Thanks!

**Comment by SzotsLevente** [comment]
Hey @aaalaniz I've verified the apk with the Analizer from Android Studio, the download size indeed increased with 22MB+ but overall is more than 9x incrase on the apk, tried using App bundles, but gotta dig more into it cuz i've ended up with an aab file half of the size of the apk but the final installed file was 42MB+.

**Comment by aaalaniz** [comment]
Hey @SzotsLevente 

Do you mind sharing some of your `apkanalyzer` commands you are using to measure the size? I am investigating our internal tool we use to measure the library size and seeing if we should update it to provide more details about the size impact.

Thanks!

**Comment by SzotsLevente** [comment]
Hey @aaalaniz i didn't use any special commands, just checked with Android Studio by using Build -> Analyze APK, is there any specific command that i should use to be able to provide more information?

**Comment by aaalaniz** [comment]
Hey @SzotsLevente 

We recently open sourced [Apkscale](https://github.com/twilio/apkscale). This is the tool we use to check the Video Android SDK size. It appears that the `apkanalyzier diff` operation we use only measures the download size.

I am closing this issue for now. If you have any additional questions or comments, I suggest you open an issue on Apkscale, so we can discuss. Adding disk size does seem like a great feature request for Apkscale.

Thanks!
