### ISSUE TITLE
Suggestion: sample showing receiving an in-app Twilio video call

### ISSUE THREAD

**Issue by robertlagrant** [twilio/video-quickstart-android#540]
### Description

Implementing a chat room that people join with a code is well explained, both in the Twilio documentation and in the code samples. 

However, is it possible to have a new sample that shows using Twilio video / VoIP / push notifications as a custom incoming call? I.e. a canonical implementation of https://developer.android.com/guide/topics/connectivity/telecom/selfManaged#common-scenarios.

**Comment by aaalaniz** [comment]
Hey @robertlagrant 

I recommend referencing our [Video Invite Example](https://github.com/twilio/video-quickstart-android/tree/master/exampleVideoInvite). The example demonstrates how to use Twilio Notify to receive a push notification when a user joins a room. It's not exactly a "calling" example, but it does provide a starting point.

Thanks!
