### ISSUE TITLE
Quickstart app microphone issue in Pixel devices

### ISSUE THREAD

**Issue by aparajita-sinha** [twilio/video-quickstart-android#541]
### Description

I have installed the video-quickstart-android app in my Pixel device. When I speak from my Pixel device, my audio is not heard by the remote participant in another device.

### Steps to Reproduce

1. Install the video-quickstart-android app in a Pixel device.
2. Install the video-quickstart-android in another Android device.
3. Join a Twilio room and speak from the Pixel device. Audio cannot be heard by the remote participant.
4. Bluetooth or wired headset also does not work.

#### Expected Behavior

Audio should be heard by the remote participants from Pixel device

#### Actual Behavior

Audio cannot be heard from the Pixel device by remote participants.

#### Reproduces how Often

100%

### Versions

All relevant version information for issue.

#### Video Android SDK

5.8.1

#### Android API

23

#### Android Device

Pixel Phone 3

**Comment by Alton09** [comment]
Hi @aparajita-sinha . Thanks for reporting this issue. I just followed your steps above and audio input/output appears to be working fine for all audio devices when testing on a Pixel XL and Pixel 3. I also ran this test on the quickstart and auickstartKotlin modules. Are you running into this issue with both modules? Also, are you sure you are successfully connecting to a video room? You should see the remote participant's video feed in the main view and the local participant's in the video thumbnail in the lower left hand corner. You should also see the name of the video room in the toolbar. Here's a screenshot of what it should look like:

![Screenshot_20200708-112000](https://user-images.githubusercontent.com/2661383/86950201-1c321000-c10d-11ea-81db-85339407e272.png)

**Comment by aparajita-sinha** [comment]
Hi @Alton09 
I have used only the quickstart app. 
Both participants had successfully connected to the room. The video was clearly visible to each other. It's just that microphone does not work in Pixel 3.  All permissions have been allowed.

**Comment by Balasnest** [comment]
@aparajita-sinha 
1. Are you facing on the latest SDK version 5.8.1? 
2. Was it working earlier? 
3. Just to confirm, is google voice service working?

**Comment by aparajita-sinha** [comment]
@Balasnest 
1. Yes using the latest SDK version 5.8.1
2. No, it never worked.
3. Yes, it is working. When I installed the twilio-video-collaboration-app then it worked fine.

**Comment by Alton09** [comment]
Hi @aparajita-sinha . Just as a sanity check, is the volume level turned up on the receiving device? Also, do you mind sharing a logcat file for the Pixel 3 device when performing these steps? This will help us further troubleshoot. Thank you!

**Comment by aparajita-sinha** [comment]
Hi @Alton09 

Yes, the volume for the receiving device was turned up.
I currently do not have client-side logging enabled.
Do I need to make any code changes specific for Pixel devices?

**Comment by Alton09** [comment]
Thank you for checking @aparajita-sinha . No specific code changes are needed for Pixel devices. Are you able to temporarily enable logging? Otherwise it will be difficult for us to troubleshoot. Thanks!

**Comment by aparajita-sinha** [comment]
Hi @Alton09 did you check in Pixel with Android 9 and above?

**Comment by aaalaniz** [comment]
Hey @aparajita-sinha 

I am closing this issue. I suspect this could have been an issue with AudioSwitch. Please open a new issue if you have any additional concrete steps to reproduce.

Thanks!
