### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by paynerc** [twilio/video-quickstart-android#543]
Ahoy!

Google has now released [Android 11 Beta 2](https://android-developers.googleblog.com/2020/07/android-11-beta-2-and-platform-stability.html), their [Platform Stability](https://developer.android.com/preview/overview#platform_stability) milestone. To ensure that your application is ready for Android 11 we are providing the following guidance and plan to update this page as we make progress on these milestones.

The table below provides a summary and estimated timeline of the work required to ensure that applications using the Video SDK are compatible with Android 11.

Milestone | Timeline | Developer Actions
-- | -- | --
Android 11 Beta 2 | July 8th, 2020 |  
Validate SDK compatibility with apps running on Android 11 but do not target Android 11. Specifically, ensure that SDKs and apps comply with [behavior changes to all apps](https://developer.android.com/preview/behavior-changes-all). | Early August | Monitor this page for SDK and app releases compatible with Android 11.Validate your applications with SDK releases compatible with Android 11 to check our work. Please note that these SDK releases are not guaranteed to work on apps that already target Android 11.(Optional) For apps not targeting Android 11, developers can publish a new version of their application with an SDK release compatible with Android 11
Android 11 Beta 3 | August |  
Validate SDK compatibility with apps that target Android 11. Specifically, ensure that SDKs and apps comply with [behavior changes to apps targeting Android 11](https://developer.android.com/preview/behavior-changes-11). | Early September | Monitor this page for SDK releases which target Android 11.Validate your applications with SDK releases which target Android 11. Please note that these releases should work in apps that target Android 11 or a lower API Level.
Provide final Android 11 compatible SDK and app releases. | End of September | Upgrade your applications to use the final Android 11 compatible SDK release.
Android 11 Final Release | Q3 |  

Our team will provide updates on this page as our work progresses. If you encounter any Android 11 compatibility issues with our SDKs or applications, please post a comment or file a separate issue and our team will investigate.

Thanks!

**Comment by paynerc** [comment]
Video Android SDK 5.x has been validated against Android 11. We have not found any compatibility issues. Please let us know if you encounter any issues while using the SDK on Android 11.

**Comment by kbagchiGWC** [comment]
The Video Android SDK `compileSDKVersion` and `targetSDKVersion` were updated to 30 from 28 in the [5.12.0 release](https://www.twilio.com/docs/video/changelog-twilio-video-android#5120-october-7th-2020). No changes are required to migrate to this version in an existing application.

**Comment by Motherland982** [comment]
Dont run now
