### ISSUE TITLE
Unable to automatically join a Room when activity is created.

### ISSUE THREAD

**Issue by TJGreen97** [twilio/video-quickstart-android#544]
I am trying to make my app join a Room automatically with a specified room name when the VideoActivity is created. I assume I must call the "connectToRoom()" function, but this causes the app to crash. I think I am calling the function before the UI has finished initializing, but I cannot figure out where it should be called. It works within a button setOnClickListener, but I want to remove this step and connect right away.

**Comment by aaalaniz** [comment]
Hey @TJGreen97 

If you provide a sample project (a quickstart fork would work), our team can provide some guidance.

Thanks!

**Comment by aaalaniz** [comment]
Hey @TJGreen97 

I will close this issue for now. Please reopen or file a new issue if you have any follow up questions.

Thanks!
