### ISSUE TITLE
java.lang.IllegalArgumentException FRONT_CAMERA is not supported on this device 

### ISSUE THREAD

**Issue by Balasnest** [twilio/video-quickstart-android#545]
### Description
```
Caused by: java.lang.IllegalArgumentException FRONT_CAMERA is not supported on this device 
    Preconditions.java:131 com.twilio.video.Preconditions.checkArgument
    CameraCapturer.java:323 com.twilio.video.CameraCapturer.<init>
    CameraCapturer.java:309 com.twilio.video.CameraCapturer.<init>
    CameraCapturer.java:309 com.twilio.video.CameraCapturer.<init>
    CameraCapturer.java:303 com.twilio.video.CameraCapturer.<init>
    CameraCapturer.java:303 com.twilio.video.CameraCapturer.<init>
    VideoActivity.java:491 com.app.videocall.VideoActivity.createAudioAndVideoTracks
    VideoActivity.java:290 com.app.videocall.VideoActivity.onCreate
    Activity.java:6303 android.app.Activity.performCreate
    Instrumentation.java:1108 android.app.Instrumentation.callActivityOnCreate
    ActivityThread.java:2402 android.app.ActivityThread.performLaunchActivity
    ActivityThread.java:2509 android.app.ActivityThread.handleLaunchActivity
    ActivityThread.java:153 android.app.ActivityThread.access$1000
    ActivityThread.java:1373 android.app.ActivityThread$H.handleMessage
    Handler.java:102 android.os.Handler.dispatchMessage
    Looper.java:154 android.os.Looper.loop
    ActivityThread.java:5523 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:739 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:629 com.android.internal.os.ZygoteInit.main
```

One of our client reported that its always crashing when video call arise. We are showing local video on screen until user accept the call. 

```
private void createAudioAndVideoTracks() {
        Logg("createAudioAndVideoTracks called!!!");
        // Share your microphone
        localAudioTrack = LocalAudioTrack.create(this, true, LOCAL_AUDIO_TRACK_NAME);

        // Share your camera
        cameraCapturer = new CameraCapturer(this, CameraCapturer.CameraSource.FRONT_CAMERA);
        localVideoTrack = LocalVideoTrack.create(this, true, cameraCapturer);
        primaryVideoView.setMirror(true);
        localVideoTrack.addRenderer(primaryVideoView);
        localVideoView = primaryVideoView;

        /*
         * Set the initial state of the UI
         */
        intializeUI();
    }
```

Note: `Device camera is working fine both front and back camera`.

What would be the exact issue for causing this crash?

Device info:
![Screenshot 2020-07-15 at 6 47 21 PM](https://user-images.githubusercontent.com/6050520/87549631-aeb54f00-c6cb-11ea-93e5-36f63b56f775.png)

**Comment by Balasnest** [comment]
@aaalaniz can you help here

**Comment by aaalaniz** [comment]
Hey @Balasnest 

Thanks for filing this issue! 

Typically we have seen this issue occur when a device does not have a front or back camera available. The `CameraCapturer` API provides a static method [isSourceAvailable](https://twilio.github.io/twilio-video-android/docs/latest/) that will check for the availability of a particular source. At first glance, I have no reason to believe that the Redmi 4A does not have a front camera though.

We have a Xiaomi MI 5s that we can test with. This may be a bug in the isSourceAvailable API. I will investigate and report back.

Thanks!

**Comment by Balasnest** [comment]
Thanks for your quick reply. I have checked with the user. He stated that both side camera is working flawlessly in WhatsApp.

**Comment by Alton09** [comment]
@Balasnest We have recently cut a new release, [5.1.0](https://www.twilio.com/docs/video/changelog-twilio-video-android#5100), and believe it will fix the issue you are experiencing. Please let us know if you are still running into any issues when using the new release. Thanks!

**Comment by tl-robertmanley** [comment]
@Alton09 I'm working with the Camera2 API and was wondering if we could get support for LEGACY mode as the product we would like to use it on will not require any special cropping.  Thanks!

**Comment by aaalaniz** [comment]
Hey @tl-robertmanley Please open a separate issue for this request. Thank you!

I am closing this issue @Balasnest. Please open a new issue if you have any follow up.

Thanks!
