### ISSUE TITLE
After a video/audio call is ended, I see this in the logcat in android-studio.

### ISSUE THREAD

**Issue by ArvindMewada** [twilio/video-quickstart-android#553]
Hi Support team,

After a video/audio call is ended, I see this in the logcat in android-studio. This is sort of recursive.
I/org.webrtc.Logging: CameraStatistics: Camera fps: 30.

Any specific way to stop it?

**Comment by liri2006** [comment]
I have the same issue, after finishing the call log keeps running and processor seems doing something:
I/tvi.webrtc.Logging(21945): EglRenderer: Dropping frame - Not initialized or already released.
I/tvi.webrtc.Logging(21945): CameraStatistics: Camera fps: 18.

**Comment by ArvindMewada** [comment]
I'm solved this bug

**Comment by ArvindMewada** [comment]
**Disconnect from room**
 ` private fun disconnect(result: Result) {
    localVideoTrack?.release();
    Log.d("ROOM d", room?.name);
    room?.disconnect()
    result.success(true)
  }`

**Comment by Otephia** [comment]
I have some problem ++

**Comment by camposbrunocampos** [comment]
any updates o this one? I still see this issue...

**Comment by camposbrunocampos** [comment]
Ok, it seems that all you need is to removeSink from your video view.
I'm doing that in the OnDestroy call of my fragment.

Ex:


```
override fun onDestroy() {
        super.onDestroy()
        _binding?.apply {
            videoTrack?.removeSink(localParticipantVideoView)
        }
    }
```

**Comment by jeffreyliu8** [comment]
remember to stop capture video

  videoCapturer.stopCapture()
  localVideoTrack?.removeSink(localVideoOutput)
