### ISSUE TITLE
 java.lang.IllegalStateException Supported formats could not be retrieved

### ISSUE THREAD

**Issue by Balasnest** [twilio/video-quickstart-android#554]
java.lang.RuntimeException Unable to start activity ComponentInfo{com.app/com.app.androidcommonslibrary.VideoActivity}: java.lang.IllegalStateException: Supported formats could not be retrieved because an error occurred connecting to the camera service 
    ActivityThread.java:2887 android.app.ActivityThread.performLaunchActivity
    ActivityThread.java:2965 android.app.ActivityThread.handleLaunchActivity
    Unknown android.app.ActivityThread.-wrap11
    ActivityThread.java:1669 android.app.ActivityThread$H.handleMessage
    Handler.java:106 android.os.Handler.dispatchMessage
    Looper.java:192 android.os.Looper.loop
    ActivityThread.java:6702 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:549 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:826 com.android.internal.os.ZygoteInit.main

Caused by: java.lang.IllegalStateException Supported formats could not be retrieved because an error occurred connecting to the camera service 
    Preconditions.java:447 com.twilio.video.Preconditions.checkState
    CameraCapturer.java:341 com.twilio.video.CameraCapturer.getSupportedFormats
    LocalVideoTrack.java:165 com.twilio.video.LocalVideoTrack.create
    LocalVideoTrack.java:60 com.twilio.video.LocalVideoTrack.create
    VideoActivity.java:532 com.app.androidcommonslibrary.VideoActivity.createAudioAndVideoTracks
    VideoActivity.java:325 com.app.androidcommonslibrary.VideoActivity.onCreate
    Activity.java:7115 android.app.Activity.performCreate
    Activity.java:7106 android.app.Activity.performCreate
    Instrumentation.java:1220 android.app.Instrumentation.callActivityOnCreate
    ActivityThread.java:2840 android.app.ActivityThread.performLaunchActivity
    ActivityThread.java:2965 android.app.ActivityThread.handleLaunchActivity
    Unknown android.app.ActivityThread.-wrap11
    ActivityThread.java:1669 android.app.ActivityThread$H.handleMessage
    Handler.java:106 android.os.Handler.dispatchMessage
    Looper.java:192 android.os.Looper.loop
    ActivityThread.java:6702 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:549 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:826 com.android.internal.os.ZygoteInit.main

**Comment by idelgado** [comment]
Please open an issue with more details by using the issue template. Thank you.
