### ISSUE TITLE
Remote Participant view display after manually resume Activity

### ISSUE THREAD

**Issue by Shubham-Mollatech** [twilio/video-quickstart-android#556]
override fun onResume() {
        super.onResume()
        /*
         * If the local video track was released when the app was put in the background, recreate.
         */
        localVideoTrack = if (localVideoTrack == null && checkPermissionForCameraAndMicrophone()) {
            LocalVideoTrack.create(
                this,
                true,
                cameraCapturerCompat.videoCapturer
            )
        } else {
            localVideoTrack
        }
        localVideoTrack?.addRenderer(localVideoView)

        /*
         * If connected to a Room then share the local video track.
         */
        localVideoTrack?.let { localParticipant?.publishTrack(it) }

        /*
         * Update encoding parameters if they have changed.
         */
        localParticipant?.setEncodingParameters(encodingParameters)

        /*
         * Update reconnecting UI
         */
        room?.let {
            reconnectingProgressBar.visibility = if (it.state != Room.State.RECONNECTING)
                View.GONE else
                View.VISIBLE
            Log.d(TAG, "Connected to ${it.name}")
        }
    }

**Comment by aaalaniz** [comment]
Hey @Shubham-Mollatech 

Can you fill out the issue template so we can properly triage and fix?

Thanks!
