### ISSUE TITLE
Can I enable MediaTek hardware codec?

### ISSUE THREAD

**Issue by mytabata** [twilio/video-quickstart-android#564]
Hi,

My testing device is Lenovo M10 FHD and it has MediaTek Helio P22T Tab with Android 9 and com.twilio:video-android:5.11.1 SDK.
No hardware codec is available for this device (MediaCodecVideo{De, En}coder.is{Vp8, Vp9, H264}HwSupported() returns false) and I can't connect to a conference room (com.twilio.video.TwilioException: No supported codec. Codec not supported.).

Maybe #500 (Huawei H264 Hardware Encoding/Decoding) is a similar issue and I have to watch the progress.
However, the situation of MediaTek is a bit different as it seems to be able to enable by field trial flags like "WebRTC-MediaTekVP8". Is there any way to set the flag?

thanks,

**Comment by aaalaniz** [comment]
Hey @mytabata 

You should be able to enable the field trials flag using the following Java snippet.

```
ReLinker.loadLibrary(context, com.twilio.video.BuildConfig.TWILIO_VIDEO_ANDROID_LIBRARY);
PeerConnectionFactory.initialize(PeerConnectionFactory.InitializationOptions.builder(context)
            .setNativeLibraryLoader(library -> true)
            .setFieldTrials("WebRTC-MediaTekVP8/Enabled/WebRTC-MediaTekH264/Enabled/")
            .createInitializationOptions());
```

Let me know if you need any further assistance. Thanks!

**Comment by mytabata** [comment]
I put this code in onCreate() or just before Video.Connect(), but both result following crash
    # Fatal error in ../../../src/modules/utility/source/jvm_android.cc, line 257
    # last system error: 11
    # Check failed: !g_jvm

anyway, thank you for the advice! I'll try some more tweaks.

**Comment by aaalaniz** [comment]
Hey @mytabata 

Good catch. The following snippet should resolve this issue. Unfortunately, reflection is required, but it should only be a one time execution cost penalty.

```
        ReLinker.loadLibrary(context, com.twilio.video.BuildConfig.TWILIO_VIDEO_ANDROID_LIBRARY);
        try {
            Class nativeLibraryClass = Class.forName("tvi.webrtc.NativeLibrary");
            Field modifiersField = nativeLibraryClass.getDeclaredField("libraryLoaded");
            modifiersField.setAccessible(true);
            modifiersField.setBoolean(null, true);
            PeerConnectionFactory.initializeFieldTrials("WebRTC-MediaTekVP8/Enabled/WebRTC-MediaTekH264/Enabled/");
            MediaCodecVideoDecoder.isVp8HwSupported();
            MediaCodecVideoDecoder.isH264HwSupported();
            MediaCodecVideoEncoder.isVp8HwSupported();
            MediaCodecVideoEncoder.isH264HwSupported();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        }
```

**Comment by mytabata** [comment]
It worked! Thank you very much!

(of course, I will enable this for development and listed internal users as this touches internal API)
