### ISSUE TITLE
Need example for video calling in Foreground service.

### ISSUE THREAD

**Issue by NitinSharma639** [twilio/video-quickstart-android#565]
Hello Team

I am making a Video calling app using twilio sdk. I need an example for video call in foreground service. Actually I can see example of video capture in service but I also need to show the remote video. I need example on how can I show remote users video while connection callbacks are in Foreground Service. 

I also raised a ticket for this. Any help is appreciated.

https://www.twilio.com/console/support/tickets/5149622

Thanks

**Comment by aaalaniz** [comment]
hey @NitinSharma639 

I recommend referencing the [Video Android Collaboration App](https://github.com/twilio/twilio-video-app-android). This application demonstrates how to manage a Room in a foreground service.

Thanks!
