### ISSUE TITLE
Twilio Flutter Support 

### ISSUE THREAD

**Issue by skpatrat** [twilio/video-quickstart-android#569]
**Is your feature request related to a problem? Please describe.**
Since more and more applications are being on Flutter, Twilio is lagging behind in terms of support.

**Describe the solution you'd like**
Flutter has been around for a while now and fully capable of supporting Twilio's APIs. Since Twilio already both Android and iOS SDKs, it is not a humongous project too.

**Describe alternatives you've considered**
I personally come from wanting to integrate Twilio's Programmable video API in my Flutter application. I have always known Twilio for its great support and easy to use libraries which offer support for a great variety of languages. I tried using the libraries which try to implement Twilio using a JS backend service or a combination of Android and iOS SDKs. They lack proper documentation and offer bad performance. A native library made on Flutter would be able to offer much better performance with the possibility of reaching out for support and issues reporting on the official Twilio library. 

I decided to put this up here in hopes to get the attention of Twilio's team towards this issue. Please consider my request.

**Comment by Alton09** [comment]
Hi @skpatrat ! Thank you for reaching out regarding support for Flutter. Our team will evaluate this request, but currently it is not on our roadmap.

**Comment by aaalaniz** [comment]
Hey @skpatrat and @singhvedant111 

As @Alton09 stated, supporting Flutter is not on our roadmap, so I will close this issue.

However, I recommend checking out this [community project](https://gitlab.com/twilio-flutter/programmable-video).

Thanks!
