### ISSUE TITLE
E/AndroidRuntime: FATAL EXCEPTION: main     Process: com.twilio.video.quickstart, PID: 3867

### ISSUE THREAD

**Issue by sumitkumar3391** [twilio/video-quickstart-android#571]
Please help I am getting below error while running project
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.twilio.video.quickstart, PID: 3867

**Comment by aaalaniz** [comment]
Hey @sumitkumar3391 

Please fill out the issue template so our team can properly investigate.

Thanks!
