### ISSUE TITLE
screen capture is not capturing video playing in the app

### ISSUE THREAD

**Issue by vkmulloly** [twilio/video-quickstart-android#572]
Hi, 
am trying to implement screen capture using twilio , but somehow screen capture is not capturing any video that is playing in the app. it is giving black screen only to video view , image is capturing fine.
Please help me on this

**Comment by aaalaniz** [comment]
Hey @vkmulloly 

Can you provide code snippets, logs, screenshots, and/or a sample project where you can reproduce the issue so we can investigate?

I recommend the [Screen Capturer Quickstart](https://github.com/twilio/video-quickstart-android/tree/master/exampleScreenCapturer) if you are getting started with capturing the screen. Additionally, you can reference the [Video Android Collaboration app](https://github.com/twilio/twilio-video-app-android) as another example of how to use the ScreenCapturer.

Thanks!

**Comment by aaalaniz** [comment]
Hey @vkmulloly 

I am going to close this issue. Please fill out the issue template to the best of your ability so our team can provide guidance.

Thank you!
