### ISSUE TITLE
How can I control Ringing tone volume as set by System settings

### ISSUE THREAD

**Issue by sunit-navsoft** [twilio/video-quickstart-android#574]
I am playing ringing tone via MediaPlayer. Therefore the ringing volume is now controlled by the Media volume as set by user. Even when phone is in silent mode my app is still ringing as Media volume is there. Can I rid of this, and set volume as set in ringing tone volume by the user. Any help will be appreciated.

**Comment by aaalaniz** [comment]
Hey @sunit-navsoft 

I recommend changing the [MediaPlayer stream type](https://developer.android.com/reference/android/media/MediaPlayer.html#setAudioStreamType(int)). Based on your description, the appropriate [type](https://developer.android.com/reference/android/media/AudioManager#STREAM_RING) may be STREAM_RING or STREAM_NOTIFICATION.

I will close this issue for now, but feel free to ask any follow up questions.

Thanks!
