### ISSUE TITLE
Hi @manjeshbhargav

### ISSUE THREAD

**Issue by Ravind88** [twilio/video-quickstart-android#576]
Hi @manjeshbhargav ,

I am using twilio android sdk and implement DominantSpeakerChanged event which is not triggering. I have already enables dominant speker through ConnectOptions Builder
val connectOptionsBuilder = ConnectOptions.Builder(token)
.roomName(roomName)
.enableInsights(enableInsights)
.enableAutomaticSubscription(enableAutomaticTrackSubscription)
.enableDominantSpeaker(enableDominantSpeaker)
.enableNetworkQuality(isNetworkQualityEnabled)
.networkQualityConfiguration(configuration)
.bandwidthProfile(bandwidthProfileOptions)

Can You suggest that what I am missing ?

Thanks,
Ravind

_Originally posted by @manjeshbhargav in https://github.com/twilio/twilio-video.js/issues/1218#issuecomment-719088039_

**Comment by paynerc** [comment]
@Ravind88,

Are you using P2P or Group Rooms? Dominant Speaker functionality is only supported with Group Rooms.

Ryan

**Comment by aaalaniz** [comment]
Hey @Ravind88 

Can you provide a room SID so we can investigate?

Thanks!

**Comment by aaalaniz** [comment]
Hey @Ravind88 

I will close this issue for now. Please provide a Room SID and we can investigate further.

Thank you!
