### ISSUE TITLE
Video Call is getting disconnected automatically after 10 to 15 few seconds.

### ISSUE THREAD

**Issue by bhavikgoswami** [twilio/video-quickstart-android#579]
I have implemented Video Calling feature and used git source code from below URL:

https://github.com/twilio/video-quickstart-android/tree/master/quickstartKotlin

Scenario: Use A is calling to User B. Both are connected and able to talk but after few seconds call is getting disconnected. I have observed that its getting disconnected from User B automatically.

Please help me to solve this issue. 

Thank You!

**Comment by aaalaniz** [comment]
Hey @bhavikgoswami 

Can you provide a room SID?

Thanks!

**Comment by aaalaniz** [comment]
Hey @bhavikgoswami 

I will close this issue. Please fill out the issue template to the best of your knowledge, so our team can provide guidance.

Thanks!
