### ISSUE TITLE
Crash while loading native library

### ISSUE THREAD

**Issue by guness** [twilio/video-quickstart-android#581]
### Crash report regarding to native library loading

It happens only one device for now, but since device is relatively new, it has potential to grow.

### Steps to Reproduce

I haven't been able to reproduce in my hand, just reporting what we received on crash reports.

#### Reproduces how Often

We can say rarely.

#### Logs

```java

Caused by l.a.a.b
libtwilio_video_android_so.so

com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary (ApkLibraryInstaller.java:128)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal (ReLinkerInstance.java:180)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary (ReLinkerInstance.java:136)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:70)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:51)
com.twilio.video.MediaFactory.instance (MediaFactory.java:44)
com.twilio.video.LocalAudioTrack.create (LocalAudioTrack.java:99)
com.twilio.video.LocalAudioTrack.create (LocalAudioTrack.java:43)
```

#### Video Android SDK

5.8.0

#### Android API

Android 10

#### Android Device

Huawei ELS-NX9

**Comment by aaalaniz** [comment]
Hey @guness 

I have a couple follow up questions.

1. Can you provided a [symbolicated stack trace](https://support.google.com/googleplay/android-developer/answer/9848633?hl=en)? 
2. Are you using apk splits or app bundles?

Thanks!

**Comment by guness** [comment]
@aaalaniz 
```
com.getkeepsafe.relinker.MissingLibraryException -> l.a.a.b:
    1:1:void <init>(java.lang.String):20:20 -> <init>
```
We have app bundles. 

Also unfortunately this device is not in the list of devices on Play Store.

**Comment by aaalaniz** [comment]
Hey @guness 

I have a couple of follow up questions.

1. Do you know the device's [ABI](https://developer.android.com/ndk/guides/abis)? If the ABI is not one of our [supported ABIs](https://www.twilio.com/docs/video/android-getting-started#supported-devices) (arm64-v8a, armeabi-v7a, x86, or x86_64) then this issue could occur.
2. Does your application follow our [proguard guidance](https://www.twilio.com/docs/video/android-getting-started#proguard)? This could also be an instance where proguard is obfuscating the name of the native library which would result in this `MissingLibraryException`.

Thanks!
