### ISSUE TITLE
Screen Capture not stop during video call 

### ISSUE THREAD

**Issue by dhrutimistry** [twilio/video-quickstart-android#585]
I am facing some issue in screen capture 
I added this feature with video calling. When I try to start screen capture it is start and participant can view screen but when I stop screen capture it can not stop in participant side.

**Comment by aaalaniz** [comment]
Hey @dhrutimistry 

Please fill out the issue template to the best of your knowledge, so our team can help triage this issue. In this case, it would be helpful to see code snippets, logs, a Room SID, and/or reproduction steps in the quickstart, the video app repo, or your own sample project.

I will close this until more information is provided.

Thank you!
