### ISSUE TITLE
During screen share audio is not hearing at participant end

### ISSUE THREAD

**Issue by vkmulloly** [twilio/video-quickstart-android#593]
Hi am using same sample code to share screen between 2 android device . it is working fine but i have an issue 
 eg : i have 2 android devices A, B
 now A started sharing the screen  B can see A's Screen.
  A navigate to youtube app and started playing a video now B can see A's screen and see youtube video But not hearing sound from youtube.

How to fix this issue

**Comment by aaalaniz** [comment]
Hey @vkmulloly 

The ScreenCapturer only supports capturing the device's screen. Capturing audio from the system is possible using the [Playback capture API](https://developer.android.com/guide/topics/media/playback-capture). To unlock this use case, I recommend referencing our Screen Capturer and Custom Audio Device example. A potential solution would be to do the following:

1. Begin capturing the screen
2. Start capturing system audio. Here is a pretty [good guide](https://www.raywenderlich.com/11393023-audio-playback-capture-in-android-x).
3. Develop a custom audio device that mixes the audio from the system and microphone into one stream.

Let me know if you need any additional guidance.

Thanks!

**Comment by Alton09** [comment]
@vkmulloly Closing this one for now. Feel free to open up another issue if needed. Thanks!

**Comment by pkdhankher** [comment]
> Hey @vkmulloly @Alton09 @aaalaniz @paynerc @kwhinnery  
> 
> The ScreenCapturer only supports capturing the device's screen. Capturing audio from the system is possible using the [Playback capture API](https://developer.android.com/guide/topics/media/playback-capture). To unlock this use case, I recommend referencing our Screen Capturer and Custom Audio Device example. A potential solution would be to do the following:
> 
> 1. Begin capturing the screen
> 2. Start capturing system audio. Here is a pretty [good guide](https://www.raywenderlich.com/11393023-audio-playback-capture-in-android-x).
> 3. Develop a custom audio device that mixes the audio from the system and microphone into one stream.
> 
> Let me know if you need any additional guidance.
> 
> Thanks!

Hi Team

I'm working on screen capture and wanted to check how it's working. So I tried to sink with a localVideoVIew (com.twilio.video.VideoView). But video frames are not smooth and flickering (like each frame is smaller than previous)
I'm adding screenshot link as an issue reference

[Issue Screenshot link](https://drive.google.com/file/d/1jmQFNOHafWe83hOXvPkcL_qENRpPUmf5/view?usp=sharing)

Please help me with this. Thank you in advance.
