### ISSUE TITLE
How to convert I420Frame to byte[] array to make it possible to write to video file

### ISSUE THREAD

**Issue by FireHook** [twilio/video-quickstart-android#594]
Hi, @aaalaniz 

Please, help me with that issue:
I need to save Twilio video locally on device. 
And stopped on the step **how to convert I420Frame to byte[] array to make it possible to write to video file**.

I've created VideoFileRenderer that implements Twilio VideoRenderer and added it to localVideoTrack. I have problem in renderFrame method, don't know how to convert I420Frame to byte[] array to make it possible to write to video file

LocalVideoTrack localVideoTrack = LocalVideoTrack.create(this,
          true,
          cameraCapturerCompat.getVideoCapturer(),
          LOCAL_VIDEO_TRACK_NAME);

VideoFileRenderer videoFileRenderer = new VideoFileRenderer(videoFile, widthOfScreen, heightOfScreen);

localVideoTrack.addRenderer(videoFileRenderer);

videoFileRendere.release();

public class VideoFileRenderer implements VideoRenderer {

    private final String TAG = this.getClass().getSimpleName();
    private final HandlerThread renderThread;
    private final Handler renderThreadHandler;
    private final FileOutputStream videoOutFile;
    private final int outputFileWidth;
    private final int outputFileHeight;
    private final int outputFrameSize;
    private final String outputFileName;
    private final ArrayList<ByteBuffer> rawFrames = new ArrayList<>();

    public VideoFileRenderer(String outputFile, int outputFileWidth, int outputFileHeight) throws IOException {
        if ((outputFileWidth % 2) == 1 || (outputFileHeight % 2) == 1) {
            throw new IllegalArgumentException("Does not support uneven width or height");
        }
        this.outputFileName = outputFile;
        this.outputFileWidth = outputFileWidth;
        this.outputFileHeight = outputFileHeight;
        outputFrameSize = outputFileWidth * outputFileHeight * 3 / 2;
        videoOutFile = new FileOutputStream(outputFile);
        videoOutFile.write(
                ("YUV4MPEG2 C420 W" + outputFileWidth + " H" + outputFileHeight + " Ip F30:1 A1:1\n")
                        .getBytes());
        renderThread = new HandlerThread(TAG);
        renderThread.start();
        renderThreadHandler = new Handler(renderThread.getLooper());
    }

    @Override
    public void renderFrame(@NonNull I420Frame frame) {
        renderThreadHandler.post(new Runnable() {
            @Override public void run() {

                ByteBuffer byteBuffer = JniCommon.nativeAllocateByteBuffer(outputFrameSize);
                YuvHelper.I420Rotate(frame.yuvPlanes[0], frame.yuvStrides[0], frame.yuvPlanes[1], frame.yuvStrides[1],
                        frame.yuvPlanes[2], frame.yuvStrides[2], byteBuffer, frame.width, frame.height,
                        frame.rotationDegree);
                frame.release();

                byteBuffer.rewind();
                rawFrames.add(byteBuffer);

            }
        });
    }

    public void release() {
        final CountDownLatch cleanupBarrier = new CountDownLatch(1);
        renderThreadHandler.post(() -> {
            renderThread.quit();
            cleanupBarrier.countDown();
        });
        ThreadUtils.awaitUninterruptibly(cleanupBarrier);
        try {
            for (ByteBuffer buffer : rawFrames) {
                videoOutFile.write("FRAME\n".getBytes(Charset.forName("US-ASCII")));

                byte[] data = new byte[outputFrameSize];
                buffer.get(data);

                videoOutFile.write(data);

                JniCommon.nativeFreeByteBuffer(buffer);
            }
            videoOutFile.close();
            Logging.d(TAG,
                    "Video written to disk as " + outputFileName + ". Number frames are " + rawFrames.size()
                            + " and the dimension of the frames are " + outputFileWidth + "x" + outputFileHeight
                            + ".");
        } catch (IOException e) {
            Logging.e(TAG, "Error writing video to disk", e);
        }
    }
}

**Comment by aaalaniz** [comment]
Hey @FireHook 

It looks like you are using our 5.0 SDK. I recommend [upgrading your application to the Video Android 6.0 SDK](https://www.twilio.com/docs/video/migrating-5x-6x). This update includes a media engine update to WebRTC 83 and an overhaul of our capturing and rendering facilities. The SDK now includes a [VideoFileRenderer](https://twilio.github.io/twilio-video-android/docs/latest/tvi/webrtc/VideoFileRenderer.html) that you may find useful to your efforts.

Thanks!

**Comment by FireHook** [comment]
> Hey @FireHook
> 
> It looks like you are using our 5.0 SDK. I recommend [upgrading your application to the Video Android 6.0 SDK](https://www.twilio.com/docs/video/migrating-5x-6x). This update includes a media engine update to WebRTC 83 and an overhaul of our capturing and rendering facilities. The SDK now includes a [VideoFileRenderer](https://twilio.github.io/twilio-video-android/docs/latest/tvi/webrtc/VideoFileRenderer.html) that you may find useful to your efforts.
> 
> Thanks!

Thank you for the response, I really appreciate it!

**Comment by FireHook** [comment]
Hey @aaalaniz 
Thanks to your recommendation I updated Twilio sdk and changed my Renderer to saving video frames into video file. The **problem is video has .y4m format**, so I can't be run on device without specific player like VLC also a size of video is huge. Could you suggest **how can I convert and write VideoFrame.Buffer which I receive in onFrame callback in .mp4 video file format**.
Best regards


public class VideoFileRenderer implements VideoSink {

    private static final String TAG = "VideoFileRenderer";

    private final HandlerThread renderThread;
    private final Handler renderThreadHandler;
    private final HandlerThread fileThread;
    private final Handler fileThreadHandler;
    private final FileOutputStream videoOutFile;
    private final String outputFileName;
    private final int outputFileWidth;
    private final int outputFileHeight;
    private final int outputFrameSize;
    private final ByteBuffer outputFrameBuffer;
    private EglBase eglBase;
    private YuvConverter yuvConverter;
    private int frameCount;

    public VideoFileRenderer(String outputFile, int outputFileWidth, int outputFileHeight,
                             final EglBase.Context sharedContext) throws IOException {
        if ((outputFileWidth % 2) == 1 || (outputFileHeight % 2) == 1) {
            throw new IllegalArgumentException("Does not support uneven width or height");
        }

        this.outputFileName = outputFile;
        this.outputFileWidth = outputFileWidth;
        this.outputFileHeight = outputFileHeight;

        outputFrameSize = outputFileWidth * outputFileHeight * 3 / 2;
        outputFrameBuffer = ByteBuffer.allocateDirect(outputFrameSize);

        videoOutFile = new FileOutputStream(outputFile);
        **videoOutFile.write(
                ("YUV4MPEG2 W" + outputFileWidth + " H" + outputFileHeight + " Ip F25:1 A1:1 C420\n")
                        .getBytes(Charset.forName("US-ASCII")));**

        renderThread = new HandlerThread(TAG + "RenderThread");
        renderThread.start();
        renderThreadHandler = new Handler(renderThread.getLooper());

        fileThread = new HandlerThread(TAG + "FileThread");
        fileThread.start();
        fileThreadHandler = new Handler(fileThread.getLooper());

        ThreadUtils.invokeAtFrontUninterruptibly(renderThreadHandler, new Runnable() {
            @Override
            public void run() {
                eglBase = EglBase.create(sharedContext, EglBase.CONFIG_PIXEL_BUFFER);
                eglBase.createDummyPbufferSurface();
                eglBase.makeCurrent();
                yuvConverter = new YuvConverter();
            }
        });
    }

    @Override
    public void onFrame(VideoFrame frame) {
        frame.retain();
        renderThreadHandler.post(() -> renderFrameOnRenderThread(frame));
    }

    private void renderFrameOnRenderThread(VideoFrame frame) {
        final VideoFrame.Buffer buffer = frame.getBuffer();

        // If the frame is rotated, it will be applied after cropAndScale. Therefore, if the frame is
        // rotated by 90 degrees, swap width and height.
        final int targetWidth = frame.getRotation() % 180 == 0 ? outputFileWidth : outputFileHeight;
        final int targetHeight = frame.getRotation() % 180 == 0 ? outputFileHeight : outputFileWidth;

        final float frameAspectRatio = (float) buffer.getWidth() / (float) buffer.getHeight();
        final float fileAspectRatio = (float) targetWidth / (float) targetHeight;

        // Calculate cropping to equalize the aspect ratio.
        int cropWidth = buffer.getWidth();
        int cropHeight = buffer.getHeight();
        if (fileAspectRatio > frameAspectRatio) {
            cropHeight = (int) (cropHeight * (frameAspectRatio / fileAspectRatio));
        } else {
            cropWidth = (int) (cropWidth * (fileAspectRatio / frameAspectRatio));
        }

        final int cropX = (buffer.getWidth() - cropWidth) / 2;
        final int cropY = (buffer.getHeight() - cropHeight) / 2;

        final VideoFrame.Buffer scaledBuffer =
                buffer.cropAndScale(cropX, cropY, cropWidth, cropHeight, targetWidth, targetHeight);
        frame.release();

        final VideoFrame.I420Buffer i420 = scaledBuffer.toI420();
        scaledBuffer.release();

        fileThreadHandler.post(() -> {
            YuvHelper.I420Rotate(i420.getDataY(), i420.getStrideY(), i420.getDataU(), i420.getStrideU(),
                    i420.getDataV(), i420.getStrideV(), outputFrameBuffer, i420.getWidth(), i420.getHeight(),
                    frame.getRotation());
            i420.release();

            try {
                **videoOutFile.write("FRAME\n".getBytes(Charset.forName("US-ASCII")));
                videoOutFile.write(
                        outputFrameBuffer.array(), outputFrameBuffer.arrayOffset(), outputFrameSize);**
            } catch (IOException e) {
                throw new RuntimeException("Error writing video to disk", e);
            }
            frameCount++;
        });
    }

    /**
     * Release all resources. All already posted frames will be rendered first.
     */
    public void release() {
        final CountDownLatch cleanupBarrier = new CountDownLatch(1);
        renderThreadHandler.post(() -> {
            yuvConverter.release();
            eglBase.release();
            renderThread.quit();
            cleanupBarrier.countDown();
        });
        ThreadUtils.awaitUninterruptibly(cleanupBarrier);
        fileThreadHandler.post(() -> {
            try {
                videoOutFile.close();
                Logging.d(TAG,
                        "Video written to disk as " + outputFileName + ". The number of frames is " + frameCount
                                + " and the dimensions of the frames are " + outputFileWidth + "x"
                                + outputFileHeight + ".");
            } catch (IOException e) {
                throw new RuntimeException("Error closing output file", e);
            }
            fileThread.quit();
        });
        try {
            fileThread.join();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            Logging.e(TAG, "Interrupted while waiting for the write to disk to complete.", e);
        }
    }


}
