### ISSUE TITLE
The app crashes with beta8/9

### ISSUE THREAD

**Issue by KarimAbdo** [twilio/video-quickstart-android#60]
<img width="1022" alt="screen shot 2017-02-22 at 5 15 51 pm" src="https://cloud.githubusercontent.com/assets/12425853/23220563/b028fbfe-f922-11e6-9b14-1791a4db6690.png">

I couldn't get any crash report on firebase or crashlytics, but in one of the tries the log kept there for a second

`02-22 17:18:59.957 D/MediaPlayer: setSubtitleAnchor in MediaPlayer
02-22 17:18:59.993 I/org.webrtc.Logging: EglBase14: SDK version: 25. isEGL14Supported: true
02-22 17:18:59.996 I/org.webrtc.Logging: EglBase14: SDK version: 25. isEGL14Supported: true
02-22 17:18:59.998 I/org.webrtc.Logging: EglBase14: SDK version: 25. isEGL14Supported: true
02-22 17:19:00.000 D/JVM: JVM::Initialize@[tid=19048]
02-22 17:19:00.000 D/JVM: JVM::JVM@[tid=19048]
02-22 17:19:00.000 D/JVM: LoadClasses
02-22 17:19:00.000 D/JVM: name: org/webrtc/voiceengine/BuildInfo
02-22 17:19:00.001 D/JVM: name: org/webrtc/voiceengine/WebRtcAudioManager
02-22 17:19:00.001 D/JVM: name: org/webrtc/voiceengine/WebRtcAudioRecord
02-22 17:19:00.001 D/JVM: name: org/webrtc/voiceengine/WebRtcAudioTrack
02-22 17:19:00.021 W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
02-22 17:19:00.050 I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
02-22 17:19:00.054 I/org.webrtc.Logging: MediaCodecVideoEncoder: Found target encoder for mime video/x-vnd.on2.vp8 : OMX.qcom.video.encoder.vp8. Color: 0x15. Bitrate adjustment: NO_ADJUSTMENT
02-22 17:19:00.055 W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
02-22 17:19:00.056 I/org.webrtc.Logging: MediaCodecVideoEncoder: Found target encoder for mime video/avc : OMX.qcom.video.encoder.avc. Color: 0x15. Bitrate adjustment: NO_ADJUSTMENT
02-22 17:19:00.056 I/org.webrtc.Logging: MediaCodecVideoDecoder: Trying to find HW decoder for mime video/x-vnd.on2.vp8
02-22 17:19:00.056 I/org.webrtc.Logging: MediaCodecVideoDecoder: Found candidate decoder OMX.qcom.video.decoder.vp8
02-22 17:19:00.057 I/org.webrtc.Logging: MediaCodecVideoDecoder: Found target decoder OMX.qcom.video.decoder.vp8. Color: 0x13
02-22 17:19:00.057 I/org.webrtc.Logging: MediaCodecVideoDecoder: Trying to find HW decoder for mime video/x-vnd.on2.vp9
02-22 17:19:00.058 I/org.webrtc.Logging: MediaCodecVideoDecoder: Found candidate decoder OMX.google.vp9.decoder
02-22 17:19:00.058 I/org.webrtc.Logging: MediaCodecVideoDecoder: No HW decoder found for mime video/x-vnd.on2.vp9
02-22 17:19:00.058 I/org.webrtc.Logging: MediaCodecVideoDecoder: Trying to find HW decoder for mime video/avc
02-22 17:19:00.058 I/org.webrtc.Logging: MediaCodecVideoDecoder: Found candidate decoder OMX.qcom.video.decoder.avc
02-22 17:19:00.059 I/org.webrtc.Logging: MediaCodecVideoDecoder: Found target decoder OMX.qcom.video.decoder.avc. Color: 0x13
02-22 17:19:00.060 D/JVM: AttachCurrentThreadIfNeeded::ctor@[tid=20382]
02-22 17:19:00.060 D/JVM: Attaching thread to JVM
02-22 17:19:00.061 D/JVM: JVM::environment@[tid=20382]
02-22 17:19:00.061 D/JVM: JNIEnvironment::ctor@[tid=20382]
02-22 17:19:00.061 D/AudioManager: ctor@[tid=20382]
02-22 17:19:00.061 D/JVM: JNIEnvironment::RegisterNatives(org/webrtc/voiceengine/WebRtcAudioManager)
02-22 17:19:00.061 D/JVM: NativeRegistration::ctor@[tid=20382]
02-22 17:19:00.061 D/JVM: NativeRegistration::NewObject@[tid=20382]
02-22 17:19:00.062 I/org.webrtc.Logging: WebRtcAudioManager: ctor@[name=Thread-14, id=19965]
02-22 17:19:00.063 I/org.webrtc.Logging: WebRtcAudioManager: Sample rate is set to 48000 Hz
02-22 17:19:00.081 I/org.webrtc.Logging: WebRtcAudioEffects: canUseAcousticEchoCanceler: true
02-22 17:19:00.081 I/org.webrtc.Logging: WebRtcAudioEffects: canUseAutomaticGainControl: false
02-22 17:19:00.082 I/org.webrtc.Logging: WebRtcAudioEffects: canUseNoiseSuppressor: true
02-22 17:19:00.085 D/AudioManager: OnCacheAudioParameters@[tid=20382]
02-22 17:19:00.085 D/AudioManager: hardware_aec: 1
02-22 17:19:00.085 D/AudioManager: hardware_agc: 0
02-22 17:19:00.085 D/AudioManager: hardware_ns: 1
02-22 17:19:00.085 D/AudioManager: low_latency_output: 1
02-22 17:19:00.085 D/AudioManager: low_latency_input: 1
02-22 17:19:00.085 D/AudioManager: pro_audio: 1
02-22 17:19:00.085 D/AudioManager: sample_rate: 48000
02-22 17:19:00.085 D/AudioManager: channels: 1
02-22 17:19:00.085 D/AudioManager: output_buffer_size: 192
02-22 17:19:00.085 D/AudioManager: input_buffer_size: 192
02-22 17:19:00.085 D/JVM: GlobalRef::ctor@[tid=20382]
02-22 17:19:00.085 D/AudioManager: JavaAudioManager::ctor@[tid=20382]
02-22 17:19:00.085 D/AudioManager: IsLowLatencyPlayoutSupported()
02-22 17:19:00.086 D/AudioManager: IsLowLatencyRecordSupported()
02-22 17:19:00.086 D/OpenSLESPlayer: ctor@[tid=20382]
02-22 17:19:00.086 D/OpenSLESRecorder: ctor@[tid=20382]
02-22 17:19:00.086 D/AudioManager: SetActiveAudioLayer(6)@[tid=20382]
02-22 17:19:00.086 D/AudioManager: delay_estimate_in_milliseconds: 50
02-22 17:19:00.086 D/OpenSLESPlayer: AttachAudioBuffer
02-22 17:19:00.086 D/OpenSLESPlayer: SetPlayoutSampleRate(48000)
02-22 17:19:00.086 D/OpenSLESPlayer: SetPlayoutChannels(1)
02-22 17:19:00.086 D/OpenSLESPlayer: AllocateDataBuffers
02-22 17:19:00.086 D/OpenSLESPlayer: native buffer size: 384
02-22 17:19:00.086 D/OpenSLESPlayer: native buffer size in ms: 4.00
02-22 17:19:00.086 D/OpenSLESPlayer: required buffer size: 1344
02-22 17:19:00.086 D/OpenSLESRecorder: AttachAudioBuffer
02-22 17:19:00.086 D/OpenSLESRecorder: SetRecordingSampleRate(48000)
02-22 17:19:00.086 D/OpenSLESRecorder: SetRecordingChannels(1)
02-22 17:19:00.086 D/OpenSLESRecorder: AllocateDataBuffers
02-22 17:19:00.086 D/OpenSLESRecorder: frames per native buffer: 192
02-22 17:19:00.086 D/OpenSLESRecorder: frames per 10ms buffer: 480
02-22 17:19:00.086 D/OpenSLESRecorder: bytes per native buffer: 384
02-22 17:19:00.086 D/OpenSLESRecorder: native sample rate: 48000
02-22 17:19:00.088 D/AudioManager: Init@[tid=20382]
02-22 17:19:00.088 I/org.webrtc.Logging: WebRtcAudioManager: init@[name=Thread-14, id=19965]
02-22 17:19:00.089 I/org.webrtc.Logging: WebRtcAudioManager: audio mode is: MODE_NORMAL
02-22 17:19:00.092 D/OpenSLESPlayer: Init@[tid=20382]
02-22 17:19:00.092 D/OpenSLESRecorder: Init@[tid=20382]
02-22 17:19:00.092 D/OpenSLESRecorder: EnableBuiltInAEC(1)
02-22 17:19:00.092 E/OpenSLESRecorder: Not implemented
02-22 17:19:00.092 D/OpenSLESRecorder: EnableBuiltInNS(1)
02-22 17:19:00.092 E/OpenSLESRecorder: Not implemented
02-22 17:19:00.107 D/room: 1-trying to connect to room 39f1db22-c833-476d-9870-1c1c01b780e2
02-22 17:19:00.247 D/room: 2-trying to connect to room 39f1db22-c833-476d-9870-1c1c01b780e2
02-22 17:19:00.257 D/TwilioVideo: [Core]:AsyncIOWorker::AsyncIOWorker()
02-22 17:19:00.258 D/TwilioVideo: [Core]:SipSignalingStackImpl::SipSignalingStackImpl()
02-22 17:19:00.258 I/TwilioVideo: [Core]:Starting async I/O worker runloop, using method: epoll
02-22 17:19:00.259 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x20 in tid 19048 (inic.androidapp)
                           
                           [ 02-22 17:19:00.259   366:  366 W/         ]
                           debuggerd: handling request: pid=19048 uid=10232 gid=10232 tid=19048`

**Comment by aaalaniz** [comment]
Does this crash occur in the quickstart for any of your devices?

**Comment by KarimAbdo** [comment]
Hello, 
I think i found the problem.
I tried the quickstart and it works and then return to my code and it didn't. then to cut some testing time i hard coded the twilio token which is generated from the online generator and suddenly, IT WORKS!

I think for some reason there is some inconsistency between android and other clients on parsing the access token.

Our backend generates the access token with video grant AND conversation because we are currently supporting both till we have a stable version.

Our python library is 5.6

**Comment by aaalaniz** [comment]
Hey @KarimAbdo 

Glad you were able figure out the issue. Can you see if you are able to reproduce #59 with 1.0.0-beta9? We introduced some bug fixes for the scenario that you described in 1.0.0-beta8. I will investigate token generation with both a conversation and video grant. This should be pretty easy to reproduce locally.

Thanks

**Comment by KarimAbdo** [comment]
That was on beta9, sorry for not mentioning that detail

**Comment by aaalaniz** [comment]
@KarimAbdo I investigated the token you sent me and you appeared to have encountered a known issue when a token contains a number for an identity. We have fixed this issue already, but have not released a version with the fix. We should have a release out soon. As a workaround, you can convert your identity to a `String`.

**Comment by aaalaniz** [comment]
@KarimAbdo We released `1.0.0-beta6` which should fix the token issues you have reported. Please confirm and close the ticket if you can.

Thanks!
