### ISSUE TITLE
No receiving incoming call notification on android. How can we test the Twilio and Firebase integration to make sure Twilio is requesting notification?

### ISSUE THREAD

**Issue by salman-pixarsart** [twilio/video-quickstart-android#602]
I'm trying to create a calling app in react-native. Outbound are working fine using SDKs but no calls notifications are being received. I've cross-checked all the steps required to receive incoming calls but still not able to receive calls on the android instead calls are being redirected to my web app.

ACCOUNT_SID, API_KEY, API_KEY_SECRET, APP_SID, PUSH_CREDENTIAL_SID cross-checked and added on the server-side. On the android app, FCM is being registered and outbound calls are being made but still no luck.

#### Expected Behavior

There should be an incoming call notification when the called. 

#### Actual Behavior

No response on the android side.

#### Android API

26

#### Android Device

Samsung S7

**Comment by Alton09** [comment]
Hi @salman-pixarsart. Is this issue related to the Voice SDK? We currently don't support outbound push notifications on the Video SDK. Thanks!

**Comment by salman-pixarsart** [comment]
Yes, this issue is related to Voice SDK but It is fixed now. Thank you for your response.

**Comment by ArjunPatidar-numero** [comment]
@salman-pixarsart  @Alton09 , I'm having the same issue as you had, The same case with me I'm unable to receive notification on the receiver end, And also help me to integrate the incoming call ringing notification.
I have cross-checked all the ACCOUNT_SID, API_KEY, API_KEY_SECRET, APP_SID, PUSH_CREDENTIAL_SID.
I'm using the Twilio video invite
