### ISSUE TITLE
Question: What is used for NS and AEC if hardware based implementations don't exist?

### ISSUE THREAD

**Issue by timusus** [twilio/video-quickstart-android#610]
We're using custom hardware that does not ship with a hardware based Noise Suppressor or Acoustic Echo Canceller.

I'd like to know what implementation of NS and AEC the Twilio Android SDK falls back to, when hardware based implementations aren't available, and the WebRtc based versions are not explicitly enabled.

The following are confirmed via debugging:

`AcousticEchoCanceler.isAvailable()` returns false
`NoiseSuppressor.isAvailable()` returns false

`WebRtcAudioUtils.isAcousticEchoCancelerSupported()` returns false
`WebRtcAudioUtils.isNoiseSuppressorSupported()` returns false

`WebRtcAudioUtils.useWebRtcBasedNoiseSuppressor()` returns false
`WebRtcAudioUtils.useWebRtcBasedNoiseSuppressor()` retruns false

However, if we pass `AudioOptions` to the local video track, with NS and AEC explicitly disabled, via
```
AudioOptions.Builder()
    .noiseSuppression(false)
    .echoCancellation(false)
```
We notice a significant difference in sound quality (it's much noisier).

So, we haven't specifically asked for software based NS or AEC, but it seems to be functioning. 

So the question is, which implementation of software based NS/AEC is Twilio using when a hardware based implementation is not supplied, and the WebRTC based version is not explicitly enabled?

**Comment by Alton09** [comment]
@timusus Thanks for reaching out regarding this question. I'm honestly not sure off the top of my head, but I can investigate further to provide an answer.
