### ISSUE TITLE
Low volume heard at the received end of the call 

### ISSUE THREAD

**Issue by TeniGada123** [twilio/video-quickstart-android#616]
I have implemented the twilio video android call for connecting two participant. One participant uses the tablet and other participant uses the browser for receiving call on smartphone.

The Tablet side participant have speaker on. The issue is that other participant on browser side could hear participant with much low volume.

Can you help me with increase in microphone gain on Tablet side so that the audio sent to the receiver end could be high.

Please suggest me the reference to increase the gain of the microphone prior to transmitting the audio, or on the Smartphone end to increase the gain on the received audio.

**Comment by Alton09** [comment]
Hi @TeniGada123 . Are you running the android quickstart on the tablet or your own native android app? If you are running a native application, you can utilize the [AudioSwitch](https://github.com/twilio/audioswitch) library to set the receiving phone to speakerphone for louder audio. I'll have to double check on audio management regarding the browser.

**Comment by Alton09** [comment]
Hi @TeniGada123 . Closing this issue for now. Please reopen if you have additional questions. Thanks!
