### ISSUE TITLE
Move Twilio Video to MavenCentral

### ISSUE THREAD

**Issue by 4brunu** [twilio/video-quickstart-android#620]
Hi,
JCenter will shut down on May 1st. 
Could you please migrate all the existing versions to mavenCentral to remains usable in gradle?

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

I use an old version, and I will need to continue to use it, so it would be nice if you could publish also the old versions on mavenCentral.
This is the version that I'm currently using.
`implementation 'com.twilio:video-android:5.10.2'`

Thanks

**Comment by Alton09** [comment]
Hi @4brunu ! Thanks for reaching out regarding this issue. Great point! We are currently in the process of migrating all of our Android artifacts over to MavenCentral. We will notify folks when this happens, but you can expect the Android SDK artifacts to be available soon!

**Comment by 4brunu** [comment]
Hi @Alton09 thanks for replying :)
Are you planing also to migrate the old versions? For example 5.10.2?
Thanks

**Comment by Alton09** [comment]
Yes, we are planning to move the older versions as well including that version. So you are covered 👍

**Comment by 4brunu** [comment]
Thanks 😊
