### ISSUE TITLE
Move all Android Video SDK Releases to MavenCentral

### ISSUE THREAD

**Issue by Alton09** [twilio/video-quickstart-android#624]
Due to the upcoming [sunsetting of Bintray](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), we are in the process of moving all of the existing`video-android` and `video-android-ktx` aar release artifacts to Maven Central. New releases will also be published to Maven Central. Once this work is complete this issue will be closed.

**Comment by alexwillingham** [comment]
Just a note, com.twilio:video-android:6.2.1 depends on com.getkeepsafe.relinker:relinker:1.3.1 which is available only from jcenter.  It is not yet available from mavenCentral.

**Comment by Alton09** [comment]
Ah yes so we moved all of the SDK artifacts over to MavenCentral. This version contains a relinker dependency that is hosted on MavenCentral. Apologies, forgot to close this ticket as part of the release process.

https://search.maven.org/artifact/com.twilio/video-android/6.3.0/aar
https://search.maven.org/artifact/com.twilio/video-android-ktx/6.3.0/aar
