### ISSUE TITLE
Video Collaboration App link not working

### ISSUE THREAD

**Issue by IgorGanapolsky** [twilio/video-quickstart-android#632]
### Description
In your README it says
NEW: Please check out the newly open-sourced video collaboration app built with the Android Video SDK.

### Steps to Reproduce

1. Click on the link for Video Collaboration App in README
2. Observe 404 error

#### Expected Behavior
I expect to follow links from the README to valid resources.

#### Actual Behavior
404 Error

#### Reproduces how Often

100

#### Logs

```
// Log output when issue occurs
```

### Versions

All relevant version information for issue.

#### Video Android SDK

[eg. 1.0.2]

#### Android API

[eg. 18]

#### Android Device

[eg. Nexus 5]

**Comment by Alton09** [comment]
Thanks for calling that out @IgorGanapolsky ! I'll fix that here shortly...
