### ISSUE TITLE
Thumbnail overlapping in recyclerview when participants disconnected

### ISSUE THREAD

**Issue by AswinKumarSrk** [twilio/video-quickstart-android#636]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```java
// Code that help reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces how Often

[What percentage of the time does it reproduce?]

#### Logs

```
// Log output when issue occurs
```

### Versions

All relevant version information for issue.

#### Video Android SDK

[eg. 1.0.2]

#### Android API

[eg. 18]

#### Android Device

[eg. Nexus 5]

**Comment by AswinKumarSrk** [comment]
private class ThumbnailAdapter extends RecyclerView.Adapter<ThumbnailAdapter.MyViewHoler>{
        



        @NonNull
        @Override
        public ThumbnailAdapter.MyViewHoler onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
            View  view = LayoutInflater.from(parent.getContext()).inflate(R.layout.custom_thumbnail,parent,false);
            return new ThumbnailAdapter.MyViewHoler(view);
        }

        @Override
        public void onBindViewHolder(@NonNull ThumbnailAdapter.MyViewHoler holder, int position) {
//      
//            ConstraintLayout.LayoutParams cellParams = new ConstraintLayout.LayoutParams(screenwidth/2, (int) (screenheight/4.5));
//
//            holder.thumbnail_video_view.setLayoutParams(cellParams);


            if (remoteParticipantList.get(position).getRemoteVideoTracks().size() > 0) {
                RemoteVideoTrackPublication remoteVideoTrackPublication =
                        remoteParticipantList.get(position).getRemoteVideoTracks().get(0);
                if (!remoteVideoTrackPublication.isTrackEnabled()){
                    holder.video_disabled.setVisibility(View.VISIBLE);

                }
                else {
                    holder.video_disabled.setVisibility(View.GONE);

                }

                if (remoteVideoTrackPublication.isTrackSubscribed()){
                    remoteVideoTrackPublication.getVideoTrack().addRenderer(holder.thumbnail_video_view);
                    holder.progressBar.setVisibility(View.GONE);

                }
                else {


                    holder.progressBar.setVisibility(View.VISIBLE);

                }

            }
            RemoteAudioTrackPublication remoteAudioTrackPublication = remoteParticipantList.get(position).getRemoteAudioTracks().get(0);
            if (remoteAudioTrackPublication.getRemoteAudioTrack()!=null){
                if (remoteAudioTrackPublication.getAudioTrack().isEnabled()){
                    holder.text_onanothercall.setVisibility(View.GONE);

                }
                else {
                    holder.text_onanothercall.setVisibility(View.VISIBLE);

                }
                if(remoteAudioTrackPublication.getRemoteAudioTrack().isPlaybackEnabled()){

                    holder.mute_audio.setImageResource(R.drawable.ic_mic_white_24dp);
                }
                else {
                    holder.mute_audio.setImageResource(R.drawable.ic_mic_off_black_24dp);
                }
            }


            holder.mute_audio.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if(remoteAudioTrackPublication.getRemoteAudioTrack().isPlaybackEnabled()){
                        holder.mute_audio.setImageResource(R.drawable.ic_mic_off_black_24dp);

                        remoteAudioTrackPublication.getRemoteAudioTrack().enablePlayback(false);
                    }
                    else {

                        holder.mute_audio.setImageResource(R.drawable.ic_mic_white_24dp);
                        remoteAudioTrackPublication.getRemoteAudioTrack().enablePlayback(true);
                    }

                }
            });
            holder.itemView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    showPrimaryView(remoteParticipantList.get(position));
                }
            });
//            NetworkQualityLevel networkQualityLevel = remoteParticipantList.get(position).getNetworkQualityLevel();
//            if (networkQualityLevel == NetworkQualityLevel.NETWORK_QUALITY_LEVEL_UNKNOWN){
//
//                holder.text_strength.setText("Unknown");
//
//            }
//            else if (networkQualityLevel == NetworkQualityLevel.NETWORK_QUALITY_LEVEL_ZERO){
//                holder.text_strength.setText("0");
//            }
//            else if (networkQualityLevel == NetworkQualityLevel.NETWORK_QUALITY_LEVEL_ONE){
//                holder.text_strength.setText("1");
//            }
//            else if (networkQualityLevel == NetworkQualityLevel.NETWORK_QUALITY_LEVEL_TWO){
//                holder.text_strength.setText("2");
//            }
//            else if (networkQualityLevel == NetworkQualityLevel.NETWORK_QUALITY_LEVEL_THREE){
//                holder.text_strength.setText("3");
//            }
//            else if (networkQualityLevel == NetworkQualityLevel.NETWORK_QUALITY_LEVEL_FOUR){
//                holder.text_strength.setText("4");
//            }
//            else if (networkQualityLevel == NetworkQualityLevel.NETWORK_QUALITY_LEVEL_FIVE){
//                holder.text_strength.setText("5");
//            }

//            holder.itemView.setOnClickListener(new View.OnClickListener() {
//                @Override
//                public void onClick(View v) {
//                    RemoteVideoTrackPublication remoteVideoTrackPublication =
//                            remoteParticipantList.get(position).getRemoteVideoTracks().get(0);
//                    if(remoteVideoTrackPublication.isTrackSubscribed()){
//                        remoteVideoTrackPublication.getVideoTrack().removeRenderer(holder.thumbnail_video_view);
//
//                    }
//                    else {
//                        remoteVideoTrackPublication.getVideoTrack().addRenderer(holder.thumbnail_video_view);
//
//
//                    }
//
//                }
//            });

//                }

//            }

        }

        @Override
        public int getItemCount() {
            return remoteParticipantList.size();


        }

        public class MyViewHoler extends RecyclerView.ViewHolder {
            VideoTextureView thumbnail_video_view;
            ProgressBar progressBar;
            TextView text_onanothercall,text_strength;
            ImageView video_disabled,mute_audio;
            public MyViewHoler(@NonNull View itemView) {
                super(itemView);
                thumbnail_video_view= itemView.findViewById(R.id.thumbnail_video_view);
                progressBar = itemView.findViewById(R.id.progressBar);
                text_onanothercall = itemView.findViewById(R.id.text_onanothercall);
                video_disabled = itemView.findViewById(R.id.video_disabled);
                mute_audio = itemView.findViewById(R.id.mute_audio);
                text_strength = itemView.findViewById(R.id.text_strength);

            }
        }

        public void addThumbnail(RemoteParticipant remoteParticipant){
            remoteParticipantList.add(remoteParticipant);
            thumbnailAdapter.notifyDataSetChanged();

//            notifyItemInserted(thumbnailAdapter.getItemCount()+1);
//            if(remoteParticipantList.size()==1){
//                ConstraintLayout.LayoutParams cellParams = new ConstraintLayout.LayoutParams(screenwidth, (int) (screenheight/3));
//                primaryVideoView.setLayoutParams(cellParams);
//            }


        }

        @Override
        public int getItemViewType(int position) {
            return position;
        }
    }

**Comment by afalls-twilio** [comment]
@AswinKumarSrk thank you for the submission and sorry about the very delayed response. Was this an issue with the quickstart application or the Ahoy applicaiton?

**Comment by afalls-twilio** [comment]
closing due to a lack of response
