### ISSUE TITLE
SurfaceTextureHelper crashing due to 0 texture width

### ISSUE THREAD

**Issue by dylanrjames** [twilio/video-quickstart-android#639]
### Description

We're seeing a rare crash during calls which seems to stem specifically from Twilio code, with very little context on what's going on since it's specifically within the `AndroidVideoDecoder` on a separately scheduled thread. Stack trace is:

```
Fatal Exception: java.lang.IllegalArgumentException: Texture width must be positive, but was 0
       at tvi.webrtc.SurfaceTextureHelper.setTextureSize(SurfaceTextureHelper.java:252)
       at tvi.webrtc.AndroidVideoDecoder.deliverTextureFrame(AndroidVideoDecoder.java:436)
       at tvi.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:411)
       at tvi.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:373)
```

We recently updated to Twilio 6.3.0 and implemented group calls/rooms, so it's unclear which this is stemming from.

I'll also note that the other "participants" in the room may be connecting from Android, iOS, or Mac OS via the Web, though the majority of them are Mac OS Web users.

### Steps to Reproduce

I don't have any way to reliably reproduce this, it has happened around 5-8 times over a few weeks but I can't find any common threads or single cause. I will note that we've only seen this for a single user/device, but our code is currently in a somewhat small beta so I'm not sure if that's relevant.

It has happened both in the middle of a call, and when first joining a call.

#### Code

I don't think this is relevant, but we do include the code mentioned in [this issue](https://github.com/twilio/video-quickstart-android/issues/470#issuecomment-745567407) and the device where we're seeing this crash is one where we use this code. I did try adding code to check for 0 width/height in these cases and try to "bottom out" to something non-zero, but that code doesn't seem to have detected a 0 there, so it's never fired and makes me think this "workaround" isn't relevant. Also, there are other devices is our testing group that would be running this code, and none of them have experienced the issue.

#### Expected Behavior

Call video feeds should remain stable.

#### Actual Behavior

Something causes (what appears to be) a `VideoView` to crash when rendering incoming video at some points.

#### Reproduces how Often

This has happened 5-8 times for the same user who has done ~15 hours of video calls. We probably have over another 60 hours of video calls across other Android users and haven't seen this issue anywhere else. It is worth noting that the single user who encountered this is the only Pixel 4 XL we've tested on. We have a few other Pixel devices (2 XL, 3, 4a, 5) though none of them have ever encountered the issue. This user definitely has the most usage though.

#### Logs

I have a full Android Bug Report for one instance of this, but none of the logs around the crash are anything interesting - mostly `chatty` expiring lines. I don't see anything else interesting.

```
05-12 12:00:51.306 10394 15805 11171 E AndroidRuntime: FATAL EXCEPTION: AndroidVideoDecoder.outputThread
05-12 12:00:51.306 10394 15805 11171 E AndroidRuntime: Process: com.pmdsoft.android, PID: 15805
05-12 12:00:51.306 10394 15805 11171 E AndroidRuntime: java.lang.IllegalArgumentException: Texture width must be positive, but was 0
05-12 12:00:51.306 10394 15805 11171 E AndroidRuntime: 	at tvi.webrtc.SurfaceTextureHelper.setTextureSize(SurfaceTextureHelper.java:252)
05-12 12:00:51.306 10394 15805 11171 E AndroidRuntime: 	at tvi.webrtc.AndroidVideoDecoder.deliverTextureFrame(AndroidVideoDecoder.java:436)
05-12 12:00:51.306 10394 15805 11171 E AndroidRuntime: 	at tvi.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:411)
05-12 12:00:51.306 10394 15805 11171 E AndroidRuntime: 	at tvi.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:373)
```

This specific instance happened in room d5642f76-0c74-4849-ae9c-ecd6a549e7a1 on 5/12/21 at 12:00:51 EST

#### Video Android SDK

com.twilio:video-android:6.3.0

#### Android API

Android 11

#### Android Device

Pixel 4 XL

**Comment by Alton09** [comment]
Hi @dylanrjames ! Thanks for filing this issue. It looks like this is a bug in the underlying WebRTC code as reported [here](https://bugs.chromium.org/p/webrtc/issues/detail?id=12492). There is a patch fix for this and we will work on applying it in one of our upcoming sprints.

**Comment by dylanrjames** [comment]
Hi @Alton09 ! Thanks for the quick response - I'm glad to hear it's a known issue and you all are working on it!

WebRTC is a bit outside my realm of expertise... It looks to me like that issue is pointing at an issue in HW VP8 decoding, which would make this isolated to streams coming in from other devices that are sending VP8 data... Correct?

Is there any current workaround I can use in the meantime? Are there older versions of Twilio I could roll back to that don't hit this crash? Can I force SW VP8 on these devices or anything?

**Comment by Alton09** [comment]
No problem @dylanrjames ! In the meantime, you can certainly change the preferred video codec that WebRTC will use when connecting to a video room. This can be achieved by passing in another codec type (like H264 or VP9) into the ConnectOptions Builder [preferredVideoCodecs(...) method](https://twilio.github.io/twilio-video-android/docs/latest/com/twilio/video/ConnectOptions.Builder.html#preferVideoCodecs-java.util.List-) before calling `Video.connect()`. Make sure to do this on every device that connects to the room though to ensure a specific codec is used.

**Comment by dylanrjames** [comment]
Hey @Alton09 - is there any sort of update on timing here? Unfortunately changing every single client to connect with a different video codec isn't an option for us (running on multiple platforms, most of which are mobile apps so deploying something like that isn't really feasible) so we're pretty much waiting on this fix.

We jumped from Twilio 5.12.0 to 6.3.0, while also adding a lot of video features... Is there any way to know where this bug was introduced so we can possibly roll back to avoid it? Do you know if this bug existed in 6.0 etc? It's not clear to me if this has to do with our upgrading of the Twilio library or possibly something else about changes to the way we're using `VideoView` etc.

**Comment by Alton09** [comment]
> Hey @Alton09 - is there any sort of update on timing here? Unfortunately changing every single client to connect with a different video codec isn't an option for us (running on multiple platforms, most of which are mobile apps so deploying something like that isn't really feasible) so we're pretty much waiting on this fix.

That is totally understandable @dylanrjames . We'll do our best to get this fix in our next sprint, so in the next couple of weeks.

> We jumped from Twilio 5.12.0 to 6.3.0, while also adding a lot of video features... Is there any way to know where this bug was introduced so we can possibly roll back to avoid it? Do you know if this bug existed in 6.0 etc? It's not clear to me if this has to do with our upgrading of the Twilio library or possibly something else about changes to the way we're using VideoView etc.

I'm not sure if this was introduced in 6.x from 5.x. I'll have to dig deeper into the WebRTC source to give you an answer here. Thanks for your patience and expect to have a fix for this soon.

**Comment by dylanrjames** [comment]
@Alton09 and anyone else for future reference - I was able to find a "reproduction case" of sorts that exhibits the same behavior... If I have another client in the room using VP8, and repeatedly unpublish/release the local video track and recreate/republish it, I'm able to reproduce this behavior intermittently. It doesn't happen with every publication, but if I do it every second or two for 2 minutes or so, eventually the Pixel device will crash.

Anecdotally, this seems to _usually_ happen when someone is first joining a group room with VP8, though it some times happens in the middle of a meeting too.

I reverted to 5.12 and I'm not able to reproduce this with the same steps, so I assume it's not an issue in that version. This seems isolated to 6.x.

**Comment by Alton09** [comment]
We have added the patch to a development branch and working on cutting a release soon. I'll be sure to update this issue as soon as it's released.

**Comment by Alton09** [comment]
Hi @dylanrjames ! We have a fix for this issue in our latest Android SDK release, [6.3.1](https://www.twilio.com/docs/video/changelog-twilio-video-android-v6#631june-24th-2021). Please upgrade to this version and let us know if this resolves your issue. Thanks for your patience on this one!

**Comment by dylanrjames** [comment]
6.3.1 seems to have fixed the issue! Thank you @Alton09!

**Comment by Alton09** [comment]
Nice! Glad to hear your issue is now resolved 😃
