### ISSUE TITLE
On back Button press call disconnect

### ISSUE THREAD

**Issue by metizror** [twilio/video-quickstart-android#644]
We implement video calls in our app. And it's working fine. But when we press the back button the call disconnect. it's working when the app was in the background. So anyway to continue to call even user presses the back button still call should not be disconnect?

**Comment by Alton09** [comment]
Hi @metizror. Thanks for reaching out! It is a common user experience to disconnect from a video room after the user presses the hardware back button. However, if the user backgrounds the app by pressing the home hardware button (or gestures on newer devices) the video room should also be run in the background. I would highly recommend following this approach for a good UX for Android users. However, if your use case requires not disconnecting from a video room when pressing the hardware back button, then one option is to override the default back press behavior. Here are a couple ways to do this:
https://developer.android.com/reference/androidx/activity/OnBackPressedDispatcher
https://stackoverflow.com/questions/3141996/android-how-to-override-the-back-button-so-it-doesnt-finish-my-activity
