### ISSUE TITLE
Required parameter \"opts.bindingType\" missing.

### ISSUE THREAD

**Issue by vipul1411** [twilio/video-quickstart-android#645]
We are using Twilio Quickstart VideoInvite and facing issue while binding. Hereby I am sharing my log response below :

{
    "message": "Required parameter \"opts.bindingType\" missing.",
    "name": "Error",
    "stack": "Error: Required parameter \"opts.bindingType\" missing.\n    at Function.create (/var/task/node_modules/twilio/lib/rest/notify/v1/service/binding.js:90:13)\n    at Object.exports.handler (/var/task/handlers/ZF487cafdee38d8357b133e5119b71cb56.js:14:21)\n    at Object.exports.handler (/var/task/node_modules/enigma-lambda/index.js:310:10)\n    at Runtime.exports.handler (/var/task/enigma.js:17:9)\n    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
}

My request body is :

{"address":"dMNTyLWjPnQ:APA91bGyjSx81xmjOUgsTSEDOivvQK26ZY5d_OKkGkGgNA4xGwTZ6iKgyjscq1gntFN5QIQVroVjr6dfzdx0Yj_Z4K3s-rtQYEtCDI-dpK_W5qCoLZC4EIjRr527biYMrIDejlkI-3ON","bindingType":"fcm","endpoint":"Sid@dMNTyLWjPnQ","identity":"Sid","tag":["video"]}

Any help is appreciated.

**Comment by sagarpatel288** [comment]
We are also getting the same issue while trying to send custom push notifications.
