### ISSUE TITLE
Crash when using VideoTextureView: java.lang.RuntimeException: Failed to create EGL context: 0x3003

### ISSUE THREAD

**Issue by edenman** [twilio/video-quickstart-android#652]
### Description

Joined a call with five participants.  App crashed after a few minutes in the call.  Now when I try to rejoin the call the app crashes immediately with the same error.  Not fixed by a reboot.

#### Reproduces how Often

100%

#### Logs

[egl-crash.txt](https://github.com/twilio/video-quickstart-android/files/6773225/egl-crash.txt)

### Versions

com.twilio:audioswitch:1.1.2
com.twilio:video-android:6.3.0

#### Android API

30

#### Android Device

Pixel 4

**Comment by edenman** [comment]
Do I need to be explicitly releasing EGL contexts or something?

**Comment by Alton09** [comment]
Thanks for reaching out regarding this issue @edenman ! Does this crash occur only when there are five participants in a room? Also, does this crash only occur on a Pixel 4 running API 30? Can you also try upgrading to the latest version of the SDK, `6.3.1`, to see if it resolves the issue?

**Comment by edenman** [comment]
1) It's not specific to the number of people in the room afaict
2) Not limited to this phone.   Has also happened to coworkers on Samsung SM-G970U1 (api 29) and SM-N960U1 (api 30)

I'll try updating to 6.3.1 but the [release notes](https://www.twilio.com/docs/video/changelog-twilio-video-android-v6) don't seem relevant to this issue.  Was there another fix that wasn't mentioned in the release notes?

**Comment by edenman** [comment]
Still happening on 6.3.1.  I think there's a couple things going on here:

1) I am probably creating too many EGL contexts.  Is there any way to see in the logs when a new EGL context is created?  Or how should I best track down the source of too many being created?
2) `VideoTextureView` shouldn't eagerly create the EGL context.  In my case, I have the view as part of the hierarchy but it might not be in use (if the participant has video turned off, for instance).  AFAICT this still takes up one EGL context 
3) If my app crashes while in a video call, it looks like none of the EGL contexts are released, causing an immediate crash when I try to rejoin the room

#1 is likely a bug in my code.  If you can provide any advice on tracking this down I'd appreciate it.
I argue that #2 is a bug in the SDK.  I can try to work around this by using a ViewStub but I don't think it'll help in this case since all the participants had video turned on.
#3 is *definitely* a bug in the twilio video SDK (or maybe webrtc itself?)

**Comment by edenman** [comment]
Oh and I guess 

4) ideally this shouldn't crash my app regardless of how many I create.  It would be great if the Twilio SDK caught the exception and just surfaced somehow that video couldn't be shown.

**Comment by Alton09** [comment]
Thanks for trying out `6.3.1`. No, the only fix was included in the release notes. Thought I'd let you know a new version is out to fix an annoying decoder issue on Pixel devices 😄 

> 1. I am probably creating too many EGL contexts. Is there any way to see in the logs when a new EGL context is created? Or how should I best track down the source of too many being created?

There are some logs you can search for to see information about Egl contexts and more information about active renderers. Type EGL into your logcat filter and enable the SDK logs with `Video.setLogLevel(LogLevel.DEBUG);` within your application.

> 2. VideoTextureView shouldn't eagerly create the EGL context. In my case, I have the view as part of the hierarchy but it might not be in use (if the participant has video turned off, for instance). AFAICT this still takes up one EGL context
I see what you are see

Yes there is probably room for improvement here by only using a context when the view is actually visible to the user. Is this impacting your app in a negative way?

> 3. If my app crashes while in a video call, it looks like none of the EGL contexts are released, causing an immediate crash when I try to rejoin the room

Have you tried creating and releasing the contexts similar to how the `VideoTextureView` is doing it within these view lifecycle methods?

```
    @Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
        // Do not setup the renderer when using developer tools to avoid EGL14 runtime exceptions
        if (!isInEditMode()) {
            eglBaseProvider = EglBaseProvider.instance(this);
            init(eglBaseProvider.getRootEglBase().getEglBaseContext(), rendererEvents);
        }
    }

    @Override
    protected void onDetachedFromWindow() {
        eglRenderer.release();
        eglBaseProvider.release(this);
        super.onDetachedFromWindow();
    }
```

I don't believe this is a bug in the SDK as long as the `eglRenderer` and `eglBaseProvider` cleanup methods are called when they are no longer needed. I only say this because our [Twilio Video Android app](https://github.com/twilio/twilio-video-app-android) uses the VideoTextureView directly and we haven't experienced crashes related to this. It might help if you could share how exactly you are creating these contexts and how they are being used in your app so that way we can further troubleshoot your issue. Hope all this helps!

**Comment by edenman** [comment]
1) Connecting to a one-on-one video call, hooked up the debugger to see what is instantiating `EglBase14Impl` instances:
a) Video.connect() creates one (MediaFactory does `EglBaseProvider.instance(temporaryEglOwner)`)
b) SurfaceTextureHelper creates three `EglBase.create(sharedContext, EglBase.CONFIG_PIXEL_BUFFER);`
c) EglRenderer creates three `this.eglBase = EglBase.create(sharedContext, configAttributes);`
d) HardwareVideoEncoder creates one because `useSurfaceMode` is set: ` this.textureEglBase = EglBase.createEgl14(this.sharedContext, EglBase.CONFIG_RECORDABLE);`

If the device has a limit of 32 (as I've heard mentioned in other sources), you can see how this would easily be reached with additional participants.

2) This is impacting my app because it crashes my app, so yes I'd consider that a negative impact.
3a) onDetachedFromWindow isn't called if the app crashes, so adding cleanup code will not help
3b) I think the twilio SDK needs to look for orphaned contexts on initialization and clean them up somehow?
4) I am not creating any Egl contexts myself, it is entirely the twilio/webrtc SDK doing it.  I am connecting to a video room and adding the `VideoTextureView` as a sink on the `VideoTrack`s

**Comment by edenman** [comment]
For every new participant, I'm seeing EglRenderer create two contexts and SurfaceTextureHelper creates another.

**Comment by Alton09** [comment]
Thanks for the additional information here @edenman! It does indeed sound like an Egl context leak in the SDK. I'll file this one as a bug and try to allocate some time to dig into it further.

**Comment by edenman** [comment]
fwiw, if anybody else runs into this, here's what I'm doing as a semi-workaround:
```
// Thin wrapper around VideoTextureView that lets us delay creating the EGL context until it's
// actually needed (when we add it as a Sink).  Originally I just had this class implement VideoSink
// itself, but onFrame is called on a non-main thread so it can't lazily inflate the view.
class VideoView(context: Context, attrs: AttributeSet?) : FrameLayout(context, attrs) {
  var mirror: Boolean = false
    set(value) {
      // The built-in setter doesn't have a short-circuit and always forces a relayout, which was
      // the cause of some of our video flickering.  Filed https://github.com/twilio/video-quickstart-android/issues/650
      // but this is an easy workaround while we wait for twilio to fix it.
      if (field != value) {
        videoTextureViewIfInflated()?.let { view ->
          view.mirror = value
        }
        field = value
      }
    }

  val sink: VideoSink
    get() = ensureVideoTextureView()

  fun removeVideoTextureView() {
    videoTextureViewIfInflated()?.let { textureView ->
      removeAllViews()
    }
  }

  private fun ensureVideoTextureView(): VideoTextureView {
    if (childCount == 0) {
      inflate(context, R.layout.video_view_contents, this)
      val textureView = videoTextureViewIfInflated().require("Not set after inflation?")
      textureView.mirror = mirror
      return textureView
    } else {
      return videoTextureViewIfInflated().require("Child is wrong type? ${getChildAt(0)}")
    }
  }

  private fun videoTextureViewIfInflated(): VideoTextureView? {
    return getChildAt(0) as? VideoTextureView
  }
}
```
This doesn't fix the "if the app crashes, egl contexts aren't released" problem, but it seems to keep the leak/crash from happening in the first place.

**Comment by afalls-twilio** [comment]
@edenman  and others, is this still an issue? (I realize the ticket is 2 years old).

**Comment by ocarevs** [comment]
@edenman We have been unable to reproduce this on our side. Is this still happening on latest version of the SDK; if so, is it possible for you to provide more extensive logs of when the crash happens?

**Comment by edenman** [comment]
I’m not at that job anymore, no way to verify or provide more logs
