### ISSUE TITLE
Unpublishing and republishing a Video track / Audio track might not be seen by Participants

### ISSUE THREAD

**Issue by akashvyasal** [twilio/video-quickstart-android#653]
### Description

I am using twillio flutter sdk for the twillio video call task. Inside that sdk, they are using Android twillio sdk v5.12.+. I am facing the issue of unpublishing/republishing a video track/audio track not seen by another participant. Please check the details below.

Flow: One participant has joined the session from the Android side and one participant is joining the session from the Web side(Developed in React). Once the user is unpublish and publishes the video track from React side, On the Android side this is not reflecting. I have debugged sdk and able to see those methods for unpublishVideostream and publish video stream are getting called and inside that, I am able to see new VideoTrack/AudioTrack but it is not seen in device.

### Steps to Reproduce

One participant has joined the session from the Android side and one participant is joining the session from the Web side(Developed in React). Once the user is unpublish and publishes the video track from React side, On the Android side this is not reflecting. I have debugged sdk and able to see those methods for unpublishVideostream and publish video stream are getting called and inside that, I am able to see new VideoTrack/AudioTrack but it is not seen in device.

#### Expected Behavior

By unpublish or republish the video stream, it should reflect that change.

#### Actual Behavior

By unpublish or republish the video stream, The new stream is not reflacting.

#### Reproduces how Often

Every time

#### Logs
RemoteParticipantListener.onVideoTrackUnsubscribed => trackSid: MT3ca25bf7c6927922da6166ca56c6dca2, isTrackEnabled: true, isTrackSubscribed: false
RemoteParticipantListener.onVideoTrackUnpublished => trackSid: MT3ca25bf7c6927922da6166ca56c6dca2, isTrackEnabled: true, isTrackSubscribed: false
RemoteParticipantListener.onVideoTrackSubscribed => trackSid: MT3ca25bf7c6927922da6166ca56c6dca2, isTrackEnabled: true, isTrackSubscribed: true

### Similar issue from the ios side

Link: https://github.com/twilio/twilio-video-ios/issues/34

#### Video Android SDK

Version: 5.12.+

#### Android API

Android version: 30

#### Android Device

Device: Realme1

#### Video React SDK

Version: 2.15.1

Could anyone please help me to find the exact cause? Thanks in advance.

Sdk link: https://github.com/twilio/twilio-video.js/

**Comment by afalls-twilio** [comment]
@akashvyasal Thank you for the bug report. Is this with the Javascript SDK running on the Android browser? If not, are you experiencing this issue with more recent versions, such as 7.1.0?

**Comment by akashvyasal** [comment]
Hello @afalls-twilio ,

Thank you for the response.

Javascript SDK is running on the website, not Android. We are joining video sessions from the web and Android. I have checked it with the version mentioned in the comment. Though I will check again with the version we are currently using and get back to you.

Thanks,

**Comment by flipper09112** [comment]
@akashvyasal you have some workaround for this issue?
