### ISSUE TITLE
RemoteParticipant.Listener events received after disconnecting from room

### ISSUE THREAD

**Issue by edenman** [twilio/video-quickstart-android#654]
### Description

When I disconnect from a `Room`, I would expect that no more events would be fired on the various listeners.

### Steps to Reproduce

1. Call `Room.disconnect()`
2. Notice more events coming on the participant listeners

#### Video Android SDK

6.3.1

#### What I want to happen

Either:
1) Change the SDK so it doesn't send any more events after calling `Room.disconnect()`
2) Allow un-setting the `RemoteParticipant.Listener`.  Right now the SDK crashes if you call `setListener(null)`

**Comment by edenman** [comment]
Would also be great to make `Room.Listener` not send any events after disconnect

**Comment by afalls-twilio** [comment]
@edenman Sorry about the late response, we have fixed similar bugs in our most recent 7.3.0 release. Please try it out and let us know if the issue persists.

**Comment by edenman** [comment]
I no longer work at the company that was using this SDK, sorry!  Feel free to close this if you think it's fixed
