### ISSUE TITLE
Old video frame is shown on view even after sink is removed

### ISSUE THREAD

**Issue by edenman** [twilio/video-quickstart-android#655]
### Description

When removing a sink from a VideoTrack, the last frame is still shown on the view until the next onFrame call

### Steps to Reproduce

1. Set up two VideoTextureViews, `A` and `B`
2. Create a `LocalVideoTrack` called `myVideo` and start capturing from the camera.
3. Call `myVideo.addSink(A)` and confirm camera video is shown on view `A`
3. Join a call.
4. Get a remote participant video track `otherVideo`
5. Call `myVideo.removeSink(A)` and `myVideo.addSink(B)` and `otherVideo.addSink(A)`

#### Expected Behavior

The local video is shown on A, B shows an empty black frame while waiting for the other track's frames

#### Actual Behavior

The local video is correctly shown on B, but it also still shows on A for a couple seconds while we're waiting for the other video track's frames

#### Reproduces how Often

100%

#### Video Android SDK

6.3.1

**Comment by atonoyan** [comment]
Hello,
I am facing the same issue.
Have you got this resolved anyhow?

**Comment by afalls-twilio** [comment]
@atonoyan @edenman Sorry for the incredibly late response... Is this still an issue with later SDK versions?

**Comment by afalls-twilio** [comment]
@atonoyan This issue can be worked around...  When sink is removed, call `onFrame(...)` with a video frame constructed with a black frame... example...


```
private fun provideBlankFrameBuffer(width: Int, height: Int): I420Buffer {
        val chromaHeight: Int = (height + 1) / 2
        val strideUV: Int = (width + 1) / 2
        val yPos = 0
        val uPos: Int = yPos + width * height
        val vPos = uPos + strideUV * chromaHeight
        val buffer = JniCommon.nativeAllocateByteBuffer(width * height + 2 * strideUV * chromaHeight)

        for (i in 0 until uPos) {
            buffer.put(0)
        }
        for (i in uPos until buffer.capacity()) {
            buffer.put(-127)
        }
        buffer.rewind()

        buffer.position(yPos)
        buffer.limit(uPos)
        val dataY = buffer.slice()
        buffer.position(uPos)
        buffer.limit(vPos)
        val dataU = buffer.slice()
        buffer.position(vPos)
        buffer.limit(vPos + strideUV * chromaHeight)
        val dataV = buffer.slice()
        return JavaI420Buffer.wrap(
            width,
            height,
            dataY,
            width,
            dataU,
            strideUV,
            dataV,
            strideUV,
            Runnable {
                JniCommon.nativeFreeByteBuffer(
                    buffer
                )
            })
    }```
...
```            
            localVideoTrack?.removeSink(uiBinding.videoViewA)
            uiBinding.videoViewA.onFrame(
                VideoFrame(provideBlankFrameBuffer(320, 340), 0, 0))```

**Comment by afalls-twilio** [comment]
@atonoyan  This issue will be fixed in the next coming release.
