### ISSUE TITLE
Add mechanism to forward logs to another destination

### ISSUE THREAD

**Issue by edenman** [twilio/video-quickstart-android#657]
I'd like to add the Twilio/webrtc logs to breadcrumbs on Sentry events so I can get more information about why/when crashes happen.  AFAICT there's no way to reroute the logs from the default logcat output.  It would be great if there was.

#### Video Android SDK

6.3.1

**Comment by afalls-twilio** [comment]
While it would be nice, we do not have plans for this on our roadmap unfortunately. I will keep you informed if things change.
