### ISSUE TITLE
VP8 Simulcast Only Publishes One Simulcast Layer

### ISSUE THREAD

**Issue by Alton09** [twilio/video-quickstart-android#660]
### Description

As of 6.0.0 of the SDK, hardware video encoding doesn't publish all of the three simulcast layers when VP8 simulcast is enabled on Android.
This affects Video Content Preferences feature from working properly for subscribing video participants since the feature requires all three simulcast layers to switch between.
Our team is working on a fix for this, but the feature does work when VP8 simulcast is used to publish video from participants using the Javascript or iOS SDKs.

#### Video Android SDK

6.x

**Comment by afalls-twilio** [comment]
@Alton09 This is known issue, infact simulcast isn't supported with hw encoding. In the near feature this will change though.
