### ISSUE TITLE
Screen Capture flickering (Not Working)

### ISSUE THREAD

**Issue by pkdhankher** [twilio/video-quickstart-android#666]
### Video Reference of Issue/Bug
[Issue Video Reference Link](https://drive.google.com/file/d/14JViK-riMSO7IGW4F2cvO-jusdcjcEJb/view?usp=sharing)

P.S.  Please download and watch the video 

### Versions

All relevant version information for the issue.

#### Video Android SDK

[eg. 5.11.1, 6.4.0]

#### Tested Android Devices
Emulators-
[1. Nexus 4 API - 24]
[2. Nexus 4 API - 24]

Real Android Devices-
[1. OnePlus 7 (Android 11)]
[2.Samsung M30 (Android 11)]

**Comment by RumitPatel** [comment]
Hi @pkdhankher , I refer quick start sample and facing the same issue. Did you get any solution?

**Comment by pkdhankher** [comment]
Hey @RumitPatel , it's not an issue. The SDK is simply capturing its own frames, which seems some flickering. However, it's working perfectly fine. Just try using it in a real scenario, and it should work without any problems.

**Comment by RumitPatel** [comment]
Thanks, @pkdhankher for the prompt response :-) . I will check that out.
