### ISSUE TITLE
After switching from the font camera to the back camera, the next click on any button get's ignored.

### ISSUE THREAD

**Issue by 4brunu** [twilio/video-quickstart-android#670]
### Description

After switching from the font camera to the back camera, the entire screen ignores the next touch.
It's like if an invisible view swallows the next click and then disappears.
The setOnClickListener method of any button displayed on the screen is not called.
This doesn't happens after switching from the back camera to the front camera.
This issue only happens when using camera2 api `camera2Capturer.switchCamera(nextCameraId)`.

### Steps to Reproduce

For example, imagine that I want to change between the front and back cameras several times.

- I'm in the front camera
- I click the button to switch camera
- It changes to the back camera
- I click the button to switch camera 
- But nothing happens! The setOnClickListener method of the button is not called.
- I click the button to switch camera again and now is works.
- It changes to the front camera
- I click the button to switch camera
- It changes to the back camera
- I click the button to switch camera 
- But nothing happens! The setOnClickListener method of the button is not called.
- I click the button to switch camera again and now is works.
- It changes to the front camera
- I click the button to switch camera
- It changes to the back camera
- I click any button on the screen 
- But nothing happens! The setOnClickListener method of the button is not called.
...

#### Code

```java
        camera2Capturer.switchCamera(nextCameraId)

```

#### Expected Behavior

- I'm in the front camera
- I click the button to switch camera
- It changes to the back camera
- I click the button to switch camera 
- It changes to the front camera
- I click the button to switch camera
- It changes to the back camera
...

#### Actual Behavior

After switching from the font camera to the back camera, the entire screen ignores the next touch.
It's like if an invisible view swallows the next click and then disappears.
The setOnClickListener method of any button displayed on the screen is not called.
This doesn't happens after switching from the back camera to the front camera.
This issue only happens when using camera2 api `camera2Capturer.switchCamera(nextCameraId)`.

#### Reproduces how Often

Always.

### Versions

All relevant version information for issue.

#### Video Android SDK

6.2.1, 5.10.2, and maybe more

#### Android API

30

#### Android Device

~~On every device including the emulator~~ On the emulator, as long as it uses the camera2 api `camera2Capturer.switchCamera(nextCameraId)`.
EDIT: Looks like this only happens in the simulator and not on the devices, at least I couldn't reproduce this issue in any real device, but I can reproduce it in the simulator.

**Comment by afalls-twilio** [comment]
@4brunu is this still an issue? sorry for the very late response.

**Comment by 4brunu** [comment]
Looks like this is fixed with the last version of Twilio video android 7.5.1.
