### ISSUE TITLE
Pure Virtual Function Called !

### ISSUE THREAD

**Issue by ka4nklnc** [twilio/video-quickstart-android#672]
I've been trying to figure out why this issue occurs for a while. On average, it appears in 1 out of 10 video calls. Occurs after the call ends. 

In a text I read on Stackoverflow, they explained it as follows.
https://stackoverflow.com/questions/14549489/how-to-fix-pure-virtual-function-call-runtime-error

Libraries I use

      com.twilio:voice-android:5.7.2
      com.twilio:video-android:6.4.0

Thank you for your help.

**Comment by anupdey99** [comment]
Any solution for the issue?

**Comment by afalls-twilio** [comment]
@anupdey99 Thank you for the report//
1) What are the steps to reproduce it? (join a call, then exit, then...)
2) What is the call stack you are experiencing?
3) Is it happening with twilio-android 7.0.3 as well?
4) What device is this happening on (what model number)?

Thanks

**Comment by afalls-twilio** [comment]
@anupdey99 We have recently fixed some bugs, checkout the 7.1.0 release and see if its still happening for you

**Comment by anupdey99** [comment]
@afalls-twilio Thanks for the update. Appreciate your hard work.
