### ISSUE TITLE
Audio output

### ISSUE THREAD

**Issue by dostalleos** [twilio/video-quickstart-android#673]
### Description

Is it possible to change audio output type? It seems that Twilio SDK uses voice call output type (volume rocker controls voice call volume during the video call). Media output would be more suitable for our use case. We are facing following issues with the voice call output:

1. It's not possible to mute output with the volume rocker.
2. Audio is not casted during screen mirroring (it still goes through the phone).

Thank you

**Comment by dostalleos** [comment]
Hello, could somebody from Twilio team answer this please?

**Comment by PratimMallick** [comment]
Hey @dostalleos . we have not added the check for point #2 yet. That is in future roadmap. The other point can be achieved by our sdk using the `setVolume` api on `HMSTrack` object

**Comment by dostalleos** [comment]
@PratimMallick Thank you for your response, but we are using Twilio Video SDK, not yours 👍

**Comment by afalls-twilio** [comment]
@dostalleos Sorry about the delayed response.. to answer your questions, you can modify the audio output, this is managed by our opensource project call audioswitch. 

As for supporting Casting out of the box, today we do not have support for that but it can be added by extending audioswitch or providing your own audio routing library.


Helpful Links
https://github.com/twilio/audioswitch
https://developers.google.com/cast

**Comment by dostalleos** [comment]
@afalls-twilio Hello, thank you for your reply. 
We are already using AudioSwitch library, but this library changes only the output between Speakerphone, Earpiece, WiredHeadset and BluetoothHeadset. I'm talking about audio output type (Voice call, Alarm clock, Media) which is in all the cases voice call. I believe this is not controlled via AudioSwitch but directly via Twilio Video SDK or WebRTC.

I understand that in most cases this is excepted behavior, but for our use case, Media output type would make more sense.
Having Media output would solve both our issues I think.
