### ISSUE TITLE
LocalVideoTrack is showing black  when getting other app call(Skype,etc.,) during twilio call?

### ISSUE THREAD

**Issue by braver-tool** [twilio/video-quickstart-android#675]
I used twilio for calling, its working good, but now am facing one issue on video local video track.

## Issue :
If I switch to Skype(or any other app) calls during twilio call, after that conversation twilio local video track is showing black when back to twilio call.

Is it possible to disable audio/video tracks, using audiomanager/audioswitch? like for pause/resume video tracks.

Please give any idea or source. Thanks in advance!):-

**Comment by afalls-twilio** [comment]
@braver-tool yes, one can disable/enable a video track with enable(true/false) method associated with the video track. As for using audioswitch to do that? I would recommend using your activities lifecycle events as to know when your activity has been backgrounded/foregrounded.

https://twilio.github.io/twilio-video-android/docs/7.0.3/com/twilio/video/LocalVideoTrack.html

**Comment by braver-tool** [comment]
@afalls-twilio thanks for the reply, Am already tried to enable/disable video track, the problem comes only, when we use another app like skype or else for video sharing/mic during Twilio video call, since when I can use the enable/disable methods? I mean how to know the other app call enters during Twilio call?

**Comment by afalls-twilio** [comment]
@braver-tool sorry for the "very" late response, if the other applications are taking control of the camera, that is the reason. Have you attempted to 'lock' the camera? another option is to disable the camera/video feed, when the twilio video application is backgrounded.. Are you using the Camera or Camera2 based capturer?

**Comment by afalls-twilio** [comment]
Closing due to a lack of response.
