### ISSUE TITLE
How to enforce software based encoding / decoding?

### ISSUE THREAD

**Issue by acrolink** [twilio/video-quickstart-android#679]
I am facing an issue on Raspberry Pie 4. All the available Android ROM's support software only video encoding and decoding. I want to force the SDK to use software encoder and decoder.

I have read that I can do that by omitting `"OMX.google."` from `SOFTWARE_IMPLEMENTATION_PREFIXES` inside `/sdk/android/src/java/org/webrtc/MediaCodecUtils.java`.

How to do that using the Twilio SDK version 7.0?

Your help and ideas are highly appreciated.

**Comment by acrolink** [comment]
I hope you give this issue consideration, Would be very useful to allow usage of either software or hardware encoders / decoders for video. To force for instance usage for software encoders and decoders.

**Comment by PratimMallick** [comment]
This can be done internally by extending `DefaultVideoEncodingFactory` or `DefaulrVideoDecodingFactory` when a Peerconnection factory is formed

**Comment by PratimMallick** [comment]
The DefaultVideoEncoderFactory is a webrtc class, this needs to be extended by a class inside twilio's SDK. 

Such things are done in 100ms video library, I am not sure about twilio

**Comment by acrolink** [comment]
> The DefaultVideoEncoderFactory is a webrtc class, this needs to be extended by a class inside twilio's SDK.

I hope this gets the attention of the developers at Twilio and make it possible to use software encoders and decoders only as an option.

In the meantime, I guess it is possible to override `DefaultVideoEncoderFactory` of `webrtc` in conjunction with Twilio if a lower version of Twilio SDK is used, since in older SDK, `webrtc` libraries were used directly (not embedded within Twilio SDK itself).

**Comment by afalls-twilio** [comment]
@acrolink We are actively discussing internally this issue and plan to provide a mechanism to managing hardware vs software encoding via the api.

**Comment by acrolink** [comment]
> @acrolink We are actively discussing internally this issue and plan to provide a mechanism to managing hardware vs software encoding via the api.

Any news on this?

**Comment by afalls-twilio** [comment]
@acrolink There is! As of the 7.1.0 release, if you would like to experiment with disabling HW encoding, you can...

in the assets directory, create a java properties file called twilio-video-config.properties in the root of your apps assets directory. This properties file should have this line in it..

`tvi.webrtc.DefaultVideoEncoderFactory.enableHWEncoding=False`

**Comment by acrolink** [comment]
@afalls-twilio ,

That is great. Any additional code changes needed in JAVA code or inside gradle scripts?

**Comment by afalls-twilio** [comment]
@acrolink nope
