### ISSUE TITLE
Device Specific crash on Screen Sharing Receiver -  src/sdk/android/src/jni/jni_generator_helper.h, line 94

### ISSUE THREAD

**Issue by pkdhankher** [twilio/video-quickstart-android#683]
### Description

When the screen is being shared by any Android Device and the Receiver is also Android (Specofocally Motorola E7) then crash on VideoTrack sync

[Description of the issue]

### Steps to Reproduce

1. [Share screen Track from any Android device]
2. [Receiver Should be Android Motorola E7/E9]
3. [Crash on ScreenSharingTrack sync with videoView]

#### Logs

```
//src/sdk/android/src/jni/jni_generator_helper.h, line 94
```
![Untitled2](https://user-images.githubusercontent.com/22525435/138490602-056e4ba3-6999-4ba4-87d1-e7a2c139bc2f.png)

### Versions

All relevant version information for the issue.

#### Video Android SDK

[eg. 6.4.0]
implementation 'com.twilio:video-android:6.4.0'

#### Android API

[eg. 29] (Android10)

#### Android Device

[eg. Motorola E7]
[eg. Motorola E9 play]

**Comment by afalls-twilio** [comment]
@pkdhankher This looks like an issue with Hardware Encoding/Decoding... What model number is the Motorola E7 (such as 
XT2095)?

**Comment by pkdhankher** [comment]
Hi Afalls, the issue is fixed with the latest lib version.
