### ISSUE TITLE
Error : Could not resolve com.twilio:video-android:6.4.+

### ISSUE THREAD

**Issue by GopalLR** [twilio/video-quickstart-android#690]
![Uploading Screenshot 2021-12-09 180108.png…]()

**Comment by GopalLR** [comment]
I already upload the screen shot which shows the error.
Yes, I was clone quick-start twilio:video app.

**Comment by afalls-twilio** [comment]
@GopalLR unfortunately, we cannot view the image, the link fails to work (infact it points back to this bug).

**Comment by phongkien** [comment]
Might be an issue with jitpack (at least from my build).
```
* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.twilio:video-android:6.4.+.
     Required by:
         project :app > project :twilio_programmable_video
      > Failed to list versions for com.twilio:video-android.
         > Unable to load Maven meta-data from https://www.jitpack.io/com/twilio/video-android/maven-metadata.xml.
            > Could not GET 'https://www.jitpack.io/com/twilio/video-android/maven-metadata.xml'.
               > Read timed out
```
![image](https://user-images.githubusercontent.com/450554/174924865-ab8055b1-f4b5-41d8-a71d-9404cf9bf9bd.png)

**Comment by afalls-twilio** [comment]
@phongkien thanks for posting that log, yes, from that log, it is looking at the wrong maven repo, it looks like its attempting to pull our package from www.jitpack.io... our package is over here...
https://search.maven.org/artifact/com.twilio/video-android/7.5.1/jar?eh=
