### ISSUE TITLE
Add sample for Jetpack Compose

### ISSUE THREAD

**Issue by antranvn** [twilio/video-quickstart-android#693]
Hello guys,
It will be great if we have a sample for Jetpack Compose.

**Comment by ChiKotlin** [comment]
No

**Comment by antranvn** [comment]
- [ ] - _why_ no

**Comment by wazzah-marham** [comment]
is twillio planning to launch jetpack compose support?

**Comment by afalls-twilio** [comment]
@wazzah-marham @antranvn @ChiKotlin Thank you for your interest in Twilio Video Android. Unfortunately, we currently do not have this on our roadmap but that is subject to change.
