### ISSUE TITLE
onNetworkQualityLevelChanged is not getting called in android

### ISSUE THREAD

**Issue by venkypandi** [twilio/video-quickstart-android#696]
Unable to get the onNetworkQualityLevelChanged listener, when I have switched off the mobile data and turned on again.

The room type has been set to Group in the twilio console.

We are checking it in two devices

room = Video.connect(requireContext(), accessToken, roomListener) {
            roomName(roomName)
            enableNetworkQuality(true)

override fun onNetworkQualityLevelChanged(
            remoteParticipant: RemoteParticipant,
            networkQualityLevel: NetworkQualityLevel
        ) {
            Log.d(TAG, "onNetworkQualityLevelChanged: $networkQualityLevel")
            if(networkQualityLevel.equals(NetworkQualityLevel.NETWORK_QUALITY_LEVEL_ZERO)){
                if(tempVideoTrack!=null && tempVideoTrack!!.identity.equals(remoteParticipant.identity)){
                    binding.tvAgentName.visibility = View.VISIBLE
                    binding.ivAudioMode.visibility = View.VISIBLE
                    binding.tvTopInfo.visibility = View.GONE
                    binding.primaryVideoView.setBackgroundColor(resources.getColor(R.color.bottomSheetBg))
                }else{
                    adapter.changeVideoStatus(remoteParticipant.identity,false)
                    adapter.notifyDataSetChanged()
                }
            }
        }

**Comment by afalls-twilio** [comment]
@venkypandi  Thank you for the bug report, can you please provide us more about this issue?  What device (Model)did you experience this on, what Android version?

**Comment by afalls-twilio** [comment]
Closing due to a lack of customer enguagment.
