### ISSUE TITLE
Twilio Video 7.0.6 - Changelog - Now builds with Java 11 instead of java 8

### ISSUE THREAD

**Issue by 4brunu** [twilio/video-quickstart-android#702]
### Description

In the changelog of Twilio Video Android 7.0.6, one of the changes is:
- Now builds with Java 11 instead of java 8

https://www.twilio.com/docs/video/changelog-twilio-video-android-v7#706-february-11th-2022

Does this means that Twilio Video Android 7.0.6 has the source and target compatibility java version of 11, like the following example, and that uses java 11 feature in the code base?

```
    compileOptions {
      sourceCompatibility JavaVersion.VERSION_11
      targetCompatibility JavaVersion.VERSION_11
    }

    // For Kotlin projects
    kotlinOptions {
      jvmTarget = "11"
    }
```

Or does it means that Twilio Video Android 7.0.6 has the source and target compatibility java version of 8, but it was built using OpenJDK 11?

#### Video Android SDK

7.0.6

**Comment by afalls-twilio** [comment]
@4brunu It means that the source and target compatibility java version of 11, exactly as you described.

**Comment by 4brunu** [comment]
Thanks 👍
