### ISSUE TITLE
How can we deploy twilio invite fetch token on our own server which is in node.js instead of twilio sdk starter, 

### ISSUE THREAD

**Issue by ArjunPatidar-numero** [twilio/video-quickstart-android#709]
Hello,

I want to implement video chat in Android, It can be one to one or group video calls, If initiated in the group then all participants should get the notification same with one to one, I'm not getting how to implement this, I go through many documents about Twilio video but still not clear yet.

Thanks
waiting for the response

**Comment by afalls-twilio** [comment]
@ArjunPatidar-numero You would have to download our server side sdk for Node and integrate that into your sever application.

https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens#generate-helper-lib
