### ISSUE TITLE
In Video invite getting the Missing video grants error on connecting room

### ISSUE THREAD

**Issue by ArjunPatidar-numero** [twilio/video-quickstart-android#710]
Hello,
I'm trying to integrate the Twilio video invite and I'm getting the 

```
W/System.err: com.twilio.video.TwilioException: Missing video grants
/VideoInviteActivity: onConnectFailure: Missing video grants
/com.numero.local I/VideoInviteActivity: onConnectFailure: []
```

When I try to connect to room,

**Comment by sdtorresl** [comment]
I could reproduce the issue and basically the problem is that the SDK Starter is missing a VideoGrant permission for the token. I fixed adding the following code in the tokenGenerator function:

```
 const videoGrant = new VideoGrant();
 token.addGrant(videoGrant)
```

**Comment by ArjunPatidar-numero** [comment]
Thanks @sdtorresl @paynerc @kwhinnery @rfbrazier  , Now I'm facing the notification issue in the video room, How can we send a notification to the participants whom we want to join in the room, I need He should receive the call ringing notification just like WhatsApp, Can you please help me with this?
