### ISSUE TITLE
Not receiving dataTrackCallback in participant device

### ISSUE THREAD

**Issue by pkdhankher** [twilio/video-quickstart-android#714]
### Description

[Sometimes dataTrack callbacks are not received by subscribers in the video room]

### Steps to Reproduce

1. Connect 3-4 participants into a room
2. Send messages to participants
3. Sometimes any random participant stopped receiving dataTrack callback and start receiving again automatically

#### Code

```java
Sender End: 
localDataTrack?.send(message)

Receiver End: 
 override fun onMessage(remoteDataTrack: RemoteDataTrack, message: String) {}
```

#### Expected Behavior

[All subscribers should receive message callback]

#### Actual Behavior

[What actually happens]

#### Reproduces how Often

[4-5/10]

#### Video Android SDK

[eg. 7.1.0]

#### Android API

[eg.29, 30]

#### Android Device

[eg. Happened in Emulator 31 and other real devices API 29-30]

**Comment by afalls-twilio** [comment]
@pkdhankher Sorry for the late response, we have reworked many things in our 7.3.0 release, could you please retry with that release and see if the issue is resolved? Thanks!

**Comment by afalls-twilio** [comment]
Closed, no response from customer.

**Comment by pkdhankher** [comment]
Thanks for the response @afalls-twilio . Sure, I'll update SDk and check if it is working now.
