### ISSUE TITLE
Use preferable cipher suites and TLS versions in android app

### ISSUE THREAD

**Issue by RajashekarRaju** [twilio/video-quickstart-android#721]
### Description

In our android application, due to compliance requirements for security and data protection, we are required to use different or preferred Cipher suites and TLS versions which are added below instead of latest one in use which are provided in [Twilio Docs](https://support.twilio.com/hc/en-us/articles/360007724794-Notice-Twilio-REST-API-s-TLS-and-Cipher-Suite-Security-Changes-for-June-2019).

### Cipher suites we need to include:

```
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
TLS_RSA_WITH_AES_128_GCM_SHA256
```
 
### Cipher suites we need to exclude:

```
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA
```

**Is there a way we can select only the allowed version and suits for our application to satisfy our requirements?**

**Comment by afalls-twilio** [comment]
There is currently no way to select the desired ciphers available.. more information can be provided going via our paid support channels.
