### ISSUE TITLE
** Please Note:  Google Play Store Submission Warnings **

### ISSUE THREAD

**Issue by afalls-twilio** [twilio/video-quickstart-android#731]
Google has identified [security issues](https://support.google.com/faqs/answer/12577537) found within WebRTC, including version M88 used by Twilio Programmable Video.  As a result, some customers have reported their submissions have been 'flagged' by Google. Your application will continue to be approved by the Play store however, you may receive the related warning. We are currently working on addressing the issue and are upgrading WebRTC. We will update this thread as we have more information to share.

**Comment by kalipersyn** [comment]
@afalls-twilio any updates on this?

**Comment by maven08** [comment]
@afalls-twilio please update on this with some ETA

**Comment by AcHsu104** [comment]
@afalls-twilio is there any update on this issue?

**Comment by afalls-twilio** [comment]
@kalipersyn @maven08 @AcHsu104 We are in the process of upgrading our internal versions of WebRTC and making/porting over the necessary modifications (we use a modified version of webrtc), we are targeting end of first quarter 2023...

**Comment by AdeelTanveerM** [comment]
Hi all, When I am trying to publish my app on Google play store I am getting this error after their review
"Your app uses a bad version of  WebRTC, which contains security vulnerabilities"

Can you please tell me how to get rid of this ? IOS has been published, no issue there.

![error](https://user-images.githubusercontent.com/120019501/209528139-6755eb76-80b3-40d1-a294-0ae8498300bb.png)

**Comment by AkbarovZohidjon** [comment]
I had also the same issue when I wanted to publish. Is there any solution for that.
<img width="579" alt="Screenshot 2023-01-17 at 13 17 29" src="https://user-images.githubusercontent.com/119106209/212844751-6fd1d6ca-9854-4dc3-9989-63a4a77f7757.png">

**Comment by AdeelTanveerM** [comment]
> I had also the same issue when I wanted to publish. Is there any solution for that. <img alt="Screenshot 2023-01-17 at 13 17 29" width="579" src="https://user-images.githubusercontent.com/119106209/212844751-6fd1d6ca-9854-4dc3-9989-63a4a77f7757.png">

@AkbarovZohidjon You will get a message in inbox of google play account after some time that "Your app is ready to be published" (something like that), then you can publish the same one with this error. Maybe just wait for that message and try roll out again existing version.

**Comment by JaredBanyard** [comment]
Any update on this?

**Comment by parthm73** [comment]
I had also faced this issue, Any update on this?

**Comment by harleenchauhan** [comment]
Please help me about this issue .

error
1 Error
1 MESSAGE FOR VERSION CODE 27
error
Vulnerable WebRTC Versions
Your app uses a bad version of WebRTC, which contains security vulnerabilities.

**Comment by deive** [comment]
Please note that Google no longer allow publish to live with this vulnerability. We can no longer publish updates while this is outstanding.

**Comment by fabiendem** [comment]
> Please note that Google no longer allow publish to live with this vulnerability. 

Can you share some source @deive please? Or a screenshot?

**Comment by deive** [comment]
@fabiendem Looks like I posted a bit too early - the update has now been approved. It just took a lot longer than expected. Phew!

**Comment by AndersonVanzo** [comment]
any update?

**Comment by JaredBanyard** [comment]
Twilio support just days they are working on it. Pretty crazy given this is
what they do. Why didn't their internal tooling flag this sooner? Why is it
taking so long to update? Have they forked webrtc or something?

**Comment by fabiendem** [comment]
> [...] We are in the process of upgrading our internal versions of WebRTC and making/porting over the necessary modifications (we use a modified version of webrtc), we are targeting end of first quarter 2023...
> 
> FYI: I believe the biggest security holes that were fixed are related to the data channel.

@afalls-twilio is there any way you could give us a status of the project please?

**Comment by spalmertwilio** [comment]
Hi Everyone.  First, thank you for your patience as this issue has been open for awhile.  Second, upgrading WebRTC is a lengthly process, and the team is diligently working to ensure we do not introduce any bugs, while simultaneously working on other issues.  We will post here, and in our normal changelogs, when when we have further updates.  Rest assured, this issue is in our “currently being worked on” top issue list.

**Comment by afalls-twilio** [comment]
Good news all! We are in the final stages of releasing Twilio Video SDK with an upgraded WebRTC version (m105). This should address all the play-store submission issues.

**Comment by afalls-twilio** [comment]
Twilio Video 7.6.1 has been released. This included an upgrade of WebRTC which should resolve this issue... get more info about the release here...
https://www.twilio.com/docs/video/changelog-twilio-video-android-v7

**Comment by deive** [comment]
Just released an update, with no security warning.
Good job, thanks very much!
