### ISSUE TITLE
How do we get RTCStatsReport using twilio android sdk.

### ISSUE THREAD

**Issue by krunalspearline** [twilio/video-quickstart-android#732]
- I would like to know that how we can get RTCStatsReport using twilio android sdk. 
- I have went throw the `com.twilio.video.Room.getStats(statsListener) ` but this is providing different report not similar like RTCStatsReport (libwebrtc stats report).

I really appreciate your help for the same. Thanks in advance!!

**Comment by krunalspearline** [comment]
I have found method `getRtcStats(@NonNull RtcStatsListener rtcStatsListener)` inside the Room class but this method is not public and not accessible publicly. Is there any otherway where we can get the `List<RTCStatsReport>`?

Thanks in advance!!

**Comment by afalls-twilio** [comment]
@krunalspearline Thank you for the question. While its not the exact WebRTC API, it does contain much of the same information.  This is accomplished by using the Room object ie..
1) register an object implementing the StatsListener interface using the getStats(..) method from the Room object.
2) This call back will be invoked when stats arrive and can include a whole variety of information.. Please look at the StatsReport object for more details.
