### ISSUE TITLE
Need to get amplitude of user's voice sound before connect to room

### ISSUE THREAD

**Issue by thanhnvpk01168** [twilio/video-quickstart-android#734]
Can you help me to get amplitude of user's voice sound before connect to room, purpose to review the camera or mic before connect to room.
thanks

**Comment by afalls-twilio** [comment]
@thanhnvpk01168 Thank you for the question. This is outside the scope of the Twilio Video SDK, that being said, if you know a way of calculating the amplitude from the PCM data and some knowledge about the device's amplifier, one could create a custom audiodevice that is active before WebRTC requests for its usage, that is actively recording audio and determining the decibels of the signal its capturing.
