### ISSUE TITLE
While switching the camera display the blank screen for remote participant.

### ISSUE THREAD

**Issue by AjayLSojitra** [twilio/video-quickstart-android#735]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

Whenever I try to switch the camera it's work for 2-3 times but after that only blank screen appear.

### Steps to Reproduce

1. Connect to the room.
2. After Remote participant connected on/off the camera.
3. And after 2-3 times switching you will got the blank screen appear.

#### Video Android SDK

7.5.1

#### Android API
compileSdk 33
Device version-12

#### Android Device

Samsung SM-G781B

**Comment by AjayLSojitra** [comment]
Any update?

**Comment by afalls-twilio** [comment]
@AjayLSojitra Thanks for filing the issue, was this with the quickstart or with code that was directly based off the quickstart by any chance?
