### ISSUE TITLE
How to make oneToOne video call ?

### ISSUE THREAD

**Issue by ananth10** [twilio/video-quickstart-android#74]
I have just run Quickstart app. when i click call button . it asks me to enter room name. so whats room name? and actually i am developing android app. on that app one user can make a call to other user. so how to do it? should i register every user programmatic ally ?  can i connect to other user based one registered user name?

**Comment by FranziscaZarrai** [comment]
@ananth10 the room name you input can basically be anything such as "Hello" or "timmi" etc - it'll be the room people join to have a conversation.

As for your usecase: Seems we have the same or at least a similar use case. You can checkout the projects i linked in this bug report:

https://github.com/twilio/video-quickstart-android/issues/73

I link the server and the mobile part there. Basically what we do to achieve a "call-like" effect:

- Each user has a dedicated room, the room name is a combination of that users credentials (such as username and company he belongs to or whatever works for you to generate a unique room name).
- Then we have an Android service running in the background, the currently logged in user is auto-joining his own room
- We get callbacks from room events, such as when someone joins our room. We use that callback to send a notification to the user whose room was joined (i.e. who received a "call") which is shown on his phone. If he clicks on it > the call interface opens
- This setup also lets you receive "call notifications" when the app is not running in the foreground

**Comment by ananth10** [comment]
@FranziscaZarrai Thank you for the response. actually i saw some code to generate token pro grammatically 

public class Main {

	// Substitute your Twilio AccountSid and ApiKey details
	public static final String ACCOUNT_SID = "ACCOUNT_SID";
	public static final String API_KEY_SID = "API_KEY_SID";
	public static final String API_KEY_SECRET = "API_KEY_SECRET";

	public static void main(String[] args) throws Exception {
		// Create a VideoGrant
		final VideoGrant grant = new VideoGrant();
		grant.setConfigurationProfileSid("configurationProfileSid");

		// Create an Access Token
		final AccessToken token = new AccessToken.Builder(ACCOUNT_SID, API_KEY_SID, API_KEY_SECRET)
		.identity("example-user") // Set the Identity of this token
		.grant(grant) // Grant access to Video
		.build();

		// Serialize the token as a JWT
		final String jwt = token.toJWT();
		System.out.println(jwt);
	}

}



i found ACCOUNT_SID in my twillio dashboard . but where can i find API_KEY_SID and  API_KEY_SECRET ?

**Comment by ananth10** [comment]
@FranziscaZarrai  i have imported Twilio Android Project into android studio . but why we need that spark ?

**Comment by FranziscaZarrai** [comment]
@ananth10 Hey there, we use Sparky to authenticate towards twilio. You do not have to use Spark - you can do your own thing, but just beware that you'll have to edit the Android project if the JSON returned by your server is not the same as ours.

**Comment by ananth10** [comment]
@FranziscaZarrai   what should i do for this "R.string.sparkyUrl" . where can i get sparkyUrl? .. please bare with me . i am little confused.

**Comment by FranziscaZarrai** [comment]
@ananth10 I think that question should be posted on this project: https://github.com/coresystemsFSM/android-twilio-video-with-service (it's also explained there int he README file what you need to do with the sparkyUrl) - if after the README it's still nto clear, please open an issue on the afore mentioned project.

**Comment by ananth10** [comment]
@FranziscaZarrai  . Okay . thank you.

**Comment by aaalaniz** [comment]
Hey @ananth10

A `Room` represents a media session between participants and as @FranziscaZarrai pointed out the name of the room can be anything ("Daily Standup", "Customer Rundown", or a UUID). The Video SDK does not provide a mechanism to "call" users. We leave this to the developer. We are encouraging developers to use a separate service for calling. Some good candidates for performing this:

[Google Cloud Messaging](https://developers.google.com/cloud-messaging/)
[Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging/)

Below is a reasonable approach to setting up a calling flow with the Video SDK:

1. User 1 taps to call User 2
2. Your app generates a unique name for a `Room`. Perhaps a combination of the two user's IDs.
3. User 1 connects to `Room` with generated unique name
4. Using one of the services listed above, send message of [high priority](https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message) with the unique name of the `Room` to User 2
5. User 2 to receives notification and you display a ringing UI
6. User 2 accepts and connects to the same `Room`

**Comment by ananth10** [comment]
@aaalaniz  Thank you for the quick response. i will follow the above flow.

**Comment by mayurgujrathi** [comment]
How to choose specific person for video chat/call in a web based application (same as skype).

What libraries do i need to use for same in backend(NodeJS) and front end(Angular).

**Comment by shoaibHassanAttech** [comment]
What if a user peer2 received call/video chat invitation over push notification from peer 1,
and we show a screen/callkit for incoming call and then user reject/refuse the invitation, then how peer 1 will know that invitation is rejected/refused.

**Comment by Onibenjo** [comment]
A notification can be sent back to peer1 upon rejection

**Comment by TJGreen97** [comment]
@aaalaniz I have followed your calling flow and it works great. I am stuck on the final point where User 2 is connected to the same room. I can get the room name from the data message payload, but after that, I cannot work out how to automatically connect to the room without the app crashing. It works if I use a button callback to connect to the room (specified in the payload) but I wish to cut out this step. Cheers

**Comment by NitinSharma639** [comment]
Hi The projects that are mentioned in this is not opening. Can you please provide updated links.
