### ISSUE TITLE
Question regarding ths usage of the NoiseCancellationAudioDevice

### ISSUE THREAD

**Issue by VanKhulup** [twilio/video-quickstart-android#746]
Hello! I'm currently working on the integration of the Noise Cancellation feature, and base my implementation on the NoiseCancellationAudioDevice. One of the business requirements is to give user option to enable/disable noise cancellation during the call via switch button. Since Video SDK does not allow to change actual audioDevice after joining the room (getting the `UnsupportedOperationException: Changing the audio device while connected to a room is not allowed ` expection if I try), my question is the following - is the `noiseCancellationAudioDevice.setPausedProcessing(boolean)` function should serve my purpose? Based on the naming it seems like the one that should do the trick, but since I'm not familiar with underlying implementation I would love to have some sort of confirmation from development team (if possible). Thanks in advance!

**Comment by afalls-twilio** [comment]
@VanKhulup you are correct, if you want to noise cancellation plugin to suspend noise cancellation, pausing it should do the trick.
