### ISSUE TITLE
App crash on orientation change with media projection permission is on

### ISSUE THREAD

**Issue by VivekKannaV** [twilio/video-quickstart-android#752]
### Description

Application crashes when media projection permission is ON & if we change the device orientation.

### Steps to Reproduce

1. Raise connection request
2. Room connected but media projection permission is ON
3. Change Orientation & Accept the permission
4. End first session
5. Raise second connection request
6. Room connected but media projection permission is ON
7. Change the orientation

PF video link: https://drive.google.com/file/d/18LgT63kMRi7J2luLIBcesRFJddb7MXbD/view?usp=share_link

#### Expected Behavior

App stays with permission with no crash

#### Actual Behavior

App got crash

#### Reproduces how Often

100%

#### Code

```java
val options = ConnectOptions.Builder(accessToken)
            .roomName(roomId)
            .enableNetworkQuality(true)
            .encodingParameters(EncodingParameters(16, 0))
            .build()

val activeRoom = Video.connect(context, options, this)
```
This code will be invoked when user accepts the permission
```java
fun startScreenShare(mediaInputResult: ActivityResult) {
        val screenCapturer = ScreenCapturer(context, mediaInputResult.resultCode, mediaInputResult.data!!, listener)
        val localVideoTrack = LocalVideoTrack.create(context, true, screenCapturer)
        if (localVideoTrack != null) {
            activeRoom?.localParticipant?.publishTrack(localVideoTrack)
        }
}
```
This code will be invoked to disconnect the room
```java
activeRoom?.disconnect()
activeRoom = null
```

#### Logs

[Twilio crash on orientation change.txt](https://github.com/twilio/video-quickstart-android/files/12860483/Twilio.crash.on.orientation.change.txt)

### Versions

KOTLIN = "1.8.21"
GRADLE_TOOLS = "8.0.1"
TARGET_SDK_VERSION = 33
BUILD_TOOLS_VERSION = "33.0.2"
JVM_TARGET_VERSION = "17"

#### Video Android SDK

7.6.4
Note: We didn't face any crash with v7.6.1

#### Android API

TARGET_SDK = 33
Android SDK: 30, Release: 11

#### Android Device

Samsung Tab Active A
Model: SM-T295
Hardware: qcom

**Comment by VivekKannaV** [comment]
Please note the following observation:

If we have the following code, we don't face crash at all even in v7.6.4
```
activeRoom?.localParticipant?.localVideoTracks?.firstOrNull()?.localVideoTrack?.release() // This line fixes the crash
activeRoom?.disconnect()
activeRoom = null
```

But we don't wanna add this line because `activeRoom?.disconnect()` is expected to do this resource release.
Also to be noted, all works good enough without the `release()` code with v7.6.1

**Comment by afalls-twilio** [comment]
@VivekKannaV how are you handling orientation changes in your application? are you setting ` android:configChanges="orientation` in the manifiest or are you letting the system tear down and restart your activity?

**Comment by VivekKannaV** [comment]
@afalls-twilio Yes, we're setting `android:configChanges="orientation"` in the manifest.

**Comment by afalls-twilio** [comment]
@VivekKannaV I presume you are also setting `screenSize` as well? so in your AndroidManifest looks like, `android:configChanges="orientation|screenSize"`?

**Comment by VivekKannaV** [comment]
@afalls-twilio 
Pls find the config changes setting here. This is from our actual project
`android:configChanges="screenSize|keyboardHidden|orientation|fontScale|uiMode|navigation|keyboard|fontWeightAdjustment"`

To narrow it down, This is from our sample forked Twilio-video-quickstart project. (We face the same crash)
`android:configChanges="orientation|screenSize"`


> Also, what is the logcat output?

Pls check the logs section in the very first comment

> Why is disconnect being called, in onDestroy(..)?

No, we don't invoke `disconnect()` in `onDestroy()`

**Comment by afalls-twilio** [comment]
@VivekKannaV thank you, so did the demo crash when you followed the same steps, because I was unable to reproduce your issue with it.

**Comment by VivekKannaV** [comment]
@afalls-twilio 
We have a forked quick start project. I have added a couple of commits for your ref.

<img width="1187" alt="image" src="https://github.com/twilio/video-quickstart-android/assets/16816349/1c8bc687-76ca-45ba-bbd4-d0f8f0efae2a">

Please feel free to checkout the last two commits from [this project](https://github.com/prasanth1308/video-quickstart-android/commits/chore/upgrade-gradle) that would help your team to repro this issue.

Kindly follow the steps shared in the first comment. You could repro the crash from e02d776 this commit.
Also added a video that was taken from this quick start project for ref.
Let us know if it helps or need more info.

Pls use the below info to join in web
_Link: https://twilio-dot-app-launcher-dev-5ef0fa0a.uc.r.appspot.com/
Room: Vivek23_

_Note: Twilio web link will be accessible for two weeks._

**Comment by afalls-twilio** [comment]
@VivekKannaV I cannot run your demo because it depends on being part of your firebase project, which I'm not part of.. I don't have access to your google-services.json...

Several Thinks..
1) Did you get a chance to check out the demo I sent you, where the screen can be rotated without crashes?
2) Why are you releasing the video track when the device is rotated in the first place?

Thanks

**Comment by vijimani17** [comment]
We can go ahead close the ticket based on @VivekKannaV confirmation.
