### ISSUE TITLE
Application crashes on device orientation changes when the application targets to target sdk version of 34

### ISSUE THREAD

**Issue by vijimani17** [twilio/video-quickstart-android#753]
**Description**

Application crashes on device orientation changes when the application targets to target sdk version of 34

**Steps to Reproduce**

- Twilio session has been created and device is in portrait mode
- Remote view is sharing successfully
- Change Orientation to  Portrait to Landscape  and vice versa

Sample twilio app tested - https://drive.google.com/file/d/1i3dfaglxS5Nth3PFQRHnsa83BHN4APeI/view

PF video link: https://drive.google.com/file/d/14AUcIzbeMOQdn8dg2kXijDhfsUiEZUVF/view

**Expected Behavior**

App stays the remote view sharing even on configuration changes

**Actual Behavior**

App got crash

**Reproduces how Often**

100%

**Code**

val options = ConnectOptions.Builder(accessToken)

.roomName(roomId)

.enableNetworkQuality(true)

.encodingParameters(EncodingParameters(16, 0))

.build()

val activeRoom = Video.connect(context, options, this)

This code will be invoked when user accepts the permission

fun startScreenShare(mediaInputResult: ActivityResult) {

val screenCapturer = ScreenCapturer(context, mediaInputResult.resultCode, mediaInputResult.data!!, listener)

val localVideoTrack = LocalVideoTrack.create(context, true, screenCapturer)

if (localVideoTrack != null) {

activeRoom?.localParticipant?.publishTrack(localVideoTrack)

}

}

This code will be invoked to disconnect the room

activeRoom?.disconnect()

activeRoom = null

Initial investigation from our end added here https://docs.google.com/document/d/1NZ09DFuEZQs3RA3RYVDbIS4gJxzOXSUht15Oa948XLw/edit

**Logs**

Twilio crash on sample app can be seen in https://docs.google.com/document/d/1NZ09DFuEZQs3RA3RYVDbIS4gJxzOXSUht15Oa948XLw/edit -> "Twilio Sample app crash"

**Video Android SDK**

7.6.4

**Android API**

TARGET_SDK = 34

Android SDK: 34, Release: 14

**Android Device**

Pixel 6A

**Note** : Since we are planning to update our application target sdk, This is a blocker issue for us to proceed further.
[Copy of Remote Access - Android 14 feature testing.pdf](https://github.com/twilio/video-quickstart-android/files/13901999/Copy.of.Remote.Access.-.Android.14.feature.testing.pdf)

**Comment by ocarevs** [comment]
Hey @vijimani17 we've merged a fix in the ScreenShare example that handles API 34 onwards behaviour https://github.com/twilio/video-quickstart-android/pull/754

**Comment by vijimani17** [comment]
@ocarevs Fix seems to be provided in the sample test app , Does any fix provided twilio library ??, 

We expect the fix to be provided in the twilio library based on android recommendation. so I wonder how this fix will fix the problem what we see in our application because we wont be asking user permission on configuration changes.

With the existing media projection instance , createVirtualDisplay api should not be called again instead we have to follow the below

If your app needs to invoke MediaProjection#createVirtualDisplay to handle configuration changes (such as the screen orientation or screen size changing), **you can follow these steps to update the VirtualDisplay for the existing MediaProjection instance:**

Invoke [VirtualDisplay#resize](https://developer.android.com/reference/kotlin/android/hardware/display/VirtualDisplay#resize) with the new width and height.
Provide a new [Surface](https://developer.android.com/reference/kotlin/android/view/Surface) with the new width and height to [VirtualDisplay#setSurface](https://developer.android.com/reference/kotlin/android/hardware/display/VirtualDisplay#setsurface).

please refer https://developer.android.com/about/versions/14/behavior-changes-14#configuration-changes

can you please check how to fix the problem without asking the user permission again on configuration changes. thanks

**Comment by afalls-twilio** [comment]
@vijimani17 No fix is necessary to the Twilio-Video library, activity configuration changes would at best be handled in the QuickStart or your application.  Furthermore, the QuickStart is not an end-all be all, it is a demo of how one could implement it screen share.  If you would like to implement the handling of screen share differently in your app, feel free to, either way it is outside the scope of the SDK and the QuickStart.

**Comment by geak** [comment]
@vijimani17, seems I was able to work around the issue. I have made my own ScreenCapturer implementation and have commented out this piece of code in observer's `onFrameCaptured` method:
```Java
                    videoDimensions = new VideoDimensions(buffer.getWidth(), buffer.getHeight());
                    int currentOrientation = getDeviceOrientation();
                    if (updateCaptureDimensions(orientation, currentOrientation)) {
                        // Swap width and height capture dimensions due to orientation update
                        Log.d("ScreenCapturer", "Swapping width and height of frame due to orientation");
                        orientation = currentOrientation;
                        webRtcScreenCapturer.changeCaptureFormat(
                                buffer.getHeight(), buffer.getWidth(), (int) (1000 / frameDelayMS));
                    }
```

The idea is to prevent `ScreenCapturer` from re-creating a VirtualDisplay on screen rotations. Can you try this approach and ping back with results please?

**Comment by vijimani17** [comment]
Hi @geak , 

Thank you for jumping in and confirm twilio has to fix the issue. I appreciate it.

We might be having work around, But fix should present in library should be the right approach.

For example , If there are 1000 clients , every client implementing work around is not the suggestable solution. Rather library is the one doing screen capture so I would say fix from twilio library is the right approach until clients' migrate to different video library by considering the android OS update time lines.

I would still request twilio team to fix and its going to be a simple one in my assumption.

Thanks.

**Comment by geak** [comment]
Hello, yeah, I understand that you want it to be fixed in the library. I also have 1000+ clients who want to use screen sharing in our app. But as far as I understand Twilio is not going to fix the issue in their library unfortunately :( Especially considering the end of life of the library..
