### ISSUE TITLE
quickstart: video fails in android client when other person exits + re-enters the room.

### ISSUE THREAD

**Issue by dvrodriguez** [twilio/video-quickstart-android#83]
(1) One person, using the quickstart android app, enters a room
(2) Another person, using the javascript library, enters the same room. Everything works as expected.
(3) The javascript person leaves the room, waits a bit, then re-enters the room.

At this point, the video in the android app of the other person no longer works.

But it's clear both are in the room. That is, 
-- The Android person can hear the Javascript person
-- The Javascript person can see and hear the Android person

When I turn on debugging in the android app, I never see the "Reporting first rendered frame" or "Frames received" messages that should happen after the Javascript person re-enters the room, so it's as if video is not getting received by the android client.

If I have the Android person disconnect from the room, then reconnect, it works.

So it appears to happen only when someone connects -> disconnects -> reconnects while the android person is in the room.

I've got an iOS client with the same functionality as the android client, and everything works fine there.

**Comment by idelgado** [comment]
Thanks for the detailed description. I believe we recently may have found this bug in some of our testing. I'll write a test case and follow up with an ETA on the fix Monday.

**Comment by aaalaniz** [comment]
Hey @dvrodriguez 

This appears to be a bug in our quickstart application. I was able to reproduce the issue between two Android quickstart clients by following the steps you provided. Thanks for the detailed steps. I'll have a fix soon.

**Comment by aaalaniz** [comment]
Hey @dvrodriguez 

After further investigation this issue does appear to be a SDK regression introduced in 1.0.0-beta12. I've validated that the issue no longer occurs with the latest internal release of the SDK. We should be releasing 1.0.0-beta13 very soon. I'll provide another update after the release.

**Comment by aaalaniz** [comment]
Hey @dvrodriguez 

This regression should be resolved in `1.0.0-beta13`. I validated the fix in the quickstart. Please re-open the issue if the problem persists.

Thanks!
