### ISSUE TITLE
No video and no audio on calls for other countries

### ISSUE THREAD

**Issue by joao-amaro-bold** [twilio/video-quickstart-android#85]
We're using Android Twilio Programmable video SDK (1.0.0-beta12) and everything is working in video calls to the same country (User A and User B are in the same country, join the same room and get local and remote video and audio tracks). 
However, when we try to call a user that is in a different country, after user B joins the room (onConnected() callback for user B and onParticipantConnected() for user A), both user A and user B get no remote video or audio tracks, despite onAudioTrackAdded()/onVideoTrackAdded() callbacks are called. 

We experienced this situation with 1.0.0-beta9 and above versions.
Any possible explanation to this situation?

Thanks

João Amaro

**Comment by idelgado** [comment]
@joao-amaro-bold Thanks for reporting this issue. I'm not aware of any limitations as it relates to specific countries.

Can you provide me with the Room SID via `room.getSid();`? And post a full log with `VideoClient.setLogLevel(LogLevel.ALL);` set when connecting to the Room?

**Comment by joao-amaro-bold** [comment]
@idelgado Thanks for fast reply.

Here it goes. Files with logs from callee (User B, answering call) prior and after joining room and caller after joining room (with 0 participants).

Thank you
[callee - after.txt](https://github.com/twilio/video-quickstart-android/files/859074/callee.-.after.txt)
[callee - prior.txt](https://github.com/twilio/video-quickstart-android/files/859075/callee.-.prior.txt)
[caller - after.txt](https://github.com/twilio/video-quickstart-android/files/859073/caller.-.after.txt)

**Comment by aaalaniz** [comment]
Hey @joao-amaro-bold 

Thanks for the logs. I noticed that our SDK is only using STUN servers to establish a PeerConnection.

```
03-21 17:10:06.600 12083-25312/ D/TwilioVideo: [Core]:Parsing 'video' endpoint config: {"video":{"network_traversal_service":{"ttl":null,"date_created":null,"date_updated":null,"ice_servers":[{"urls":"stun:global.stun.twilio.com:3478?transport=udp"}]}}}
```

Can you check that the Video Configuration Profile you are using to generate a token has Network Traversal enabled? Here are the steps.

1. Navigate to your [Video Configuration Profiles](https://www.twilio.com/console/video/profiles)
2. Validate the Network Traversal box is checked in the Configuration Profile you are using. (Screenshot below)

![screen shot 2017-03-21 at 12 47 42 pm](https://cloud.githubusercontent.com/assets/1734140/24162193/b42ba5ae-0e34-11e7-8a62-2e40e3644544.png)

**Comment by joao-amaro-bold** [comment]
Hey @aaalaniz 
Thanks for response. It's solved now. It was NTS that was disabled.

Thanks a lot

João Amaro

**Comment by aaalaniz** [comment]
Awesome!
