### ISSUE TITLE
How to invite a participant in programmable video

### ISSUE THREAD

**Issue by sopnonill87** [twilio/video-quickstart-android#87]
I am making a video chat application using twilio programmable chat. I m facing some problems. Can't find anywhere how to invite a new participant when i am trying to call him. Can anybody help me with this?

**Comment by FranziscaZarrai** [comment]
@sopnonill87 If you have a one-to-one call use-case, checkout this thread where the subject was discussed and a possible solution was proposed by @aaalaniz at the end of the thread:

https://github.com/twilio/video-quickstart-android/issues/74

**Comment by idelgado** [comment]
We recently added an example in our repo showing how to register and send push notifications to invite other participants to video rooms.

https://github.com/twilio/video-quickstart-android/tree/master/exampleVideoInvite

While this example uses Twilio Notify, inviting can be accomplished using other push channels as well.

**Comment by aaalaniz** [comment]
Please reopen if you have any further questions about using Notify to invite participants to a Room @sopnonill87 

Thanks!

**Comment by kishorejethava** [comment]
Is there code example for REST API which is used in _exampleVideoInvite_ like

snippet of _TwilioSDKStarterAPI.java_
```
@POST("/register")
Call<Void> register(@Body Binding binding);
//Send notifications to Twilio Notify registrants
@POST("/send-notification")
Call<Void> sendNotification(@Body Notification notification);
```

**Comment by aaalaniz** [comment]
Hey @kishorejethava 

The backend example used with `exampleVideoInvite` can be found at [sdk-starter-java](https://github.com/TwilioDevEd/sdk-starter-java).

Thanks!

**Comment by deepbhavsar** [comment]
@aaalaniz 
I have downloaded starter sdk from https://github.com/TwilioDevEd/sdk-starter-java
I have setup all mentioned things in .md file after run command `java -jar target/sdk-starter-1.0-SNAPSHOT.jar`
It is showing me started and all.
Could you please tell me from where to get `TWILIO_SDK_STARTER_SERVER_URL` which I have to mentioned `local.properties` ?
After that command how to setup `ngrok`. 
Please help me. Thanks..!!!

**Comment by shoaibHassanAttech** [comment]
What if a user peer2 received call/video chat invitation over push notification from peer 1,
and we show a screen/callkit for incoming call and then user reject/refuse the invitation, then how peer 1 will know that invitation is rejected/refused.
