### ISSUE TITLE
How to capture camera frame?

### ISSUE THREAD

**Issue by ananth10** [twilio/video-quickstart-android#89]
I need to capture the camera frame and  have to do image processing? is there any api to capture camera frame?

**Comment by aaalaniz** [comment]
Hey @ananth10 

We have an API on `CameraCapturer` to capture an image. I recommend exploring our [advanced camera capturer module](https://github.com/twilio/video-quickstart-android/tree/master/exampleAdvancedCameraCapturer) which shows an example of how to take a picture while the camera capturer is running.

**Comment by ananth10** [comment]
@aaalaniz . Thank you much. i will try it.

**Comment by ananth10** [comment]
@aaalaniz i need to capture camera frame during 1:1 video call. is it possible using [advanced camera capturer module](url) ?

**Comment by aaalaniz** [comment]
Hey @ananth10 

The advanced camera capturer module only demonstrates how to set custom `CameraParameters` or capture an image with the `CameraCapturer`. Unfortunately, the module does not demonstrate capturing every frame.

Are you interested in recording or doing some additional processing for each frame?

If you are more interested in recording, we are currently working on a media recording feature for the Video SDK. The recording feature will be implemented server side and will allow developers to obtain video and audio tracks via a REST API. The feature is in development and should be made available later this year.

If you are interested in additional image processing for each frame, then unfortunately we do not currently support this feature. However, we are discussing adding image processing capabilities to our SDK.

Please provide more details for your use case, so I can provide better guidance.

Thanks

**Comment by kvikrama** [comment]
@aaalaniz we want to process every frame because the frames will need correction before we can send it to remote side. OR Alternately we can do the correction on the receive side as well.

Please guide us on steps to do the same. This need not necessarily be in your SDK. We are using opencv. Hence we just need the frames so that we can process them.

**Comment by aaalaniz** [comment]
Hey @kvikrama 

I would suggest exploring the [custom renderer module](https://github.com/twilio/video-quickstart-android/tree/master/exampleCustomVideoRenderer). In the example, we demonstrate implementing a custom renderer that captures the latest rendered frame into a `Bitmap`. Even though we display one image, the custom renderer processes each I420 frame. These I420 frames could be piped into opencv for additional processing before rendering the frame.

**Comment by ananth10** [comment]
We are processed bitmap using opencv now. but how this frame going to  reflect on videoview? .Should i convert bitmap to i420Frame? or how do i pass i420Frame back to render ?

**localMedia = LocalMedia.create(this);
localAudioTrack = localMedia.addAudioTrack(true);
cameraCapturer = new CameraCapturer(this, CameraSource.FRONT_CAMERA);
localVideoTrack = localMedia.addVideoTrack(true, cameraCapturer); 
primaryVideoView.setMirror(true);
**snapshotVideoRenderer = new SnapshotVideoRenderer(VideoActivity.this,mImageView);
localVideoTrack.addRenderer(snapshotVideoRenderer);
localVideoTrack.addRenderer(primaryVideoView);**
localVideoView = primaryVideoView;**

```
@Override
    public void renderFrame(final I420Frame i420Frame) {
        // Capture bitmap and post to main thread
        final Bitmap bitmap = captureBitmap(i420Frame);
        
         //bitmap processed using opencv
    }
```

**Comment by aaalaniz** [comment]
Hey @ananth10 

I suggest creating an OpenCvRenderer that contains a `VideoView`. When `renderFrame` is called you can process the frame and convert it back to `I420Frame` and then forward the processed frame to our `VideoView`. The class below provides a decent starting point for implementing this.

```
public class OpenCvRenderer implements VideoRenderer {
    private final VideoView videoView;

    public OpenCvRenderer(VideoView videoView) {
        this.videoView = videoView;
    }

    @Override
    public void renderFrame(I420Frame i420Frame) {
        I420Frame openCvProcessedI420Frame = processFrameWithOpenCv(i420Frame);

        videoView.renderFrame(openCvProcessedI420Frame);
    }

    private I420Frame processFrameWithOpenCv(I420Frame i420Frame) {
        // TODO: Process frame with opencv and convert to i420 frame

        return i420Frame;
    }
}
```

**Comment by aaalaniz** [comment]
@ananth10 @kvikrama Please reopen if you have any more questions. Thanks!

**Comment by hrlyrab** [comment]
Hi @aaalaniz I have a question sir, can a camera like CCTV cameras burst a shot while it is recording?

**Comment by aaalaniz** [comment]
Hey @hrlyrab 

I think it depends on whether the device supports the Camera2 API. It might be possible, but I can't tell you with certainty until I research further. If you provide specific device and hardware information, I can capture this in our backlog as a feature request.

Thanks!

**Comment by hrlyrab** [comment]
Good day sir! I'm using Raspberry PI 3B v1.2, Raspberry PI Camera v2.1, and Raspberry PI Camera Rev 1.3.

**Comment by aaalaniz** [comment]
Hey @hrlyrab 

Thanks for the details! Are you using [Android Things](https://developer.android.com/things/)?

**Comment by aaalaniz** [comment]
Hey @hrlyrab 

Android things is not required. I was just inquiring out of curiosity. How do you plan on using Twilio Video with Raspberry PI?

Thanks!

**Comment by CandiceWright** [comment]
Hi @aaalaniz ! I am wondering if there is such functionality in Twilio video for swift that allows a picture to be taken while camera capturer is running? I have looked through the documentation but cannot seem to find anything. Thank you

**Comment by aaalaniz** [comment]
Hey @CandiceWright 

Taking a picture while the CameraCapturer is running is not available on Video iOS today. I recommend opening an issue on the [Twilio Video iOS repo](https://github.com/twilio/twilio-video-ios) to get feedback from our iOS engineers. 

Thanks!

**Comment by CandiceWright** [comment]
ok. Thank you @aaalaniz

**Comment by Byronium** [comment]
If it's helpful at all, for iOS, this solution worked for me: https://github.com/twilio/video-quickstart-ios/issues/500#issuecomment-641851462

I tried alternative approaches in https://github.com/twilio/video-quickstart-ios/issues/142 and https://github.com/twilio/video-quickstart-ios/issues/496 but the solution in https://github.com/twilio/video-quickstart-ios/issues/500 was most concise and worked with the latest sdks 3.x and 4.x.
