### ISSUE TITLE
Missing media when adding audio/video tracks quickly while connected to room

### ISSUE THREAD

**Issue by aaalaniz** [twilio/video-quickstart-android#90]
While connected to a `Room` there is a bug in our negotiation of media when adding audio and/or video tracks quickly. In some cases video is not flowing to participants.

*Steps to Reproduce*
1 . Alice connect to Room B with no media
2. Bob connect to Room B with no media
3. Bob adds two `LocalVideoTrack`s with `ScreenCapturer` and `CameraCapturer` one right after the other.

*Expected Result*
Both video tracks are visible to Alice.

*Actual Result*
Both video tracks are received but only the `CameraCapturer` video track is visible to Alice

*Workaround*
Insert 2-5 second delay between successive additions of audio and video tracks.

**Comment by nkharshiladze** [comment]
I had a problem of flashing screens, video or audio not being subscribed etc. I added delay before connecting to the room and the problem was solved. I don't use dialog before connecting, I call connectToRoom method right after receiving token from server.
