### ISSUE TITLE
How to enable video and audio recording for video session?

### ISSUE THREAD

**Issue by ananth10** [twilio/video-quickstart-android#97]
I need to record video call session between two users. How to do it using "com.twilio:video-android:1.0.0-beta16" library?  but i saw doc there they used JS to create a room
```

curl -X POST https://video.twilio.com/v1/Rooms \

--data "RecordParticipantOnConnect=true" \

--data "Type=group"
```
but i have been passing desired roomName to  ConnectionOption like below

```
   ConnectOptions connectOptions = new ConnectOptions.Builder(accessToken)
                .roomName("DailyStandup")
                .localMedia(localMedia)
                .build();
        room = Video.connect(this, connectOptions, roomListener());
```

Now question is how to enable recording using SDK? . Is there any option like **"RecordParticipantOnConnect=true"** to enable recording?

**Comment by ktoraskartwilio** [comment]
Hi @ananth10 

I work on the Product team at Twilio. 
Recordings is currently in a limited developer preview. We will be opening a public beta in the coming weeks. Can you please send me a note directly (ktoraskar@twilio.com) with your account SID, a description of your use case and how you intend to use recordings.

Thanks,
Kedar

**Comment by idelgado** [comment]
Please open a new issue if you have additional comments regarding this topic.

**Comment by chaitaliyyy** [comment]
I need to record video call session between two users. How to do it using  JS
