### ISSUE TITLE
User audio not mirroring on tv when user having video call .

### ISSUE THREAD

**Issue by ananth10** [twilio/video-quickstart-android#98]
We are doing tv mirror using google cast sdk. so when video session started user can enable

cast button then they can see video UI on TV. i can successfully displaying VideoView UI on TV .

But I audio not mirroring on TV's speaker. as per the google cast SDK . when cast enabled it will automatically capture audio and mirror to TV's speaker.

 i just created sample activity and just played one audio file using android MediaPlayer api. then cast sdk automatically mirror audio on TV's speaker.

but when i am in video call .i can hear remote side user's voice on mobile speaker. after i enabled cast button videoview mirroring on Tv but call audio is not mirroing on TV. still i can hear on mobile speaker.

so how can i resolve this? can i access remote user's audio track and can i play it on using mediaplayer api? still not have clear idea. can you guys help me to figure this out?

**Comment by dreamerns** [comment]
Hi ananth10,

First thing that comes to mind is that you might need to change audio mode and focus in order for MediaRouter to pick it up. In our quickstart app we are setting mode to MODE_IN_COMMUNICATION and audio focus to STREAM_VOICE_CALL in [VideoActivity](https://github.com/twilio/video-quickstart-android/blob/master/quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java#L620). Try to change these values to MODE_NORMAL and STREAM_MUSIC. If it still doesn't work, then I suggest to change [MediaRouteSelector](https://developer.android.com/guide/topics/media/mediarouter.html#mediarouteselector) control category to [CATEGORY_LIVE_VIDEO](https://developer.android.com/reference/android/support/v7/media/MediaControlIntent.html#CATEGORY_LIVE_VIDEO). 
Let me know how it goes!

Thanks,
Nikola

**Comment by ananth10** [comment]
@dreamerns  i have tried both things  1. i have changed  MODE_IN_COMMUNICATION  to MODE_NORMAL and  STREAM_VOICE_CALL to STREAM_MUSIC 
2. Changed MediaRouteSelector control to CATEGORY_LIVE_VIDEO. but still audio not mirroring on TV's speaker.

**Comment by dreamerns** [comment]
@ananth10 
Unfortunately, I haven't tried casting myself, so I'm not sure what can be a problem. I need to investigate more. 
In meantime,  I do have another idea that you might want to try. Instead of mirroring room from your device to tv, maybe you can create receiver app with Video JS SDK that could act as another participant in the room? That way you could only notify receiver app from your devices on which room to connect and then connect from chromecast to that room.

**Comment by kvikrama** [comment]
@dreamerns , Twilio Team.

   This feature is required in our product. We are mirroring screen to TV and we need audio to be mirrored as well. Request you to prioritise the ticket and address the issue.

**Comment by idelgado** [comment]
As far as I can tell, with my fairly limited knowledge of the google cast sdk it relies on the Android `android.media.MediaPlayer` to broadcast the audio to the google chromecast. Unfortunately webrtc does not use `android.media.MediaPlayer` to output media.

There might be a way to capture the webrtc AudioTrack audio and provide it to the MediaPlayer but this is outside the scope of what we currently have on our roadmap.

My hunch is that this isn't really an issue with the video SDK per say but more so of what interfaces are supported by google cast to broadcast audio.

Have you reached out to the google cast team to see what they support in terms of broadcasting audio outside the context of MediaPlayer?

**Comment by idelgado** [comment]
I see you've posted this https://github.com/googlecast/CastRemoteDisplay-android/issues/25. This would have been useful information to share in your comment.

We'll take another look with this new information and see if we can route the audio in that mode.

**Comment by kvikrama** [comment]
Thanks @idelgado

**Comment by kvikrama** [comment]
@idelgado , team, Any update on this item ?

**Comment by dreamerns** [comment]
@kvikrama I integrated google cast in our demo app using remote display api (https://developers.google.com/cast/docs/remote) and hit the same roadblock. Video is displaying, but audio is not mirroring to cast device. My initial thought was that OpenSL ES might play audio differently and prevent REMOTE_SUBMIX to pick it up, so I tried forcing WebRTC to always use Java AudioTrack. I also tried changing stream type from STREAM_VOICE to STREAM_MUSIC in both WebRTC and our application, but nothing seems to be working. It seems that using MediaPlayer is the only way to broadcast audio to google chromecast, which is not being used by WebRTC.

**Comment by kvikrama** [comment]
@dreamerns Thanks for the info.
Is Twilio team planning to change this in SDK ??

**Comment by aaalaniz** [comment]
Hey @kvikrama and @ananth10 

As @idelgado previously mentioned, playing audio through `MediaPlayer` is outside the scope of our current road map, so we will not be making this change in the SDK anytime soon. I recommend following up with Google Cast team for help publishing audio without using `MediaPlayer`.

**Comment by aaalaniz** [comment]
Closing because there is nothing actionable Twilio can do for this ticket.
