### ISSUE TITLE
Inconsistencies of audio input level and quality when changing audio output

### ISSUE THREAD

**Issue by iorikingdom** [twilio/video-quickstart-android#99]
When turn the speaker on at android 7.0 devices such as xperia sony ,
the speaker volume would be turn down automatically.
Twilio-video is android 7.0 supported?

**Comment by aaalaniz** [comment]
Hi @iorikingdom 

The Video Android SDK does support Android 7.0+. Are you saying that when you turn speaker on while connected to a `Room` on Sony Xperia the audio received by other participants is quieter? Can you try adding a `LocalAudioTrack` with echo cancellation disabled to see if that affects the audio. Snippet below for reference.

```
// Create local media 
LocalMedia localMedia = LocalMedia.create(context);

// Create audio options
AudioOptions audioOptions = new AudioOptions.Builder()
    .echoCancellation(false)
    .build();

// Add audio track
LocalAudioTrack localAudioTrack = localMedia.addAudioTrack(true, audioOptions);
```

**Comment by iorikingdom** [comment]
HI @aaalaniz 

Thanks for your reply.
I have tried this snippet but it seem not working.
It is any other way to find out this problem? 

```
// Create local media 
LocalMedia localMedia = LocalMedia.create(context);

// Create audio options
AudioOptions audioOptions = new AudioOptions.Builder()
    .echoCancellation(false)
    .build();

// Add audio track
LocalAudioTrack localAudioTrack = localMedia.addAudioTrack(true, audioOptions);

```

**Comment by aaalaniz** [comment]
Hi @iorikingdom

Thanks for trying my suggestion. We are able to reproduce a similar audio issue on some of our devices. We are currently working on a solution. I or @dreamerns will update this issue when we have any updates.

Thanks

**Comment by niekvse** [comment]
@aaalaniz Could you give a status update on this bug? We're having a similar problem, where we get a howling feedback noise even using the AudioOptions with echoCancellation and noiseSuppression enabled. Note that we have audioManager.setSpeakerphoneOn(true), and other than this we use the example code from the CallActivity. 

Were you able to have a video call with speaker sound enabled to a reasonable volume, without the howling feedback noise? 

Any tips are welcome.

**Comment by aaalaniz** [comment]
Hey @niekvse 

Unfortunately echo on some devices is just a known issue at the moment. I recommend referencing our [Troubleshooting Audio](https://github.com/twilio/video-quickstart-android#troubleshooting-audio) article.  I recommend disabling hardware echo cancellation in cases where echo is really bad. Can you provide a list of devices that are producing bad echo?

Thanks!

**Comment by aaalaniz** [comment]
See my previous comment for guidance managing audio issues in your application. I will close this for now.
